---
output: slidy_presentation
title: "Stretching and Shrinking Functions"
---


# Agenda

* Entrance Ticket: [ET_1001](https://bart.instructure.com/courses/2110/quizzes/3209)
    * When function transformation given as an equation like $y=\ldots f(x\ldots)\ldots$:
        * To get new $x$ values, set argument=$a$, where $a$ is an old $x$ value.
        * To get new $y$ values, replace $f(\ldots)$ with $b$, where $b$ is an old $y$ value.
* [OCW_1001_scaling_descriptions](https://bart.instructure.com/courses/2110/quizzes/3210)
    * Describe the stretching/shrinking shown with equation and graph.
* [OCW_1001_B_stretch_eqs](https://bart.instructure.com/courses/2110/quizzes/3211)
    * From graph, determine the function-stretch equation.


# Stretching/shrinking

Transformations are described relative to $y=f(x)$.

* $y=f(2x)$ causes points to shrink horizontally towards the $y$ axis.
$$(a,b)\to \left(\frac{a}{2}~,~b\right)$$
* $y=f{\left(\frac{x}{2}\right)}$ causes points to stretch horizontally away from the $y$ axis.
$$(a,b)\to \left(2a~,~b\right)$$
* $y=2\cdot f(x)$ causes points to stretch vertically away from the $x$ axis.
$$(a,b)\to \left(a~,~2b\right)$$
* $y=\frac{f(x)}{2}$ causes points to shrink vertically toward the $x$ axis.
$$(a,b)\to \left(a~,~\frac{b}{2}\right)$$

Of course, I'm just using 2 as an example. This generalizes with any scale factor.

* The horizontal transformations are "backwards" and indicated by operations inside the argument. 
* The vertical transformations are "normal" and indicated by operations outside the function.






