---
title: "Sub plans for Chad Worley on 2024 Jan 22"
output: 
  html_document:
    toc: true
---

This file's live link: [https://chadworley.github.io/subplans/SubPlans_CW_2024Jan22.html](https://chadworley.github.io/subplans/SubPlans_CW_2024Jan22.html)

## Precalculus 8:15-9:12 in Dubois 402

* All students have problems on Canvas to work on: [examples](https://chadworley.github.io/precalculus/024_rtt_extensions/024_shared1.html).
* They can (and should) help each other.
* Students should also prepare for a written test on Tuesday Jan 23. Below are practice tests along with solutions. These practice tests are already on Canvas.
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE1.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE1.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE1_sol.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE1_sol.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2_sol.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2_sol.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE3.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE3_sol.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2_sol.pdf)
  
## Topics in Algebra 9:15-10:12 in McNair 125

* Students work on w22 problems (loaded on Canvas). Only Jalyn has finished any of them so far. Jalyn could help others or work on fixing mistakes on the Desmos practice problems.
  * Here are w22 examples: [https://chadworley.github.io/alg_1_topics/data_stats_intro/w22_shared1.html](https://chadworley.github.io/alg_1_topics/data_stats_intro/w22_shared1.html)
* Last Friday, most students missed all the problems in the Desmos practice problems: [Practice A1.3.05](https://student.desmos.com/activitybuilder/student-greeting/65aa1069a22a9fb3772b7680)
  * Students should try the problems again.
  * Student link: [https://student.desmos.com/activitybuilder/student-greeting/65aa1069a22a9fb3772b7680](https://student.desmos.com/activitybuilder/student-greeting/65aa1069a22a9fb3772b7680)
  * Students can find link on Canvas.


## Precalculus 10:15-11:12 in Achebe 401

* All students have problems on Canvas to work on: [examples](https://chadworley.github.io/precalculus/024_rtt_extensions/024_shared1.html).
* They can (and should) help each other.
* Students should also prepare for a written test on Tuesday Jan 23. Below are practice tests along with solutions. These practice tests are already on Canvas.
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE1.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE1.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE1_sol.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE1_sol.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2_sol.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2_sol.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE3.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2.pdf)
  * [https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE3_sol.pdf](https://chadworley.github.io/precalculus/024_rtt_extensions/written_exam/output/024_WE2_sol.pdf)

## Lunch 2 11:45-12:12 in Seeger 503

* Lunch duties

## Math Workshop 7C 1:45-2:12 Ozu 204

* On the TV, display the [math workshop curriculum](https://docs.google.com/spreadsheets/d/1toFPp7NyFy9iAHSyK8UATmdQ_yiWGjwF5zT673RWvW8/edit?usp=sharing){target="_blank"}, and scroll to the correct columns for 7C.
* Students can play mathigon: [https://mathigon.org/](https://mathigon.org/)
* The games are in the cabinet.
* If students have other math to work on, that is fine too.

## Math Workshop 6D 2:45-3:12 Rockwell 103

* On the TV, display the [math workshop curriculum](https://docs.google.com/spreadsheets/d/1toFPp7NyFy9iAHSyK8UATmdQ_yiWGjwF5zT673RWvW8/edit?usp=sharing){target="_blank"}, and scroll to the correct columns for 6D.
* Students can play MangaHigh: [https://www.mangahigh.com/en-us/](https://www.mangahigh.com/en-us/)
* The games are in the cabinet.
* If students have other math to work on, that is fine too.


## Math Workshop 6B 3:15-3:42 Graham 102

* On the TV, display the [math workshop curriculum](https://docs.google.com/spreadsheets/d/1toFPp7NyFy9iAHSyK8UATmdQ_yiWGjwF5zT673RWvW8/edit?usp=sharing){target="_blank"}, and scroll to the correct columns for 6B.
* Students can play MangaHigh: [https://www.mangahigh.com/en-us/](https://www.mangahigh.com/en-us/)
* The games are in the cabinet.
* If students have other math to work on, that is fine too.
