---
title: "Sub plans for Chad Worley on 2025 Nov 05"
output: 
  html_document:
    toc: true
  pdf_document:
    toc: true
urlcolor: blue
---


## Algebra 2 8:00-9:05 in Marquez 409

* Homeroom until 8:10.
* Students complete entrance ticket (online Canvas quiz).
    * [https://bart.instructure.com/courses/2110/quizzes/3282](https://bart.instructure.com/courses/2110/quizzes/3282)
* Hand out [paper practice](https://chadworley.github.io/algtwo2026/u03/1105/p1105/p1105_v001-020.pdf) (on Desk in Marquez)
    * **p1105: Factoring when $a=$ prime**
* Most students still need to complete Blooket_1103 (online work)
    * [https://bart.instructure.com/courses/2110/assignments/29355](https://bart.instructure.com/courses/2110/assignments/29355)
* If students have finished all the above, they are invited to take on a serious challenge, mostly for glory:
    * [https://bart.instructure.com/courses/2110/assignments/29388](https://bart.instructure.com/courses/2110/assignments/29388)



## Math Literacy 10:06 - 11:01 in Marquez 409

* Students finish entrance ticket (online Canvas quiz):
    * [https://bart.instructure.com/courses/1945/quizzes/3287](https://bart.instructure.com/courses/1945/quizzes/3287)
* Approximately half of the students still need to complete their Blooket work from Monday.
    * [https://bart.instructure.com/courses/1945/assignments/29383](https://bart.instructure.com/courses/1945/assignments/29383)
* Hand out [paper practice](https://chadworley.github.io/ml2026/u04/1105/p1105/p1105_v001-012.pdf) (on Desk in Marquez)
    * **p1105: Factoring when $a=1$**
* If students finish everything, they should spend their remaining time on other academic pursuits.



## Algebra 2 11:04-12:01 in Carson 301

* Students complete entrance ticket (online Canvas quiz).
    * [https://bart.instructure.com/courses/2110/quizzes/3282](https://bart.instructure.com/courses/2110/quizzes/3282)
* Hand out [paper practice](https://chadworley.github.io/algtwo2026/u03/1105/p1105/p1105_v001-020.pdf) (on Desk in Marquez)
    * **p1105: Factoring when $a=$ prime**
* Most students still need to complete Blooket_1103 (online work)
    * [https://bart.instructure.com/courses/2110/assignments/29355](https://bart.instructure.com/courses/2110/assignments/29355)
* If students have finished all the above, they are invited to take on a serious challenge, mostly for glory:
    * [https://bart.instructure.com/courses/2110/assignments/29388](https://bart.instructure.com/courses/2110/assignments/29388)

    
## Crew 12:04 - 12:31 in Holiday 206

* Hang out with some kids for half an hour.

## Project Based Learning 2:02-2:57 in Mondrian 205

* Materials to distribute:
    * Paper packets: [Frieze Patterns with Stencils](https://chadworley.github.io/pbl/frieze/frieze_pattern_stencil.pdf)
    * Stencils
    * Color pencils
* Hand out **Frieze Patterns with Stencils**
    * [https://chadworley.github.io/pbl/frieze/frieze_pattern_stencil.pdf](https://chadworley.github.io/pbl/frieze/frieze_pattern_stencil.pdf)
* Allow students to take a few stencils at a time. I want to get all of these back at the end of class.
* Remind students that these packets will be graded on:
    * Using the correct transformations!
    * Showing attention to detail.
    * Quality.
    * Having multiple colors.
    * Using multiple stencils.
* At end of class, please collect the packets (and stencil and pencils). If they need more time, I will redistribute the packets on Friday.

## Flex Block (Coloring and Drawing) 3:00-3:42 in Seeger 503 (Cafeteria)

* Hopefully someone brings paper and colored pencils.
* If not, there will be multiple adults, so someone can go get some.
    * I'd recommend checking into the Learning Center... because Truran has printed a bunch of color-in-the-lines pages. Noyes knows where they are (if Truran is out).



