---
title: "Sub plans for Chad Worley on 2025 May 30"
output: 
  pdf_document:
    toc: true
urlcolor: blue
---

This file's live link: [https://chadworley.github.io/subplans/SubPlans_CW_2025May30.html](https://chadworley.github.io/subplans/SubPlans_CW_2025May30.html)

## Algebra 2 8:00-8:40 in Gates 309

* Display [the agenda](https://chadworley.github.io/a2/weekly_a2.html#unit-18-exponential-equations-and-logarithms) (go to week 41, Friday)
    * Students also have the link to the agenda at top of Canvas.
    * Students can also find all assignments on Canvas.
* All students should start (~5 minutes) by working on the entrance ticket: [Canvas](https://bart.instructure.com/courses/1314/quizzes/3085)/[public](https://chadworley.github.io/a2/ET2/ET_161.html)
* Students have a few assignments on matrices due today:
    * s19_30_can_add_matrices [Canvas](https://bart.instructure.com/courses/1314/quizzes/3098)/[public](https://chadworley.github.io/a2/u19/outhtml/30_can_add_matrices.html)
    * s19_31_add_matrices [Canvas](https://bart.instructure.com/courses/1314/quizzes/3099)/[public](https://chadworley.github.io/a2/u19/outhtml/31_add_matrices.html)
    * s19_32_subtract_matrices [Canvas](https://bart.instructure.com/courses/1314/quizzes/3100)/[public](https://chadworley.github.io/a2/u19/outhtml/32_subtract_matrices.html)
    * s19_33_ntwrk_incidence_mat [Canvas](https://bart.instructure.com/courses/1314/quizzes/3101)/[public](https://chadworley.github.io/a2/u19/outhtml/33_ntwrk_incidence_mat.html)
* Most students also need some time to catch up on older assignments.


## Math Literacy 9:16-9:46 in Fuller 310

* Students should prepare for their portfolio presentations.

## Algebra 2 9:49-10:49 in Gates 309 (Room change to Carson 301)

* Display [the agenda](https://chadworley.github.io/a2/weekly_a2.html#unit-18-exponential-equations-and-logarithms) (go to week 41, Friday)
    * Students also have the link to the agenda at top of Canvas.
    * Students can also find all assignments on Canvas.
* All students should start (~5 minutes) by working on the entrance ticket: [Canvas](https://bart.instructure.com/courses/1314/quizzes/3085)/[public](https://chadworley.github.io/a2/ET2/ET_161.html)
* Students have a few assignments on matrices due today:
    * s19_30_can_add_matrices [Canvas](https://bart.instructure.com/courses/1314/quizzes/3098)/[public](https://chadworley.github.io/a2/u19/outhtml/30_can_add_matrices.html)
    * s19_31_add_matrices [Canvas](https://bart.instructure.com/courses/1314/quizzes/3099)/[public](https://chadworley.github.io/a2/u19/outhtml/31_add_matrices.html)
    * s19_32_subtract_matrices [Canvas](https://bart.instructure.com/courses/1314/quizzes/3100)/[public](https://chadworley.github.io/a2/u19/outhtml/32_subtract_matrices.html)
    * s19_33_ntwrk_incidence_mat [Canvas](https://bart.instructure.com/courses/1314/quizzes/3101)/[public](https://chadworley.github.io/a2/u19/outhtml/33_ntwrk_incidence_mat.html)
* Most students also need some time to catch up on older assignments.

## WIN 10:22-10:52 in Graham 102

* The first half hour should be **silent** independent-work time. Students should be working on ALEKS (online math).
* The second half hour, students can **quietly** work on other work.
* Students should stay in their chairs, at desks, one kid per desk.


## Crew 11:28-11:58 in Mondrian 205 (Room change to Dubois 402)

* Students will eat lunch.





