---
title: "Sub plans for Chad Worley on 2025 May 16"
output: 
  pdf_document:
    toc: true
urlcolor: blue
---

This file's live link: [https://chadworley.github.io/subplans/SubPlans_CW_2025May16.html](https://chadworley.github.io/subplans/SubPlans_CW_2025May16.html)

## Algebra 2 8:00-9:12 in Gates 309

* Display [the agenda](https://chadworley.github.io/a2/weekly_a2.html#unit-18-exponential-equations-and-logarithms) (go to week 39, Friday)
    * Students also have the link to the agenda at top of Canvas.
    * Students can also find all assignments on Canvas.
* All students should start (~10 minutes) by working on the entrance ticket: [Canvas](https://bart.instructure.com/courses/1314/quizzes/3023)/[public](https://chadworley.github.io/a2/ET2/ET_152.html)
* Students have a new mastery assignment (on Canvas):
    * [s18_mastery](https://bart.instructure.com/courses/1314/quizzes/3035)
* Most students also need some time to catch up on older assignments.


## Math Literacy 10:06-11:01 in Fuller 310

* Students have the following problems to work through on Canvas:
    * may16_01_eval_expo_base2 [Canvas](https://bart.instructure.com/courses/1282/quizzes/3036)/[public](https://chadworley.github.io/ml/may16/outhtml/01_eval_expo_base2.html)
    * may16_02_eval_expo_base10 [Canvas](https://bart.instructure.com/courses/1282/quizzes/3037)/[public](https://chadworley.github.io/ml/may16/outhtml/02_eval_expo_base10.html)
    * may16_03_solve_expo_base2 [Canvas](https://bart.instructure.com/courses/1282/quizzes/3038)/[public](https://chadworley.github.io/ml/may16/outhtml/03_solve_expo_base2.html)
    * may16_04_solve_expo_base10 [Canvas](https://bart.instructure.com/courses/1282/quizzes/3039)/[public](https://chadworley.github.io/ml/may16/outhtml/04_solve_expo_base10.html)
    * may16_05_eval_log_base2 [Canvas](https://bart.instructure.com/courses/1282/quizzes/3040)/[public](https://chadworley.github.io/ml/may16/outhtml/05_eval_log_base2.html)
    * may16_06_eval_log_base10 [Canvas](https://bart.instructure.com/courses/1282/quizzes/3041)/[public](https://chadworley.github.io/ml/may16/outhtml/06_eval_log_base10.html)
    * may16_07_eval_log_base_2_3_10 [Canvas](https://bart.instructure.com/courses/1282/quizzes/3042)/[public](https://chadworley.github.io/ml/may16/outhtml/07_eval_log_base_2_3_10.html)
* If students need to, they can also work on their project (preparing a presentation involving precise instructions)

## Algebra 2 11:04-12:01 in Gates 309

* Display [the agenda](https://chadworley.github.io/a2/weekly_a2.html#unit-18-exponential-equations-and-logarithms) (go to week 39, Friday)
    * Students also have the link to the agenda at top of Canvas.
    * Students can also find all assignments on Canvas.
* All students should start (~10 minutes) by working on the entrance ticket: [Canvas](https://bart.instructure.com/courses/1314/quizzes/3023)/[public](https://chadworley.github.io/a2/ET2/ET_152.html)
* Students have a new mastery assignment:
    * [s18_mastery](https://bart.instructure.com/courses/1314/quizzes/3035)
* Most students also need some time to catch up on older assignments.

## Crew 12:34-1:01 in Mondrian (205)

* Take students to Adams Theater to watch the musical.

## WIN 1:04-1:59 in Graham (102)

* The first half hour should be **silent** independent-work time. Students should be working on ALEKS (online math).
* The second half hour, students can **quietly** work on other work.
* Students should stay in their chairs, at desks, one kid per desk.







