---
title: "Sub plans for Chad Worley on 2023 Oct 20"
output: 
  html_document:
    toc: true
---

## Precalculus 8:15-9:12 in Dubois 402

* All students have problems on Canvas to work on.
* They can (and should) help each other.
* These [014 shared problems](https://chadworley.github.io/precalculus/unit_02_functions/03_functions_galore/014_shared1.html){target="_blank"} and [015 shared problems](https://chadworley.github.io/precalculus/unit_3_linear/015_linear_shared1.html){target="_blank"} provide examples similar to the current questions on Canvas.

## Topics in Alg 9:15-10:12 in McNair 125

* 

## Precalculus 10:15-11:12 in Achebe 401

* All students have problems on Canvas to work on.
* They can (and should) help each other.
* These [014 shared problems](https://chadworley.github.io/precalculus/unit_02_functions/03_functions_galore/014_shared1.html){target="_blank"} and [015 shared problems](https://chadworley.github.io/precalculus/unit_3_linear/015_linear_shared1.html){target="_blank"} provide examples similar to the current questions on Canvas.

## Lunch 2 11:45-12:12 in Seeger 503

* Lunch duties

## Math Workshop 7C 1:45-2:12 Ozu 204

* See [math workshop curriculum](https://docs.google.com/spreadsheets/d/1toFPp7NyFy9iAHSyK8UATmdQ_yiWGjwF5zT673RWvW8/edit?usp=sharing){target="_blank"}.
* Specifically, kids will play on computer. You show [the slides](https://docs.google.com/presentation/d/1qoDxArDCC7JypqSrwwM91o5op08dVgJ6UD2DJlpIQdc/edit?usp=sharing){target="_blank"}.
* It can be helpful to run [deledao](https://portals.deledao.com/teacher/#/teacher-signin){target="_blank"} to watch screens and close inappropriate tabs.

## Math Workshop 6D 2:45-3:12 Rockwell 103

* See [math workshop curriculum](https://docs.google.com/spreadsheets/d/1toFPp7NyFy9iAHSyK8UATmdQ_yiWGjwF5zT673RWvW8/edit?usp=sharing){target="_blank"}.
* Specifically, kids will play on computer. You show [the slides](https://docs.google.com/presentation/d/1hND39Tb9qpppoqh7mZrl1aCQGVBO1UeGmC1MKphKYOE/edit?usp=sharing){target="_blank"}.
* It can be helpful to run [deledao](https://portals.deledao.com/teacher/#/teacher-signin){target="_blank"} to watch screens and close inappropriate tabs.

## Math Workshop 6B 3:15-3:42 Graham 102

* See [math workshop curriculum](https://docs.google.com/spreadsheets/d/1toFPp7NyFy9iAHSyK8UATmdQ_yiWGjwF5zT673RWvW8/edit?usp=sharing).
* Specifically, kids will play on computer. You show [the slides](https://docs.google.com/presentation/d/1hND39Tb9qpppoqh7mZrl1aCQGVBO1UeGmC1MKphKYOE/edit?usp=sharing).
* It can be helpful to run [deledao](https://portals.deledao.com/teacher/#/teacher-signin){target="_blank"} to watch screens and close inappropriate tabs.
