---
title: "Sub plans for Chad Worley on 2025 Jan 02"
output: 
  html_document:
    toc: true
---

This file's live link: [https://chadworley.github.io/subplans/SubPlans_CW_2025Jan02.html](https://chadworley.github.io/subplans/SubPlans_CW_2025Jan02.html)

## Algebra 2 8:10-9:12 in Gates 309

* Display [the agenda](file:///Users/chad.worley@bartcharter.org/Documents/chadworley.github.io/a2/weekly_a2.html) (go to week 20)
* Remind students they should be working through the assigned problems.
* Each problem has a link to 8 examples with solutions.
* They can and should help each other.

## Math Literacy 10:06-11:01 in Fuller 310

* Students should complete at least 30 minutes of focused work on Aleks.


## Algebra 2 11:04-12:01 in Gates 309

* Display [the agenda](file:///Users/chad.worley@bartcharter.org/Documents/chadworley.github.io/a2/weekly_a2.html) (go to week 20)
* Remind students they should be working through the assigned problems.
* Each problem has a link to 8 examples with solutions.
* They can and should help each other.

## Crew 12:34-1:01 in Mondrian (205)

* See [the slideshow](https://docs.google.com/presentation/d/1zKdtLoqtBSP-KQYLI95GKgppDIyVo6T-IjG-af4Ft0U/edit?usp=sharing)















