---
title: "Sub plans for Chad Worley on 2025 May 29"
output: 
  pdf_document:
    toc: true
urlcolor: blue
---

This file's live link: [https://chadworley.github.io/subplans/SubPlans_CW_2025May29.html](https://chadworley.github.io/subplans/SubPlans_CW_2025May29.html)

## Algebra 2 8:00-8:40 in Gates 309

* Display [the agenda](https://chadworley.github.io/a2/weekly_a2.html#unit-18-exponential-equations-and-logarithms) (go to week 41, Thursday)
    * Students also have the link to the agenda at top of Canvas.
    * Students can also find all assignments on Canvas.
* All students should start (~5 minutes) by working on the entrance ticket: [Canvas](https://bart.instructure.com/courses/1314/quizzes/3084)/[public](https://chadworley.github.io/a2/ET2/ET_160.html)
* Students have a few assignments on matrices due today:
    * s19_26_Cramers_rule_2x2 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3094)/[public](https://chadworley.github.io/a2/u19/outhtml/26_Cramers_rule_2x2.html)
    * s19_27_mult_2x2_mats [Canvas](https://bart.instructure.com/courses/1314/quizzes/3095)/[public](https://chadworley.github.io/a2/u19/outhtml/27_mult_2x2_mats.html)
    * s19_28_Identity_Matrix [Canvas](https://bart.instructure.com/courses/1314/quizzes/3096)/[public](https://chadworley.github.io/a2/u19/outhtml/28_Identity_Matrix.html)
    * s19_29_check_if_inverse [Canvas](https://bart.instructure.com/courses/1314/quizzes/3097)/[public](https://chadworley.github.io/a2/u19/outhtml/29_check_if_inverse.html)
* Most students also need some time to catch up on older assignments.


## Math Literacy 9:16-9:46 in Fuller 310

* Students should prepare for their portfolio presentations.

## Algebra 2 9:49-10:49 in Gates 309 (Probable room change to Carson 301)

* Display [the agenda](https://chadworley.github.io/a2/weekly_a2.html#unit-18-exponential-equations-and-logarithms) (go to week 41, Thursday)
    * Students also have the link to the agenda at top of Canvas.
    * Students can also find all assignments on Canvas.
* All students should start (~5 minutes) by working on the entrance ticket: [Canvas](https://bart.instructure.com/courses/1314/quizzes/3084)/[public](https://chadworley.github.io/a2/ET2/ET_160.html)
* Students have a few assignments on matrices due today:
    * s19_26_Cramers_rule_2x2 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3094)/[public](https://chadworley.github.io/a2/u19/outhtml/26_Cramers_rule_2x2.html)
    * s19_27_mult_2x2_mats [Canvas](https://bart.instructure.com/courses/1314/quizzes/3095)/[public](https://chadworley.github.io/a2/u19/outhtml/27_mult_2x2_mats.html)
    * s19_28_Identity_Matrix [Canvas](https://bart.instructure.com/courses/1314/quizzes/3096)/[public](https://chadworley.github.io/a2/u19/outhtml/28_Identity_Matrix.html)
    * s19_29_check_if_inverse [Canvas](https://bart.instructure.com/courses/1314/quizzes/3097)/[public](https://chadworley.github.io/a2/u19/outhtml/29_check_if_inverse.html)
* Most students also need some time to catch up on older assignments.

## Crew 11:28-11:58 in Mondrian 205 (Probable room change to Dubois 402)

* Students will eat lunch.





