---
title: "Sub plans for Chad Worley on 2025 Jan 27"
output: 
  html_document:
    toc: true
---

This file's live link: [https://chadworley.github.io/subplans/SubPlans_CW_2025Jan27.html](https://chadworley.github.io/subplans/SubPlans_CW_2025Jan27.html)

## Algebra 2 8:00-9:12 in Gates 309

* Display [the agenda](https://chadworley.github.io/a2/weekly_a2.htmlunit-12-radians-angles-arc-lengths-weeks-23-24) (go to week 24, Monday)
    * Students also have the link to the agenda at top of Canvas.
    * Students can also find all assignments on Canvas.
* All students should start (~10 minutes) by working on the entrance ticket: [Canvas](https://bart.instructure.com/courses/1314/quizzes/2644)/[public](https://chadworley.github.io/a2/ET2/ET_089.html)
* Students have a few assignments with upcoming due dates:
    * [u12__mastery](https://bart.instructure.com/courses/1314/quizzes/2715) 
        * Due Tue Jan 28
    * [Blooket HW](https://play.blooket.com/play?hwId=67937c3f87e5b6df67ac9491)
        * Due Wed Jan 29
        * Once completed, students need to tell me their nicknames with [a google form](https://docs.google.com/forms/d/e/1FAIpQLSfWdtJVkwSaEhJgaNAYdo_SS7zryWN6ELn3XebowrSYoA_RhQ/viewform?usp=header).
    * [Written exam practice](https://bart.instructure.com/courses/1314/assignments/24036) (the 2nd paper handed out on Friday to every student, should be a version between 11 and 99, not version -2 that we all worked through together on Friday)
        * Due Thu Jan 30
        * If necessary, students can get a new one through the Canvas assignment.
    * Study for written exam on Thu Jan 30.
        * [examples](https://chadworley.github.io/a2/u12/written_exam/practice/u12we_examples.pdf)
        * [solutions](https://chadworley.github.io/a2/u12/written_exam/practice/u12we_examples_sols.pdf)
* Some students also need some time to catch up on older assignments.


## Math Literacy 10:06-11:01 in Fuller 310

* Students should complete at least 30 minutes of focused work on Aleks.
* If you say, "It's an ALEKS day!", they'll know what to do.
* The expectation is that every student should finish at least 2 topics.

## Algebra 2 11:04-12:01 in Gates 309

* Display [the agenda](https://chadworley.github.io/a2/weekly_a2.htmlunit-12-radians-angles-arc-lengths-weeks-23-24) (go to week 24, Monday)
    * Students also have the link to the agenda at top of Canvas.
    * Students can also find all assignments on Canvas.
* All students should start (~10 minutes) by working on the entrance ticket: [Canvas](https://bart.instructure.com/courses/1314/quizzes/2644)/[public](https://chadworley.github.io/a2/ET2/ET_089.html)
* Students have a few assignments with upcoming due dates:
    * [u12__mastery](https://bart.instructure.com/courses/1314/quizzes/2715) 
        * Due Tue Jan 28
    * [Blooket HW](https://play.blooket.com/play?hwId=67937c3f87e5b6df67ac9491)
        * Due Wed Jan 29
        * Once completed, students need to tell me their nicknames with [a google form](https://docs.google.com/forms/d/e/1FAIpQLSfWdtJVkwSaEhJgaNAYdo_SS7zryWN6ELn3XebowrSYoA_RhQ/viewform?usp=header).
    * [Written exam practice](https://bart.instructure.com/courses/1314/assignments/24036) (the 2nd paper handed out on Friday to every student, should be a version between 11 and 99, not version -2 that we all worked through together on Friday)
        * Due Thu Jan 30
        * If necessary, students can get a new one through the Canvas assignment.
    * Study for written exam on Thu Jan 30.
        * [examples](https://chadworley.github.io/a2/u12/written_exam/practice/u12we_examples.pdf)
        * [solutions](https://chadworley.github.io/a2/u12/written_exam/practice/u12we_examples_sols.pdf)
* Some students also need some time to catch up on older assignments.

## Crew 12:34-1:01 in Mondrian (205)

* See [the slideshow](https://docs.google.com/presentation/d/1vHrkD6znsUHjC3sMo5NG0ssSXQ5eDHPlIyZwg0rnyHg/edit?usp=gmail_thread)

## WIN 1:04-1:59 in Graham (102)

* Students should complete at least 25 minutes of quiet, focused work on **ALEKS**.
* After that, I'd recommend Blooket, Seterra, Semantle, or other academic pursuits.
* Students should sit in chairs, at desks, one kid per desk.




