---
title: "Math Literacy Syllabus"
author: "Mr. Worley"
date: "`r Sys.Date()`"
output: 
    html_document:
        toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Canvas

* [https://bart.instructure.com/courses/1282](https://bart.instructure.com/courses/1282)

## Teacher Contact

* Mr. Worley (he/him)
* chad.worley@bartcharter.org
* https://bartcharter-org.zoom.us/j/9643150067
* 413-481-9370

## Math Literacy

* Math Literacy is a project-based math class. Our goal is to develop, build, and **document** various projects with mathematical basis. The documentation is absolutely critical. I expect most documentation will take the form of a slideshow/presentation, but I am open to other media (paper/poster/video/website).
* In the documentation, it will be important to make (a few) references to mathematical concepts.
* Each project should be viewed as a possible element to your senior portfolio.
* You are expected to add your own flair into each project.
* See project ideas list: https://chadworley.github.io/ml/Project_ideas.html

## Classroom Procedures & Expectations

* No personal electronics.
    * You will get bored. That's okay.
* Typical class:
    * Entrance ticket:
        * Usually you'll be asked for a plan/goals for day/week.
    * Lecture:
        * Review project guidelines/examples.
        * Relevant mathematical concepts.
    * Class discussions. This is time for people to propose future projects or suggest tools they've found useful.
    * Individual work time.
        * Check-ins. I will have frequent one-on-one check-ins to monitor progress.
    * Exit ticket: 
        * Usually you'll document what you accomplished that day.
* Presentations
    * Everyone will need to present a Senior Portfolio this year, so I feel everyone could use some practice. This class feels like an excellent place to practice presenting your projects. Right now, I feel like every project should be followed by a presentation.
    * If you'd prefer making a screencast, that will also be accepted. In Canvas, we have [Studio](https://bart.instructure.com/courses/1282/external_tools/65).
* Quietude:
    * Last year I struggled to keep classes quiet enough for students to focus. I felt very bad for these students who became more frustrated through the year.
    * An incredibly useful concept is [negative externality](https://en.wikipedia.org/wiki/Externality). When individuals pursue self interests, they often cause costs onto others. Common examples are pollution (chemical or noise). A society should tax these behaviors for the betterment of the whole.
    * I am expected to maintain a calm environment conducive to learning.

## Work turn in policy

* Turn work in **ON CANVAS**. Do not send it to me in an email.

## Late Work Policy

* Each day late incurs a -2% penalty, down to -30% at the most extreme. In other words, if you hand it in $x$ days late, and you get a fraction $y$ of the points (where $y$ is between 0 and 1), then your late-adjusted fraction will be:
$$y_{\mathrm{adj}} = y-0.02 \cdot y\cdot \min(15,\,\lfloor x \rfloor)$$
But, each quarter's work will not be accepted after the quarter ends.

## Academic Honesty

* Be honest with your assignments. Cite your sources.
* If you use an AI to help you, say which one and how it was used.

## Absent Students

* If a student is absent they should get the # of days out +1 to make up the work. If a student is struggling with this they should reach out to the teacher to discuss.

## Participation

* Participation will be used as part of your effort grade.
* More importantly, please do not cause distractions.

## Code of conduct

These guidelines will help us maintain a positive and productive learning environment.

### Electronics Policy

* Personal electronics: From the moment you enter the building in the morning until after dismissal, all personal electronics must be turned off and kept out of sight. This includes phones, tablets, ear buds, air pods, and any other personal devices. The school-provided Chromebook is available for student use during the day when teachers instruct for them to be used in class. Students using or displaying personal electronics during school hours will be subject to disciplinary actions, the device will be confiscated and a parent or guardian may be required to come to campus to collect it.

### Food and Drink Policy

* Classrooms: No food or drinks are allowed in the classrooms, with the exception of water in a twist-top lid container. This helps keep our learning environment clean and focused.
* Cafeteria: Please remember that food is not to be taken out of the cafeteria after breakfast or lunch. This helps us maintain a clean and respectful space for everyone.

### Drug-Free Environment

* Our School is an environment that is expected to be free from tobacco, tobacco  products including vapes, alcohol, and controlled/illegal substances. BART maintains a no tolerance policy for tobacco, vapes, alcohol, or illegal/controlled substance possession or  use on school grounds/school-related  events where students are  present.

### Dress Code

* Expectations: Students are expected to adhere to the school dress code as outlined in the student handbook. This policy is designed to ensure that everyone is dressed appropriately for the school environment. Students not in compliance with the dress code will be asked to change and may face disciplinary action if the issue is not resolved. Per the student handbook, the following are not permitted:
* Bulky coats (worn in the building)
* Flip-flops or open toed shoes 
* Hats/caps(exception for religious or medical requirements)
* Sunglasses 
* The purposeful display of undergarments
* Any clothing or accessory that obscures the face or ears (exception for religious or medical requirements)
* Images or language depicting or referring to drugs, alcohol, violence, hate speech, profanity, or pornography. 
* Swimsuits 
* Pajamas and/or bedding materials (blankets, stuffed animals)
* Accessories that could be considered dangerous or used as a weapon

### Tardiness and Attendance

* Tardiness: Being present for school and on time to class is crucial for your success. Accumulating 5 tardies in a quarter will result in disciplinary action and loss of privileges. Attendance will be closely monitored. Every absence will be communicated to parents or guardians. Accumulating 3 or more absences in a quarter can lead to disciplinary action, a formal attendance plan, and loss of privileges. If you accumulate 10 or more absences in a semester-long course, or 20 or more absences in a full-year course, you may lose credit for the course. 

### Bathrooms

* Bathrooms are closed during passing time.
* SmartPass required from teacher to access bathrooms.
* Students should use the restroom in the wing of their level (HS/MS). 

