---
title: "Math Literacy Calendar"
output:
  html_document:
    toc: true
    toc_depth: 1
    theme: united
---

#### Link to current version

https://chadworley.github.io/mk/weekly_ml.html

# Unit 1: Wallpaper Groups

## Week 1 {.tabset}

### Wed Aug 21

* Review the [syllabus](https://chadworley.github.io/a2/syllabus_ml.html).
* First day survey (on Canvas)
* Slides: [Introduction to Wallpaper Groups](https://chadworley.github.io/ml/u01_wallpaper_groups/wallpaper_groups_presentation.html#1)
* Students start [Wallpaper Project](https://chadworley.github.io/ml/u01_wallpaper_groups/Wallpaper_Assignment.html)

### Thu Aug 22

* Entrance ticket: Project check in (Canvas)
* Look at some examples of historical wallpapers/tilings for inspiration.
* Continue working on [Wallpaper Project](https://chadworley.github.io/ml/u01_wallpaper_groups/Wallpaper_Assignment.html)

### Fri Aug 23

* Canvas Quiz: Identify transformations [Canvas](https://bart.instructure.com/courses/1282/quizzes/2278)/[public](https://chadworley.github.io/ml/u01_wallpaper_groups/transforms_shared1.html).
* Canvas Quiz: Identify Frieze groups [Canvas](https://bart.instructure.com/courses/1282/quizzes/2276)/[public](https://chadworley.github.io/ml/u01_wallpaper_groups/frieze_shared1.html)
* Continue working on Wallpaper Project [Canvas](https://bart.instructure.com/courses/1282/assignments/21403)/[public](https://chadworley.github.io/ml/u01_wallpaper_groups/Wallpaper_Assignment.html)

## Week 2 {.tabset}

### Mon Aug 26

* [Turn and Talk](https://chadworley.github.io/ml/u01_wallpaper_groups/Turn_and_Talk_wallpaper_01.html)
* Continue working on Wallpaper Project [Canvas](https://bart.instructure.com/courses/1282/assignments/21403)/[public](https://chadworley.github.io/ml/u01_wallpaper_groups/Wallpaper_Assignment.html)

### Tue Aug 27

* Graded Problem: rotate point [Canvas](https://bart.instructure.com/courses/1282/quizzes/2287)/[public](https://chadworley.github.io/ml/u01_wallpaper_groups/outhtml/03_rotate_point.html)

### Wed Aug 28

* Graded Problem: translate point [Canvas](https://bart.instructure.com/courses/1282/quizzes/2297)/[public](https://chadworley.github.io/ml/u01_wallpaper_groups/outhtml/04_translate_point.html)

### Thu Aug 28

* Continue work on wallpaper project.

### Fri Aug 29

* Continue work on wallpaper project.


# Unit 2: Build in 3D

## Week 3 {.tabset}

### Tue Sep 3

* ET: Wallpaper reflection
* XT: Brainstorm for 3D-Build Project

### Wed Sep 4

* Sketch with Sketchup (submit a png)

### Thu Sep 5

* Aleks: Initial Knowledge Check

### Fri Sep 6

* Sketchup for web fundamentals day 1
    * Go to [https://app.sketchup.com](https://app.sketchup.com).
    * Also, go to [https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1](https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1)
    * Download the exercise files.
    * Under Quick Start, watch:
        * Video 1 
        * Video 2
    * Complete the task given at the end of video 2. Export a png of your result. Submit the png on Canvas.

## Week 4 {.tabset}

### Mon Sep 9

* Sketchup for web fundamentals day 2
    * Go to [https://app.sketchup.com](https://app.sketchup.com).
    * Also, go to [https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1](https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1)
    * Under Quick Start, finish watching videos.
        * Video 3
        * Video 4
    * Complete your version of the playground structure that the videos walk you through. Submit a png file of your finished playground structure.


### Tue Sep 10

* Sketchup for web fundamentals day 3
    * Go to [https://app.sketchup.com](https://app.sketchup.com).
    * Also, go to [https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1](https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1)
    * Under Quick Start, finish watching videos.
        * Video 5
        * Video 6
    * Complete your version of the playground structure that the videos walk you through. Submit a png file of your finished playground structure.

### Wed Sep 11

* Sketchup for web fundamentals day 4
    * Go to [https://app.sketchup.com](https://app.sketchup.com).
    * Also, go to [https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1](https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1)
    * Under Quick Start, finish watching videos.
        * Video 7
    * Complete your version of the playground structure that the videos walk you through. Submit a png file of your finished playground structure.

### Thu Sep 12

* Sketchup for web fundamentals day 5
    * Go to [https://app.sketchup.com](https://app.sketchup.com).
    * Also, go to [https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1](https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1)
    * Under Quick Start, finish watching videos.
        * Video 8
        * Video 9
    * Complete your version of the playground structure that the videos walk you through. Submit a png file of your finished playground structure.

### Fri Sep 13

* Sketchup for web fundamentals day 6
    * Go to [https://app.sketchup.com](https://app.sketchup.com).
    * Also, go to [https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1](https://learn.sketchup.com/courses/sketchup-web-fundamentals-part1)
    * Under Quick Start, finish watching videos.
        * Video 10
    * Complete your version of the playground structure that the videos walk you through. Submit a png file of your finished playground structure.


## Week 5 {.tabset}

### Mon Sep 16

* Log at least 30 minutes on Aleks on your path.

### Tue Sep 17

* Log at least 30 minutes on Aleks on your path.

### Wed Sep 18

* Learn to read calipers [Canvas](https://bart.instructure.com/courses/1282/quizzes/2329)/[public](https://chadworley.github.io/ml/u02_build_3d/outhtml/read_caliper.html)
* Read-caliper master [Canvas](https://bart.instructure.com/courses/1282/quizzes/2332)
* Start [Project Vernier Caliper](https://bart.instructure.com/courses/1282/assignments/22085)

### Thu Sep 19

* Clone trinket in SketchUp. [Canvas](https://bart.instructure.com/courses/1282/assignments/22098)

### Fri Sep 20

* Clone trinket in SketchUp. [Canvas](https://bart.instructure.com/courses/1282/assignments/22098)


## Week 6 {.tabset}

### Mon Sep 23

* Project Initial Intersection [Canvas](https://bart.instructure.com/courses/1282/assignments/22281)/[public](https://chadworley.github.io/ml/u02_build_3d/Project_Intersect_Initials.html)

### Tue Sep 24

* Log 30 minutes on Aleks

### Wed Sep 25

* Field Trip

### Thu Sep 26

* Union, intersection, and subtraction in Sketchup [Canvas](https://bart.instructure.com/courses/1282/quizzes/2378)/[public](https://chadworley.github.io/ml/u02_build_3d/outhtml/union_intersect_subtract.html)

### Fri Sep 27

* Venn diagrams [practice](https://chadworley.github.io/ml/u02_build_3d/Venn__shared1.html)
* Canvas questions:
    * https://bart.instructure.com/courses/1282/quizzes/2379
    * https://bart.instructure.com/courses/1282/quizzes/2380
    * https://bart.instructure.com/courses/1282/quizzes/2381
    

## Week 7 {.tabset}

### Mon Sep 30

* Log 30 minutes on Aleks

### Tue Oct 1

* Scale rectangular prism: [Canvas](https://bart.instructure.com/courses/1282/quizzes/2387)/[public](https://chadworley.github.io/ml/u02_build_3d/outhtml/scale_rectangular_prism.html)

### Wed Oct 2

* TinkerCAD intro: [Canvas](https://bart.instructure.com/courses/1282/assignments/22404)

### Thu Oct 3

* TinkerCAD balloon car: [Canvas](https://bart.instructure.com/courses/1282/assignments/22425)



