```{r,echo=F}
while(T){
  rots = round(runif(1,0.1,10),1)
  degs = rots*360
  if(rots%%0.5 != 0){break}
}
shuch = list(c(0,degs/180*pi))
```

Question
========

Convert `r degs`$^\circ$ to rotations. How many rotations is equivalent to `r degs` degrees?

Solution
========

One rotation is equivalent to 360$^\circ$. Use this equivalence as a [conversion factor](https://en.wikipedia.org/wiki/Conversion_of_units).

$$`r degs`^\circ \cdot \frac{1~\mathrm{ rotation}}{360^\circ} ~~=~~ `r rots`~\mathrm{ rotations}$$

```{r,echo=F,fig.dim=c(4,4)}
par(pty="s")
for(i in 1:length(shuch)){
  par(mar=c(1,1,1,1),pty="s")
  plot(0,0,type="n",ann=F,axes=F,xlim=c(-1,1),ylim=c(-1,1))
  abline(h=0)
  abline(v=0)
  a1 = shuch[[i]][1]
  a2 = shuch[[i]][2]
  lines(c(0,cos(a1)),c(0,sin(a1)),col="blue",lwd=3)
  lines(c(0,cos(a2)),c(0,sin(a2)),col="blue",lwd=3)
  len = 500
  th = seq(a1,a2,(a2-a1)/len)
  if(abs(a2-a1)>2*pi){
    r = seq(0.4,0.8,0.4/len)
  } else {
    r = 0.8
  }
  len = length(th)-1
  lines(r*cos(th),r*sin(th),lwd=2,col="red")
  arrows(0.8*cos(th[len]),0.8*sin(th[len]),0.8*cos(th[len+1]),0.8*sin(th[len+1]),lwd=2,col="red",length=0.1)
  for(theta in 1:360){
    thet = theta/180*pi
    if(theta%%10==0){
      lines(c(0.9*cos(thet),cos(thet)),c(0.9*sin(thet),sin(thet)),lwd=2)
    } else {
      lines(c(0.95*cos(thet),cos(thet)),c(0.95*sin(thet),sin(thet)))
    }
  }
  for(theta in seq(0,360,36)){
    thet = theta/180*pi
    lines(c(1.1*cos(thet),cos(thet)),c(1.1*sin(thet),sin(thet)),lwd=2,col="purple")
  }
}
```
\

Meta-information
============
extype: num
exsolution: `r rots`
exname: convert_degs_to_rots