---
title: "Lesson Plan for determining if a relation is a function, and whether a function is a one-to-one function."
---

* ET (5 min)
    * 2 random SAT questions (different qs for each student)
    * Can attempt up to 5 times (with different qs each time)
    * SAT questions are mostly Algebra 1 and Geometry review
* Determine if a [relation](https://en.wikipedia.org/wiki/Binary_relation) is a function, and determine if function is [one-to-one](https://en.wikipedia.org/wiki/Injective_function):
    * [Slides](PRES_is_relation_a_function.html) (+25 min = 30 min)
    * Relation given as list of ordered pairs:
        * https://chadworley.github.io/algtwo2026/u01/outhtml/01_is_relation_a_function.html
        * Students try their classwork versions (+5 min = 35 min)
    * Relation given as plotted points:
        * https://chadworley.github.io/algtwo2026/u01/outhtml/02_are_points_a_function.html
        * Students try their classwork versions (+5 min = 40 min)
    * Relation given as line segments pointing between elements of two sets:
        * https://chadworley.github.io/algtwo2026/u01/outhtml/03_are_connections_a_function.html
        * Students try their classwork versions (+5 min = 45 min)
    * Relation given as a plotted curve:
        * https://chadworley.github.io/algtwo2026/u01/outhtml/04_is_curve_a_function.html
        * Students try their classwork versions (+5 min = 50 min)
    * Students tasked with completing repetitive practice (HW), which consists of a "quiz" containing all four types of questions.


