---
title: "Some Possible Stats Projects"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
---


# Possible project ideas to start mulling over

* Calculate a confidence interval of a proportion from a sample
  * What is the probability a coin spun on table lands heads?
  * What is your probability of making a free throw?
* Calculate a confidence interval of a mean from a sample
  * What is the average of a weighted die?
  * What is the average number of kernels in a popcorn bag?
* Determine whether a correlation exists between variables (linear regression on two continuous variables)
  * Do taller people have taller favorite animals?
* Test if difference of means or proportions is significant (best if [randomized controlled experiment](https://en.wikipedia.org/wiki/Randomized_controlled_trial){target="_blank"})
  * [https://en.wikipedia.org/wiki/Anchoring_(cognitive_bias)](https://en.wikipedia.org/wiki/Anchoring_(cognitive_bias)){target="_blank"}
  * Are you significantly better at throwing darts with your right hand than your left? (This would need discussion of your inability to properly blind the participant.)
  * Do egg shells increase the growth rate of potato plants?
  * Does singing to plants increase their growth rate?
  * Are you significantly better than your friend at Mario Kart?
  * [https://en.wikipedia.org/wiki/Stroop_effect](https://en.wikipedia.org/wiki/Stroop_effect){target="_blank"}
  * Can you complete two tasks simultaneously (significantly) faster than sequentially?
* Exemplify the central limit theorem
  * Simulate and describe a [Galton board](https://en.wikipedia.org/wiki/Galton_board){target="_blank"} 
* Design a random-number generator, and investigate its fairness
  * Do a [chi-squared test](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test#Fairness_of_dice){target="_blank"} on a weighted die.
  
  
  

  
  