---
title: "Is a relation a function? And is the function one-to-one?"
---

# Relation

* A [relation](https://en.wikipedia.org/wiki/Binary_relation) associates some elements of one set called the domain with some elements of another set (possibly the same) called the codomain. There are many ways to express relations:
* Segments connecting elements of sets:
    
```{r,echo=FALSE,fig.dim=c(5,5)}
shouldAafoB = F
shouldBafoA = T

n = 5
A = c(3,5,6,8,9)
B = c(1,9,7,5,7)
mystr = paste("(",A,", ",B,")",collapse="~~")

par(pty="s")
plot(0,0,type="n",axes = F,asp=1,xlim=c(0,10),ylim=c(0,10),ann=FALSE)
for(i in 0:9){
  text(0,i,i)
  text(10,i,i)
}
text(0,10,"x",cex=2)
text(10,10,"y",cex=2)
for(i in 1:n){
  lines(c(0.5,9.5),c(A[i],B[i]))
}
```
\

* A list of ordered pairs

$$`r mystr`$$

* A plot of points
    
```{r,echo=FALSE,fig.dim=c(5,5)}
par(pty="s")
plot(A,B,xlim=c(0,10),ylim=c(0,10),xlab="x",ylab="y",asp=1,pch=20,cex=2)
for(i in 0:10){
  abline(h=i,lty=3)
  abline(v=i,lty=3)
}
```
\

# Is relation a function?

* We say $y$ is a function of $x$ if the relation passes the [vertical line test](https://en.wikipedia.org/wiki/Vertical_line_test).

```{r,echo=FALSE,fig.dim=c(5,5)}

A = c(3,5,5,7,9)
B = c(1,3,7,5,2)

par(pty="s")
plot(A,B,xlim=c(0,10),ylim=c(0,10),xlab="x",ylab="y",asp=1,pch=20,cex=2,main="This relation FAILS the vertical line test.\nSo y is not a function of x.")
for(i in 0:10){
  abline(h=i,lty=3)
  abline(v=i,lty=3)
}
abline(v=5,col="red")
```
\






