---
output: pdf_document
geometry: margin=0.7cm
---

```{r,echo=F}
vspaceminus = -0.9
```

\vfill

Frieze Patterns with Stencils \hspace{3in} Name:

```{r,echo=F,fig.dim=c(8,2),fig.align='center'}
par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(0,8),ylim=c(0,2),axes=F,ann=F)
for(i in c(0,2,4,6,8)){
    lines(c(i,i),c(0,2))
}
lines(c(0,8),c(0,0))
lines(c(0,8),c(2,2))
text(0,1,"p1 (hop)",adj=c(0.5,-0.5),srt=90)
```

\vspace{`r vspaceminus`cm}

```{r,echo=F,fig.dim=c(8,2),fig.align='center'}
par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(0,8),ylim=c(0,2),axes=F,ann=F)
for(i in c(0,2,4,6,8)){
    lines(c(i,i),c(0,2))
}
lines(c(0,8),c(0,0))
lines(c(0,8),c(2,2))
text(0,1,"p11g (step)",adj=c(0.5,-0.5),srt=90)
```


\vspace{`r vspaceminus`cm}

```{r,echo=F,fig.dim=c(8,2),fig.align='center'}
par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(0,8),ylim=c(0,2),axes=F,ann=F)
for(i in c(0,2,4,6,8)){
    lines(c(i,i),c(0,2))
}
lines(c(0,8),c(0,0))
lines(c(0,8),c(2,2))
text(0,1,"p1m1 (sidle)",adj=c(0.5,-0.5),srt=90)
```

\vspace{`r vspaceminus`cm}

```{r,echo=F,fig.dim=c(8,2),fig.align='center'}
par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(0,8),ylim=c(0,2),axes=F,ann=F)
for(i in c(0,2,4,6,8)){
    lines(c(i,i),c(0,2))
}
lines(c(0,8),c(0,0))
lines(c(0,8),c(2,2))
text(0,1,"p2 (spinning hop)",adj=c(0.5,-0.5),srt=90)
```


\vspace{`r vspaceminus`cm}

```{r,echo=F,fig.dim=c(8,2),fig.align='center'}
par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(0,8),ylim=c(0,2),axes=F,ann=F)
for(i in c(0,2,4,6,8)){
    lines(c(i,i),c(0,2))
}
lines(c(0,8),c(0,0))
lines(c(0,8),c(2,2))
text(0,1,"p2mg (spinning sidle)",adj=c(0.5,-0.5),srt=90)
```


\vspace{`r vspaceminus`cm}

```{r,echo=F,fig.dim=c(8,4),fig.align='center'}
par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(0,8),ylim=c(0,4),axes=F,ann=F)
for(i in c(0,2,4,6,8)){
    lines(c(i,i),c(0,4))
}
lines(c(0,8),c(0,0))
lines(c(0,8),c(2,2))
lines(c(0,8),c(4,4))
text(0,2,"p11m   (jump)",adj=c(0.5,-0.5),srt=90)
```

\vfill

```{r,echo=F,fig.dim=c(8,4),fig.align='center'}
par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(0,8),ylim=c(0,4),axes=F,ann=F)
for(i in c(0,2,4,6,8)){
    lines(c(i,i),c(0,4))
}
lines(c(0,8),c(0,0))
lines(c(0,8),c(2,2))
lines(c(0,8),c(4,4))
text(0,2,"p2mm (spinning jump)",adj=c(0.5,-0.5),srt=90)
```

\vfill