---
header-includes:
   - \usepackage{array}
   - \usepackage{color}
   - \usepackage{tabularx}
output: pdf_document
params:
    rseed: 1
    showsol: true
    titex: "Practice"
urlcolor: blue
---

Name: \hspace{4in} Date: \hfill \vspace{3pt} \hrule

## \sc u15ws2: Draw Waves

<!-- 1 -->
```{r q1prep,echo=F}
P = sample(c(4,6,8,10),1)
A = sample(c(2,3,4),1)*sample(c(-1,1),1)
D = sample(c(-2,-1,1,2),1)
cs = sample(c("cos","sin"))
x = seq(-10,10,0.05)
if(cs[1]=="cos"){
    y = A*cos(2*pi/P*x)+D
    st = paste0("y=",A,"\\cos\\left(\\frac{\\pi}{",round(P/2),"}t\\right)+",D)
    st = gsub("+-","-",st,fixed=T)
}
if(cs[1]=="sin"){
    y = A*sin(2*pi/P*x)+D
    st = paste0("y=",A,"\\sin\\left(\\frac{\\pi}{",round(P/2),"}t\\right)+",D)
    st = gsub("+-","-",st,fixed=T)
}
```


1. Plot $`r st`$.

```{r,echo=F,fig.dim=c(7,3.5)}
par(mar=c(0,0,0,0))
plot(0,0,"n",axes=F,ann=F,xlim=c(-10,10),ylim=c(-6,6),asp=1)
for(xx in seq(-10,10,1)){
    lines(c(xx,xx),c(-6,6),col="grey",lwd=0.8)    
}
for(yy in seq(-6,6,1)){
    lines(c(-10,10),c(yy,yy),col="grey",lwd=0.8)    
}
for(xx in seq(-10,10,5)){
    lines(c(xx,xx),c(-6,6),col="darkgrey",lwd=1.2)    
}
for(yy in seq(-5,5,5)){
    lines(c(-10,10),c(yy,yy),col="darkgrey",lwd=1.2)    
}
arrows(-10.5,0,10.5,0,0.1,15,3,lwd=1.5)
arrows(0,-6.5,0,6.5,0.1,15,3,lwd=1.5)
text(10.5,0,"t",adj=c(0.5,1.3))
text(10,0,"10",adj=c(0.5,-0.3))
text(-10,0,"-10",adj=c(0.5,-0.3))
text(0,6.3,"y",adj=c(1.3,0.5))
text(0,5,"5",adj=c(-0.3,0.5))
text(0,-5,"-5",adj=c(-0.3,0.5))

if(params$showsol){
    lines(x,y,col="red",lwd=2)
    ttt = seq(-5*P,5*P,P/4)
    ttt = ttt[abs(ttt)<=10]
    if(cs[1]=="cos"){
        points(ttt,A*cos(2*pi/P*ttt)+D,pch=19,col="red")
    } else {
        points(ttt,A*sin(2*pi/P*ttt)+D,pch=19,col="red")
    }
    
}
```

\vfill
\vfill

<!-- 2 -->
```{r q2prep,echo=F}
P = sample(c(4,6,8,10),1)
A = sample(c(2,3,4),1)*sample(c(-1,1),1)
D = sample(c(-2,-1,1,2),1)
# cs = sample(c("cos","sin"))
x = seq(-10,10,0.05)
if(cs[2]=="cos"){
    y = A*cos(2*pi/P*x)+D
    st = paste0("y=",A,"\\cos\\left(\\frac{\\pi}{",round(P/2),"}t\\right)+",D)
    st = gsub("+-","-",st,fixed=T)
}
if(cs[2]=="sin"){
    y = A*sin(2*pi/P*x)+D
    st = paste0("y=",A,"\\sin\\left(\\frac{\\pi}{",round(P/2),"}t\\right)+",D)
    st = gsub("+-","-",st,fixed=T)
}
```


2. Plot $`r st`$.

```{r,echo=F,fig.dim=c(7,3.5)}
par(mar=c(0,0,0,0))
plot(0,0,"n",axes=F,ann=F,xlim=c(-10,10),ylim=c(-6,6),asp=1)
for(xx in seq(-10,10,1)){
    lines(c(xx,xx),c(-6,6),col="grey",lwd=0.8)    
}
for(yy in seq(-6,6,1)){
    lines(c(-10,10),c(yy,yy),col="grey",lwd=0.8)    
}
for(xx in seq(-10,10,5)){
    lines(c(xx,xx),c(-6,6),col="darkgrey",lwd=1.2)    
}
for(yy in seq(-5,5,5)){
    lines(c(-10,10),c(yy,yy),col="darkgrey",lwd=1.2)    
}
arrows(-10.5,0,10.5,0,0.1,15,3,lwd=1.5)
arrows(0,-6.5,0,6.5,0.1,15,3,lwd=1.5)
text(10.5,0,"t",adj=c(0.5,1.3))
text(10,0,"10",adj=c(0.5,-0.3))
text(-10,0,"-10",adj=c(0.5,-0.3))
text(0,6.3,"y",adj=c(1.3,0.5))
text(0,5,"5",adj=c(-0.3,0.5))
text(0,-5,"-5",adj=c(-0.3,0.5))

if(params$showsol){
    lines(x,y,col="red",lwd=2)
    ttt = seq(-5*P,5*P,P/4)
    ttt = ttt[abs(ttt)<=10]
    if(cs[2]=="cos"){
        points(ttt,A*cos(2*pi/P*ttt)+D,pch=19,col="red")
    } else {
        points(ttt,A*sin(2*pi/P*ttt)+D,pch=19,col="red")
    }
    
}
```

\vfill
\vfill





\newpage

<!-- 3 -->

```{r q3prep,echo=F}
P = sample(c(4,6,8,10),1)
A = sample(c(2,3,4),1)*sample(c(-1,1),1)
D = sample(c(-2,-1,1,2),1)
cs = sample(c("cos","sin"))
x = seq(-10,10,0.05)
if(cs[1]=="cos"){
    y = A*cos(2*pi/P*x)+D
    st = paste0("y=",A,"\\cos\\left(\\frac{\\pi}{",round(P/2),"}t\\right)+",D)
    st = gsub("+-","-",st,fixed=T)
}
if(cs[1]=="sin"){
    y = A*sin(2*pi/P*x)+D
    st = paste0("y=",A,"\\sin\\left(\\frac{\\pi}{",round(P/2),"}t\\right)+",D)
    st = gsub("+-","-",st,fixed=T)
}
```

3. Give an equation for the plot below:

```{r,echo=F,fig.dim=c(7,3.5)}
par(mar=c(0,0,0,0))
plot(0,0,"n",axes=F,ann=F,xlim=c(-10,10),ylim=c(-6,6),asp=1)
for(xx in seq(-10,10,1)){
    lines(c(xx,xx),c(-6,6),col="grey",lwd=0.8)    
}
for(yy in seq(-6,6,1)){
    lines(c(-10,10),c(yy,yy),col="grey",lwd=0.8)    
}
for(xx in seq(-10,10,5)){
    lines(c(xx,xx),c(-6,6),col="darkgrey",lwd=1.2)    
}
for(yy in seq(-5,5,5)){
    lines(c(-10,10),c(yy,yy),col="darkgrey",lwd=1.2)    
}
arrows(-10.5,0,10.5,0,0.1,15,3,lwd=1.5)
arrows(0,-6.5,0,6.5,0.1,15,3,lwd=1.5)
text(10.5,0,"t",adj=c(0.5,-0.3))
text(10,0,"10",adj=c(0.5,1.3))
text(-10,0,"-10",adj=c(0.5,1.3))
text(0,6.3,"y",adj=c(-0.3,0.5))
text(0,5,"5",adj=c(1.3,0.5))
text(0,-5,"-5",adj=c(1.3,0.5))

lines(x,y,col="blue",lwd=2)
ttt = seq(-5*P,5*P,P/4)
ttt = ttt[abs(ttt)<=10]
if(cs[1]=="cos"){
    points(ttt,A*cos(2*pi/P*ttt)+D,pch=19,col="blue")
} else {
    points(ttt,A*sin(2*pi/P*ttt)+D,pch=19,col="blue")
}
```

\vfill

```{r,echo=F,results='asis'}
if(params$showsol){
    cat(paste0("\\color{red}$$",st,"$$\n\\color{black}"))
}
```

\vfill

<!-- 4 -->

```{r q4prep,echo=F}
P = sample(c(4,6,8,10),1)
A = sample(c(2,3,4),1)*sample(c(-1,1),1)
D = sample(c(-2,-1,1,2),1)
# cs = sample(c("cos","sin"))
x = seq(-10,10,0.05)
if(cs[2]=="cos"){
    y = A*cos(2*pi/P*x)+D
    st = paste0("y=",A,"\\cos\\left(\\frac{\\pi}{",round(P/2),"}t\\right)+",D)
    st = gsub("+-","-",st,fixed=T)
}
if(cs[2]=="sin"){
    y = A*sin(2*pi/P*x)+D
    st = paste0("y=",A,"\\sin\\left(\\frac{\\pi}{",round(P/2),"}t\\right)+",D)
    st = gsub("+-","-",st,fixed=T)
}
```

4. Give an equation for the plot below:

```{r,echo=F,fig.dim=c(7,3.5)}
par(mar=c(0,0,0,0))
plot(0,0,"n",axes=F,ann=F,xlim=c(-10,10),ylim=c(-6,6),asp=1)
for(xx in seq(-10,10,1)){
    lines(c(xx,xx),c(-6,6),col="grey",lwd=0.8)    
}
for(yy in seq(-6,6,1)){
    lines(c(-10,10),c(yy,yy),col="grey",lwd=0.8)    
}
for(xx in seq(-10,10,5)){
    lines(c(xx,xx),c(-6,6),col="darkgrey",lwd=1.2)    
}
for(yy in seq(-5,5,5)){
    lines(c(-10,10),c(yy,yy),col="darkgrey",lwd=1.2)    
}
arrows(-10.5,0,10.5,0,0.1,15,3,lwd=1.5)
arrows(0,-6.5,0,6.5,0.1,15,3,lwd=1.5)
text(10.5,0,"t",adj=c(0.5,-0.3))
text(10,0,"10",adj=c(0.5,1.3))
text(-10,0,"-10",adj=c(0.5,1.3))
text(0,6.3,"y",adj=c(-0.3,0.5))
text(0,5,"5",adj=c(1.3,0.5))
text(0,-5,"-5",adj=c(1.3,0.5))

lines(x,y,col="blue",lwd=2)
ttt = seq(-5*P,5*P,P/4)
ttt = ttt[abs(ttt)<=10]
if(cs[2]=="cos"){
    points(ttt,A*cos(2*pi/P*ttt)+D,pch=19,col="blue")
} else {
    points(ttt,A*sin(2*pi/P*ttt)+D,pch=19,col="blue")
}
```

\vfill

```{r,echo=F,results='asis'}
if(params$showsol){
    cat(paste0("\\color{red}$$",st,"$$\n\\color{black}"))
}
```

\vfill
