---
title: "Statistics Research Project"
output: pdf_document
---


# Project Description

In this open-ended Statistics project, each student will have the opportunity to **collect data** and **analyze the data** by constructing one or more confidence intervals (and/or $p$-values). The project aims to provide students with a hands-on experience in applying statistical concepts and techniques to real-life situations.

Students will be encouraged to choose a topic of interest that allows them to incorporate something they enjoy into their project. For example, they could investigate the probability of making a free throw by shooting 100 free throws, or explore whether singing to seedlings influences their growth rate.

The project will consist of the following components:

* Data Collection: Each student will collect their own data by conducting experiments or surveys related to their chosen topic. The methodology should be carefully considered and reported.
* Data Analysis: Using the collected data, students will calculate one or more confidence intervals that indicate estimates (and uncertainties) of parameters (such as a probability or a population mean). For more advanced projects, a significance test's $p$-value can be reported instead of a confidence interval.
* Interpretation: Students will interpret their confidence intervals (or $p$-values) in the context of their chosen topic. They should explain what the confidence intervals represent, what the confidence level indicates, and any potential limitations or assumptions of their analysis.
* Report: Each student will present their findings as a paper, in-class presentation, or video. Reports should be clear, concise, and engaging, and should effectively communicate the main ideas, methodology, and results of the project.

# Parts of a research report

Below is a rough guide to a standard research report. 

* Abstract
  * The abstract is a overview of the whole report. It summarizes everything in a single paragraph. I recommend writing the abstract last, but placing it in the beginning of the report.
* Background
  * Why did you pick this research topic? 
  * Why should other people find this interesting? 
  * What other work have people done on this topic or similar topics?
* Methods
  * As precisely as possible, describe how you collected the data.
  * How did you try to minimize bias in your sampling method?
  * How did you randomly assign participants while keeping them blind to their treatment?
* Analysis
  * How did you analyze the data? 
  * What equations did you use? 
  * What confidence intervals or $p$-values did you calculate?
* Discussion
  * How should we interpret your analysis?
  * What are some possible sources of bias?
  * What new questions occurred to you during this research that someone else might explore?
* Bibliography
  * If you cited other work, please list the citations in a consistent manner.


# Grading rubric


| Criteria | Points |
|----------------------|---:|
| State your research question and why it's interesting. | 5 |
| Clearly explain the methodology used to collect data. | 5 |
| Provide a link to the raw data (probably stored in a shared google sheet). | 2 |
| Consider the potential for bias in the sample, and attempt to minimize it. | 3 |
| Calculate appropriate sample statistics (some possibilities: $n$, $\hat{p}$, $\bar{x}$, $s$) | 5 |
| Accurately calculate confidence intervals or $p$-values; show formulas. | 5 |
| Interpret the meaning of the confidence intervals or p-values for your context. | 5 |
| Present findings in a clear, concise, and engaging manner | 5 |
| Show creativity and originality in the approach and presentation of the project | 5  |



