---
title: "Algebra 1 Topics: weekly outline"
author: Chad Worley
date: "`r format(Sys.time(), '%Y %B %d')`"
output:
  html_document:
    toc: true
    toc_depth: 2
---

## Week 1: Aug 21 - Aug 25

### Monday Aug 21

* Half day for 6th and 9th graders.

### Tuesday Aug 22

* **Entrance:** 
  * Getting-to-know-you survey
* **Objectives:** 
  * Get overview of class
* **Agenda:** 
  * Introductions
* **Homework:**
  * None
  
### Wednesday Aug 23

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Solve 2-step equations.
* **Agenda:** 
  * [Kuta: two step equations (integers)](https://cdn.kutasoftware.com/Worksheets/PreAlg/Two-Step%20Equations%20With%20Integers.pdf){target="_blank"}
* **Homework:**
  * None
  
### Thursday Aug 24

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Solve 2-step equations.
* **Agenda:** 
  * [Kuta: two step equations](https://cdn.kutasoftware.com/Worksheets/Alg1/Two-Step%20Equations.pdf){target="_blank"}
* **Homework:**
  * None
  
### Friday Aug 25

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Categorize numbers as counting, rational, irrational, etc.
* **Agenda:** 
  * [Real Numbers Worksheet](https://drive.google.com/file/d/1g9ocH8kj57xVqGSiqj6Ey2G1MVpKN5_n/view?usp=drive_link){target="_blank"}
* **Homework:**
  * None

## Week 2: Aug 28 - Sep 1

### Monday Aug 28

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Correctly apply the order of operations to evaluate expressions.
* **Agenda:** 
  * [Order-of-Operations Worksheet](https://drive.google.com/file/d/1Uejis5TCCsnLlPzMRmK3NHnODxFdhn20/view?usp=drive_link){target="_blank"}
* **Homework:**
  * None
  
### Tuesday Aug 29

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Simplify fractions.
* **Agenda:** 
  * [Simplifying fractions worksheet](https://drive.google.com/file/d/12gruU-BfSaf9r6c_0l_hmgRC6k4KhvgS/view?usp=drive_link){target="_blank"}
* **Homework:**
  * None

### Wednesday Aug 30

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Use the exponent rules to simplify and evaluate expressions
* **Agenda:** 
  * [Exponent-rules worksheet](https://drive.google.com/file/d/19TSZnQWgvTQB0Vq4TU6eZOLGn1OROwsg/view?usp=drive_link){target="_blank"}
* **Homework:**
  * None

### Thursday Aug 31

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Translate expressions between natural language and algebraic symbols.
* **Agenda:** 
  * [Expression translation worksheet](https://drive.google.com/file/d/1LeHWQ8YF-yxgpw0PWfxeCFnm32GYkVKN/view?usp=drive_link){target="_blank"}
* **Homework:**
  * None

### Friday Sep 01

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Evaluate expressions when provided values for the variables.
* **Agenda:** 
  * [Evaluating expressions worksheet](https://drive.google.com/file/d/1oMgNJlcuWbSvyTe4-H6B_PkwjuSdgQIo/view?usp=drive_link){target="_blank"}
* **Homework:**
  * None
  
## Week 3: Sep 04 - Sep 08

### Mon Sep 04

* Holiday

### Tue Sep 05

* I-ready testing

### Wed Sep 06

* I-ready testing

### Thu Sep 07

* I-ready testing

### Fri Sep 08

* I-ready testing

## Week 4: Sep 11 - Sep 15

### Mon Sep 11

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Practice problem-solving skills, using elementary- and middle-school math olympiad questions.
* **Agenda:** 
  * Solve questions from Olympiad 1 from Dr. George Lenchner's Contest Problems
* **Homework:**
  * None
  
### Tue Sep 12

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Practice problem-solving skills, using elementary- and middle-school math olympiad questions.
* **Agenda:** 
  * Solve questions from Olympiad 2 from Dr. George Lenchner's Contest Problems
* **Homework:**
  * None
  
### Wed Sep 13

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Practice problem-solving skills, using elementary- and middle-school math olympiad questions.
* **Agenda:** 
  * Solve questions from Olympiad 3 from Dr. George Lenchner's Contest Problems
* **Homework:**
  * None
  
### Thu Sep 14

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Practice problem-solving skills, using elementary- and middle-school math olympiad questions.
* **Agenda:** 
  * Solve questions from Olympiad 4 from Dr. George Lenchner's Contest Problems
* **Homework:**
  * None
  
### Fri Sep 15

* **Entrance:** 
  * [Estimation 180](https://estimation180.com/){target="_blank"}
* **Objectives:** 
  * Practice problem-solving skills, using elementary- and middle-school math olympiad questions.
* **Agenda:** 
  * Solve questions from Olympiad 5 from Dr. George Lenchner's Contest Problems
* **Homework:**
  * None

