---
title: "Riley's problem"
output: 
    html_document:
        toc: true

---

# Problem statement

Each day a student is given 3 multiple-choice questions with 4 possible choices but only 1 correct choice. Students are given 3 attempts; after each attempt they are told how many questions they got right, but not which questions were correct.

On each attempt, the questions and choices remain constant, and students remember their past guesses and results.

Also, in this class, only the highest score (of the 3 attempts) counts. So, we are not "simply" maximizing the expected points of the third attempt. I'm not sure if this matters yet, but I think it will.

If we assume the students do not read the questions, but use an optimal strategy, then what is the expected number of correct questions?

# Enumeration of possible sequences:

There is a lot of variability to consider.

* How many questions did student get correct on first attempt? This will follow a binomial distribution.
* What strategy is used on the second attempt? Hopefully we can identify the optimal strategies...
* How many questions did the student get correct on second attempt?
* What strategy is used on the third attempt?

## Binomial distribution of first attempt

Let random variable $X$ represent the number of points on first attempt.

$$P(X=0)~=~\left(\frac{3}{4}\right)^3~\approx~`r 0.75^3`$$
$$P(X=1)~=~3\left(\frac{3}{4}\right)^2\left(\frac{1}{4}\right)~\approx~`r 3*0.75^2*0.25`$$
$$P(X=2)~=~3\left(\frac{1}{4}\right)^2\left(\frac{3}{4}\right)~\approx~`r 3*0.75*0.25^2`$$
$$P(X=3)~=~\left(\frac{1}{4}\right)^3~\approx~`r 0.25^3`$$

We can calculate the expected points of the first attempt:

$$\mathrm{EV}(X)~=~0\cdot \left(\frac{3}{4}\right)^3 ~+~ 1\cdot 3\left(\frac{3}{4}\right)^2\left(\frac{1}{4}\right) ~+~ 2\cdot 3\left(\frac{1}{4}\right)^2\left(\frac{3}{4}\right)~+~3\cdot \left(\frac{1}{4}\right)^3 ~=~ \frac{3}{4}$$

Of course... since each question was independent, and each had a 1/4 chance of a point... we could have known the expected number of points was simply $3\cdot\frac{1}{4}$.


## First attempt gets 0 correct

When student misses all 3 on the first attempt, the only reasonable strategy is to randomly select 3 new choices. The second attempt will follow a binomial distribution. Let random variable $Y$ equal points on 2nd attempt.

$$P(Y=0|X=0)~=~\left(\frac{2}{3}\right)^3 ~\approx~ `r (2/3)^3`$$
$$P(Y=1|X=0)~=~3\left(\frac{2}{3}\right)^2\left(\frac{1}{3}\right) ~\approx~ `r 3*(2/3)^2*(1/3)`$$
$$P(Y=2|X=0)~=~3\left(\frac{2}{3}\right)\left(\frac{1}{3}\right)^2 ~\approx~ `r 3*(2/3)*(1/3)^2`$$
$$P(Y=3|X=0)~=~\left(\frac{1}{3}\right)^3 ~\approx~ `r (1/3)^3`$$

Also, given the first attempt got 0 correct, we can calculate the expected value of the 2nd attempt.

$$\mathrm{EV}(Y|X=0)~~=~~ 0\cdot \left(\frac{2}{3}\right)^3~+~1\cdot 3\left(\frac{2}{3}\right)^2\left(\frac{1}{3}\right)~+~2\cdot 3\left(\frac{2}{3}\right)\left(\frac{1}{3}\right)^2~+~3\cdot \left(\frac{1}{3}\right)^3$$

Of course, the easier way is to recognize each question is independent. Each question has a 1/3 chance of getting a point.

$$\mathrm{EV}(Y|X=0)~~=~~ 3\cdot\frac{1}{3}~=~1$$

### First attempt gets 0 correct and second attempt gets 0 correct

If the student has gotten $X=0$ and $Y=0$, then again the best strategy is to pick new choices for all three questions. Again, the possible points follow a binomial distribution. Let $Z$ represent the points on the third attempt.

$$P(Z=0 | X=0 \cap Y=0)~=~ \left(\frac{1}{2}\right)^3 ~\approx~ `r (1/2)^3`$$
$$P(Z=1 | X=0 \cap Y=0)~=~ 3\cdot\left(\frac{1}{2}\right)^2\left(\frac{1}{2}\right) ~\approx~ `r 3*(1/2)^3`$$
$$P(Z=2 | X=0 \cap Y=0)~=~ 3\cdot\left(\frac{1}{2}\right)\left(\frac{1}{2}\right)^2 ~\approx~ `r 3*(1/2)^3`$$
$$P(Z=3 | X=0 \cap Y=0)~=~ \left(\frac{1}{2}\right)^3 ~\approx~ `r (1/2)^3`$$

Let's just find the expected value the easy way:

$$\mathrm{EV}(Z|X=0\cap Y=0)~=~3\cdot \frac{1}{2}~=~\frac{3}{2}$$

### First attempt gets 0 correct and second attempt gets 1 correct

Now things are getting interesting. We need to consider various strategies. We can select 3 unchosen choices, keep 1 choice the same, keep 2 choices the same, or keep all 3 the same. Clearly, we are not interested in the last option, because only the highest attempt matters, and keeping all 3 choices simply guarantees the last attempt's score matches the second attempt's score.

#### First attempt gets 0 correct, second attempt gets 1 correct, keep no priors

$$P(Z=0|X=0\cap Y=0 \cap \text{keep no priors})~=~\left(\frac{1}{2}\right)^2$$
$$P(Z=1|X=0\cap Y=0 \cap \text{keep no priors})~=~2\left(\frac{1}{2}\right)^2$$
$$P(Z=2|X=0\cap Y=0 \cap \text{keep no priors})~=~\left(\frac{1}{2}\right)^2$$


$$\mathrm{EV}(Z|X=0\cap Y=0 \cap \text{keep no priors})~=~ 1$$

#### First attempt gets 0 correct, second attempt gets 1 correct, keep 1 prior







