```{r data generation, echo = FALSE, results = "hide"}
funs = list(c("$\\lvert x \\rvert$","absolute value",function(x){abs(x)}),
            c("$x^2$","quadratic",function(x){x^2}),
            c("$x^3$","cubic",function(x){x^3}),
            c("$\\frac{1}{x}$","reciprocal",function(x){1/x}),
            c("$\\sqrt{x}$","square root",function(x){x^(1/2)}),
            c("$\\sqrt[3]{x}$","cube root",function(x){abs(x)^(1/3)*sign(x)}),
            c("$2^x$","exponential",function(x){2^x}),
            c("$\\log_{2}(x)$","logarithmic",function(x){log(x)/log(2)})
            )

n = length(funs)
w = sample(1:n,1)
fe = funs[[w]][1]
fn = funs[[w]][2]
ff = funs[[w]][3]

hk = sample(1:6,2)

```

Question
========

```{r,echo=F,warning=F}
library(kableExtra)

names = character()
lats = character()
for(i in 1:length(funs)){
    lats = c(lats,funs[[i]][[1]])
    names = c(names,funs[[i]][[2]])
}
df = data.frame(names,lats)
colnames(df) = c("names","expressions")
kable(df) %>%
    kable_styling("bordered",full_width = F)

```




Answerlist
--------



Solution
========



Meta-information
============
extype: cloze
exclozetype: schoice|schoice
exsolution: 
exname: match_parent_functions
exshuffle: false