```{r data generation, echo = FALSE, results = "hide"}
knitr::opts_chunk$set(echo = FALSE)
options(scipen=100)

# sample size
# total
# mean
# median
# a count <, <=, >, >=
# a proportion <, <=, >, >=

while(T){
  n = sample(8:12,1)
  a = sample(3:6,1)*10
  w = 40 #sample(2:4,1)*10
  b = a+w
  x = sample(a:b,n,T)
  
  xlo = min(x)
  xhi = max(x)
  
  tot = sum(x)
  xbar = mean(x)
  med = median(x)
  b1 = sample(xlo:xhi,1)
  cs = c(sum(x<b1),sum(x<=b1),sum(x>b1),sum(x>=b1))
  b2 = sample(xlo:xhi,1)
  ps = c(mean(x<b2),mean(x<=b2),mean(x>b2),mean(x>=b2))
  
  types = sample(1:4,2)
  syms = c("<","\\le",">","\\ge")
  cnt = cs[types[1]]
  prp = ps[types[2]]
  if(cnt>1 || cnt<(n-1) || prp>0.08 || prp<0.92){break}
}

```

Question
========

A spinner was made to model a [discrete-uniform distribution](https://en.wikipedia.org/wiki/Discrete_uniform_distribution).

```{r,fig.dim=c(6,6)}
par(mar=c(0,0,0,0),pty="s")
plot(0,0,type="n",xlim=c(-1,1),ylim=c(-1,1),axes=F,ann=F)
W = w+1
vals = a:b
t = seq(0,2*pi,pi/100)
t2 = seq(0,2*pi,length.out=(W+1))
t3 = (t2[1:W]+t2[2:(W+1)])/2
polygon(sin(t),cos(t))
for(tt in t2){
  lines(c(0,sin(tt)),c(0,cos(tt)))
}
for(i in 1:W){
  text(sin(t3[i])*0.8,cos(t3[i])*0.8,vals[i])
}
arrows(-0.4,-0.2,0.4,0.2,)
```


<style type="text/css" rel="stylesheet">
.bordered-table {
    border-collapse: collapse;
    border-spacing: 0;
    border:2px solid #000000;
}
.bordered-table th {
    border:2px solid #000000;
    padding: 4px;
}
.bordered-table td{
    border:2px solid #000000;
    padding: 4px;
}
</style>


```{r tab_data, echo=FALSE, results="asis"}
opts <- options(knitr.kable.NA = "")
mydf = data.frame(x)
colnames(mydf) = c("Values")
knitr::kable(mydf,format="html", align = "c",row.names=F,table.attr='class="bordered-table"')
```
\


Solution
========



Meta-information
================
extype: cloze
exsolution: 
exclozetype: 
exname: CI 2 means MC