---
title: "Dice-rolling project"
output:
  pdf_document:
    toc: no
  html_document:
    toc: yes
---

# Simulate 100d6, with 1000 repetitions.

This simulation is getting a bit unwieldy to code into a spreadsheet. Instead, 

1. [https://chadworley.github.io/cltsim.html?poss=1\*2\*3\*4\*5\*6&wght=1\*1\*1\*1\*1\*1&nnn=100](https://chadworley.github.io/cltsim.html?poss=1*2*3*4*5*6&wght=1*1*1*1*1*1&nnn=100&nreps=1000){target="_blank"}
2. Make sure the probability distribution matches a 6-sided die.
3. Make sure $n=100$.
4. Make sure the number of repetitions is 1000.
5. Click "Get Sample!"
6. Click "Copy Text Area"

# Paste the data into a spreadsheet.

7. Open a new sheet.
8. Click on cell A1.
9. Paste.

# Make a histogram of the 1000 sums

10. Highlight the first column (click on the top of the column, where it says "A").
11. Insert; chart
12. Set the chart type to histogram (or "Histogram Chart").
13. Click "Customize".
14. Click "Histogram".
15. Set the bucket size to 10.
16. Click "Chart & axis titles"
17. Name the chart "MY NAME rolled 100 6-sided dice 1000 times!"
18. Change the horizontal axis label to "The sum of 100 dice"
19. Change the vertical axis label to "Frequency"

# Paste the histogram into a google doc

20. Open a new doc.
21. Type your name at the top.
22. Type something like, "I repeatedly simulated the act of rolling 100 standard dice and getting their total."
23. Paste the histogram. (We will add more information to this doc soon.)
24. Calculate the expected sum (also called the expected total). Remember, for a fair 6-sided die, $\mu=3.5$. Also, we use $n$ to represent our sample size (which is 100 in this case).
$$E(100\text{d}6) = n\mu$$
25. Calculate the margin of error (twice the standard error, which you can find on the simulation webpage). 
$$\text{ME} = 2\sigma\sqrt{n}$$
26. Estimate the percentage of sums that are within the margin of error from the expected sum. In other words, what fraction of sums are between $n\mu-2\sigma\sqrt{n}$ and $n\mu+2\sigma\sqrt{n}$?

# Roll some real dice

27. As a class, roll 100 standard dice and get the total.
28. In the doc, write something like, "the class rolled 100 standard dice and got a total of __".
29. Write whether the total is within the margin of error from the expected total.
30. As a class, roll 100 special 3-D printed dice and get the total.
31. In the doc, write something like, "the class rolled 100 special 3-D printed dice and got a total of __".
32. Write whether the total is within the margin of error from the expected total.

# Analyze the results

33. In the doc, discuss what conclusions you draw from the data and the simulation.
34. Export the doc as a pdf.
35. Submit your work on Canvas.


