---
title: "007_running_ave_proj"
date: "`r Sys.Date()`"
output: pdf_document
---

## Roll dice, get running averages

1. In cells A1:A6 put the numbers 1, 2, 3, 4, 5, and 6.
2. In B1 type `N`
3. In B2 type `=count(A1:A100)`
4. In B3 type `mu`
5. In B4 type `=average(A1:A100)`
6. In B5 type `sigma`
7. In B6 type `=stdevp(A1:A100)`
8. In D1 type `=index($A$1:$A$100,RANDBETWEEN(1,$B$2),1)`, and drag formula down to D100
9. In A101 type `=1`
10. In A102 type `=A101+1`, and drag down to A200
11. In D101 type `=average(D$1:D1)`, and drag down to D200
12. Highlight D1:D200, and drag right until column Z
13. Highlight A101:Z200, and click `Insert` and `Chart`
14. For `Chart type` select `Line`
15. At bottom of `Setup` menu, click the checkbox `Use column A as labels`
16. In `Customize`, under `Chart & axis titles`, set the title to `Running averages`
17. Set the horizontal axis title to `i`
18. Set the vertical axis title to `xbar` or `sample mean`
19. Under `Series`, set the line color to black with opacity of 50%

## Add curves for $\mu-\frac{2\sigma}{\sqrt{i}}$ and $\mu+\frac{2\sigma}{\sqrt{i}}$

1. In cell B101 type `=B$4-2*B$6/sqrt(A101)`
1. In cell C101 type `=B$4+2*B$6/sqrt(A101)`
1. Highlight B101:C101, drag down to row 200
1. Add those columns as series on the line chart. Color = red, opacity = 100%

## Make histogram of all means at $i=100$.

1. Highlight D200:Z200
1. Insert chart (histogram)
1. Mark the checkbox `Switch rows / columns`
1. Set the bin size
1. Title the histogram
1. Label the axes

## Calculate sample statistics for rolls at $i=1$ and means at $i=100$

1. In B8 type `xbar of first rolls`
1. In B9 type `=average(D101:Z101)`
1. In B10 type `s of first rolls`
1. In B11 type `=stdev(D101:Z101)`
1. In B13 type `xbar of final averages`
1. In B14 type `=average(D200:Z200)`
1. In B15 type `s of final averages`
1. In B16 type `=stdev(D200:Z200)`

## Document your work

1. Open a new (google) Doc
1. Write your name
1. Describe what you did
1. Paste the running-means chart into the doc
1. Describe what the grey lines are
1. Describe what the red curves are
1. Paste the histogram into the doc
1. Explain the histogram
1. Report the population parameters
1. Report the sample statistics of the rolls at $i=1$
1. Report the sample statistics of the means at $i=100$
1. Submit on Canvas.


