---
output: html_document
geometry: margin=1in 
params:
    rseed: 0
    showsol: true
    useseed: false
    titex: "PCW_09_30: Write Curve Equations"
urlcolor: blue
---

PCW_0930_v`r params$rseed`: Write the equation for each shifted parent function.... NAME:

```{r,echo=F,warning=F}
if(params$useseed){
    set.seed(params$rseed)
}
fun2 = list(c("|x|","absolute value",function(x){abs(x)}),
            c("(x)^2","quadratic",function(x){x^2}),
            c("(x)^3","cubic",function(x){x^3}),
            c("\\frac{1}{x}","reciprocal",function(x){1/x}),
            c("\\sqrt{x}","square root",function(x){x^(1/2)}),
            c("\\sqrt[3]{x}","cube root",function(x){abs(x)^(1/3)*sign(x)}),
            c("2^{x}","exponential",function(x){2^x}),
            c("\\log_{2}(x)","logarithmic",function(x){log(x)/log(2)})
            )



hkposs = c(-3,-2,-1,1,2,3)
hkl = list()
pp = 1
for(i in hkposs){
    for(j in hkposs){
        if(abs(i)!=abs(j)){
            hkl[[pp]] = c(i,j)
            pp = pp+1
        }
    }
}

ord = sample(c(1:8,1:8,1:8))
ord2 = sample(1:24)
hks = list()
ft = list()
for(i in 1:24){
    hki = hkl[[i]]
    h = hki[1]
    k = hki[2]
    hks[[i]] = c(h,k)
    ff = fun2[[ord[i]]][[1]]
    ff = gsub("x",paste0("x+",-h,collapse=""),ff,fixed=T)
    ff = paste0(ff,"+",k,collapse="")
    ff = gsub("+-","-",ff,fixed=T)
    ft[[i]] = ff
}

mkplot = function(){
    danum = 7
    plot(0,0,"n",axes=F,ann=F,xlim=c(-danum,danum),ylim=c(-danum,danum))
    j = seq(-danum,danum,0.2)
    for(i in -danum:danum){
        lines(c(-danum,danum),c(i,i),lwd=0.3)
        lines(c(i,i),c(-danum,danum),lwd=0.3)
    }
    for(i in seq(-(danum %/% 5)*5,(danum %/% 5)*5,5)){
        lines(c(-danum,danum),c(i,i),lwd=0.8)
        lines(c(i,i),c(-danum,danum),lwd=0.8)
    }
    abline(h=0,lwd=1.5)
    abline(v=0,lwd=1.5)
}

prsol = function(ff,h,k){
    x = seq(-7,7,0.001)
    y = ff(x-h)+k
    x2 = x[!is.na(y)]
    y2 = y[!is.na(y)]
    x = x2[abs(y2)<=7]
    y = y2[abs(y2)<=7]
    breaks = unique(c(0,which(abs(diff(y))>10),length(x)))
    for(j in 1:(length(breaks)-1)){
        suppressWarnings(lines(x[(breaks[j]+1):(breaks[j+1]-1)],y[(breaks[j]+1):(breaks[j+1]-1)],type="l",lwd=2,col="blue"))
    }
    
    xp = -10:10
    yp = ff(xp-h)+k
    xp2 = xp[!is.na(yp)]
    yp2 = yp[!is.na(yp)]
    xp = xp2[abs(yp2)<=10]
    yp = yp2[abs(yp2)<=10]
    if(length(yp)>0){
        for(i in 1:length(xp)){
            if(yp[i]%%1==0){points(xp[i],yp[i],pch=19,cex=0.8,col="blue")}
        }
    }
}

```

```{r,echo=F,fig.dim=c(6.5,8*6.5/6),warning=F}
par(mar=c(3,1.5,0,1.5),oma=c(0,0,0,0),pty="s",mfrow=c(4,3))
library(latex2exp)
for(i in 1:12){
    mkplot()
    prsol(fun2[[ord[i]]][[3]],hks[[i]][1],hks[[i]][2])
    mtext("EQ:",1,at=-7)
    if(params$showsol){
        mtext(TeX(paste0("$y=",ft[[i]],"$")),1,col="red",line = 2)
    }
}
```

\newpage

PCW_0930_v`r params$rseed`: Write the equation for each shifted parent function

```{r,echo=F,fig.dim=c(6.5,8*6.5/6),warning=F}
par(mar=c(3,1.5,0,1.5),oma=c(0,0,0,0),pty="s",mfrow=c(4,3))

for(i in 13:24){
    mkplot()
    prsol(fun2[[ord[i]]][[3]],hks[[i]][1],hks[[i]][2])
    mtext("EQ:",1,at=-7)
    if(params$showsol){
        mtext(TeX(paste0("$y=",ft[[i]],"$")),1,col="red",line = 2)
    }
}
```
