---
output: html_document
---

\pagenumbering{gobble}

\sc Name: \vspace{5pt} \hrule \normalfont

## at1125paper: Derivation of Quadratic Formula

Begin with a generalized quadratic equation in standard form.

$$ax^2+bx+c~=~0$$

Subtract $c$ from both sides.

\vfill

Divide both sides by $a$. On the left side, distribute the divisor, and simplify the quadratic term.

\vfill

Complete the square by adding the square of half the linear coefficient to both sides of the equation.
$$x^2+\frac{bx}{a}+\left(\frac{b}{2a}\right)^2~=~\left(\frac{b}{2a}\right)^2-\frac{c}{a}$$
Factor the perfect square. (Factor the left side of the equation.)

\vfill

On the right side, distribute the exponent to all three factors of the quotient.


\vfill

On the right side, make a common denominator.

\vfill

On right side, combine fractions.
$$\left(x+\frac{b}{2a}\right)^2~=~\frac{b^2-4ac}{4a^2}$$

\newpage

$$\left(x+\frac{b}{2a}\right)^2~=~\frac{b^2-4ac}{4a^2}$$

Undo the squaring.

\vfill

Get $x$ by itself.

\vfill

Distribute the radical over the division in the last term.
$$x~=~\frac{-b}{2a}\pm\frac{\sqrt{b^2-4ac}}{\sqrt{4a^2}}$$
Simplify the denominator.

\vfill

Combine the fractions.

\vfill

\vfill


