```{r data generation, echo = FALSE, results = "hide"}
n = 6 # make this an even number probably... 6 is good
hk = sample(2:6,2)

cfs = list()
eqs = character()

i = 0
while(i<n){
    hki = sample(hk)*sample(c(-1,1),2)
    h = hki[1]
    k = hki[2]
    ab = sample(c(-1,1),2)
    a = ab[1]
    b = ab[2]
    cf = c(ab,hki)
    if(ab[1]==-1 && ab[2]==-1){
        eq = paste0("-\\sqrt{-(x+",-h,")}+",k,collapse="")
        eq = gsub("+-","-",eq,fixed=T)
    }
    if(ab[1]==1 && ab[2]==-1){
        eq = paste0("\\sqrt{-(x+",-h,")}+",k,collapse="")
        eq = gsub("+-","-",eq,fixed=T)
    }
    if(ab[1]==-1 && ab[2]==1){
        eq = paste0("-\\sqrt{x+",-h,"}+",k,collapse="")
        eq = gsub("+-","-",eq,fixed=T)
    }
    if(ab[1]==1 && ab[2]==1){
        eq = paste0("\\sqrt{x+",-h,"}+",k,collapse="")
        eq = gsub("+-","-",eq,fixed=T)
    }
    if(!(eq%in%eqs)){
        i = i+1
        cfs[[i]] = cf
        eqs[[i]] = eq
    }
}
```

Question
========

```{r,echo=F,fig.dim=c(6,n*3/2)}
par(mar=c(0,0,0,0),
    mfrow=c(ceiling(n/2),2))

for(i in 1:n){
    cf = cfs[[i]]
    plot(0,0,"n",xlim=c(-10,10),ylim=c(-10,10),axes=F,ann=F)
    for(j in -10:10){
        lines(c(j,j),c(-10,10),col="lightgrey",cex=0.8)
        lines(c(-10,10),c(j,j),col="lightgrey",cex=0.8)
    }
    for(j in seq(-10,10,5)){
        lines(c(j,j),c(-10,10),col="darkgrey",cex=1.2)
        lines(c(-10,10),c(j,j),col="darkgrey",cex=1.2)
    }
    arrows(-10.5,0,10.5,0,0.1,10,3,lwd=2)
    arrows(0,-10.5,0,10.5,0.1,10,3,lwd=2)
    x = seq(0,20,0.1)
    y = sqrt(x)
    x = x*sign(cf[1])
    y = y*sign(cf[2])
    x = x+cf[3]
    y = y+cf[4]
    x2 = x[abs(x)<=10]
    y2 = y[abs(x)<=10]
    x3 = x2[abs(y)<=10]
    y3 = y2[abs(y)<=10]
    lines(x3,y3,lwd=3,col="red")
}


```
\


Answerlist
--------



Solution
========



Meta-information
============
extype: cloze
exclozetype: 
exsolution: 
exname: inverse_cube_function