---
output: slidy_presentation
---

# Factoring by grouping

You should read the [Khan Academy article](https://www.khanacademy.org/math/algebra-basics/alg-basics-quadratics-and-polynomials/alg-basics-factoring-quadratics-2/a/factoring-by-grouping).

Consider the expression:

$$6x^2+4x+21x+14$$

Notice there is one quadratic term, two linear terms, and one constant. Also, notice that $6\cdot 14 = 4\cdot 21$. Thus the expression is ready to be factored by grouping.

1. For the two first terms, $6x^2$ and $4x$, the greatest common factor is $2x$. Factor it out.
$$2x(3x+2)+21x+14$$
2. For the last two terms, $21x$ and $14$, the greatest common factor is $7$. Factor it out.
$$2x(3x+2)+7(3x+2)$$
3. Now we have two terms, $2x(3x+2)$ and $7(3x+2)$, and both terms share a factor of $(3x+2)$, so we can apply distributive property... backwards... to factor the expression.
$$(3x+2)(2x+7)$$

# Factoring a trinomial by grouping

You should read [this other Khan Academy article](https://www.khanacademy.org/math/algebra-basics/alg-basics-quadratics-and-polynomials/alg-basics-factoring-quadratics-2/a/factoring-quadratics-leading-coefficient-not-1).


Consider the expression:

$$6x^2+25x+14$$

How can we get it set up for factoring by grouping?

>- We need to split the $25x$ into two terms whose coefficients' product equals $6\cdot 14$.
>- Calculate $6\cdot 14$. $$6\cdot 14 = `r 6*14`$$
>- We want two numbers whose product equals `r 6*14` and whose sum is 25.
>- Those numbers are 4 and 21.
$$4\cdot 21 = `r 4*21`$$
$$4+21 = `r 4+21`$$
>- Split the linear term. $$6x^2+4x+21x+14$$
>- Now the problem is equivalent to the problem on the first slide.



