---
title: Curriculum Alignment Guide for Algebra 2
output: 
  html_document:
    toc: true
    toc_depth: 2
---

### Link to this file

https://chadworley.github.io/a2/CAG/CAG_A2.html

### Overview of Algebra 2

We will follow the [Massachusetts standards](https://chadworley.github.io/ALG_2_mass_standards/Alg2.pdf), which identify four critical areas:

1. Statistics
   * Relate data display and summary statistics to probability and explore a variety of data collection methods.
2. Rational expressions
   * Relate arithmetic of rational expressions to arithmetic of rational numbers.
3. Trigonometric functions
   * Expand understandings of functions and graphing to include trigonometric functions.
4. Exponential and logarithmic functions
   * Synthesize and generalize functions and extend understanding of exponential functions to logarithmic functions.


# Unit 1: Statistics

The goal of Statistics is to systematically make inferences about populations based on samples. How do we determine whether dice are unfairly weighted? How do we determine whether a new medicine is beneficial to patients? These questions are difficult to answer because of natural variability: not every patient will die without the treatment, and not every patient will survive with the treatment.

The vast complexity underlying the variability can be modeled using probability. We learn that probabilistic models can be useful even when the events are fully deterministic (i.e. the weather). We use random-number generators and spreadsheets to run simulations and summarize data. Our study of probability culminates in the [central limit theorem](https://en.wikipedia.org/wiki/Central_limit_theorem). 

The central limit theorem provides the foundation for inferential statistics. We do not derive this connection rigorously. However, we will practice judging whether a null-hypothesis simulation is copacetic with an observation. Students complete a project where they investigate a possible correlation, estimate a population mean, or run an experiment.


* Weeks 1-8
* Essential Questions: 
  * How do we design and execute a research study?
* Skills and Content:
  * S-IC.A.1: Understand statistics as a process for making inferences about population parameters based on a random sample from that population.
  * S-IC.B.3: Recognize the purposes of and differences among sample surveys, experiments, and observational studies; explain how randomization relates to each.
  * S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.
  * S-IC.B.4: Use data from a sample survey to estimate a population mean or proportion; develop a margin of error through the use of simulation models for random sampling.
  * S-IC.B.5: Use data from a randomized experiment to compare two treatments; use simulations to decide if differences between parameters are significant.
  * S-ID.A.4: Use the mean and standard deviation of a data set to fit it to a normal distribution and to estimate population percentages. Recognize that there are data sets for which such a procedure is not appropriate. Use calculators, spreadsheets, and tables to estimate areas under the normal curve.

## Alignment

* S-IC.A.1: Understand statistics as a process for making inferences about population parameters based on a random sample from that population.
    * [Slides](https://chadworley.github.io/a2/u01/p01_sam_stat_pop_prop.html)
    * u01_01_sam_stat_pop_param [Canvas](https://bart.instructure.com/courses/1314/quizzes/2212)/[public](https://chadworley.github.io/a2/u01/outhtml/01_sam_stat_pop_param.html)
    * Assignment: Write 12 research questions (Due Monday Aug 26) [Canvas](https://bart.instructure.com/courses/1314/assignments/21622)/[public](https://chadworley.github.io/a2/u01/asn_research_questions.html)
* S-IC.B.3: Recognize the purposes of and differences among sample surveys, experiments, and observational studies; explain how randomization relates to each.
    * [Slides](https://chadworley.github.io/a2/u01/p02_survey_experi_obsstu.html)
    * 02_survey_experi_obsstu [Canvas](https://bart.instructure.com/courses/1314/quizzes/2213)/[public](https://chadworley.github.io/a2/u01/outhtml/02_survey_experi_obsstu.html)
    * 03_sample_bias [Canvas](https://bart.instructure.com/courses/1314/quizzes/2214)/[public](https://chadworley.github.io/a2/u01/outhtml/03_sample_bias.html)
    * 04_corr_or_cause [Canvas](https://bart.instructure.com/courses/1314/quizzes/2229)/[public](https://chadworley.github.io/a2/u01/outhtml/04_corr_or_cause.html)
* S-ID.A: Summarize, represent, and interpret data on a single count or measurement variable. Use calculators, spreadsheets, and other technology as appropriate.
    * [Slides](https://chadworley.github.io/a2/u01/p05_spreadsheet_intro.html#/)
    * u01_05_basic_data_analysis [Canvas](https://bart.instructure.com/courses/1314/quizzes/2288)/[public](https://chadworley.github.io/a2/u01/outhtml/05_basic_data_analysis.html)
    * u01_06_big_data_analysis [Canvas](https://bart.instructure.com/courses/1314/quizzes/2289)/[public](https://chadworley.github.io/a2/u01/outhtml/06_big_data_analysis.html)
    * [Slides: standard deviation](https://chadworley.github.io/a2/u01/pres_sd.html)
    * u01_07_sd_pop [Canvas](https://bart.instructure.com/courses/1314/quizzes/2299)/[public](https://chadworley.github.io/a2/u01/outhtml/07_sd_pop.html)
    * u01_08_sd_sam [Canvas](https://bart.instructure.com/courses/1314/quizzes/2300)/[public](https://chadworley.github.io/a2/u01/outhtml/08_sd_sam.html)
    * u01_09_read_histogram [Canvas](https://bart.instructure.com/courses/1314/quizzes/2302)/[public](https://chadworley.github.io/a2/u01/outhtml/09_read_histogram.html)
    * u01_10_identify_shape [Canvas](https://bart.instructure.com/courses/1314/quizzes/2303)/[public](https://chadworley.github.io/a2/u01/outhtml/10_identify_shape.html)
    * u01_11_make_hist_see_shape [Canvas](https://bart.instructure.com/courses/1314/quizzes/2304)/[public](https://chadworley.github.io/a2/u01/outhtml/11_make_hist_see_shape.html)
    * u01_12_sample_percentiles [Canvas](https://bart.instructure.com/courses/1314/quizzes/2305)/[public](https://chadworley.github.io/a2/u01/outhtml/12_sample_percentiles.html)
* *S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.*
    * u02_01_ME_dice_tots [Canvas](https://bart.instructure.com/courses/1314/quizzes/2307)/[public](https://chadworley.github.io/a2/u02/outhtml/01_ME_dice_tots.html)
    * u02_02_stoplight_sim [Canvas](https://bart.instructure.com/courses/1314/quizzes/2308)/[public](https://chadworley.github.io/a2/u02/outhtml/02_stoplight_sim.html)
    * u02_03_simulated_means [Canvas](https://bart.instructure.com/courses/1314/quizzes/2309)/[public](https://chadworley.github.io/a2/u02/outhtml/03_simulated_means.html)
    * u02_04_prop_test_sim [Canvas](https://bart.instructure.com/courses/1314/quizzes/2310)/[public](https://chadworley.github.io/a2/u02/outhtml/04_prop_test_sim.html)
    * [Project Coin Spin](https://chadworley.github.io/a2/u02/project_coin_spin/project_coin_spin.html)
* S-IC.B.4: Use data from a sample survey to estimate a population mean or proportion; develop a margin of error through the use of simulation models for random sampling.
    * Slides: [bootstrapping and confidence intervals](https://chadworley.github.io/a2/u02/slides_Bootstrapping.html)
    * u02_05_resample_mean_ME [Canvas](https://bart.instructure.com/courses/1314/quizzes/2315)/[public](https://chadworley.github.io/a2/u02/outhtml/05_resample_mean_ME.html)
    * u02_06_CI_mean [Canvas](https://bart.instructure.com/courses/1314/quizzes/2321)/[public](https://chadworley.github.io/a2/u02/outhtml/06_CI_mean.html)
    * u02_07_CI_mean_raw [Canvas](https://bart.instructure.com/courses/1314/quizzes/2322)/[public](https://chadworley.github.io/a2/u02/outhtml/07_CI_mean_raw.html)
    * u02_08_CI_interpret [Canvas](https://bart.instructure.com/courses/1314/quizzes/2323)/[public](https://chadworley.github.io/a2/u02/outhtml/08_CI_interpret.html)
    * [Project Dice](https://chadworley.github.io/a2/u02/project_dice/project_dice.html)
* *S-IC.B.5: Use data from a randomized experiment to compare two treatments; use simulations to decide if differences between parameters are significant.*
    * u02_09_reshuffle_two_mean [Canvas](https://bart.instructure.com/courses/1314/quizzes/2326)/[public](https://chadworley.github.io/a2/u02/outhtml/09_reshuffle_two_mean.html)
    * u02_10_hyptest_2_means_data [Canvas](https://bart.instructure.com/courses/1314/quizzes/2327)/[public](https://chadworley.github.io/a2/u02/outhtml/10_hyptest_2_means_data.html)
    * Project Measure or Compare [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)
* S-ID.A.4: Use the mean and standard deviation of a data set to fit it to a normal distribution and to estimate population percentages. Recognize that there are data sets for which such a procedure is not appropriate. Use calculators, spreadsheets, and tables to estimate areas under the normal curve.
    * Slides: [Central Limit Theorem and Normal Probability](https://chadworley.github.io/a2/u03/slides_central_limit_theorem.html#(1))
    * u03_01_leftarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2335)/[public](https://chadworley.github.io/a2/u03/outhtml/01_leftarea_from_x.html)
    * u03_02_rightarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2336)/[public](https://chadworley.github.io/a2/u03/outhtml/02_rightarea_from_x.html)
    * u03_03_centralarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2337)/[public](https://chadworley.github.io/a2/u03/outhtml/03_centralarea_from_x.html)
    * u03_04_twotailarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2338)/[public](https://chadworley.github.io/a2/u03/outhtml/04_twotailarea_from_x.html)
    * u03_05_betweenarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2339)/[public](https://chadworley.github.io/a2/u03/outhtml/05_betweenarea_from_x.html)
    * u03_06_norm_fit_less [Canvas](https://bart.instructure.com/courses/1314/quizzes/2370)/[public](https://chadworley.github.io/a2/u03/outhtml/06_norm_fit_less.html)
    * u03_07_norm_fit_more [Canvas](https://bart.instructure.com/courses/1314/quizzes/2371)/[public](https://chadworley.github.io/a2/u03/outhtml/07_norm_fit_more.html)
    * u03_08_norm_fit_between [Canvas](https://bart.instructure.com/courses/1314/quizzes/2372)/[public](https://chadworley.github.io/a2/u03/outhtml/08_norm_fit_between.html)
    * u03_09_calculate_z_from_sample_mean [Canvas](https://bart.instructure.com/courses/1314/quizzes/2374)/[public](https://chadworley.github.io/a2/u03/outhtml/09_calculate_z_from_sample_mean.html)
    * u03_10_compare_zs_means [Canvas](https://bart.instructure.com/courses/1314/quizzes/2375)/[public](https://chadworley.github.io/a2/u03/outhtml/10_compare_zs_means.html)
    * u03_11_ave_less [Canvas](https://bart.instructure.com/courses/1314/quizzes/2382)/[public](https://chadworley.github.io/a2/u03/outhtml/11_ave_less.html)
    * u03_12_ave_more [Canvas](https://bart.instructure.com/courses/1314/quizzes/2383)/[public](https://chadworley.github.io/a2/u03/outhtml/12_ave_more.html)
    * u03_13_binomial_exact_approx [Canvas](https://bart.instructure.com/courses/1314/quizzes/2386)/[public](https://chadworley.github.io/a2/u03/outhtml/13_binomial_exact_approx.html)

## Mastery assessments

* Assignment: Write 12 research questions (Due Monday Aug 26) [Canvas](https://bart.instructure.com/courses/1314/assignments/21622)/[public](https://chadworley.github.io/a2/u01/asn_research_questions.html)
* u01__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2306)
* [Project Coin Spin](https://chadworley.github.io/a2/u02/project_coin_spin/project_coin_spin.html)
* [Project Dice](https://chadworley.github.io/a2/u02/project_dice/project_dice.html)
* u02__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2328)
* Project Measure or Compare [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)
* norm_prob_mastery (due Mon Sep 23) [Canvas](https://bart.instructure.com/courses/1314/quizzes/2340)
* u03__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2385)


