---
title: "Algebra 2 Calendar"
output:
  html_document:
    toc: true
    toc_depth: 1
    theme: united
---

```{css, echo=FALSE}
body {
  padding-bottom: 300px;
}
```

[Link to current version](https://chadworley.github.io/a2/weekly_a2.html)

# Unit 1: Statistical Fundamentals (weeks 1-2)

## Week 1 {.tabset}

### Wed Aug 21

* Entrance ticket ET_001 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2254)/[public](https://chadworley.github.io/a2/ET/ET_001.html)
* Review the [syllabus](https://chadworley.github.io/a2/syllabus_a2.html).
* [First day survey](https://forms.gle/UiZrKtkPGFZ7Po8F9)
* Students will participate in a survey. We discuss some of the questions together.
* *S-IC.B: Make inferences and justify conclusions from sample surveys, experiments, and observational studies.*

### Thu Aug 22

* Entrance ticket ET_002 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2255)/[public](https://chadworley.github.io/a2/ET/ET_002.html)
* Define population, parameter, sample, and statistic.
* Discuss how the goal of Statistics is to estimate population parameters from sample statistics.
* [Slides](https://chadworley.github.io/a2/u01/p01_sam_stat_pop_prop.html)
* Graded problem: u01_01_sam_stat_pop_param [Canvas](https://bart.instructure.com/courses/1314/quizzes/2212)/[public](https://chadworley.github.io/a2/u01/outhtml/01_sam_stat_pop_param.html)
* Assignment: Write 12 research questions (Due Monday Aug 26) [Canvas](https://bart.instructure.com/courses/1314/assignments/21622)/[public](https://chadworley.github.io/a2/u01/asn_research_questions.html)
* *S-IC.A.1: Understand statistics as a process for making inferences to be made about population parameters based on a random sample from that population.*

### Fri Aug 23

* Entrance ticket ET_003 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2256)/[public](https://chadworley.github.io/a2/ET/ET_003.html)
* Define survey, experiment, and observational study. We discuss the importance of random samples and random assignment.
* [Slides](https://chadworley.github.io/a2/u01/p02_survey_experi_obsstu.html)
* Graded problems:
  * 02_survey_experi_obsstu [Canvas](https://bart.instructure.com/courses/1314/quizzes/2213)/[public](https://chadworley.github.io/a2/u01/outhtml/02_survey_experi_obsstu.html)
  * 03_sample_bias [Canvas](https://bart.instructure.com/courses/1314/quizzes/2214)/[public](https://chadworley.github.io/a2/u01/outhtml/03_sample_bias.html)
  * 04_corr_or_cause [Canvas](https://bart.instructure.com/courses/1314/quizzes/2229)/[public](https://chadworley.github.io/a2/u01/outhtml/04_corr_or_cause.html)
* Reminder of assignment: Write 12 research questions (Due Monday Aug 26) [Canvas](https://bart.instructure.com/courses/1314/assignments/21622)/[public](https://chadworley.github.io/a2/u01/asn_research_questions.html)
* *S-IC.B.3: Recognize the purposes of and differences among sample surveys, experiments, and observational studies; explain how randomization relates to each.*

## Week 2 {.tabset}

### Mon Aug 26

* Entrance ticket ET_004: [Canvas](https://bart.instructure.com/courses/1314/quizzes/2257)/[public](https://chadworley.github.io/a2/ET/ET_004.html).
* Turn and Talk: [Research Questions](https://chadworley.github.io/a2/u01/Turn_Talk_Research_Questions.html)
* Reminder of assignment: Write 12 research questions (Due Monday Aug 26) [Canvas](https://bart.instructure.com/courses/1314/assignments/21622)/[public](https://chadworley.github.io/a2/u01/asn_research_questions.html)


### Tue Aug 27

* Entrance ticket ET_005: [Canvas](https://bart.instructure.com/courses/1314/quizzes/2258)/[public](https://chadworley.github.io/a2/ET/ET_005.html).
* [Slides](https://chadworley.github.io/a2/u01/p05_spreadsheet_intro.html#/)
* Graded problems:
    * u01_05_basic_data_analysis [Canvas](https://bart.instructure.com/courses/1314/quizzes/2288)/[public](https://chadworley.github.io/a2/u01/outhtml/05_basic_data_analysis.html)
    * u01_06_big_data_analysis [Canvas](https://bart.instructure.com/courses/1314/quizzes/2289)/[public](https://chadworley.github.io/a2/u01/outhtml/06_big_data_analysis.html)
* *S-ID.A: Summarize, represent, and interpret data on a single count or measurement variable. Use calculators, spreadsheets, and other technology as appropriate.*
    
### Wed Aug 27

* Entrance ticket ET_006: [Canvas](https://bart.instructure.com/courses/1314/quizzes/2258)/[public](https://chadworley.github.io/a2/ET/ET_006.html)
* [Slides: standard deviation](https://chadworley.github.io/a2/u01/pres_sd.html)
* Graded problems:
    * u01_07_sd_pop [Canvas](https://bart.instructure.com/courses/1314/quizzes/2299)/[public](https://chadworley.github.io/a2/u01/outhtml/07_sd_pop.html)
    * u01_08_sd_sam [Canvas](https://bart.instructure.com/courses/1314/quizzes/2300)/[public](https://chadworley.github.io/a2/u01/outhtml/08_sd_sam.html)
* *S-ID.A: Summarize, represent, and interpret data on a single count or measurement variable. Use calculators, spreadsheets, and other technology as appropriate.*

### Thu Aug 28

* ET_007 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2260)/[public](https://chadworley.github.io/a2/ET/ET_007.html)
* u01_09_read_histogram [Canvas](https://bart.instructure.com/courses/1314/quizzes/2302)/[public](https://chadworley.github.io/a2/u01/outhtml/09_read_histogram.html)
* u01_10_identify_shape [Canvas](https://bart.instructure.com/courses/1314/quizzes/2303)/[public](https://chadworley.github.io/a2/u01/outhtml/10_identify_shape.html)
* u01_11_make_hist_see_shape [Canvas](https://bart.instructure.com/courses/1314/quizzes/2304)/[public](https://chadworley.github.io/a2/u01/outhtml/11_make_hist_see_shape.html)
* u01_12_sample_percentiles [Canvas](https://bart.instructure.com/courses/1314/quizzes/2305)/[public](https://chadworley.github.io/a2/u01/outhtml/12_sample_percentiles.html)

### Fri Aug 29

* ET_008 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2261)/[public](https://chadworley.github.io/a2/ET/ET_008.html)
* u01__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2306)

# Unit 2: Statistical Simulation (weeks 3-5)

## Week 3 {.tabset}

### Mon Sep 2

* No school!

### Tue Sep 3

* ET_009 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2262)/[public](https://chadworley.github.io/a2/ET/ET_009.html)
* u02_01_ME_dice_tots [Canvas](https://bart.instructure.com/courses/1314/quizzes/2307)/[public](https://chadworley.github.io/a2/u02/outhtml/01_ME_dice_tots.html)
* *S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.*

### Wed Sep 4

* ET_010 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2263)/[public](https://chadworley.github.io/a2/ET/ET_010.html)
* u02_02_stoplight_sim [Canvas](https://bart.instructure.com/courses/1314/quizzes/2308)/[public](https://chadworley.github.io/a2/u02/outhtml/02_stoplight_sim.html)
* u02_03_simulated_means [Canvas](https://bart.instructure.com/courses/1314/quizzes/2309)/[public](https://chadworley.github.io/a2/u02/outhtml/03_simulated_means.html)
* *S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.*

### Thu Sep 5

* [Aleks Initial Knowledge Check](https://bart.instructure.com/courses/1314/assignments/21853)

### Fri Sep 6

* ET_011 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2264)/[public](https://chadworley.github.io/a2/ET/ET_011.html)
* [Project Coin Spin](https://chadworley.github.io/a2/u02/project_coin_spin/project_coin_spin.html)
* *S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.*

## Week 4 {.tabset}

### Mon Sep 9

* ET_012 [canvas](https://bart.instructure.com/courses/1314/quizzes/2265)/[public](https://chadworley.github.io/a2/ET/ET_012.html)
* Continue [Project Coin Spin](https://chadworley.github.io/a2/u02/project_coin_spin/project_coin_spin.html)
* *S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.*

### Tue Sep 10

* ET_013 [canvas](https://bart.instructure.com/courses/1314/quizzes/2266)/[public](https://chadworley.github.io/a2/ET/ET_013.html)
* u02_04_prop_test_sim [Canvas](https://bart.instructure.com/courses/1314/quizzes/2310)/[public](https://chadworley.github.io/a2/u02/outhtml/04_prop_test_sim.html)
* Aleks
    * Finish Initial Knowledge Check
    * Start "your path" when finished with the knowledge check.
* *S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.*
    
### Wed Sep 11

* ET_014 [canvas](https://bart.instructure.com/courses/1314/quizzes/2267)/[public](https://chadworley.github.io/a2/ET/ET_014.html)
* Slides: [bootstrapping and confidence intervals](https://chadworley.github.io/a2/u02/slides_Bootstrapping.html)
* u02_05_resample_mean_ME [Canvas](https://bart.instructure.com/courses/1314/quizzes/2315)/[public](https://chadworley.github.io/a2/u02/outhtml/05_resample_mean_ME.html)
* [Project Dice](https://chadworley.github.io/a2/u02/project_dice/project_dice.html)
* *S-IC.B.4: Use data from a sample survey to estimate a population mean or proportion; develop a margin of error through the use of simulation models for random sampling.*


### Thu Sep 12

* ET_015 [canvas](https://bart.instructure.com/courses/1314/quizzes/2268)/[public](https://chadworley.github.io/a2/ET/ET_015.html)
* Continue [Project Dice](https://chadworley.github.io/a2/u02/project_dice/project_dice.html)
* *S-IC.B.4: Use data from a sample survey to estimate a population mean or proportion; develop a margin of error through the use of simulation models for random sampling.*

### Fri Sep 13

* ET_016 [canvas](https://bart.instructure.com/courses/1314/quizzes/2269)/[public](https://chadworley.github.io/a2/ET/ET_016.html)
* u02_06_CI_mean [Canvas](https://bart.instructure.com/courses/1314/quizzes/2321)/[public](https://chadworley.github.io/a2/u02/outhtml/06_CI_mean.html)
* u02_07_CI_mean_raw [Canvas](https://bart.instructure.com/courses/1314/quizzes/2322)/[public](https://chadworley.github.io/a2/u02/outhtml/07_CI_mean_raw.html)
* u02_08_CI_interpret [Canvas](https://bart.instructure.com/courses/1314/quizzes/2323)/[public](https://chadworley.github.io/a2/u02/outhtml/08_CI_interpret.html)
* *S-IC.B.4: Use data from a sample survey to estimate a population mean or proportion; develop a margin of error through the use of simulation models for random sampling.*

## Week 5 {.tabset}

### Mon Sep 16

* ET_017 [canvas](https://bart.instructure.com/courses/1314/quizzes/2270)/[public](https://chadworley.github.io/a2/ET/ET_017.html)
* u02_09_reshuffle_two_mean [Canvas](https://bart.instructure.com/courses/1314/quizzes/2326)/[public](https://chadworley.github.io/a2/u02/outhtml/09_reshuffle_two_mean.html)
* Project Measure or Compare [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)
* *S-IC.B.5: Use data from a randomized experiment to compare two treatments; use simulations to decide if differences between parameters are significant.*


### Tue Sep 17

* ET_018 [canvas](https://bart.instructure.com/courses/1314/quizzes/2271)/[public](https://chadworley.github.io/a2/ET/ET_018.html)
* u02_10_hyptest_2_means_data [Canvas](https://bart.instructure.com/courses/1314/quizzes/2327)/[public](https://chadworley.github.io/a2/u02/outhtml/10_hyptest_2_means_data.html)
* Project Measure or Compare [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)
* *S-IC.B.5: Use data from a randomized experiment to compare two treatments; use simulations to decide if differences between parameters are significant.*

### Wed Sep 18

* ET_019 [canvas](https://bart.instructure.com/courses/1314/quizzes/2272)/[public](https://chadworley.github.io/a2/ET/ET_019.html)
* u02__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2328)
* (Due Fri Sep 27) Project Measure or Compare [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)
* *S-ID.A: Summarize, represent, and interpret data on a single count or measurement variable. Use calculators, spreadsheets, and other technology as appropriate.*
* *S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.*
* *S-IC.B.4: Use data from a sample survey to estimate a population mean or proportion; develop a margin of error through the use of simulation models for random sampling.*
* *S-IC.B.5: Use data from a randomized experiment to compare two treatments; use simulations to decide if differences between parameters are significant.*

### Thu Sep 19

* ET_020: plan your project [canvas](https://bart.instructure.com/courses/1314/assignments/22096)
* Project Measure or Compare [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)
* *S-IC.B.6: Evaluate reports based on data.*

# Unit 3: Central Limit Theorem (weeks 5-7)

## Week 5 continued {.tabset}

### Fri Sep 20

* ET_021 [canvas](https://bart.instructure.com/courses/1314/quizzes/2333)/[public](https://chadworley.github.io/a2/ET2/ET_021.html)
* Slides: [Central Limit Theorem and Normal Probability](https://chadworley.github.io/a2/u03/slides_central_limit_theorem.html#(1))
* u03_01_leftarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2335)/[public](https://chadworley.github.io/a2/u03/outhtml/01_leftarea_from_x.html)
* u03_02_rightarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2336)/[public](https://chadworley.github.io/a2/u03/outhtml/02_rightarea_from_x.html)
* u03_03_centralarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2337)/[public](https://chadworley.github.io/a2/u03/outhtml/03_centralarea_from_x.html)
* u03_04_twotailarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2338)/[public](https://chadworley.github.io/a2/u03/outhtml/04_twotailarea_from_x.html)
* u03_05_betweenarea_from_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/2339)/[public](https://chadworley.github.io/a2/u03/outhtml/05_betweenarea_from_x.html)
* norm_prob_mastery (due Mon Sep 23) [Canvas](https://bart.instructure.com/courses/1314/quizzes/2340)
* *S-ID.A.4: Use the mean and standard deviation of a data set to fit it to a normal distribution and to estimate population percentages. Recognize that there are data sets for which such a procedure is not appropriate. Use calculators, spreadsheets, and tables to estimate areas under the normal curve.*


## Week 6 {.tabset}

### Mon Sep 23

* ET_022 [canvas](https://bart.instructure.com/courses/1314/quizzes/2341)/[public](https://chadworley.github.io/a2/ET2/ET_022.html)
* u03_06_norm_fit_less [Canvas](https://bart.instructure.com/courses/1314/quizzes/2370)/[public](https://chadworley.github.io/a2/u03/outhtml/06_norm_fit_less.html)
* u03_07_norm_fit_more [Canvas](https://bart.instructure.com/courses/1314/quizzes/2371)/[public](https://chadworley.github.io/a2/u03/outhtml/07_norm_fit_more.html)
* u03_08_norm_fit_between [Canvas](https://bart.instructure.com/courses/1314/quizzes/2372)/[public](https://chadworley.github.io/a2/u03/outhtml/08_norm_fit_between.html)
* *S-ID.A.4: Use the mean and standard deviation of a data set to fit it to a normal distribution and to estimate population percentages. Recognize that there are data sets for which such a procedure is not appropriate. Use calculators, spreadsheets, and tables to estimate areas under the normal curve.*

### Tue Sep 24

* ET_023 [canvas](https://bart.instructure.com/courses/1314/quizzes/2342)/[public](https://chadworley.github.io/a2/ET2/ET_023.html)
* Useful file: [z table](https://chadworley.github.io/a2/tools/ztable.pdf)
* u03_09_calculate_z_from_sample_mean [Canvas](https://bart.instructure.com/courses/1314/quizzes/2374)/[public](https://chadworley.github.io/a2/u03/outhtml/09_calculate_z_from_sample_mean.html)
* u03_10_compare_zs_means [Canvas](https://bart.instructure.com/courses/1314/quizzes/2375)/[public](https://chadworley.github.io/a2/u03/outhtml/10_compare_zs_means.html)
* Work on Project Measure or Compare [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)
* *S-ID.A.4: Use the mean and standard deviation of a data set to fit it to a normal distribution and to estimate population percentages. Recognize that there are data sets for which such a procedure is not appropriate. Use calculators, spreadsheets, and tables to estimate areas under the normal curve.*

### Wed Sep 25

* ET_024 [canvas](https://bart.instructure.com/courses/1314/quizzes/2343)/[public](https://chadworley.github.io/a2/ET2/ET_024.html)
* Catch up on previous assignments.
* Work on Project Measure or Compare. [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)

### Thu Sep 26

* ET_025 [canvas](https://bart.instructure.com/courses/1314/quizzes/2344)/[public](https://chadworley.github.io/a2/ET2/ET_025.html)
* Catch up on previous assignments.
* Work on Project Measure or Compare. [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)


### Fri Sep 27

* ET_026 [canvas](https://bart.instructure.com/courses/1314/quizzes/2345)/[public](https://chadworley.github.io/a2/ET2/ET_026.html)
* Catch up on previous assignments.
* Work on Project Measure or Compare. [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)

## Week 7 {.tabset}

### Mon Sep 30

* ET_027 [canvas](https://bart.instructure.com/courses/1314/quizzes/2346)/[public](https://chadworley.github.io/a2/ET2/ET_027.html)
* u03_11_ave_less [Canvas](https://bart.instructure.com/courses/1314/quizzes/2382)/[public](https://chadworley.github.io/a2/u03/outhtml/11_ave_less.html)
* u03_12_ave_more [Canvas](https://bart.instructure.com/courses/1314/quizzes/2383)/[public](https://chadworley.github.io/a2/u03/outhtml/12_ave_more.html)
* Catch up on previous assignments.
* Work on Project Measure or Compare. [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)

### Tue Oct 01

* ET_028 [canvas](https://bart.instructure.com/courses/1314/quizzes/2347)/[public](https://chadworley.github.io/a2/ET2/ET_028.html)
* u03_13_binomial_exact_approx [Canvas](https://bart.instructure.com/courses/1314/quizzes/2386)/[public](https://chadworley.github.io/a2/u03/outhtml/13_binomial_exact_approx.html)
* u03__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2385) (Due Wed Oct 2)
* Catch up on previous assignments.
* Work on Project Measure or Compare. [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)


### Wed Oct 02

* ET_029 [canvas](https://bart.instructure.com/courses/1314/quizzes/2348)/[public](https://chadworley.github.io/a2/ET2/ET_029.html)
* u03__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2385) (Due Wed Oct 2)
* Catch up on previous assignments.
* Work on Project Measure or Compare. [Canvas](https://bart.instructure.com/courses/1314/assignments/22063)/[public](https://chadworley.github.io/a2/u02/project_measure_or_compare/project_measure_or_compare.html)

# Unit 4: Probability (weeks 7-8)

## Week 7 continued {.tabset}

### Thu Oct 03

* ET_030 [canvas](https://bart.instructure.com/courses/1314/quizzes/2349)/[public](https://chadworley.github.io/a2/ET2/ET_030.html)
* u04_01_venn_rects [Canvas](https://bart.instructure.com/courses/1314/quizzes/2389)/[public](https://chadworley.github.io/a2/u04/outhtml/01_venn_rects.html)
* u04_02_venn_clubs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2390)/[public](https://chadworley.github.io/a2/u04/outhtml/02_venn_clubs.html)
* u04_03_venn_probs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2391)/[public](https://chadworley.github.io/a2/u04/outhtml/03_venn_probs.html)
* *S-MD.B.6: (+) Use probabilities to make fair decisions (e.g., drawing by lots, using a random number generator).*
* *S-MD.B.7: (+) Analyze decisions and strategies using probability concepts (e.g., product testing, medical testing, pulling a hockey goalie at the end of a game and replacing the goalie with an extra skater).*

### Fri Oct 04

* ET_031 [canvas](https://bart.instructure.com/courses/1314/quizzes/2350)/[public](https://chadworley.github.io/a2/ET2/ET_031.html)
* u04_04_ind_or_mut_exclu [Canvas](https://bart.instructure.com/courses/1314/quizzes/2392)/[public](https://chadworley.github.io/a2/u04/outhtml/04_ind_or_mut_exclu.html)
* u04_05_cards [Canvas](https://bart.instructure.com/courses/1314/quizzes/2393)/[public](https://chadworley.github.io/a2/u04/outhtml/05_cards.html)
* u04_06_winlose [Canvas](https://bart.instructure.com/courses/1314/quizzes/2394)/[public](https://chadworley.github.io/a2/u04/outhtml/06_winlose.html)
* *S-MD.B.6: (+) Use probabilities to make fair decisions (e.g., drawing by lots, using a random number generator).*
* *S-MD.B.7: (+) Analyze decisions and strategies using probability concepts (e.g., product testing, medical testing, pulling a hockey goalie at the end of a game and replacing the goalie with an extra skater).*

## Week 8 {.tabset}

### Mon Oct 07

* ET_032 [canvas](https://bart.instructure.com/courses/1314/quizzes/2351)/[public](https://chadworley.github.io/a2/ET2/ET_032.html)
* u04_07_bobhappy [Canvas](https://bart.instructure.com/courses/1314/quizzes/2395)/[public](https://chadworley.github.io/a2/u04/outhtml/07_bobhappy.html)
* u04_08_scratchoff_value [Canvas](https://bart.instructure.com/courses/1314/quizzes/2396)/[public](https://chadworley.github.io/a2/u04/outhtml/08_scratchoff_value.html)
* u04_09_ski_paths [Canvas](https://bart.instructure.com/courses/1314/quizzes/2397)/[public](https://chadworley.github.io/a2/u04/outhtml/09_ski_paths.html)
* *S-MD.B.6: (+) Use probabilities to make fair decisions (e.g., drawing by lots, using a random number generator).*
* *S-MD.B.7: (+) Analyze decisions and strategies using probability concepts (e.g., product testing, medical testing, pulling a hockey goalie at the end of a game and replacing the goalie with an extra skater).*

### Tue Oct 08

* ET_033 [canvas](https://bart.instructure.com/courses/1314/quizzes/2352)/[public](https://chadworley.github.io/a2/ET2/ET_033.html)
* u04__mastery [canvas](https://bart.instructure.com/courses/1314/quizzes/2400)

### Wed Oct 09

* ET_034 [canvas](https://bart.instructure.com/courses/1314/quizzes/2353)/[public](https://chadworley.github.io/a2/ET2/ET_034.html)
* u04__mastery [canvas](https://bart.instructure.com/courses/1314/quizzes/2400)

# Unit 5: Polynomial Operations (weeks 8-9)

## Week 8 continued {.tabset}

### Thu Oct 10

* ET_035 [canvas](https://bart.instructure.com/courses/1314/quizzes/2354)/[public](https://chadworley.github.io/a2/ET2/ET_035.html)
* Textbook: [add and subtract polynomials](https://openstax.org/books/intermediate-algebra-2e/pages/5-1-add-and-subtract-polynomials)
* u05_01_base10_eval [Canvas](https://bart.instructure.com/courses/1314/quizzes/2405)/[public](https://chadworley.github.io/a2/u05/outhtml/01_base10_eval.html)
* u05_02_base10_placevalue [Canvas](https://bart.instructure.com/courses/1314/quizzes/2406)/[public](https://chadworley.github.io/a2/u05/outhtml/02_base10_placevalue.html)
* u05_03_polynomial_terminology [Canvas](https://bart.instructure.com/courses/1314/quizzes/2407)/[public](https://chadworley.github.io/a2/u05/outhtml/03_polynomial_terminology.html)
* u05_04_add_base10 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2408)/[public](https://chadworley.github.io/a2/u05/outhtml/04_add_base10.html)
* u05_05_add_poly [Canvas](https://bart.instructure.com/courses/1314/quizzes/2409)/[public](https://chadworley.github.io/a2/u05/outhtml/05_add_poly.html)
* u05_06_subtract_poly [Canvas](https://bart.instructure.com/courses/1314/quizzes/2410)/[public](https://chadworley.github.io/a2/u05/outhtml/06_subtract_poly.html)
* *A-APR.A.1: Understand that polynomials form a system analogous to the integers, namely, they are closed under certain operations.*
* *A-APR.A.1.a: Perform operations on polynomial expressions (addition, subtraction, multiplication, and division), and compare the system of polynomials to the system of integers when performing operations.*
* *A-SSE.A.1.a: Interpret parts of an expression, such as terms, factors, and coefficients.*

### Fri Oct 11

* ET_036 [canvas](https://bart.instructure.com/courses/1314/quizzes/2355)/[public](https://chadworley.github.io/a2/ET2/ET_036.html)
* Textbook: [multiply polynomials](https://openstax.org/books/intermediate-algebra-2e/pages/5-3-multiply-polynomials)
* u05_07_multiply_2digits [Canvas](https://bart.instructure.com/courses/1314/quizzes/2426)/[public](https://chadworley.github.io/a2/u05/outhtml/07_multiply_2digits.html)
* u05_08_base10_multiply [Canvas](https://bart.instructure.com/courses/1314/quizzes/2427)/[public](https://chadworley.github.io/a2/u05/outhtml/08_base10_multiply.html)
* u05_09_multiply_binomials [Canvas](https://bart.instructure.com/courses/1314/quizzes/2429)/[public](https://chadworley.github.io/a2/u05/outhtml/09_multiply_binomials.html)
* *A-APR.A.1.a: Perform operations on polynomial expressions (addition, subtraction, multiplication, and division), and compare the system of polynomials to the system of integers when performing operations.*

## Week 9 {.tabset}

### Mon Oct 14

* No school!

### Tue Oct 15

* ET_037 [canvas](https://bart.instructure.com/courses/1314/quizzes/2356)/[public](https://chadworley.github.io/a2/ET2/ET_037.html)
* u05_10_mult_get_diff_of_sqrs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2431)/[public](https://chadworley.github.io/a2/u05/outhtml/10_mult_get_diff_of_sqrs.html)
* u05_11_binomial_squared [Canvas](https://bart.instructure.com/courses/1314/quizzes/2432)/[public](https://chadworley.github.io/a2/u05/outhtml/11_binomial_squared.html)
* u05_12_multiply_linear_quadratic [Canvas](https://bart.instructure.com/courses/1314/quizzes/2433)/[public](https://chadworley.github.io/a2/u05/outhtml/12_multiply_linear_quadratic.html)
* u05_13_multiply_linear_cubic [Canvas](https://bart.instructure.com/courses/1314/quizzes/2434)/[public](https://chadworley.github.io/a2/u05/outhtml/13_multiply_linear_cubic.html)
* u05_14_mult_quad_quad [Canvas](https://bart.instructure.com/courses/1314/quizzes/2435)/[public](https://chadworley.github.io/a2/u05/outhtml/14_mult_quad_quad.html)
* u05_15_linear_cubed [Canvas](https://bart.instructure.com/courses/1314/quizzes/2436)/[public](https://chadworley.github.io/a2/u05/outhtml/15_linear_cubed.html)
* u05_16_linear_to_the_fourth [Canvas](https://bart.instructure.com/courses/1314/quizzes/2438)/[public](https://chadworley.github.io/a2/u05/outhtml/16_linear_to_the_fourth.html)
* *A-APR.A.1.a: Perform operations on polynomial expressions (addition, subtraction, multiplication, and division), and compare the system of polynomials to the system of integers when performing operations.*
* *A-APR.C.5: (+) Know and apply the Binomial Theorem for the expansion of $(x + y)^n$ in powers of x and y for a positive integer n, where x and y are any numbers, with coefficients determined for example by Pascal’s Triangle.*

### Wed Oct 16

* ET_038 [canvas](https://bart.instructure.com/courses/1314/quizzes/2357)/[public](https://chadworley.github.io/a2/ET2/ET_038.html)
* u05_17_long_division [Canvas](https://bart.instructure.com/courses/1314/quizzes/2450)/[public](https://chadworley.github.io/a2/u05/outhtml/17_long_division.html)
* u05_18_poly_long_division [Canvas](https://bart.instructure.com/courses/1314/quizzes/2453)/[public](https://chadworley.github.io/a2/u05/outhtml/18_poly_long_division.html)
* u05_19_synthetic_division [Canvas](https://bart.instructure.com/courses/1314/quizzes/2454)/[public](https://chadworley.github.io/a2/u05/outhtml/19_synthetic_division.html)
* *A-APR.A.1.a: Perform operations on polynomial expressions (addition, subtraction, multiplication, and division), and compare the system of polynomials to the system of integers when performing operations.*
* *A-APR.B.2: Know and apply the Remainder Theorem: For a polynomial $p(x)$ and a number $a$, the remainder on division by $x – a$ is $p(a)$, so $p(a) = 0$ if and only if $(x – a)$ is a factor of $p(x)$.*

### Thu Oct 17

* ET_039 [canvas](https://bart.instructure.com/courses/1314/quizzes/2358)/[public](https://chadworley.github.io/a2/ET2/ET_039.html)
* Practice exam [canvas](https://bart.instructure.com/courses/1314/assignments/22575)/[public](https://chadworley.github.io/a2/u05/written_exam/prac_01/po_prac_v1-40.pdf)
* *A-APR.A.1.a: Perform operations on polynomial expressions (addition, subtraction, multiplication, and division), and compare the system of polynomials to the system of integers when performing operations.*
* *A-APR.C.5: (+) Know and apply the Binomial Theorem for the expansion of $(x + y)^n$ in powers of x and y for a positive integer n, where x and y are any numbers, with coefficients determined for example by Pascal’s Triangle.*
* *A-APR.B.2: Know and apply the Remainder Theorem: For a polynomial $p(x)$ and a number $a$, the remainder on division by $x – a$ is $p(a)$, so $p(a) = 0$ if and only if $(x – a)$ is a factor of $p(x)$.*
* *A-APR.D.6: 6. Rewrite simple rational expressions in different forms; write $\frac{a(x)}{b(x)}$ in the form $q(x) + \frac{r(x)}{b(x)}$, where $a(x)$, $b(x)$, $q(x)$, and $r(x)$ are polynomials with the degree of $r(x)$ less than the degree of $b(x)$, using inspection, long division, or, for the more complicated examples, a computer algebra system.*

### Fri Oct 18

* No ET
* Polynomial exam

# Unit 5: Factoring Polynomials (weeks 10-12)

## Week 10 {.tabset}

### Mon Oct 21

* ET_040 [canvas](https://bart.instructure.com/courses/1314/quizzes/2359)/[public](https://chadworley.github.io/a2/ET2/ET_040.html)
* u06_01_prime_factorization [Canvas](https://bart.instructure.com/courses/1314/quizzes/2463)/[public](https://chadworley.github.io/a2/u06/outhtml/01_prime_factorization.html)
* u06_02_factor_quadratic [Canvas](https://bart.instructure.com/courses/1314/quizzes/2464)/[public](https://chadworley.github.io/a2/u06/outhtml/02_factor_quadratic.html)
* u06_03_quadratic_formula [Canvas](https://bart.instructure.com/courses/1314/quizzes/2465)/[public](https://chadworley.github.io/a2/u06/outhtml/03_quadratic_formula.html)
* **REMEMBER**: You can still take the unit-5 polynomial exam! ([practice](https://chadworley.github.io/a2/u05/written_exam/prac_01/po_prac_v1-40.pdf) and [solution](https://chadworley.github.io/a2/u05/written_exam/prac_01/po_sol_1-40.pdf))
    * No notes
    * No calculators
    * No talking or getting outside help
    * As many attempts as you want
    * Highest score
    * You can ask me for a copy in class, or you can schedule a time to take it in the learning center (email me with time and day).


### Tue Oct 21

* ET_041 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2360)/[public](https://chadworley.github.io/a2/ET2/ET_041.html)
* u06_04_quadratic_formula_complex [Canvas](https://bart.instructure.com/courses/1314/quizzes/2466)/[public](https://chadworley.github.io/a2/u06/outhtml/04_quadratic_formula_complex.html)
* u06_05_solve_cubic_easy_integers [Canvas](https://bart.instructure.com/courses/1314/quizzes/2467)/[public](https://chadworley.github.io/a2/u06/outhtml/05_solve_cubic_easy_integers.html)
* u06_06_solve_cubic_one_real [Canvas](https://bart.instructure.com/courses/1314/quizzes/2468)/[public](https://chadworley.github.io/a2/u06/outhtml/06_solve_cubic_one_real.html)
* u06_07_add_complex [Canvas](https://bart.instructure.com/courses/1314/quizzes/2469)/[public](https://chadworley.github.io/a2/u06/outhtml/07_add_complex.html)
* u06_08_subtract_complex [Canvas](https://bart.instructure.com/courses/1314/quizzes/2470)/[public](https://chadworley.github.io/a2/u06/outhtml/08_subtract_complex.html)
* u06_09_multiply_complex [Canvas](https://bart.instructure.com/courses/1314/quizzes/2471)/[public](https://chadworley.github.io/a2/u06/outhtml/09_multiply_complex.html)
* *N-CN.C.7: Solve quadratic equations with real coefficients that have complex solutions.*
* *N-CN.A.1: Know there is a complex number $i$ such that $i^2 = −1$, and every complex number has the form $a + bi$ with $a$ and $b$ real.*
* *N-CN.A.2: Use the relation $i^2 = –1$ and the Commutative, Associative, and Distributive properties to add, subtract, and multiply complex numbers.*

### Wed Oct 22

* ET_042 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2361)/[public](https://chadworley.github.io/a2/ET2/ET_042.html)
* u06_10_check_complex_solution [Canvas](https://bart.instructure.com/courses/1314/quizzes/2472)/[public](https://chadworley.github.io/a2/u06/outhtml/10_check_complex_solution.html)
* u06_11_read_complex_plot [Canvas](https://bart.instructure.com/courses/1314/quizzes/2473)/[public](https://chadworley.github.io/a2/u06/outhtml/11_read_complex_plot.html)
* u06_12_complex_modulus [Canvas](https://bart.instructure.com/courses/1314/quizzes/2474)/[public](https://chadworley.github.io/a2/u06/outhtml/12_complex_modulus.html)
* u06_13_solve_polynomial_complex_roots [Canvas](https://bart.instructure.com/courses/1314/quizzes/2475)/[public](https://chadworley.github.io/a2/u06/outhtml/13_solve_polynomial_complex_roots.html)
* *N-CN.C.9: (+) Know the Fundamental Theorem of Algebra; show that it is true for quadratic polynomials.*


### Thu Oct 24

* ET_043 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2362)/[public](https://chadworley.github.io/a2/ET2/ET_043.html)
* u06_14_factor_diff_of_squares [Canvas](https://bart.instructure.com/courses/1314/quizzes/2479)/[public](https://chadworley.github.io/a2/u06/outhtml/14_factor_diff_of_squares.html)
* u06_15_factor_sum_of_squares [Canvas](https://bart.instructure.com/courses/1314/quizzes/2480)/[public](https://chadworley.github.io/a2/u06/outhtml/15_factor_sum_of_squares.html)
* u06_16_quadratic_from_zeros [Canvas](https://bart.instructure.com/courses/1314/quizzes/2481)/[public](https://chadworley.github.io/a2/u06/outhtml/16_quadratic_from_zeros.html)
* u06_17_cubic_from_zeros [Canvas](https://bart.instructure.com/courses/1314/quizzes/2482)/[public](https://chadworley.github.io/a2/u06/outhtml/17_cubic_from_zeros.html)
* u06_18_cubic_from_zeros_doub [Canvas](https://bart.instructure.com/courses/1314/quizzes/2483)/[public](https://chadworley.github.io/a2/u06/outhtml/18_cubic_from_zeros_doub.html)
* *F-IF.C.8: Write a function defined by an expression in different but equivalent forms to reveal and explain different properties of the function.*


### Fri Oct 25

* ET_044 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2363)/[public](https://chadworley.github.io/a2/ET2/ET_044.html)
* u06_19_cubic_from_zeros_trip [Canvas](https://bart.instructure.com/courses/1314/quizzes/2484)/[public](https://chadworley.github.io/a2/u06/outhtml/19_cubic_from_zeros_trip.html)
* u06_20_cubic_from_zeros_comp [Canvas](https://bart.instructure.com/courses/1314/quizzes/2485)/[public](https://chadworley.github.io/a2/u06/outhtml/20_cubic_from_zeros_comp.html)
* u06_21_polynomial_ends [Canvas](https://bart.instructure.com/courses/1314/quizzes/2486)/[public](https://chadworley.github.io/a2/u06/outhtml/21_polynomial_ends.html)
* u06_22_polynomial_ends_B [Canvas](https://bart.instructure.com/courses/1314/quizzes/2487)/[public](https://chadworley.github.io/a2/u06/outhtml/22_polynomial_ends_B.html)
* *F-IF.C.7.c: Graph polynomial functions, identifying zeros when suitable factorizations are available, and showing end behavior.*

## Week 11 {.tabset}

### Mon Oct 28

* Hispanic Heritage Showcase

### Tue Oct 29

* PSAT

### Wed Oct 30

* ET_045 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2364)/[public](https://chadworley.github.io/a2/ET2/ET_045.html)
* u06_24_flip_parabola [Canvas](https://bart.instructure.com/courses/1314/quizzes/2502)/[public](https://chadworley.github.io/a2/u06/outhtml/24_flip_parabola.html)
* u06_25_cannon_balloon [Canvas](https://bart.instructure.com/courses/1314/quizzes/2503)/[public](https://chadworley.github.io/a2/u06/outhtml/25_cannon_balloon.html)
* u06_26_intersect_cubic_line [Canvas](https://bart.instructure.com/courses/1314/quizzes/2504)/[public](https://chadworley.github.io/a2/u06/outhtml/26_intersect_cubic_line.html)

### Thu Oct 31

* ET_046 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2365)/[public](https://chadworley.github.io/a2/ET2/ET_046.html)
* u06_27_sketch_factored_poly [Canvas](https://bart.instructure.com/courses/1314/quizzes/2507)/[public](https://chadworley.github.io/a2/u06/outhtml/27_sketch_factored_poly.html)
* u06_28_match_graph_poly_eq [Canvas](https://bart.instructure.com/courses/1314/quizzes/2511)/[public](https://chadworley.github.io/a2/u06/outhtml/28_match_graph_poly_eq.html)
* u06_29_vertex_form_animation [Canvas](https://bart.instructure.com/courses/1314/quizzes/2512)/[public](https://chadworley.github.io/a2/u06/outhtml/29_vertex_form_animation.html)


### Fri Nov 01

* ET_047 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2366)/[public](https://chadworley.github.io/a2/ET2/ET_047.html)
* Practice written exam! [public](https://chadworley.github.io/a2/u06/written_exam/practice/poe_v001-050.pdf)

## Week 12 {.tabset}

### Mon Nov 04

* ET_048 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2367)/[public](https://chadworley.github.io/a2/ET2/ET_048.html)
* Written exam! [practice](https://chadworley.github.io/a2/u06/written_exam/practice/poe_v001-050.pdf)/[solutions](https://chadworley.github.io/a2/u06/written_exam/practice/poe_sol_v001-050.pdf)

### Tue Nov 05

* Election Day

### Wed Nov 06

* ALEKS Knowledge Check:
    * Open [Classlink](https://launchpad.classlink.com/bart) (in BART Managed)
    * Click on McGraw Hill
    * Open your class' ALEKS
    * Start your Knowledge Check
    * When finished, **TAKE A SCREENSHOT** (as a png)
    * Submit the screenshot [on Canvas](https://bart.instructure.com/courses/1314/assignments/23007)

### Thu Nov 07

* ALEKS Knowledge Check:
    * Open [Classlink](https://launchpad.classlink.com/bart) (in BART Managed)
    * Click on McGraw Hill
    * Open your class' ALEKS
    * Start your Knowledge Check
    * When finished, **TAKE A SCREENSHOT** (as a png)
    * Submit the screenshot [on Canvas](https://bart.instructure.com/courses/1314/assignments/23007)
* Unit 6 written exam: [practice](https://chadworley.github.io/a2/u06/written_exam/practice/poe_v001-050.pdf)/[solutions](https://chadworley.github.io/a2/u06/written_exam/practice/poe_sol_v001-050.pdf)
* *F-IF.C.7.c: Graph polynomial functions, identifying zeros when suitable factorizations are available, and showing end behavior.*

# Unit 7: Function Basics (weeks 12-13)

## Week 12 continued {.tabset}

### Fri Nov 08

* ET_049 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2368)/[public](https://chadworley.github.io/a2/ET2/ET_049.html)
* u07_01_is_relation_a_function [Canvas](https://bart.instructure.com/courses/1314/quizzes/2513)/[public](https://chadworley.github.io/a2/u07/outhtml/01_is_relation_a_function.html)
* u07_02_are_points_a_function [Canvas](https://bart.instructure.com/courses/1314/quizzes/2514)/[public](https://chadworley.github.io/a2/u07/outhtml/02_are_points_a_function.html)
* u07_03_are_connections_a_function [Canvas](https://bart.instructure.com/courses/1314/quizzes/2515)/[public](https://chadworley.github.io/a2/u07/outhtml/03_are_connections_a_function.html)
* u07_04_is_curve_a_function [Canvas](https://bart.instructure.com/courses/1314/quizzes/2516)/[public](https://chadworley.github.io/a2/u07/outhtml/04_is_curve_a_function.html)
* u07_05_evaluate_function [Canvas](https://bart.instructure.com/courses/1314/quizzes/2517)/[public](https://chadworley.github.io/a2/u07/outhtml/05_evaluate_function.html)
* u07_06_eval_func_from_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2518)/[public](https://chadworley.github.io/a2/u07/outhtml/06_eval_func_from_graph.html)
* u07_07_inv_func_from_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2519)/[public](https://chadworley.github.io/a2/u07/outhtml/07_inv_func_from_graph.html)

## Week 13 {.tabset}

### Mon Nov 11

No school!

### Tue Nov 12

* ET_050 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2536)/[public](https://chadworley.github.io/a2/ET2/ET_050.html)
* u07_08_inverse_table [Canvas](https://bart.instructure.com/courses/1314/quizzes/2527)/[public](https://chadworley.github.io/a2/u07/outhtml/08_inverse_table.html)
* u07_09_two-step_inverse_alg [Canvas](https://bart.instructure.com/courses/1314/quizzes/2528)/[public](https://chadworley.github.io/a2/u07/outhtml/09_two-step_inverse_alg.html)
* u07_10_graph_inverse [Canvas](https://bart.instructure.com/courses/1314/quizzes/2529)/[public](https://chadworley.github.io/a2/u07/outhtml/10_graph_inverse.html)
* u07_11_f_of_neg_a [Canvas](https://bart.instructure.com/courses/1314/quizzes/2530)/[public](https://chadworley.github.io/a2/u07/outhtml/11_f_of_neg_a.html)
* u07_12_neg_of_f_a [Canvas](https://bart.instructure.com/courses/1314/quizzes/2531)/[public](https://chadworley.github.io/a2/u07/outhtml/12_neg_of_f_a.html)
* u07_13_negs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2532)/[public](https://chadworley.github.io/a2/u07/outhtml/13_negs.html)
* u07_14_even_or_odd_polynomial [Canvas](https://bart.instructure.com/courses/1314/quizzes/2533)/[public](https://chadworley.github.io/a2/u07/outhtml/14_even_or_odd_polynomial.html)
* u07_15_even_or_odd_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2534)/[public](https://chadworley.github.io/a2/u07/outhtml/15_even_or_odd_graph.html)
* u07_16_domain_range_basic [Canvas](https://bart.instructure.com/courses/1314/quizzes/2535)/[public](https://chadworley.github.io/a2/u07/outhtml/16_domain_range_basic.html)
* *F-BF.B.4: Find inverse functions algebraically and graphically.*

### Wed Nov 13

* ET_051 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2537)/[public](https://chadworley.github.io/a2/ET2/ET_051.html)
* u07_online_mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2562)
* u07_written_practice_exam [Canvas](https://bart.instructure.com/courses/1314/assignments/23105)
    * [Practice](https://chadworley.github.io/a2/u07/written_exam/practice/ieodr_v001-050.pdf)
    * [Solutions](https://chadworley.github.io/a2/u07/written_exam/practice/ieodr_sol_v001-050.pdf)
* u07_written_exam


### Thu Nov 14

* ET_052 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2538)/[public](https://chadworley.github.io/a2/ET2/ET_052.html)
* u07_online_mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2562)
* u07_written_practice_exam [Canvas](https://bart.instructure.com/courses/1314/assignments/23105)
    * [Practice](https://chadworley.github.io/a2/u07/written_exam/practice/ieodr_v001-050.pdf)
    * [Solutions](https://chadworley.github.io/a2/u07/written_exam/practice/ieodr_sol_v001-050.pdf)
* u07_written_exam
* If you're done with everything, please practice in ALEKS or help your peers (but not DIRECTLY on Mastery assignments).

### Fri Nov 15

* ET_053 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2539)/[public](https://chadworley.github.io/a2/ET2/ET_053.html)
* u08_01_intervals_inc_dec_pos_neg_quad [Canvas](https://bart.instructure.com/courses/1314/quizzes/2563)/[public](https://chadworley.github.io/a2/u08/outhtml/01_intervals_inc_dec_pos_neg_quad.html)
* u08_02_intervals_sinusoidal [Canvas](https://bart.instructure.com/courses/1314/quizzes/2564)/[public](https://chadworley.github.io/a2/u08/outhtml/02_intervals_sinusoidal.html)
* u08_03_translate_table [Canvas](https://bart.instructure.com/courses/1314/quizzes/2565)/[public](https://chadworley.github.io/a2/u08/outhtml/03_translate_table.html)
* u08_04_stretch_table [Canvas](https://bart.instructure.com/courses/1314/quizzes/2566)/[public](https://chadworley.github.io/a2/u08/outhtml/04_stretch_table.html)

# Unit 8: Intervals, Transformations, Compositions, and Slope (weeks 14-15)

## Week 14 {.tabset}

### Mon Nov 18

* ET_054 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2540)/[public](https://chadworley.github.io/a2/ET2/ET_054.html)
* u08_05_translate_and_stretch [Canvas](https://bart.instructure.com/courses/1314/quizzes/2567)/[public](https://chadworley.github.io/a2/u08/outhtml/05_translate_and_stretch.html)
* u08_06_compose_table [Canvas](https://bart.instructure.com/courses/1314/quizzes/2568)/[public](https://chadworley.github.io/a2/u08/outhtml/06_compose_table.html)
* u08_07_compose_graphs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2569)/[public](https://chadworley.github.io/a2/u08/outhtml/07_compose_graphs.html)
* u08_08_intervals_check [Canvas](https://bart.instructure.com/courses/1314/quizzes/2571)/[public](https://chadworley.github.io/a2/u08/outhtml/08_intervals_check.html)
* u08_09_translate_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2572)/[public](https://chadworley.github.io/a2/u08/outhtml/09_translate_graph.html)
* u08_10_stretch_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2573)/[public](https://chadworley.github.io/a2/u08/outhtml/10_stretch_graph.html)
* *F-IF.B.4: For a function that models a relationship between two quantities, interpret key features of graphs and tables in terms of the quantities, and sketch graphs showing key features given a verbal description of the relationship. Key features include: intercepts; intervals where the function is increasing, decreasing, positive, or negative; relative maximums and minimums; symmetries; end behavior; and periodicity.*
* *F-BF.B.3: Identify the effect on the graph of replacing $f(x)$ by $f(x)+k$, $k\,f(x)$, $f(kx)$, and $f(x + k)$ for specific values of $k$ (both positive and negative); find the value of $k$ given the graphs. Include simple rational, radical, logarithmic, and trigonometric functions. Utilize technology to experiment with cases and illustrate an explanation of the effects on the graph using technology. Include recognizing even and odd functions from their graphs and algebraic expressions for them.*

### Tue Nov 19

* ET_055 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2541)/[public](https://chadworley.github.io/a2/ET2/ET_055.html)
* u08_11_animate_transforms [Canvas](https://bart.instructure.com/courses/1314/quizzes/2578)/[public](https://chadworley.github.io/a2/u08/outhtml/11_animate_transforms.html)
* u08_12_identify_transformation [Canvas](https://bart.instructure.com/courses/1314/quizzes/2575)/[public](https://chadworley.github.io/a2/u08/outhtml/12_identify_transformation.html)
* u08_13_AROC_from_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2576)/[public](https://chadworley.github.io/a2/u08/outhtml/13_AROC_from_graph.html)
* u08_14_projectile_ave_vel [Canvas](https://bart.instructure.com/courses/1314/quizzes/2577)/[public](https://chadworley.github.io/a2/u08/outhtml/14_projectile_ave_vel.html)
* *F-IF.B.6: Calculate and interpret the average rate of change of a function (presented symbolically or as a table) over a specified interval. Estimate the rate of change from a graph.*

### Wed Nov 20

* ET_056 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2542)/[public](https://chadworley.github.io/a2/ET2/ET_056.html)
* u08_15_aroc_table [Canvas](https://bart.instructure.com/courses/1314/quizzes/2581)/[public](https://chadworley.github.io/a2/u08/outhtml/15_aroc_table.html)
* u08_16_instant_AROC [Canvas](https://bart.instructure.com/courses/1314/quizzes/2582)/[public](https://chadworley.github.io/a2/u08/outhtml/16_instant_AROC.html)

### Thu Nov 21 

* ET_057 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2543)/[public](https://chadworley.github.io/a2/ET2/ET_057.html)
* u08_17_AROC_dimensions [Canvas](https://bart.instructure.com/courses/1314/quizzes/2592)/[public](https://chadworley.github.io/a2/u08/outhtml/17_AROC_dimensions.html)
* u08__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2594)


### Fri Nov 22 

* ET_058 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2544)/[public](https://chadworley.github.io/a2/ET2/ET_058.html)
* u08_written_practice [Canvas](https://bart.instructure.com/courses/1314/assignments/23224)/[public_blanks](https://chadworley.github.io/a2/u08/written_exam/practice/u08we_v001-050.pdf)/[public_solutions](https://chadworley.github.io/a2/u08/written_exam/practice/u08we_sol_v001-010.pdf)

## Week 15 {.tabset}

### Mon Nov 25

* ET_059 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2545)/[public](https://chadworley.github.io/a2/ET2/ET_059.html) 
* A quick review of [practice version 2](https://chadworley.github.io/a2/u08/written_exam/practice/u08we_v002.pdf). Here is its [solution](https://chadworley.github.io/a2/u08/written_exam/practice/u08we_sol_v002.pdf).
* Finish the practice exams.
* For last 20 minutes, EVERYONE takes the exam in silence. Handheld (non-graphing) calculators are okay, but not needed.
* u08_written_exam [Canvas](https://bart.instructure.com/courses/1314/assignments/23252)/[public_practice](https://chadworley.github.io/a2/u08/written_exam/practice/u08we_v001-050.pdf)/[public_solutions](https://chadworley.github.io/a2/u08/written_exam/practice/u08we_sol_v001-010.pdf)

### Tue Nov 26

* ET_060 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2546)/[public](https://chadworley.github.io/a2/ET2/ET_060.html) 
* Catch up
* Retake exams
* Continue path on ALEKS

### Wed Nov 27

* ET_061 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2547)/[public](https://chadworley.github.io/a2/ET2/ET_061.html) 
* Catch up
* Retake exams
* Continue path on ALEKS


# Unit 9: Review and Interim (weeks 16-17)

## Week 16 {.tabset}

### Mon Dec 02

* ET_062 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2548)/[public](https://chadworley.github.io/a2/ET2/ET_062.html) 
* u09_01_factor_quad_w_primes [Canvas](https://bart.instructure.com/courses/1314/quizzes/2596)/[public](https://chadworley.github.io/a2/u09/outhtml/01_factor_quad_w_primes.html)
* u09_02_solve_quadratric_simple [Canvas](https://bart.instructure.com/courses/1314/quizzes/2597)/[public](https://chadworley.github.io/a2/u09/outhtml/02_solve_quadratric_simple.html)
* u09_03_solve_quad_w_primes [Canvas](https://bart.instructure.com/courses/1314/quizzes/2598)/[public](https://chadworley.github.io/a2/u09/outhtml/03_solve_quad_w_primes.html)
* ALEKS: Interim Practice
* The Interim will be on Wed Dec 11th

### Tue Dec 03

* ET_063 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2549)/[public](https://chadworley.github.io/a2/ET2/ET_063.html) 
* u09_04_car_force_power [Canvas](https://bart.instructure.com/courses/1314/quizzes/2600)/[public](https://chadworley.github.io/a2/u09/outhtml/04_car_force_power.html)
* u09_05_inverse_cube_function [Canvas](https://bart.instructure.com/courses/1314/quizzes/2601)/[public](https://chadworley.github.io/a2/u09/outhtml/05_inverse_cube_function.html)
* ALEKS: Interim Practice
* The Interim will be on Wed Dec 11th

### Wed Dec 04

* ET_064 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2550)/[public](https://chadworley.github.io/a2/ET2/ET_064.html)
* ALEKS: Interim Practice
* The Interim will be on Wed Dec 11th
* For the Interim, you must have your chromebook!

### Thu Dec 05

* SNOW DAY!!!

### Fri Dec 04

* ET_065 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2551)/[public](https://chadworley.github.io/a2/ET2/ET_065.html)
* ALEKS: Interim Practice
* The Interim will be on Wed Dec 11th
* For the Interim, you must have your chromebook!
* You can make a hand-written reference on an index card (approximately 3 in x 5 in).
* You will be allowed to use hand-held calculators and [Desmos](https://www.desmos.com/calculator)

## Week 17 {.tabset}

### Mon Dec 9

* ET_066 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2552)/[public](https://chadworley.github.io/a2/ET2/ET_066.html)
* ALEKS: Interim Practice
* The Interim will be on Wed Dec 11th
* For the Interim, you must have your chromebook!
* You can make a hand-written reference on an index card (approximately 3 in x 5 in).
* You will be allowed to use hand-held calculators and [Desmos](https://www.desmos.com/calculator)

### Tue Dec 10

* ET_067 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2553)/[public](https://chadworley.github.io/a2/ET2/ET_067.html)
* ALEKS: Interim Practice
* The Interim will be on Wed Dec 11th
* For the Interim, you must have your chromebook!
* You can make a hand-written reference on an index card (approximately 3 in x 5 in).
* You will be allowed to use hand-held calculators and [Desmos](https://www.desmos.com/calculator)

### Wed Dec 11

* ALEKS: Interim
* You can have a hand-written reference on an index card (approximately 3 in x 5 in).
* You will be allowed to use hand-held calculators and [Desmos](https://www.desmos.com/calculator).
* No other tabs are allowed during this interim test.
* You may only work on the test under supervision by a teacher who knows the rules (1 note card, Desmos, and hand-held calculators only).
* When finished, remain silent. Please find something quiet to work on.
* You will have 1 retake (to have a 2nd attempt at missed questions).
* At end of test period, hand in scratch paper and index card. (Put your name of both.)

### Thu Dec 12

* ALEKS: Interim
* You can have a hand-written reference on an index card (approximately 3 in x 5 in).
* You will be allowed to use hand-held calculators and [Desmos](https://www.desmos.com/calculator).
* No other tabs are allowed during this interim test.
* You may only work on the test under supervision by a teacher who knows the rules (1 note card, Desmos, and hand-held calculators only).
* When finished, remain silent. Please find something quiet to work on.
* You will have 1 retake (to have a 2nd attempt at missed questions).
* At end of test period, hand in scratch paper and index card. (Put your name of both.)

### Fri Dec 13

* ALEKS: Interim
* You can have a hand-written reference on an index card (approximately 3 in x 5 in).
* You will be allowed to use hand-held calculators and [Desmos](https://www.desmos.com/calculator).
* No other tabs are allowed during this interim test.
* You may only work on the test under supervision by a teacher who knows the rules (1 note card, Desmos, and hand-held calculators only).
* When finished, remain silent. Please find something quiet to work on.
* I've added a 3rd attempt, so everyone can continue improving their score.
* At end of test period, hand in scratch paper and index card. (Put your name of both.)


# Unit 10: Radicals, Rationals, Extraneous Solutions (week 18)

## Week 18 {.tabset}

### Mon Dec 16

* ET_068 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2554)/[public](https://chadworley.github.io/a2/ET2/ET_068.html)
* u10_01_sqrt_lake_area [Canvas](https://bart.instructure.com/courses/1314/quizzes/2610)/[public](https://chadworley.github.io/a2/u10/outhtml/01_sqrt_lake_area.html)
* u10_02_points_on_sqrtx [Canvas](https://bart.instructure.com/courses/1314/quizzes/2623)/[public](https://chadworley.github.io/a2/u10/outhtml/02_points_on_sqrtx.html)
* u10_03_translate_flip_sqrt [Canvas](https://bart.instructure.com/courses/1314/quizzes/2612)/[public](https://chadworley.github.io/a2/u10/outhtml/03_translate_flip_sqrt.html)
* u10_04_sqrt_shift_points [Canvas](https://bart.instructure.com/courses/1314/quizzes/2613)/[public](https://chadworley.github.io/a2/u10/outhtml/04_sqrt_shift_points.html)
* u10_05_points_on_cbrtx [Canvas](https://bart.instructure.com/courses/1314/quizzes/2624)/[public](https://chadworley.github.io/a2/u10/outhtml/05_points_on_cbrtx.html)
* u10_06_translate_flip_cbrt [Canvas](https://bart.instructure.com/courses/1314/quizzes/2615)/[public](https://chadworley.github.io/a2/u10/outhtml/06_translate_flip_cbrt.html)
* *F-IF.C.7.b Graph square root and cube root functions.*

### Tue Dec 17

* ET_069 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2555)/[public](https://chadworley.github.io/a2/ET2/ET_069.html)
* u10_07_sqrt_line_extraneous [Canvas](https://bart.instructure.com/courses/1314/quizzes/2616)/[public](https://chadworley.github.io/a2/u10/outhtml/07_sqrt_line_extraneous.html)
* u10_08_factrd_rational_featrs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2617)/[public](https://chadworley.github.io/a2/u10/outhtml/08_factrd_rational_featrs.html)
* u10_09_expndd_rational_featrs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2618)/[public](https://chadworley.github.io/a2/u10/outhtml/09_expndd_rational_featrs.html)
* u10_10_find_rational_hole [Canvas](https://bart.instructure.com/courses/1314/quizzes/2619)/[public](https://chadworley.github.io/a2/u10/outhtml/10_find_rational_hole.html)
* u10_11_line_thru_rational_hole [Canvas](https://bart.instructure.com/courses/1314/quizzes/2620)/[public](https://chadworley.github.io/a2/u10/outhtml/11_line_thru_rational_hole.html)
* *A-REI.A.2: Solve simple rational and radical equations in one variable, and give examples showing how extraneous solutions may arise.*

### Wed Dec 18

* ET_070 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2625)/[public](https://chadworley.github.io/a2/ET2/ET_070.html)
* u10_12_add_rationals [Canvas](https://bart.instructure.com/courses/1314/quizzes/2655)/[public](https://chadworley.github.io/a2/u10/outhtml/12_add_rationals.html)
* u10_13_subtract_rationals [Canvas](https://bart.instructure.com/courses/1314/quizzes/2656)/[public](https://chadworley.github.io/a2/u10/outhtml/13_subtract_rationals.html)
* u10_14_mult_rationals [Canvas](https://bart.instructure.com/courses/1314/quizzes/2657)/[public](https://chadworley.github.io/a2/u10/outhtml/14_mult_rationals.html)
* u10_15_div_rationals [Canvas](https://bart.instructure.com/courses/1314/quizzes/2658)/[public](https://chadworley.github.io/a2/u10/outhtml/15_div_rationals.html)
* *A-APR.D.7: (+) Understand that rational expressions form a system analogous to the rational numbers, closed under addition, subtraction, multiplication, and division by a nonzero rational expression; add, subtract, multiply, and divide rational expressions.*

### Thu Dec 19

* ET_071 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2626)/[public](https://chadworley.github.io/a2/ET2/ET_071.html)
* u10_16_inverse_rational [Canvas](https://bart.instructure.com/courses/1314/quizzes/2659)/[public](https://chadworley.github.io/a2/u10/outhtml/16_inverse_rational.html)
* u10_17_radical_dom_rng [Canvas](https://bart.instructure.com/courses/1314/quizzes/2660)/[public](https://chadworley.github.io/a2/u10/outhtml/17_radical_dom_rng.html)
* u10__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2664)
* *F-BF.B.4: Solve an equation of the form $f(x) = c$ for a simple function $f$ that has an inverse and write an expression for the inverse.*

### Fri Dec 20

* ET_072 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2627)/[public](https://chadworley.github.io/a2/ET2/ET_072.html)
* u10__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2664)


# Unit 11: Distance, Circles, Inequalities, Creating Equations (weeks 20-22)

## Week 20 {.tabset}

### Thu Jan 02

* ET_073 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2628)/[public](https://chadworley.github.io/a2/ET2/ET_073.html)
* u11_01_distance_formula [Canvas](https://bart.instructure.com/courses/1314/quizzes/2665)/[public](https://chadworley.github.io/a2/u11/outhtml/01_distance_formula.html)
* u11_02_points_within_distance [Canvas](https://bart.instructure.com/courses/1314/quizzes/2666)/[public](https://chadworley.github.io/a2/u11/outhtml/02_points_within_distance.html)
* u11_03_points_in_overlap [Canvas](https://bart.instructure.com/courses/1314/quizzes/2667)/[public](https://chadworley.github.io/a2/u11/outhtml/03_points_in_overlap.html)
* u11_04_trilateration [Canvas](https://bart.instructure.com/courses/1314/quizzes/2668)/[public](https://chadworley.github.io/a2/u11/outhtml/04_trilateration.html)
* **A-CED.A.2: Create equations in two or more variables to represent relationships between quantities; graph equations on coordinate axes with labels and scales.**
* **A-CED.A.3: Represent constraints by equations or inequalities, and by systems of equations and/or inequalities, and interpret solutions as viable or non-viable options in a modeling context.**

### Fri Jan 03

* ET_074 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2629)/[public](https://chadworley.github.io/a2/ET2/ET_074.html)
* u11_05_triangle_perimeter [Canvas](https://bart.instructure.com/courses/1314/quizzes/2669)/[public](https://chadworley.github.io/a2/u11/outhtml/05_triangle_perimeter.html)
* u11_06_archery_target [Canvas](https://bart.instructure.com/courses/1314/quizzes/2670)/[public](https://chadworley.github.io/a2/u11/outhtml/06_archery_target.html)
* u11_07_three_dim_dist [Canvas](https://bart.instructure.com/courses/1314/quizzes/2671)/[public](https://chadworley.github.io/a2/u11/outhtml/07_three_dim_dist.html)
* u11_08_circ_by_compltng_sqr [Canvas](https://bart.instructure.com/courses/1314/quizzes/2672)/[public](https://chadworley.github.io/a2/u11/outhtml/08_circ_by_compltng_sqr.html)
* u11_09_ratio_between_points [Canvas](https://bart.instructure.com/courses/1314/quizzes/2673)/[public](https://chadworley.github.io/a2/u11/outhtml/09_ratio_between_points.html)

## Week 21 {.tabset}

### Mon Jan 06

* ET_075 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2630)/[public](https://chadworley.github.io/a2/ET2/ET_075.html)
* u11_10_check_sols_ineq [Canvas](https://bart.instructure.com/courses/1314/quizzes/2674)/[public](https://chadworley.github.io/a2/u11/outhtml/10_check_sols_ineq.html)
* u11_11_linear_programming [Canvas](https://bart.instructure.com/courses/1314/quizzes/2675)/[public](https://chadworley.github.io/a2/u11/outhtml/11_linear_programming.html)
* u11_12_dist_point_to_line [Canvas](https://bart.instructure.com/courses/1314/quizzes/2676)/[public](https://chadworley.github.io/a2/u11/outhtml/12_dist_point_to_line.html)

### Tue Jan 07

* ET_076 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2631)/[public](https://chadworley.github.io/a2/ET2/ET_076.html)
* u11_13_ticket_prices [Canvas](https://bart.instructure.com/courses/1314/quizzes/2677)/[public](https://chadworley.github.io/a2/u11/outhtml/13_ticket_prices.html)
* u11_14_resize_image_even_border [Canvas](https://bart.instructure.com/courses/1314/quizzes/2678)/[public](https://chadworley.github.io/a2/u11/outhtml/14_resize_image_even_border.html)
* u11_15_optimize_run_swim [Canvas](https://bart.instructure.com/courses/1314/quizzes/2679)/[public](https://chadworley.github.io/a2/u11/outhtml/15_optimize_run_swim.html)
* u11_16_nth_score [Canvas](https://bart.instructure.com/courses/1314/quizzes/2680)/[public](https://chadworley.github.io/a2/u11/outhtml/16_nth_score.html)

### Wed Jan 08

* ET_077 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2632)/[public](https://chadworley.github.io/a2/ET2/ET_077.html)
* u11_17_circ_params_from_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2681)/[public](https://chadworley.github.io/a2/u11/outhtml/17_circ_params_from_graph.html)
* u11_18_circ_params_from_eq [Canvas](https://bart.instructure.com/courses/1314/quizzes/2682)/[public](https://chadworley.github.io/a2/u11/outhtml/18_circ_params_from_eq.html)
* u11_19_circ_2nd_coordinate [Canvas](https://bart.instructure.com/courses/1314/quizzes/2683)/[public](https://chadworley.github.io/a2/u11/outhtml/19_circ_2nd_coordinate.html)
* u11_20_fef_dist_ellipse [Canvas](https://bart.instructure.com/courses/1314/quizzes/2684)/[public](https://chadworley.github.io/a2/u11/outhtml/20_fef_dist_ellipse.html)
* u11_21_ellipse_get_pams [Canvas](https://bart.instructure.com/courses/1314/quizzes/2685)/[public](https://chadworley.github.io/a2/u11/outhtml/21_ellipse_get_pams.html)
* u11_22_polynom_to_stndrd_ell [Canvas](https://bart.instructure.com/courses/1314/quizzes/2686)/[public](https://chadworley.github.io/a2/u11/outhtml/22_polynom_to_stndrd_ell.html)

### Thu Jan 09

* ET_078 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2633)/[public](https://chadworley.github.io/a2/ET2/ET_078.html)
* u11_23_round_trip_ave_speed [Canvas](https://bart.instructure.com/courses/1314/quizzes/2687)/[public](https://chadworley.github.io/a2/u11/outhtml/23_round_trip_ave_speed.html)
* u11_24_lagrange_polynomial [Canvas](https://bart.instructure.com/courses/1314/quizzes/2688)/[public](https://chadworley.github.io/a2/u11/outhtml/24_lagrange_polynomial.html)
* u11_25_cubic_regression [Canvas](https://bart.instructure.com/courses/1314/quizzes/2689)/[public](https://chadworley.github.io/a2/u11/outhtml/25_cubic_regression.html)
* u11_26_predict_with_trendline [Canvas](https://bart.instructure.com/courses/1314/quizzes/2690)/[public](https://chadworley.github.io/a2/u11/outhtml/26_predict_with_trendline.html)

### Fri Jan 10

* ET_079 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2634)/[public](https://chadworley.github.io/a2/ET2/ET_079.html)
* u11__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2691)

## Week 22 {.tabset}

### Mon Jan 13

* ET_080 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2635)/[public](https://chadworley.github.io/a2/ET2/ET_080.html)
* u11__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2691)

### Tue Jan 14

* ET_081 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2636)/[public](https://chadworley.github.io/a2/ET2/ET_081.html)
* u11__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2691)


### Wed Jan 15

* ET_082 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2637)/[public](https://chadworley.github.io/a2/ET2/ET_082.html)
* u11__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2691)

### Thu Jan 16

* ET_083 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2638)/[public](https://chadworley.github.io/a2/ET2/ET_083.html)
* End-of-quarter make-up day

### Fri Jan 17

* ET_084 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2639)/[public](https://chadworley.github.io/a2/ET2/ET_084.html)
* End-of-quarter make-up day


# Unit 12: Radians, angles, arc lengths (weeks 23-24)

## Week 23 {.tabset}

### Tue Jan 21

* ET_085 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2640)/[public](https://chadworley.github.io/a2/ET2/ET_085.html)
* u12_slides_radians [public](https://chadworley.github.io/a2/u12/slides/u12_slides_radians.html)
* u12_01_arc_length_from_frac [Canvas](https://bart.instructure.com/courses/1314/quizzes/2693)/[public](https://chadworley.github.io/a2/u12/outhtml/01_arc_length_from_frac.html)
* u12_02_arc_length_from_degs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2694)/[public](https://chadworley.github.io/a2/u12/outhtml/02_arc_length_from_degs.html)
* u12_03_arc_len_frm_intrr_ang [Canvas](https://bart.instructure.com/courses/1314/quizzes/2695)/[public](https://chadworley.github.io/a2/u12/outhtml/03_arc_len_frm_intrr_ang.html)
* u12_04_arc_len_from_unit_arc [Canvas](https://bart.instructure.com/courses/1314/quizzes/2696)/[public](https://chadworley.github.io/a2/u12/outhtml/04_arc_len_from_unit_arc.html)
* u12_05_radians_from_r_L [Canvas](https://bart.instructure.com/courses/1314/quizzes/2697)/[public](https://chadworley.github.io/a2/u12/outhtml/05_radians_from_r_L.html)
* u12_06_radians_from_unit_arc [Canvas](https://bart.instructure.com/courses/1314/quizzes/2698)/[public](https://chadworley.github.io/a2/u12/outhtml/06_radians_from_unit_arc.html)
* u12_07_radians_from_arc_length [Canvas](https://bart.instructure.com/courses/1314/quizzes/2699)/[public](https://chadworley.github.io/a2/u12/outhtml/07_radians_from_arc_length.html)
* u12_08_angle_conversions [Canvas](https://bart.instructure.com/courses/1314/quizzes/2700)/[public](https://chadworley.github.io/a2/u12/outhtml/08_angle_conversions.html)
* *F-TF.A.1: Understand radian measure of an angle as the length of the arc on the unit circle subtended by the angle.*


### Wed Jan 22

* ET_086 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2641)/[public](https://chadworley.github.io/a2/ET2/ET_086.html)
* u12_09_standard_pos_deg [Canvas](https://bart.instructure.com/courses/1314/quizzes/2707)/[public](https://chadworley.github.io/a2/u12/outhtml/09_standard_pos_deg.html)
* u12_10_large_angle_deg [Canvas](https://bart.instructure.com/courses/1314/quizzes/2708)/[public](https://chadworley.github.io/a2/u12/outhtml/10_large_angle_deg.html)
* u12_11_coterminal_degs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2709)/[public](https://chadworley.github.io/a2/u12/outhtml/11_coterminal_degs.html)
* u12_12_plot_angle_rads [Canvas](https://bart.instructure.com/courses/1314/quizzes/2710)/[public](https://chadworley.github.io/a2/u12/outhtml/12_plot_angle_rads.html)
* u12_13_plot_coterminal_rads [Canvas](https://bart.instructure.com/courses/1314/quizzes/2711)/[public](https://chadworley.github.io/a2/u12/outhtml/13_plot_coterminal_rads.html)
* u12_14_large_angle_rad [Canvas](https://bart.instructure.com/courses/1314/quizzes/2712)/[public](https://chadworley.github.io/a2/u12/outhtml/14_large_angle_rad.html)
* u12_15_sector_area [Canvas](https://bart.instructure.com/courses/1314/quizzes/2713)/[public](https://chadworley.github.io/a2/u12/outhtml/15_sector_area.html)
* u12_16_conical_ratio [Canvas](https://bart.instructure.com/courses/1314/quizzes/2714)/[public](https://chadworley.github.io/a2/u12/outhtml/16_conical_ratio.html)


### Thu Jan 23

* ET_087 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2642)/[public](https://chadworley.github.io/a2/ET2/ET_087.html)
* Make-up day


### Fri Jan 24

* ET_088 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2643)/[public](https://chadworley.github.io/a2/ET2/ET_088.html)
* As a class, we will work on [u12_written_exam_example_v-2](https://chadworley.github.io/a2/u12/written_exam/example/u12pwe_v-02.pdf)
* As a class, we will practice converting between radians and degrees on [Blooket](https://dashboard.blooket.com/set/6791b18623f16bc7ffff3a8c).
* Independent work: written exam practice (paper copy distributed after Blooket) 
    * due Thu Jan 30 in class
* Independent work: [Blooket HW](https://play.blooket.com/play?hwId=67937c3f87e5b6df67ac9491)
    * Please fill out [this google form](https://docs.google.com/forms/d/e/1FAIpQLSfWdtJVkwSaEhJgaNAYdo_SS7zryWN6ELn3XebowrSYoA_RhQ/viewform?usp=header) with your nickname.
    * due Wed Jan 29 before midnight (the Blooket will become unavailable.)


## Week 24 {.tabset}

### Mon Jan 27

* ET_089 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2644)/[public](https://chadworley.github.io/a2/ET2/ET_089.html)
* [u12__mastery](https://bart.instructure.com/courses/1314/quizzes/2715) (Due Tue Jan 28 @ 11:59 PM)
* [Blooket HW](https://play.blooket.com/play?hwId=67937c3f87e5b6df67ac9491) (Due Wed Jan 29 @ 11:59 PM)
    * When done, fill out [this google form](https://docs.google.com/forms/d/e/1FAIpQLSfWdtJVkwSaEhJgaNAYdo_SS7zryWN6ELn3XebowrSYoA_RhQ/viewform?usp=header) with your nickname.
* [Written exam practice](https://bart.instructure.com/courses/1314/assignments/24036) (On paper, due Thu Jan 30 @ class)
* The written exam will be on Thursday Jan 30 in class.

### Tue Jan 28

* ET_090 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2645)/[public](https://chadworley.github.io/a2/ET2/ET_090.html)
* [u12__mastery](https://bart.instructure.com/courses/1314/quizzes/2715) (Due Tue Jan 28 @ 11:59 PM)
* [Blooket HW](https://play.blooket.com/play?hwId=67937c3f87e5b6df67ac9491) (Due Wed Jan 29 @ 11:59 PM)
    * When done, fill out [this google form](https://docs.google.com/forms/d/e/1FAIpQLSfWdtJVkwSaEhJgaNAYdo_SS7zryWN6ELn3XebowrSYoA_RhQ/viewform?usp=header) with your nickname.
* [Written exam practice](https://bart.instructure.com/courses/1314/assignments/24036) (On paper, due Thu Jan 30 @ class)
* The written exam will be on Thursday Jan 30 in class.


### Wed Jan 29

* ET_091 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2646)/[public](https://chadworley.github.io/a2/ET2/ET_091.html)
* [Blooket HW](https://play.blooket.com/play?hwId=67937c3f87e5b6df67ac9491) (Due Wed Jan 29 @ 11:59 PM)
    * When done, fill out [this google form](https://docs.google.com/forms/d/e/1FAIpQLSfWdtJVkwSaEhJgaNAYdo_SS7zryWN6ELn3XebowrSYoA_RhQ/viewform?usp=header) with your nickname.
* [Written exam practice](https://bart.instructure.com/courses/1314/assignments/24036) (On paper, due Thu Jan 30 @ class)
* The written exam will be on Thursday Jan 30 in class.


### Thu Jan 30

* ET_092 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2647)/[public](https://chadworley.github.io/a2/ET2/ET_092.html)
* Hand in [written exam practice](https://bart.instructure.com/courses/1314/assignments/24036)
* Study for the written exam on Friday.

### Fri Jan 31

* ET_093 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2648)/[public](https://chadworley.github.io/a2/ET2/ET_093.html)
* Take the written exam! [practice](https://chadworley.github.io/a2/u12/written_exam/practice/u12we_examples.pdf)/[solutions](https://chadworley.github.io/a2/u12/written_exam/practice/u12we_examples_sols.pdf)


# Unit 13: Trig Basics (weeks 25-26)

## Week 25 {.tabset}

### Mon Feb 3

* ET_094 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2649)/[public](https://chadworley.github.io/a2/ET2/ET_094.html)
* u13_01_triangle_3rd_angle_deg [Canvas](https://bart.instructure.com/courses/1314/quizzes/2719)/[public](https://chadworley.github.io/a2/u13/outhtml/01_triangle_3rd_angle_deg.html)
* u13_02_triangle_3rd_angle_rad [Canvas](https://bart.instructure.com/courses/1314/quizzes/2720)/[public](https://chadworley.github.io/a2/u13/outhtml/02_triangle_3rd_angle_rad.html)
* u13_03_right_tri_complems_deg [Canvas](https://bart.instructure.com/courses/1314/quizzes/2721)/[public](https://chadworley.github.io/a2/u13/outhtml/03_right_tri_complems_deg.html)
* u13_04_right_tri_complems_rad [Canvas](https://bart.instructure.com/courses/1314/quizzes/2722)/[public](https://chadworley.github.io/a2/u13/outhtml/04_right_tri_complems_rad.html)
* u13_05_reference_angle_deg [Canvas](https://bart.instructure.com/courses/1314/quizzes/2723)/[public](https://chadworley.github.io/a2/u13/outhtml/05_reference_angle_deg.html)
* u13_06_reference_angle_rad [Canvas](https://bart.instructure.com/courses/1314/quizzes/2724)/[public](https://chadworley.github.io/a2/u13/outhtml/06_reference_angle_rad.html)
* u13_07_unit_hyp_pyth_thm [Canvas](https://bart.instructure.com/courses/1314/quizzes/2725)/[public](https://chadworley.github.io/a2/u13/outhtml/07_unit_hyp_pyth_thm.html)

### Tue Feb 4

* ET_095 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2650)/[public](https://chadworley.github.io/a2/ET2/ET_095.html)
* u13_08_uc_other_coord_from_Q [Canvas](https://bart.instructure.com/courses/1314/quizzes/2726)/[public](https://chadworley.github.io/a2/u13/outhtml/08_uc_other_coord_from_Q.html)
* u13_09_uc_slope_from_x_and_Q [Canvas](https://bart.instructure.com/courses/1314/quizzes/2727)/[public](https://chadworley.github.io/a2/u13/outhtml/09_uc_slope_from_x_and_Q.html)
* u13_10_uc_x_from_slope_Q1 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2728)/[public](https://chadworley.github.io/a2/u13/outhtml/10_uc_x_from_slope_Q1.html)
* u13_11_uc_x_y_from_slope_and_Q [Canvas](https://bart.instructure.com/courses/1314/quizzes/2729)/[public](https://chadworley.github.io/a2/u13/outhtml/11_uc_x_y_from_slope_and_Q.html)
* SOHCAHTOA Review Blooket [Canvas](https://bart.instructure.com/courses/1314/assignments/24145)

### Wed Feb 5

* ET_096 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2651)/[public](https://chadworley.github.io/a2/ET2/ET_096.html)
* Use trig function to find unknown length of right triangles, and use inverse trig function to find angle.
    * u13_12_sine_get_opposite [Canvas](https://bart.instructure.com/courses/1314/quizzes/2730)/[public](https://chadworley.github.io/a2/u13/outhtml/12_sine_get_opposite.html)
    * u13_13_sine_get_hypotenuse [Canvas](https://bart.instructure.com/courses/1314/quizzes/2731)/[public](https://chadworley.github.io/a2/u13/outhtml/13_sine_get_hypotenuse.html)
    * u13_14_sine_get_angle [Canvas](https://bart.instructure.com/courses/1314/quizzes/2732)/[public](https://chadworley.github.io/a2/u13/outhtml/14_sine_get_angle.html)
    * u13_15_cosine_get_adjacent [Canvas](https://bart.instructure.com/courses/1314/quizzes/2733)/[public](https://chadworley.github.io/a2/u13/outhtml/15_cosine_get_adjacent.html)
    * u13_16_cosine_get_hypotenuse [Canvas](https://bart.instructure.com/courses/1314/quizzes/2734)/[public](https://chadworley.github.io/a2/u13/outhtml/16_cosine_get_hypotenuse.html)
    * u13_17_cosine_get_angle [Canvas](https://bart.instructure.com/courses/1314/quizzes/2735)/[public](https://chadworley.github.io/a2/u13/outhtml/17_cosine_get_angle.html)
    * u13_18_tangent_get_opposite [Canvas](https://bart.instructure.com/courses/1314/quizzes/2736)/[public](https://chadworley.github.io/a2/u13/outhtml/18_tangent_get_opposite.html)
    * u13_19_tangent_get_adjacent [Canvas](https://bart.instructure.com/courses/1314/quizzes/2737)/[public](https://chadworley.github.io/a2/u13/outhtml/19_tangent_get_adjacent.html)
    * u13_20_tangent_get_angle [Canvas](https://bart.instructure.com/courses/1314/quizzes/2738)/[public](https://chadworley.github.io/a2/u13/outhtml/20_tangent_get_angle.html)
* Investigate how coordinates on unit circle relate to trigonometric ratios.
    * u13_21_trigs_from_uc_point_Q1 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2739)/[public](https://chadworley.github.io/a2/u13/outhtml/21_trigs_from_uc_point_Q1.html)
    * u13_22_pnt_n_slope_from_ang_Q1 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2740)/[public](https://chadworley.github.io/a2/u13/outhtml/22_pnt_n_slope_from_ang_Q1.html)



### Thu Feb 6

* SNOW DAY!!

### Fri Feb 7

* ET_097 (Pop Quiz) [Canvas](https://bart.instructure.com/courses/1314/quizzes/2750)

## Week 26 {.tabset}

### Mon Feb 10

* ET_098 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2653)/[public](https://chadworley.github.io/a2/ET2/ET_098.html)
* Slides: [unit circle defs of trig functions](https://chadworley.github.io/a2/u13/slides/unit_circ_defs.html#(1))
* u13_23_plr_vect_add_simp [Canvas](https://bart.instructure.com/courses/1314/quizzes/2751)/[public](https://chadworley.github.io/a2/u13/outhtml/23_plr_vect_add_simp.html)
* u13_24_polar_to_rect [Canvas](https://bart.instructure.com/courses/1314/quizzes/2752)/[public](https://chadworley.github.io/a2/u13/outhtml/24_polar_to_rect.html)
* u13_25_unit_circ_intro [Canvas](https://bart.instructure.com/courses/1314/quizzes/2753)/[public](https://chadworley.github.io/a2/u13/outhtml/25_unit_circ_intro.html)
* u13_26_unit_circ_float [Canvas](https://bart.instructure.com/courses/1314/quizzes/2754)/[public](https://chadworley.github.io/a2/u13/outhtml/26_unit_circ_float.html)
* u13_27_match_parametrics [Canvas](https://bart.instructure.com/courses/1314/quizzes/2755)/[public](https://chadworley.github.io/a2/u13/outhtml/27_match_parametrics.html)

### Tue Feb 11

* ET_099 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2654)/[public](https://chadworley.github.io/a2/ET2/ET_099.html)
* u13_28_sin_from_cos_and_Q [Canvas](https://bart.instructure.com/courses/1314/quizzes/2777)/[public](https://chadworley.github.io/a2/u13/outhtml/28_sin_from_cos_and_Q.html)
* u13_29_sin_from_tan_and_Q [Canvas](https://bart.instructure.com/courses/1314/quizzes/2778)/[public](https://chadworley.github.io/a2/u13/outhtml/29_sin_from_tan_and_Q.html)
* u13_30_cos_from_sin_and_Q [Canvas](https://bart.instructure.com/courses/1314/quizzes/2779)/[public](https://chadworley.github.io/a2/u13/outhtml/30_cos_from_sin_and_Q.html)
* u13_31_cos_from_tan_and_Q [Canvas](https://bart.instructure.com/courses/1314/quizzes/2780)/[public](https://chadworley.github.io/a2/u13/outhtml/31_cos_from_tan_and_Q.html)
* u13_32_tan_from_sin_and_Q [Canvas](https://bart.instructure.com/courses/1314/quizzes/2783)/[public](https://chadworley.github.io/a2/u13/outhtml/32_tan_from_sin_and_Q.html)
* u13_33_tan_from_cos_and_Q [Canvas](https://bart.instructure.com/courses/1314/quizzes/2782)/[public](https://chadworley.github.io/a2/u13/outhtml/33_tan_from_cos_and_Q.html)
* *F-TF.C.8: Prove the Pythagorean identity $\sin^2(\theta) + \cos^2(\theta) = 1$ and use it to find $\sin(\theta)$, $\cos(\theta)$, or $\tan(\theta)$ given $\sin(\theta)$, $\cos(\theta)$, or $\tan(\theta)$ and the quadrant.*

### Wed Feb 12

* ET_100 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2757)/[public](https://chadworley.github.io/a2/ET2/ET_100.html)
* u13__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2785)


### Thu Feb 13


* u13__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2785)
* Blooket: [Solve Right Triangles](https://play.blooket.com/play?hwId=67ae0691bfcd44ddfec331db) due Mon Feb 24.

### Fri Feb 14

* ET_101 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2758)/[public](https://chadworley.github.io/a2/ET2/ET_101.html)
* [Slides: Pythagorean Identities](https://chadworley.github.io/a2/u13/slides/Pythagorean_Identitiy.html#(1))
* u13__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2785)
* Blooket: [Solve Right Triangles](https://play.blooket.com/play?hwId=67ae0691bfcd44ddfec331db) due Mon Feb 24.


# Unit 14: Vectors and Special Right Triangles (weeks 28-29)

## Week 28 {.tabset}

### Mon Feb 24

* ET_102 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2759)/[public](https://chadworley.github.io/a2/ET2/ET_102.html)
* [Slides: Pythagorean Identities](https://chadworley.github.io/a2/u13/slides/Pythagorean_Identitiy.html#(1))
* [Desmos: Trig Circle](https://www.desmos.com/calculator/vbkwdngceg)
* [Cheat Sheet](https://chadworley.github.io/a2/u13/rtt_cheat_sheet/cheat_sheet_uc_trig.pdf)
* [Review (Mastery) of Pythagorean Identities](https://bart.instructure.com/courses/1314/quizzes/2786)
* [Blooket (Effort) more Pythagorean Identity Practice](https://play.blooket.com/play?hwId=67bbee34b2cd265b715b9341)
* *F-TF.C.8: Prove the Pythagorean identity $\sin^2(\theta) + \cos^2(\theta) = 1$ and use it to find $\sin(\theta)$, $\cos(\theta)$, or $\tan(\theta)$ given $\sin(\theta)$, $\cos(\theta)$, or $\tan(\theta)$ and the quadrant.*


### Tue Feb 25

* ET_103 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2760)/[public](https://chadworley.github.io/a2/ET2/ET_103.html)
* u14_01_shadow_speed [Canvas](https://bart.instructure.com/courses/1314/quizzes/2794)/[public](https://chadworley.github.io/a2/u14/outhtml/01_shadow_speed.html)
* u14_02_sunset_shadow_speed [Canvas](https://bart.instructure.com/courses/1314/quizzes/2795)/[public](https://chadworley.github.io/a2/u14/outhtml/02_sunset_shadow_speed.html)
* u14_03_bearing_distance_decomp [Canvas](https://bart.instructure.com/courses/1314/quizzes/2796)/[public](https://chadworley.github.io/a2/u14/outhtml/03_bearing_distance_decomp.html)
* u14_04_rect_to_polar [Canvas](https://bart.instructure.com/courses/1314/quizzes/2797)/[public](https://chadworley.github.io/a2/u14/outhtml/04_rect_to_polar.html)
* u14_05_add_vectors [Canvas](https://bart.instructure.com/courses/1314/quizzes/2798)/[public](https://chadworley.github.io/a2/u14/outhtml/05_add_vectors.html)
* *N-VM.A.1: Recognize vector quantities as having both magnitude and direction. Represent vector quantities by directed line segments, and use appropriate symbols for vectors and their magnitudes.*
* *N-VM.A.3: Solve problems involving velocity and other quantities that can be represented by vectors.*

### Wed Feb 26

* ET_104 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2761)/[public](https://chadworley.github.io/a2/ET2/ET_104.html)
* u14_06_turn_atan2_degs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2804)/[public](https://chadworley.github.io/a2/u14/outhtml/06_turn_atan2_degs.html)
* u14_07_turn_atan2_rads [Canvas](https://bart.instructure.com/courses/1314/quizzes/2805)/[public](https://chadworley.github.io/a2/u14/outhtml/07_turn_atan2_rads.html)
* u14_08_short_turn_degs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2806)/[public](https://chadworley.github.io/a2/u14/outhtml/08_short_turn_degs.html)
* u14_09_short_turn_rads [Canvas](https://bart.instructure.com/courses/1314/quizzes/2807)/[public](https://chadworley.github.io/a2/u14/outhtml/09_short_turn_rads.html)
* u14_10_rotate_point_degs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2808)/[public](https://chadworley.github.io/a2/u14/outhtml/10_rotate_point_degs.html)
* u14_11_rotate_point_rads [Canvas](https://bart.instructure.com/courses/1314/quizzes/2809)/[public](https://chadworley.github.io/a2/u14/outhtml/11_rotate_point_rads.html)

### Thu Feb 27

* ET_105 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2762)/[public](https://chadworley.github.io/a2/ET2/ET_105.html)
* u14_12_canoe_river_degs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2810)/[public](https://chadworley.github.io/a2/u14/outhtml/12_canoe_river_degs.html)
* u14_13_canoe_river_rads [Canvas](https://bart.instructure.com/courses/1314/quizzes/2811)/[public](https://chadworley.github.io/a2/u14/outhtml/13_canoe_river_rads.html)
* A story of two very special right triangles [pdf](https://chadworley.github.io/a2/u14/srt_story/srt_story.pdf)/[html](https://chadworley.github.io/a2/u14/srt_story/srt_story.html)
* Practice written quiz on special right triangles [blank](https://chadworley.github.io/a2/u14/srt_story/srt_story_test.pdf)/[key](https://chadworley.github.io/a2/u14/srt_story/srt_story_test_KEY.pdf)

### Fri Feb 28

* ET_106 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2763)/[public](https://chadworley.github.io/a2/ET2/ET_106.html)
* Blooket: Unit Circle Special Angles [questions](https://dashboard.blooket.com/set/67c12088620424410a04eb80)/[hw](https://play.blooket.com/play?hwId=67c1a755131b919074eb8c91)
* u14_14_UC_specials [Canvas](https://bart.instructure.com/courses/1314/quizzes/2812)
* UC_special_angle_mastery [Canvas](https://bart.instructure.com/courses/1314/assignments/24441)

## Week 29 {.tabset}

### Mon Mar 03

* ET_107 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2764)/[public](https://chadworley.github.io/a2/ET2/ET_107.html)
* UC_special_angle_mastery [Canvas](https://bart.instructure.com/courses/1314/assignments/24441)
* trig_review_mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2815)/[public](https://chadworley.github.io/a2/u14/review_quiz/trig_review_shared1.html)
* *Work through some review of right-triangle and unit-circle trigonometry, along with some polar coordinates and vectors, before we move onto wave trigonometry.*

### Tue Mar 04

* ET_108 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2765)/[public](https://chadworley.github.io/a2/ET2/ET_108.html)
* UC_special_angle_mastery [Canvas](https://bart.instructure.com/courses/1314/assignments/24441)
* trig_review_mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2815)/[public](https://chadworley.github.io/a2/u14/review_quiz/trig_review_shared1.html)
* *Work through some review of right-triangle and unit-circle trigonometry, along with some polar coordinates and vectors, before we move onto wave trigonometry.*

# Unit 15: Sinusoidal Wave Functions (weeks 29-31)

## Week 29 continued {.tabset}

### Wed Mar 05

* ET_109 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2766)/[public](https://chadworley.github.io/a2/ET2/ET_109.html)
* u15ws1: Draw waves [Canvas](https://bart.instructure.com/courses/1314/assignments/24499)/[public](https://chadworley.github.io/a2/u15/draw_sin_cos/draw_sin_cos.pdf)
* u15_01_circle_to_wave [Canvas](https://bart.instructure.com/courses/1314/quizzes/2821)/[public](https://chadworley.github.io/a2/u15/outhtml/01_circle_to_wave.html)
* u15_02_trig_parents [Canvas](https://bart.instructure.com/courses/1314/quizzes/2817)/[public](https://chadworley.github.io/a2/u15/outhtml/02_trig_parents.html)
* u15_03_sin_amp [Canvas](https://bart.instructure.com/courses/1314/quizzes/2818)/[public](https://chadworley.github.io/a2/u15/outhtml/03_sin_amp.html)


### Thu Mar 06

* ET_110 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2767)/[public](https://chadworley.github.io/a2/ET2/ET_110.html)
* u15_04_wave_vert_reflect [Canvas](https://bart.instructure.com/courses/1314/quizzes/2836)/[public](https://chadworley.github.io/a2/u15/outhtml/04_wave_vert_reflect.html)
* u15_05_sin_mid [Canvas](https://bart.instructure.com/courses/1314/quizzes/2829)/[public](https://chadworley.github.io/a2/u15/outhtml/05_sin_mid.html)
* u15_06_sin_period [Canvas](https://bart.instructure.com/courses/1314/quizzes/2830)/[public](https://chadworley.github.io/a2/u15/outhtml/06_sin_period.html)
* u15_07_sin_amp_per_mid [Canvas](https://bart.instructure.com/courses/1314/quizzes/2831)/[public](https://chadworley.github.io/a2/u15/outhtml/07_sin_amp_per_mid.html)
* u15_08_get_freq [Canvas](https://bart.instructure.com/courses/1314/quizzes/2832)/[public](https://chadworley.github.io/a2/u15/outhtml/08_get_freq.html)


### Fri Mar 07

* ET_111 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2768)/[public](https://chadworley.github.io/a2/ET2/ET_111.html)
* Desmos: [Sinusoidal Sliders](https://www.desmos.com/calculator/spi7j1lzqy)
* Worksheet: [City Climate](https://chadworley.github.io/a2/u15/city_climate/city_climate.pdf)

## Week 30 {.tabset}

### Mon Mar 10

* ET_112 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2769)/[public](https://chadworley.github.io/a2/ET2/ET_112.html)
* u15_09_wave_amp [Canvas](https://bart.instructure.com/courses/1314/quizzes/2833)/[public](https://chadworley.github.io/a2/u15/outhtml/09_wave_amp.html)
* u15_10_wave_period [Canvas](https://bart.instructure.com/courses/1314/quizzes/2834)/[public](https://chadworley.github.io/a2/u15/outhtml/10_wave_period.html)
* u15_11_wave_midline [Canvas](https://bart.instructure.com/courses/1314/quizzes/2835)/[public](https://chadworley.github.io/a2/u15/outhtml/11_wave_midline.html)
* u15_12_fit_monthly_temp [Canvas](https://bart.instructure.com/courses/1314/quizzes/2839)/[public](https://chadworley.github.io/a2/u15/outhtml/12_fit_monthly_temp.html)
* u15_13_mass_spring_period [Canvas](https://bart.instructure.com/courses/1314/quizzes/2840)/[public](https://chadworley.github.io/a2/u15/outhtml/13_mass_spring_period.html)

### Tue Mar 11

* ET_113 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2770)/[public](https://chadworley.github.io/a2/ET2/ET_113.html)
* Blooket: [Amplitude, Period, Midline](https://play.blooket.com/play?hwId=67d022b74feb4c8069a0b36b) (in class or solo)
* u15_14_pick_wave_pams [Canvas](https://bart.instructure.com/courses/1314/quizzes/2841)/[public](https://chadworley.github.io/a2/u15/outhtml/14_pick_wave_pams.html)
* u15_15_pick_wave_pams2 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2842)/[public](https://chadworley.github.io/a2/u15/outhtml/15_pick_wave_pams2.html)
* u15_16_ferris_wheel_key_drop [Canvas](https://bart.instructure.com/courses/1314/quizzes/2843)/[public](https://chadworley.github.io/a2/u15/outhtml/16_ferris_wheel_key_drop.html)

### Wed Mar 12

* ET_114 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2771)/[public](https://chadworley.github.io/a2/ET2/ET_114.html)
* [Practice quiz](https://chadworley.github.io/a2/u15/draw_waves/practice/u15ws2_prac.pdf)
* Blooket: [Wave features from equation](https://dashboard.blooket.com/set/67d0dcda619d98388d6f4ccb)
* u15_17_pick_wave_pams3 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2849)/[public](https://chadworley.github.io/a2/u15/outhtml/17_pick_wave_pams3.html)
* u15_18_pick_wave_pams4 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2850)/[public](https://chadworley.github.io/a2/u15/outhtml/18_pick_wave_pams4.html)
* u15_19_wave_feats_from_eq [Canvas](https://bart.instructure.com/courses/1314/quizzes/2851)/[public](https://chadworley.github.io/a2/u15/outhtml/19_wave_feats_from_eq.html)

### Thu Mar 13

* ET_115 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2772)/[public](https://chadworley.github.io/a2/ET2/ET_115.html)
* Practice for quiz: [Blooket](https://dashboard.blooket.com/set/67cf3cfd9bec714ea4a496e5)
* Take the quiz: [practice](https://chadworley.github.io/a2/u15/draw_waves/practice/u15ws2_prac.pdf)/[solutions](https://chadworley.github.io/a2/u15/draw_waves/practice/u15ws2_prac_sol.pdf)

## Week 31 {.tabset}

### Mon Mar 17

* ET_116 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2773)/[public](https://chadworley.github.io/a2/ET2/ET_116.html)
* u15_20_spatiotemporal_wave [Canvas](https://bart.instructure.com/courses/1314/quizzes/2856)/[public](https://chadworley.github.io/a2/u15/outhtml/20_spatiotemporal_wave.html)
* u15_21_bobbing_duck [Canvas](https://bart.instructure.com/courses/1314/quizzes/2854)/[public](https://chadworley.github.io/a2/u15/outhtml/21_bobbing_duck.html)
* u15_22_visible_light_freq [Canvas](https://bart.instructure.com/courses/1314/quizzes/2855)/[public](https://chadworley.github.io/a2/u15/outhtml/22_visible_light_freq.html)

### Tue Mar 18

* ET_117 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2774)/[public](https://chadworley.github.io/a2/ET2/ET_117.html)
* u15__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2861)
* Read: [Additive Synthesis](https://bart.instructure.com/courses/1314/pages/reading-additive-synthesis-music)


### Wed Mar 19

* ET_118 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2775)/[public](https://chadworley.github.io/a2/ET2/ET_118.html)
* u16_01_match_animations [Canvas](https://bart.instructure.com/courses/1314/quizzes/2863)/[public](https://chadworley.github.io/a2/u16/outhtml/01_match_animations.html)
* u16_02_string_animation [Canvas](https://bart.instructure.com/courses/1314/quizzes/2864)/[public](https://chadworley.github.io/a2/u16/outhtml/02_string_animation.html)
* u16_03_octave_phase [Canvas](https://bart.instructure.com/courses/1314/quizzes/2865)/[public](https://chadworley.github.io/a2/u16/outhtml/03_octave_phase.html)


### Thu Mar 20

* ET_119 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2776)/[public](https://chadworley.github.io/a2/ET2/ET_119.html)
* ALEKS: Trig Work
    * Go to [classlink](https://launchpad.classlink.com/bart)
    * Click on McGraw Hill
    * Find Assignment called "Trigonometry Work"
    * Work through the problems

### Fri Mar 21

* ET_120 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2866)/[public](https://chadworley.github.io/a2/ET2/ET_120.html)
* ALEKS: Trig Work
    * Go to [classlink](https://launchpad.classlink.com/bart)
    * Click on McGraw Hill
    * Find Assignment called "Trigonometry Work"
    * Work through the problems



# Unit 16: Trig review (weeks 32-33)

## Week 32 {.tabset}

### Mon Mar 24

* ET_121 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2867)/[public](https://chadworley.github.io/a2/ET2/ET_121.html)
* ALEKS: Trig Work
    * Go to [classlink](https://launchpad.classlink.com/bart)
    * Click on McGraw Hill
    * Find Assignment called "Trigonometry Work"
    * Work through the problems

### Tue Mar 25

* ET_122 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2868)/[public](https://chadworley.github.io/a2/ET2/ET_122.html)
* Blooket: [Period, frequency, and angular frequency](https://dashboard.blooket.com/set/67e160d38a97e294fce711d5)
* ALEKS: Trig MASTERY
    * Go to [classlink](https://launchpad.classlink.com/bart)
    * Click on McGraw Hill
    * Find Assignment called "Trig ALEKS Mastery"
    * Work through the problems

### Wed Mar 26

* ET_123 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2869)/[public](https://chadworley.github.io/a2/ET2/ET_123.html)
* ALEKS: Trig MASTERY
    * Go to [classlink](https://launchpad.classlink.com/bart)
    * Click on McGraw Hill
    * Find Assignment called "Trig ALEKS Mastery"
    * Work through the problems

### Thu Mar 27

* ET_124 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2870)/[public](https://chadworley.github.io/a2/ET2/ET_124.html)
* ALEKS: Trig MASTERY
    * Go to [classlink](https://launchpad.classlink.com/bart)
    * Click on McGraw Hill
    * Find Assignment called "Trig ALEKS Mastery"
    * Work through the problems

### Fri Mar 28

* ET_125 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2871)/[public](https://chadworley.github.io/a2/ET2/ET_125.html)
* ALEKS: Trig MASTERY
    * Go to [classlink](https://launchpad.classlink.com/bart)
    * Click on McGraw Hill
    * Find Assignment called "Trig ALEKS Mastery"
    * Work through the problems


## Week 33 {.tabset}

### Mon Mar 31

* ET_126 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2872)/[public](https://chadworley.github.io/a2/ET2/ET_126.html)
* Continue working on ALEKS

### Tue Apr 01

* ET_127 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2873)/[public](https://chadworley.github.io/a2/ET2/ET_127.html)
* Trig Final Practice [Canvas](https://bart.instructure.com/courses/1314/assignments/24805)


### Wed Apr 02

* ET_128 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2874)/[public](https://chadworley.github.io/a2/ET2/ET_128.html)
* Trig Final Practice [Canvas](https://bart.instructure.com/courses/1314/assignments/24805)


### Thu Apr 03

* ET_129 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2875)/[public](https://chadworley.github.io/a2/ET2/ET_129.html)
* Trig Final [Canvas](https://bart.instructure.com/courses/1314/assignments/24808)

### Fri Apr 04

* ET_130 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2877)/[public](https://chadworley.github.io/a2/ET2/ET_130.html)
* Trig Final [Canvas](https://bart.instructure.com/courses/1314/assignments/24808)



# Unit 17: Exponential Functions

## Week 34 {.tabset}

### Mon Apr 07

* ET_131 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2878)/[public](https://chadworley.github.io/a2/ET2/ET_131.html)
* Slides: [Percentage to Scale Factor](https://chadworley.github.io/a2/u17/slides_percent/slides_percent.html#(1))
* Blooket: [Scale Factor from Percent OF, MORE, or LESS](https://dashboard.blooket.com/set/67f3292298a3f826ae03c8d3)
* u17_01_percent_of [Canvas](https://bart.instructure.com/courses/1314/quizzes/2887)/[public](https://chadworley.github.io/a2/u17/outhtml/01_percent_of.html)
* u17_02_percent_more [Canvas](https://bart.instructure.com/courses/1314/quizzes/2888)/[public](https://chadworley.github.io/a2/u17/outhtml/02_percent_more.html)
* u17_03_percent_less [Canvas](https://bart.instructure.com/courses/1314/quizzes/2889)/[public](https://chadworley.github.io/a2/u17/outhtml/03_percent_less.html)
* u17_prcnt_of_more_less_mstry [Canvas](https://bart.instructure.com/courses/1314/quizzes/2890)



### Tue Apr 08

* ET_132 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2879)/[public](https://chadworley.github.io/a2/ET2/ET_132.html)
* u17_04_percent_changes [Canvas](https://bart.instructure.com/courses/1314/quizzes/2896)/[public](https://chadworley.github.io/a2/u17/outhtml/04_percent_changes.html)
* u17_05_certificate_of_deposit [Canvas](https://bart.instructure.com/courses/1314/quizzes/2897)/[public](https://chadworley.github.io/a2/u17/outhtml/05_certificate_of_deposit.html)
* u17_06_exponential_population [Canvas](https://bart.instructure.com/courses/1314/quizzes/2898)/[public](https://chadworley.github.io/a2/u17/outhtml/06_exponential_population.html)
* u17_07_equal_temperament_up [Canvas](https://bart.instructure.com/courses/1314/quizzes/2899)/[public](https://chadworley.github.io/a2/u17/outhtml/07_equal_temperament_up.html)
* u17_08_equal_temperament_down [Canvas](https://bart.instructure.com/courses/1314/quizzes/2900)/[public](https://chadworley.github.io/a2/u17/outhtml/08_equal_temperament_down.html)
* u17_09_mug_cooling [Canvas](https://bart.instructure.com/courses/1314/quizzes/2901)/[public](https://chadworley.github.io/a2/u17/outhtml/09_mug_cooling.html)
* u17_Apr8_mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2908)


### Wed Apr 09

* ET_133 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2880)/[public](https://chadworley.github.io/a2/ET2/ET_133.html)
* Wikipedia: [Factor Theorem](https://en.wikipedia.org/wiki/Factor_theorem)
* Desmos: [Compound Interest (Periodic and Continuous)](https://www.desmos.com/calculator/gv4wl6nqzy)
* u17_10_inc_dec_weirdness [Canvas](https://bart.instructure.com/courses/1314/quizzes/2914)/[public](https://chadworley.github.io/a2/u17/outhtml/10_inc_dec_weirdness.html)
* u17_11_cmpnd_intrst [Canvas](https://bart.instructure.com/courses/1314/quizzes/2915)/[public](https://chadworley.github.io/a2/u17/outhtml/11_cmpnd_intrst.html)
* u17_12_cmpnd_intrst_continuous [Canvas](https://bart.instructure.com/courses/1314/quizzes/2916)/[public](https://chadworley.github.io/a2/u17/outhtml/12_cmpnd_intrst_continuous.html)
* u17_13_doubling_time_from_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2917)/[public](https://chadworley.github.io/a2/u17/outhtml/13_doubling_time_from_graph.html)
* u17_14_half_life_from_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2918)/[public](https://chadworley.github.io/a2/u17/outhtml/14_half_life_from_graph.html)
* u17_15_geometric_value_from_index [Canvas](https://bart.instructure.com/courses/1314/quizzes/2919)/[public](https://chadworley.github.io/a2/u17/outhtml/15_geometric_value_from_index.html)


### Thu Apr 10

* ET_134 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2881)/[public](https://chadworley.github.io/a2/ET2/ET_134.html)
* u17_16_logistic_map [Canvas](https://bart.instructure.com/courses/1314/quizzes/2920)/[public](https://chadworley.github.io/a2/u17/outhtml/16_logistic_map.html)
* u17_17_gen_fib_seqs [Canvas](https://bart.instructure.com/courses/1314/quizzes/2921)/[public](https://chadworley.github.io/a2/u17/outhtml/17_gen_fib_seqs.html)
* u17_18_sum_geometric [Canvas](https://bart.instructure.com/courses/1314/quizzes/2922)/[public](https://chadworley.github.io/a2/u17/outhtml/18_sum_geometric.html)
* u17_19_geometric_sum [Canvas](https://bart.instructure.com/courses/1314/quizzes/2923)/[public](https://chadworley.github.io/a2/u17/outhtml/19_geometric_sum.html)
* u17_20_fractal_lines [Canvas](https://bart.instructure.com/courses/1314/quizzes/2924)/[public](https://chadworley.github.io/a2/u17/outhtml/20_fractal_lines.html)
* u17_21_fractal_area [Canvas](https://bart.instructure.com/courses/1314/quizzes/2925)/[public](https://chadworley.github.io/a2/u17/outhtml/21_fractal_area.html)
* u17_Apr10_geo_sum_mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2926)
* Make fancy/cool proof of partial geometric series formula. [Canvas](https://bart.instructure.com/courses/1314/assignments/25268)

### Fri Apr 11

* ET_135 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2882)/[public](https://chadworley.github.io/a2/ET2/ET_135.html)
* s17_22_mortgage [Canvas](https://bart.instructure.com/courses/1314/quizzes/2937)/[public](https://chadworley.github.io/a2/u17/outhtml/22_mortgage.html)
* s17_mortgage_mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2939)


## Week 35 {.tabset}

### Mon Apr 14

* ET_136 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2883)/[public](https://chadworley.github.io/a2/ET2/ET_136.html)
* s17_23_life_annuity [Canvas](https://bart.instructure.com/courses/1314/quizzes/2940)/[public](https://chadworley.github.io/a2/u17/outhtml/23_life_annuity.html)
* s17_24_geo_subtract_equations [Canvas](https://bart.instructure.com/courses/1314/quizzes/2941)/[public](https://chadworley.github.io/a2/u17/outhtml/24_geo_subtract_equations.html)
* s17_annuity__mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/2942)


### Tue Apr 15

* ET_137 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2884)/[public](https://chadworley.github.io/a2/ET2/ET_137.html)
* s17_25_size_small_m-ary_tree [Canvas](https://bart.instructure.com/courses/1314/quizzes/2947)/[public](https://chadworley.github.io/a2/u17/outhtml/25_size_small_m-ary_tree.html)
* s17_26_size_large_m-ary_tree [Canvas](https://bart.instructure.com/courses/1314/quizzes/2944)/[public](https://chadworley.github.io/a2/u17/outhtml/26_size_large_m-ary_tree.html)
* s17_27_geom_dist [Canvas](https://bart.instructure.com/courses/1314/quizzes/2948)/[public](https://chadworley.github.io/a2/u17/outhtml/27_geom_dist.html)
* s17_28_geom_dist_cumulative [Canvas](https://bart.instructure.com/courses/1314/quizzes/2949)/[public](https://chadworley.github.io/a2/u17/outhtml/28_geom_dist_cumulative.html)

### Wed Apr 16

* No school

### Thu Apr 17

* ET_138 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2885)/[public](https://chadworley.github.io/a2/ET2/ET_138.html)
* Blooket: [Identify Parameters of Geometric Series](https://dashboard.blooket.com/set/67fe81fae6450d74eab0f979)
* [Practice Test on Partial Geometric Series Formula](https://chadworley.github.io/a2/u17/we_geom_series/practice/practice.html) (Test tomorrow, Apr 18)

### Fri Apr 18

* ET_139 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2886)/[public](https://chadworley.github.io/a2/ET2/ET_139.html)
* Test on Partial Geometric Series Formula


# Unit 18: Exponential Equations and Logarithms

## Week 37 {.tabset}

### Mon Apr 28

* ET_140 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2952)/[public](https://chadworley.github.io/a2/ET2/ET_140.html)
* In-class Blooket: [FOIL and Factor](https://dashboard.blooket.com/set/680ee46d44ae9e71bb8e99c6)
* s18_01_common_base_solv_eq [Canvas](https://bart.instructure.com/courses/1314/quizzes/2962)/[public](https://chadworley.github.io/a2/u18/outhtml/01_common_base_solv_eq.html)
* s18_02_common_base_lin_mult [Canvas](https://bart.instructure.com/courses/1314/quizzes/2963)/[public](https://chadworley.github.io/a2/u18/outhtml/02_common_base_lin_mult.html)
* s18_03_common_base_lin_div [Canvas](https://bart.instructure.com/courses/1314/quizzes/2964)/[public](https://chadworley.github.io/a2/u18/outhtml/03_common_base_lin_div.html)
* s18_04_common_base_quad [Canvas](https://bart.instructure.com/courses/1314/quizzes/2965)/[public](https://chadworley.github.io/a2/u18/outhtml/04_common_base_quad.html)
* s18_05_com_base_quad_rats [Canvas](https://bart.instructure.com/courses/1314/quizzes/2967)/[public](https://chadworley.github.io/a2/u18/outhtml/05_com_base_quad_rats.html)


### Tue Apr 29

* ET_141 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2953)/[public](https://chadworley.github.io/a2/ET2/ET_141.html)
* [Portfolio day!](https://bart.instructure.com/courses/1314/assignments/25438)


### Wed Apr 30

* ET_142 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2954)/[public](https://chadworley.github.io/a2/ET2/ET_142.html)
* [Portfolio day!](https://bart.instructure.com/courses/1314/assignments/25438)


### Thu May 01

* Boston Trip


### Fri May 02

* Boston Trip





## Week 38 {.tabset}

### Mon May 05

* ET_143 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2955)/[public](https://chadworley.github.io/a2/ET2/ET_143.html)
* Cheat sheet: [$\log_2$, $\log_3$, and $\log_{10}$ examples](https://chadworley.github.io/a2/u18/exp_log/exp_log.pdf)
* Desmos: [Exp and Log are Inverses](https://www.desmos.com/calculator/nxmjntxlge)
* s18_06_eval_expo_base2 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2968)/[public](https://chadworley.github.io/a2/u18/outhtml/06_eval_expo_base2.html)
* s18_07_eval_expo_base10 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2969)/[public](https://chadworley.github.io/a2/u18/outhtml/07_eval_expo_base10.html)
* s18_08_solve_expo_base2 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2970)/[public](https://chadworley.github.io/a2/u18/outhtml/08_solve_expo_base2.html)
* s18_09_solve_expo_base10 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2971)/[public](https://chadworley.github.io/a2/u18/outhtml/09_solve_expo_base10.html)
* s18_10_eval_log_base2 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2972)/[public](https://chadworley.github.io/a2/u18/outhtml/10_eval_log_base2.html)
* s18_11_eval_log_base10 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2973)/[public](https://chadworley.github.io/a2/u18/outhtml/11_eval_log_base10.html)
* s18_12_eval_log_base_2_3_10 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2974)/[public](https://chadworley.github.io/a2/u18/outhtml/12_eval_log_base_2_3_10.html)
* s18_13_solve_exponent [Canvas](https://bart.instructure.com/courses/1314/quizzes/2975)/[public](https://chadworley.github.io/a2/u18/outhtml/13_solve_exponent.html)


### Tue May 06

* ET_144 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2956)/[public](https://chadworley.github.io/a2/ET2/ET_144.html)
* s18_14_two-step_inverse_alg [Canvas](https://bart.instructure.com/courses/1314/quizzes/2976)/[public](https://chadworley.github.io/a2/u18/outhtml/14_two-step_inverse_alg.html)
* s18_15_solve_exponential [Canvas](https://bart.instructure.com/courses/1314/quizzes/2977)/[public](https://chadworley.github.io/a2/u18/outhtml/15_solve_exponential.html)
* s18_16_solve_logarithmic [Canvas](https://bart.instructure.com/courses/1314/quizzes/2978)/[public](https://chadworley.github.io/a2/u18/outhtml/16_solve_logarithmic.html)
* s18_17_equal_temperament_get_freq [Canvas](https://bart.instructure.com/courses/1314/quizzes/2979)/[public](https://chadworley.github.io/a2/u18/outhtml/17_equal_temperament_get_freq.html)
* s18_18_equal_temperament_get_key [Canvas](https://bart.instructure.com/courses/1314/quizzes/2980)/[public](https://chadworley.github.io/a2/u18/outhtml/18_equal_temperament_get_key.html)
* s18_19_cents [Canvas](https://bart.instructure.com/courses/1314/quizzes/2981)/[public](https://chadworley.github.io/a2/u18/outhtml/19_cents.html)
* s18_20_f2_from_cents [Canvas](https://bart.instructure.com/courses/1314/quizzes/2982)/[public](https://chadworley.github.io/a2/u18/outhtml/20_f2_from_cents.html)
* s18_21_equal_temperament_fifth_error [Canvas](https://bart.instructure.com/courses/1314/quizzes/2983)/[public](https://chadworley.github.io/a2/u18/outhtml/21_equal_temperament_fifth_error.html)
* s18_22_earthquake_magnitude [Canvas](https://bart.instructure.com/courses/1314/quizzes/2984)/[public](https://chadworley.github.io/a2/u18/outhtml/22_earthquake_magnitude.html)
* s18_23_earthquake_energy [Canvas](https://bart.instructure.com/courses/1314/quizzes/2985)/[public](https://chadworley.github.io/a2/u18/outhtml/23_earthquake_energy.html)
* s18_24_earthquake_nrg_rat [Canvas](https://bart.instructure.com/courses/1314/quizzes/2986)/[public](https://chadworley.github.io/a2/u18/outhtml/24_earthquake_nrg_rat.html)
* s18_25_earthquake_mag_diff [Canvas](https://bart.instructure.com/courses/1314/quizzes/2987)/[public](https://chadworley.github.io/a2/u18/outhtml/25_earthquake_mag_diff.html)
* s18_26_pH [Canvas](https://bart.instructure.com/courses/1314/quizzes/2988)/[public](https://chadworley.github.io/a2/u18/outhtml/26_pH.html)
* s18_27_hydrogen_ion_conc [Canvas](https://bart.instructure.com/courses/1314/quizzes/2989)/[public](https://chadworley.github.io/a2/u18/outhtml/27_hydrogen_ion_conc.html)
* s18_28_pOH [Canvas](https://bart.instructure.com/courses/1314/quizzes/2990)/[public](https://chadworley.github.io/a2/u18/outhtml/28_pOH.html)
* s18_29_hydroxide_ion_conc [Canvas](https://bart.instructure.com/courses/1314/quizzes/2991)/[public](https://chadworley.github.io/a2/u18/outhtml/29_hydroxide_ion_conc.html)


### Wed May 07

* ET_145 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2957)/[public](https://chadworley.github.io/a2/ET2/ET_145.html)
* s18_30_decibels_from_power [Canvas](https://bart.instructure.com/courses/1314/quizzes/2992)/[public](https://chadworley.github.io/a2/u18/outhtml/30_decibels_from_power.html)
* s18_31_power_from_decibels [Canvas](https://bart.instructure.com/courses/1314/quizzes/2993)/[public](https://chadworley.github.io/a2/u18/outhtml/31_power_from_decibels.html)
* s18_32_inverse_table [Canvas](https://bart.instructure.com/courses/1314/quizzes/2994)/[public](https://chadworley.github.io/a2/u18/outhtml/32_inverse_table.html)
* s18_33_log10_inverse_table [Canvas](https://bart.instructure.com/courses/1314/quizzes/2995)/[public](https://chadworley.github.io/a2/u18/outhtml/33_log10_inverse_table.html)
* s18_34_log2_inverse_table [Canvas](https://bart.instructure.com/courses/1314/quizzes/2996)/[public](https://chadworley.github.io/a2/u18/outhtml/34_log2_inverse_table.html)
* s18_35_graph_inverse [Canvas](https://bart.instructure.com/courses/1314/quizzes/2997)/[public](https://chadworley.github.io/a2/u18/outhtml/35_graph_inverse.html)
* s18_36_inv_func_from_graph [Canvas](https://bart.instructure.com/courses/1314/quizzes/2998)/[public](https://chadworley.github.io/a2/u18/outhtml/36_inv_func_from_graph.html)
* s18_37_semi-log_get_exp [Canvas](https://bart.instructure.com/courses/1314/quizzes/2999)/[public](https://chadworley.github.io/a2/u18/outhtml/37_semi-log_get_exp.html)
* s18_38_semi-log_get_log [Canvas](https://bart.instructure.com/courses/1314/quizzes/3000)/[public](https://chadworley.github.io/a2/u18/outhtml/38_semi-log_get_log.html)
* s18_39_semi-log_get_base [Canvas](https://bart.instructure.com/courses/1314/quizzes/3001)/[public](https://chadworley.github.io/a2/u18/outhtml/39_semi-log_get_base.html)
* s18_40_slide_rule [Canvas](https://bart.instructure.com/courses/1314/quizzes/3002)/[public](https://chadworley.github.io/a2/u18/outhtml/40_slide_rule.html)


### Thu May 08

* ET_146 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2958)/[public](https://chadworley.github.io/a2/ET2/ET_146.html)
* s18_41_solve_e_to_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/3005)/[public](https://chadworley.github.io/a2/u18/outhtml/41_solve_e_to_x.html)
* s18_42_solve_ln_x [Canvas](https://bart.instructure.com/courses/1314/quizzes/3006)/[public](https://chadworley.github.io/a2/u18/outhtml/42_solve_ln_x.html)
* s18_43_cooling_solve_time [Canvas](https://bart.instructure.com/courses/1314/quizzes/3007)/[public](https://chadworley.github.io/a2/u18/outhtml/43_cooling_solve_time.html)
* s18_44_doubling_time_from_eq [Canvas](https://bart.instructure.com/courses/1314/quizzes/3008)/[public](https://chadworley.github.io/a2/u18/outhtml/44_doubling_time_from_eq.html)
* s18_45_half-life_from_eq [Canvas](https://bart.instructure.com/courses/1314/quizzes/3009)/[public](https://chadworley.github.io/a2/u18/outhtml/45_half-life_from_eq.html)


### Fri May 09

* ET_147 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2959)/[public](https://chadworley.github.io/a2/ET2/ET_147.html)
* s18_46_shifted_exp_log [Canvas](https://bart.instructure.com/courses/1314/quizzes/3010)/[public](https://chadworley.github.io/a2/u18/outhtml/46_shifted_exp_log.html)
* s18_47_exp_shift_stretch_equiv [Canvas](https://bart.instructure.com/courses/1314/quizzes/3011)/[public](https://chadworley.github.io/a2/u18/outhtml/47_exp_shift_stretch_equiv.html)
* s18_48_exp_base_and_stretch_eq [Canvas](https://bart.instructure.com/courses/1314/quizzes/3012)/[public](https://chadworley.github.io/a2/u18/outhtml/48_exp_base_and_stretch_eq.html)

## Week 39 {.tabset}

### Mon May 12

* ET_148 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2960)/[public](https://chadworley.github.io/a2/ET2/ET_148.html)
* s18_49_ave_ROI [Canvas](https://bart.instructure.com/courses/1314/quizzes/3014)/[public](https://chadworley.github.io/a2/u18/outhtml/49_ave_ROI.html)
* s18_50_newtons_cooling_fit [Canvas](https://bart.instructure.com/courses/1314/quizzes/3015)/[public](https://chadworley.github.io/a2/u18/outhtml/50_newtons_cooling_fit.html)
* s18_51_exp_get_3rd_y [Canvas](https://bart.instructure.com/courses/1314/quizzes/3016)/[public](https://chadworley.github.io/a2/u18/outhtml/51_exp_get_3rd_y.html)

### Tue May 13

* ET_149 [Canvas](https://bart.instructure.com/courses/1314/quizzes/2961)/[public](https://chadworley.github.io/a2/ET2/ET_149.html)
* s18_52_exponential_asymptote [Canvas](https://bart.instructure.com/courses/1314/quizzes/3017)/[public](https://chadworley.github.io/a2/u18/outhtml/52_exponential_asymptote.html)
* s18_53_logarithmic_asymptote [Canvas](https://bart.instructure.com/courses/1314/quizzes/3018)/[public](https://chadworley.github.io/a2/u18/outhtml/53_logarithmic_asymptote.html)
* [s18_written_quiz_practice](https://bart.instructure.com/courses/1314/assignments/25650):
    * [s18we_examples](https://chadworley.github.io/a2/u18/we/examples/s18we_examp_v001-010.pdf)
    * [s18we_examples_solutions](https://chadworley.github.io/a2/u18/we/examples/s18we_examp_sol_v001-010.pdf)
    * [s18we_practice](https://chadworley.github.io/a2/u18/we/practice/practice.html) - handed in for effort points


### Wed May 14

* ET_150 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3021)/[public](https://chadworley.github.io/a2/ET2/ET_150.html)
* s18_54_crdnt_tbl_shftd_exp2 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3031)/[public](https://chadworley.github.io/a2/u18/outhtml/54_crdnt_tbl_shftd_exp2.html)
* s18_55_crdnt_tbl_shftd_log2 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3032)/[public](https://chadworley.github.io/a2/u18/outhtml/55_crdnt_tbl_shftd_log2.html)
* s18_56_exp_yint [Canvas](https://bart.instructure.com/courses/1314/quizzes/3033)/[public](https://chadworley.github.io/a2/u18/outhtml/56_exp_yint.html)
* [s18_written_quiz_practice](https://bart.instructure.com/courses/1314/assignments/25650):
    * [s18we_examples](https://chadworley.github.io/a2/u18/we/examples/s18we_examp_v001-010.pdf)
    * [s18we_examples_solutions](https://chadworley.github.io/a2/u18/we/examples/s18we_examp_sol_v001-010.pdf)
    * [s18we_practice](https://chadworley.github.io/a2/u18/we/practice/practice.html) - handed in for effort points

### Thu May 15

* ET_151 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3022)/[public](https://chadworley.github.io/a2/ET2/ET_151.html)
* Take the u18 quiz!

### Fri May 16

* ET_152 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3023)/[public](https://chadworley.github.io/a2/ET2/ET_152.html)
* Take the [u18 online mastery](https://bart.instructure.com/courses/1314/quizzes/3035)

# Unit 19: Matrices

## Week 40 {.tabset}

### Mon May 19

* ET_153 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3024)/[public](https://chadworley.github.io/a2/ET2/ET_153.html)
* Quiet make-up day.
    * [10 points of effort for merely staying quiet](https://bart.instructure.com/courses/1314/assignments/25727)!
* SAT practice available (optional) [Canvas](https://bart.instructure.com/courses/1314/quizzes/3050)

### Tue May 20

* ET_154 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3025)/[public](https://chadworley.github.io/a2/ET2/ET_154.html)
* s18_57_match_parent_functions [Canvas](https://bart.instructure.com/courses/1314/quizzes/3058)/[public](https://chadworley.github.io/a2/u18/outhtml/57_match_parent_functions.html)
* Quiet make-up day.
    * [10 points of effort for merely staying quiet](https://bart.instructure.com/courses/1314/assignments/25727)!
* SAT practice available (optional) [Canvas](https://bart.instructure.com/courses/1314/quizzes/3051)


### Wed May 21

* ET_155 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3026)/[public](https://chadworley.github.io/a2/ET2/ET_155.html)
* s19_01_groceries_get_total [Canvas](https://bart.instructure.com/courses/1314/quizzes/3059)/[public](https://chadworley.github.io/a2/u19/outhtml/01_groceries_get_total.html)
* s19_02_groceries_get_total_B [Canvas](https://bart.instructure.com/courses/1314/quizzes/3060)/[public](https://chadworley.github.io/a2/u19/outhtml/02_groceries_get_total_B.html)
* s19_03_groceries_get_uc [Canvas](https://bart.instructure.com/courses/1314/quizzes/3061)/[public](https://chadworley.github.io/a2/u19/outhtml/03_groceries_get_uc.html)
* s19_04_get_matrix_aij [Canvas](https://bart.instructure.com/courses/1314/quizzes/3062)/[public](https://chadworley.github.io/a2/u19/outhtml/04_get_matrix_aij.html)
* s19_05_get_matrix_aij_B [Canvas](https://bart.instructure.com/courses/1314/quizzes/3063)/[public](https://chadworley.github.io/a2/u19/outhtml/05_get_matrix_aij_B.html)


### Thu May 22

* ET_156 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3027)/[public](https://chadworley.github.io/a2/ET2/ET_156.html)
* s19_06_matrix_dimensions [Canvas](https://bart.instructure.com/courses/1314/quizzes/3064)/[public](https://chadworley.github.io/a2/u19/outhtml/06_matrix_dimensions.html)
* s19_07_can_mats_mult [Canvas](https://bart.instructure.com/courses/1314/quizzes/3065)/[public](https://chadworley.github.io/a2/u19/outhtml/07_can_mats_mult.html)
* s19_08_dimensions_of_product [Canvas](https://bart.instructure.com/courses/1314/quizzes/3066)/[public](https://chadworley.github.io/a2/u19/outhtml/08_dimensions_of_product.html)
* s19_09_mult_mats_diagram [Canvas](https://bart.instructure.com/courses/1314/quizzes/3067)/[public](https://chadworley.github.io/a2/u19/outhtml/09_mult_mats_diagram.html)
* s19_10_mult_mats_dgrm_B [Canvas](https://bart.instructure.com/courses/1314/quizzes/3068)/[public](https://chadworley.github.io/a2/u19/outhtml/10_mult_mats_dgrm_B.html)
* s19_11_mult_mats_no_dgrm [Canvas](https://bart.instructure.com/courses/1314/quizzes/3069)/[public](https://chadworley.github.io/a2/u19/outhtml/11_mult_mats_no_dgrm.html)
* s19_12_mult_mats [Canvas](https://bart.instructure.com/courses/1314/quizzes/3070)/[public](https://chadworley.github.io/a2/u19/outhtml/12_mult_mats.html)


### Fri May 23

* ET_157 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3028)/[public](https://chadworley.github.io/a2/ET2/ET_157.html)
* s19_13_groceries_SageMath [Canvas](https://bart.instructure.com/courses/1314/quizzes/3071)/[public](https://chadworley.github.io/a2/u19/outhtml/13_groceries_SageMath.html)
* s19_14_transpose_matrix [Canvas](https://bart.instructure.com/courses/1314/quizzes/3072)/[public](https://chadworley.github.io/a2/u19/outhtml/14_transpose_matrix.html)
* s19_15_2D_rotation_mat_post [Canvas](https://bart.instructure.com/courses/1314/quizzes/3073)/[public](https://chadworley.github.io/a2/u19/outhtml/15_2D_rotation_mat_post.html)
* s19_16_rotate_2D_points [Canvas](https://bart.instructure.com/courses/1314/quizzes/3074)/[public](https://chadworley.github.io/a2/u19/outhtml/16_rotate_2D_points.html)



## Week 41 {.tabset}

### Tue May 27

* ET_158 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3029)/[public](https://chadworley.github.io/a2/ET2/ET_158.html)
* s19_17_rotate_2D [Canvas](https://bart.instructure.com/courses/1314/quizzes/3075)/[public](https://chadworley.github.io/a2/u19/outhtml/17_rotate_2D.html)
* s19_18_shear_2D [Canvas](https://bart.instructure.com/courses/1314/quizzes/3076)/[public](https://chadworley.github.io/a2/u19/outhtml/18_shear_2D.html)
* s19_19_squeeze_2D [Canvas](https://bart.instructure.com/courses/1314/quizzes/3077)/[public](https://chadworley.github.io/a2/u19/outhtml/19_squeeze_2D.html)
* s19_20_projection_3D_to_2D [Canvas](https://bart.instructure.com/courses/1314/quizzes/3078)/[public](https://chadworley.github.io/a2/u19/outhtml/20_projection_3D_to_2D.html)
* s19_21_multiple_transforms [Canvas](https://bart.instructure.com/courses/1314/quizzes/3079)/[public](https://chadworley.github.io/a2/u19/outhtml/21_multiple_transforms.html)


### Wed May 28

* ET_159 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3030)/[public](https://chadworley.github.io/a2/ET2/ET_159.html)
* s19_22_area_parallelogram [Canvas](https://bart.instructure.com/courses/1314/quizzes/3080)/[public](https://chadworley.github.io/a2/u19/outhtml/22_area_parallelogram.html)
* s19_23_determinant_A [Canvas](https://bart.instructure.com/courses/1314/quizzes/3081)/[public](https://chadworley.github.io/a2/u19/outhtml/23_determinant_A.html)
* s19_24_determinant_B [Canvas](https://bart.instructure.com/courses/1314/quizzes/3082)/[public](https://chadworley.github.io/a2/u19/outhtml/24_determinant_B.html)
* s19_25_determinant_C [Canvas](https://bart.instructure.com/courses/1314/quizzes/3083)/[public](https://chadworley.github.io/a2/u19/outhtml/25_determinant_C.html)


### Thu May 29

* ET_160 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3084)/[public](https://chadworley.github.io/a2/ET2/ET_160.html)
* s19_26_Cramers_rule_2x2 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3103)/[public](https://chadworley.github.io/a2/u19/outhtml/26_Cramers_rule_2x2.html)
* s19_27_mult_2x2_mats [Canvas](https://bart.instructure.com/courses/1314/quizzes/3095)/[public](https://chadworley.github.io/a2/u19/outhtml/27_mult_2x2_mats.html)
* s19_28_Identity_Matrix [Canvas](https://bart.instructure.com/courses/1314/quizzes/3096)/[public](https://chadworley.github.io/a2/u19/outhtml/28_Identity_Matrix.html)
* s19_29_check_if_inverse [Canvas](https://bart.instructure.com/courses/1314/quizzes/3097)/[public](https://chadworley.github.io/a2/u19/outhtml/29_check_if_inverse.html)


### Fri May 30

* ET_161 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3085)/[public](https://chadworley.github.io/a2/ET2/ET_161.html)
* s19_30_can_add_matrices [Canvas](https://bart.instructure.com/courses/1314/quizzes/3098)/[public](https://chadworley.github.io/a2/u19/outhtml/30_can_add_matrices.html)
* s19_31_add_matrices [Canvas](https://bart.instructure.com/courses/1314/quizzes/3099)/[public](https://chadworley.github.io/a2/u19/outhtml/31_add_matrices.html)
* s19_32_subtract_matrices [Canvas](https://bart.instructure.com/courses/1314/quizzes/3100)/[public](https://chadworley.github.io/a2/u19/outhtml/32_subtract_matrices.html)


## Week 42 {.tabset}

### Mon Jun 02

* ET_162 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3086)/[public](https://chadworley.github.io/a2/ET2/ET_162.html)
* s19_33_ntwrk_incidence_mat [Canvas](https://bart.instructure.com/courses/1314/quizzes/3101)/[public](https://chadworley.github.io/a2/u19/outhtml/33_ntwrk_incidence_mat.html)
* s19_34_spinning_pyramid [Canvas](https://bart.instructure.com/courses/1314/quizzes/3104)/[public](https://chadworley.github.io/a2/u19/outhtml/34_spinning_pyramid.html)
* s19_online_mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/3105)


### Tue Jun 03

* ET_163 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3087)/[public](https://chadworley.github.io/a2/ET2/ET_163.html)
* s19_online_mastery [Canvas](https://bart.instructure.com/courses/1314/quizzes/3105)

### Wed Jun 04

* ET_164 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3106)
* s19 written exam [example](https://chadworley.github.io/a2/u19/paper/example/s19_WE_example_v001-010.pdf)/[solution](https://chadworley.github.io/a2/u19/paper/example/s19_WE_example_sol_v001-010.pdf)
* s19 written exam [practice](https://chadworley.github.io/a2/u19/paper/practice/practice.html) - handed in for credit!

### Thu Jun 05

* ET_165 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3107)
* s19 written exam [mastery](https://bart.instructure.com/courses/1314/assignments/25907)
    * No notes
    * No calculator

### Fri Jun 06

* ET_166 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3108)
* s19 written exam [mastery](https://bart.instructure.com/courses/1314/assignments/25907)
    * No notes
    * No calculator
* Blooket: [NY Regents Algebra 2](https://dashboard.blooket.com/set/68419cac8f755ba79f79c497)

# Unit 20: Cumulative Review

## Week 43 {.tabset}

### Mon Jun 09

* ET_167 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3109)
* ALEKS: "Cumulative Review"
    * Bart Managed
    * Classlink
    * McGraw Hill
    * Algebra 2
    * Assignments
    * "Cumulative Review"
* If you have a 0 on any mastery assignment, please focus on improving the 0.

### Tue Jun 10

* ET_168 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3110)
* ALEKS: "Cumulative Review"
    * Bart Managed
    * Classlink
    * McGraw Hill
    * Algebra 2
    * Assignments
    * "Cumulative Review"
* If you have a 0 on any mastery assignment, please focus on improving the 0.

### Wed Jun 11

* ET_169 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3111)
* ALEKS: "Cumulative Review"
    * Bart Managed
    * Classlink
    * McGraw Hill
    * Algebra 2
    * Assignments
    * "Cumulative Review"
* If you have a 0 on any mastery assignment, please focus on improving the 0.

### Thu Jun 12

* ET_170 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3112)
* ALEKS: "Cumulative Review"
    * Bart Managed
    * Classlink
    * McGraw Hill
    * Algebra 2
    * Assignments
    * "Cumulative Review"
* If you have a 0 on any mastery assignment, please focus on improving the 0.


### Fri Jun 13

* ET_171 [Canvas](https://bart.instructure.com/courses/1314/quizzes/3113)
* ALEKS: "Cumulative Review"
    * Bart Managed
    * Classlink
    * McGraw Hill
    * Algebra 2
    * Assignments
    * "Cumulative Review"
* If you have a 0 on any mastery assignment, please focus on improving the 0.




