---
title: "Algebra 2 Weekly Calendar"
output:
  html_document:
    toc: true
    theme: united
---

## Week 1 {.tabset}

### Wed Aug 21

* [First day survey](https://forms.gle/UiZrKtkPGFZ7Po8F9)
* Students will participate in a survey. We discuss some of the questions together.
* *S-IC.B: Make inferences and justify conclusions from sample surveys, experiments, and observational studies.*

### Thu Aug 22

* Look at syllabus.
* Define population, parameter, sample, and statistic.
* Discuss how the goal of Statistics is to estimate population parameters from sample statistics.
* [Slides](https://chadworley.github.io/a2/u01/p01_sam_stat_pop_prop.html)
* [Practice problems: Q1](https://chadworley.github.io/a2/u01/u01_shared1.html#Q1v1)
* **Canvas** (graded problems): 
  * u01_01_sam_stat_pop_prop
* *S-IC.A.1: Understand statistics as a process for making inferences to be made about population parameters based on a random sample from that population.*

### Fri Aug 23

* Define survey, experiment, and observational study. We discuss the importance of random samples and random assignment.
* [Slides](https://chadworley.github.io/a2/u01/p02_survey_experi_obsstu.html)
* [Practice Problems: Q2, Q3, Q4](https://chadworley.github.io/a2/u01/u01_shared1.html#Q2v1)
* **Canvas** (graded problems):
  * 02_survey_experi_obsstu
  * 03_sample_bias
  * 04_corr_or_cause
  * List 2 research questions with corresponding study designs that you could do for each type:
    * Survey for a mean
    * Survey for a proportion
    * Experiment
* *S-IC.B.3: Recognize the purposes of and differences among sample surveys, experiments, and observational studies; explain how randomization relates to each.*

## Week 2 {.tabset}

### Mon Aug 26

* Spreadsheets! ([google sheets](https://sheets.new))
* [Slides](https://chadworley.github.io/a2/u01/p05_spreadsheet_intro.html#/)
* [Practice: Q5, Q6](https://chadworley.github.io/a2/u01/u01_shared1.html#Q5v1)
* Canvas:
  * 05_basic_data_analysis
  * 06_big_data_analysis
* *S-ID.A: Summarize, represent, and interpret data on a single count or measurement variable. Use calculators, spreadsheets, and other technology as appropriate.*

### Tue Aug 27

* Learn to read and make histograms.
* [Practice: Q7, Q8](https://chadworley.github.io/a2/u01/u01_shared1.html#Q7v1)
* Canvas:
  * 07_read_histogram
  * 08_make_hist_see_shape.Rmd
* *S-ID.A: Summarize, represent, and interpret data on a single count or measurement variable. Use calculators, spreadsheets, and other technology as appropriate.*

### Wed Aug 28

* Learn to simulate dice in spreadsheet.
* Learn about [MARGIN OF ERROR](https://en.wikipedia.org/wiki/Margin_of_error).
* Learn to compare model to observation to make conclusion.
* [Slides](https://chadworley.github.io/a2/u01/p09_dice_sim.html)
* [Practice: Q9, Q10](https://chadworley.github.io/a2/u01/u01_shared1.html#Q9v1)
* Canvas:
  * 09_ME_dice_tots
* *S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.*



* Simulate dice (based on discrete-uniform model)
* Investigate "Margin of Error" and "Interval of typical means"
* Roll dice (the dice might be 3D printed...)
* Compare. Write reports.
* *S-IC.A.2: Decide if a specified model is consistent with results from a given data-generating process, e.g., using simulation.*



