```{r,echo=F,warning=F}
options(scipen=99)

A4freq = 440 + sample(1:10,1)*sample(c(-1,1),1)
nsteps = sample(4:11,1)

notes = c("A^{\\#}_4","B_4","C_5","C^{\\#}_5","D_5","D^{\\#}_5","E_5","F_5","F^{\\#}_5","G_5","G^{\\#}_5")

freq = A4freq*2^(nsteps/12)

```

Question
========

Most modern music is written in a [twelve-tone equal temperament](https://en.wikipedia.org/wiki/Equal_temperament#Mathematics) system. Thus, when playing an ascending [chromatic scale](https://en.wikipedia.org/wiki/Chromatic_scale), every new note's [fundamental frequency](https://en.wikipedia.org/wiki/Fundamental_frequency) is approximately $`r (2^(1/12)-1)*100`$% higher than the previous note's.

Typically, the A above [middle C](https://en.wikipedia.org/wiki/C_(musical_note)#Middle_C) (noted as $A_4$ in [scientific pitch notation](https://en.wikipedia.org/wiki/Scientific_pitch_notation)) is tuned to a frequency of [440 Hz](https://en.wikipedia.org/wiki/A440_(pitch_standard)), but throughout history this was not so standardized.

Let's imagine an orchestra tunes $A_4$ to `r A4freq` Hz. What will the frequency be of the $`r notes[nsteps]`$ that is `r nsteps` [notes](https://en.wikipedia.org/wiki/Semitone) higher than $A_4$?



Solution
========

Find the scale factor.

$$1+`r 2^(1/12)-1`~=~`r 2^(1/12)`$$



The exact scale factor for twelve-tone equal temperament is $2^{1/12}$. 

You multiply the given frequency by the scale factor `r nsteps` times.

$$`r A4freq`\cdot `r 2^(1/12)`^{`r nsteps`} ~=~ `r freq`$$


Some composers (including BART legend 
James Bergin), compose in other equal temperaments. Some common ones include [5, 7, 9](https://en.wikipedia.org/wiki/Equal_temperament#Five-,_seven-,_and_nine-tone_temperaments_in_ethnomusicology), [15](https://en.wikipedia.org/wiki/15_equal_temperament), [17](https://en.wikipedia.org/wiki/17_equal_temperament), [19](https://en.wikipedia.org/wiki/19_equal_temperament), [22](https://en.wikipedia.org/wiki/22_equal_temperament), [23](https://en.wikipedia.org/wiki/23_equal_temperament), [24](https://en.wikipedia.org/wiki/Quarter_tone),
[31](https://en.wikipedia.org/wiki/31_equal_temperament),
[34](https://en.wikipedia.org/wiki/34_equal_temperament), [41](https://en.wikipedia.org/wiki/41_equal_temperament),
[53](https://en.wikipedia.org/wiki/53_equal_temperament), [58](https://en.wikipedia.org/wiki/58_equal_temperament), [72](https://en.wikipedia.org/wiki/72_equal_temperament), and [96](https://en.wikipedia.org/wiki/96_equal_temperament) (I believe Mr. Bergin is partial to 72-EDO). In a 72-tone equal temperament, two adjacent notes have a scale factor of $2^{1/72}\approx `r 2^(1/72)`$, so as you play a chromatic scale, the frequency increases by `r (2^(1/72)-1)*100`% for each note.

Meta-information
============
extype: num
exsolution: `r freq`
exname: equal_temperament_up
extol: 1