```{r,echo=F,warning=F}
options(scipen=99)

A4freq = 440 + sample(1:10,1)*sample(c(-1,1),1)
nsteps = sample(4:11,1)

# notes = c("A^{\\#}_4","B_4","C_5","C^{\\#}_5","D_5","D^{\\#}_5","E_5","F_5","F^{\\#}_5","G_5","G^{\\#}_5")
notes = c("G^{\\#}_4","G_4","F^{\\#}_4","F_4","E_4","D^{\\#}_4","D_4","C^{\\#}_4","C_4","B_3","A^{\\#}_3")

freq = A4freq*2^(-nsteps/12)

```

Question
========

Most modern music is written in a [twelve-tone equal temperament](https://en.wikipedia.org/wiki/Equal_temperament#Mathematics) system. Thus, when playing a descending [chromatic scale](https://en.wikipedia.org/wiki/Chromatic_scale), every new note's [fundamental frequency](https://en.wikipedia.org/wiki/Fundamental_frequency) is approximately $`r (1-2^(-1/12))*100`$% lower than the previous note's.

Typically, the A above [middle C](https://en.wikipedia.org/wiki/C_(musical_note)#Middle_C) (noted as $A_4$ in [scientific pitch notation](https://en.wikipedia.org/wiki/Scientific_pitch_notation)) is tuned to a frequency of [440 Hz](https://en.wikipedia.org/wiki/A440_(pitch_standard)), but throughout history this was not so standardized.

Let's imagine an orchestra tunes $A_4$ to `r A4freq` Hz. What will the frequency be of the $`r notes[nsteps]`$ that is `r nsteps` [notes](https://en.wikipedia.org/wiki/Semitone) lower than $A_4$?



Solution
========

Find the scale factor.

$$1-`r 1-2^(-1/12)`~=~`r 2^(-1/12)`$$



The exact scale factor for twelve-tone equal temperament is $2^{-1/12}$ (when descending by [semitones](https://en.wikipedia.org/wiki/Semitone)). 

You multiply the given frequency by the scale factor `r nsteps` times.

$$`r A4freq`\cdot `r 2^(-1/12)`^{`r nsteps`} ~=~ `r freq`$$



Meta-information
============
extype: num
exsolution: `r freq`
exname: equal_temperament_down
extol: 1