```{r,echo=FALSE}
options(scipen=99)
r = round(runif(1,3.56996,4),5)
f1 = round(runif(1,0.02,0.98),2)

n = sample(20:40,1)

ends = c("th","st","nd","rd","th","th","th","th","th","th","th")
end = ends[n%%10+1]

f = f1

fs = c(f1)

for(i in 2:n){
    f = r*f*(1-f)
    fs = c(fs,f)
}

fn = f

ss = paste0("| ",1:n," | ",fs," |",collapse="\n")
ss2 = paste0("| ",1:5," | ",fs[1:5]," |",collapse="\n")

```


Question
========

In Desmos, we can [produce sequences defined recursively](https://help.desmos.com/hc/en-us/articles/25917735966989-Recursion#h_01HVHM10ASS971T6VMMHEX9HD9). In basic [Chaos Theory](https://en.wikipedia.org/wiki/Chaos_theory), it is common to discuss the [logistic map](https://en.wikipedia.org/wiki/Logistic_map).

Let's produce a sequence using the logistic map with $r=`r r`$ and $f(1)=`r f1`$. In Desmos, write the following expressions:
$$f(n)~=~ `r r`\cdot f(n-1) \cdot \Big(1-f(n-1)\Big)$$
$$f(1)~=~ `r f1`$$

You can then click on the `Create Table` button that shows up to the left of your first equation. By default, it will show the first 5 elements of the sequence in the table (along with the indices in the first column):

| $x$ | $f(x)$ |
|:---:|:---:|
`r ss2`

 If you click on the last row's $x$ value and repeatedly hit the `Enter` key on your keyboard, you can extend the sequence as far as you'd like.

Find the **`r n``r end`** term of the sequence.

$$f(`r n`)~=~ ?$$


Solution
========

$$f(`r n`)=`r fn`$$

In Desmos, if you follow those steps, you can generate the entire sequence:

| $x$ | $f(x)$ |
|:---:|:---:|
`r ss`

You might notice there is not really a pattern. That's chaos!

More specifically, if you adjust $f(1)$ very slightly (maybe make $f(1)=`r f1+0.01`$ or  $f(1)=`r f1-0.01`$ ), you should see that $f(`r n`)$ can change a lot. This phenomenon is called the [butterfly effect](https://en.wikipedia.org/wiki/Butterfly_effect): a small change to the initial conditions can cause a large change in final conditions.




Meta-information
============
extype: num
exsolution: `r fn`
exname: logistic_map
extol: 0.001