```{r,echo=F,warning=F}
options(scipen=99)

wp = sample(1:3,1)
cf = c(12,24,52)[wp]
wrd = c("monthly","semimonthly","weekly")[wp]
apr = runif(1,0.5,0.7)
pr = signif(apr/cf,3)
APR = pr*cf
APY = (1+pr)^cf-1

```

Question
========

Consider an (unrealistically awesome) account that pays `r pr*100`% interest `r wrd` (assume there are exactly `r cf` payments evenly spaced throughout the year).

An account begins the year with $100. We wish to consider two possibilities: [simple interest](https://en.wikipedia.org/wiki/Interest#Simple_interest) and [compound interest](https://en.wikipedia.org/wiki/Compound_interest).

* Under simple interest, the interest payments themselves do **not** earn interest. Most real accounts do not work like this. Assuming these payments are added to the account, the result would be **linear growth**.
* Under compound interest, the payments themselves earn interest in future payments. The growth of the account will be proportional to its current value, producing [exponential growth](https://en.wikipedia.org/wiki/Exponential_growth).




Solution
========




Meta-information
============
extype: num
exsolution: 
exname: inc_dec_weirdness
extol: 0.01