```{r,echo=F,warning=F}
fixer = function(exp){
  exp = gsub("+-","-",exp,fixed=T)
  exp = gsub("--","+",exp,fixed=T)
  return(exp)
}

while(T){
  m = 6*sample(1:10,1)*sample(c(-1,1),1)
  b = 2*sample(1:10,1)*sample(c(-1,1),1)
  c = sample(1:10,1)*sample(c(-1,1),1)
  d = sample(1:10,1)*sample(c(-1,1),1)
  
  A = round(m/6)
  B = round(b/2)
  C = round(c)
  D = round(d)
  
  G = round(m/2)
  H = round(b)
  I = round(c)
  
  J = round(m)
  K = round(b)
  
  exp1 = fixer(paste0(A,"t^3+",B,"t^2+",C,"t+",D,collapse=""))
  exp2 = fixer(paste0(3*A,"t^2+",2*B,"t+",C,collapse=""))
  exp3 = fixer(paste0(6*A,"t+",2*B,collapse=""))
  ts = c(0,1,2)
  sols1 = A*ts^3+B*ts^2+C*ts+D
  sols2 = G*ts^2+H*ts+I
  sols3 = J*ts+K
  
  allsols = c(sols1,sols2,sols3)
  ac = sort(unique(allsols))
  if(length(unique(sign(sols1)))>1 && 
     length(unique(sign(sols2)))>1 && 
     length(unique(sign(sols3)))>1 &&
     max(abs(allsols))<100){break}
}


sols = character()
for(sol in allsols){
  sols = c(sols,paste0(1*(sol==ac),collapse=""))
}
al = paste0("* ",rep(ac,9),collapse="\n")


```

Question
========

A particle moves up and down along a 1-dimensional path. It's acceleration ($a(t)$ in $\mathrm{\frac{m}{s^2}}$) is a function of time ($t$ in seconds).

$$a(t)=`r exp3`$$

The particle's velocity is also a function of time. Also, $v(0)=`r I`$.

$$v(t) ~=~ `r I` + \int_{0}^{t}a(t)\,dt$$


The particle's position is also a function of time. Also, $x(0)=`r D`$.

$$x(t) ~=~ `r D` + \int_{0}^{t}v(t)\,dt$$


Evaluate position, velocity, and acceleration at $t=0$, $t=1$, and $t=2$.

<style>
select.question_input {
width: 5em;
}
tr {height: 3em;}

table, th, td {
  border:1px solid black;
  padding:5px;
}
</style>


<table>
<tr>
    <th>t</th>
    <th>y(t)</th>
    <th>v(t)</th>
    <th>a(t)</th>
</tr>
<tr>
  <td>0</td>
  <td>##ANSWER1##</td>
  <td>##ANSWER4##</td>
  <td>##ANSWER7##</td>
</tr>
<tr>
  <td>1</td>
  <td>##ANSWER2##</td>
  <td>##ANSWER5##</td>
  <td>##ANSWER8##</td>
</tr>
<tr>
  <td>2</td>
  <td>##ANSWER3##</td>
  <td>##ANSWER6##</td>
  <td>##ANSWER9##</td>
</tr>
</table>


Answerlist
--------

`r al`


Solution
========

We were given acceleration as a function of time.

$$a(t)=`r exp3`$$
To find the antiderivative, add 1 to each power and then divide each coefficient by the new power. Then, add the constant of integration to match the given [initial value](https://en.wikipedia.org/wiki/Initial_condition).

$$v(t)=`r exp2`$$

To find the antiderivative, add 1 to each power and then divide each coefficient by the new power. Then, add the constant of integration to match the given [initial value](https://en.wikipedia.org/wiki/Initial_condition).

$$y(t)=`r exp1`$$

<style>
select.question_input {
width: 5em;
}
tr {height: 3em;}

table, th, td {
  border:1px solid black;
  padding:5px;
}
</style>

<table>
<tr>
    <th>t</th>
    <th>y(t)</th>
    <th>v(t)</th>
    <th>a(t)</th>
</tr>
<tr>
  <td>0</td>
  <td>`r allsols[1]`</td>
  <td>`r allsols[4]`</td>
  <td>`r allsols[7]`</td>
</tr>
<tr>
  <td>1</td>
  <td>`r allsols[2]`</td>
  <td>`r allsols[5]`</td>
  <td>`r allsols[8]`</td>
</tr>
<tr>
  <td>2</td>
  <td>`r allsols[3]`</td>
  <td>`r allsols[6]`</td>
  <td>`r allsols[9]`</td>
</tr>
</table>



Meta-information
============
extype: cloze
exclozetype: `r paste0(rep("schoice",9),collapse="|")`
exsolution: `r paste0(sols,collapse="|")`
exname: integ_acc_vel_pos