```{r,echo=FALSE}
library(reticulate)
options(scipen=999)
r1 = sample(seq(1,3,0.1),1)
r2 = sample(seq(1,3,0.1),1)
t1 = sample(seq(0.1,1.5,0.1),1)*sample(c(-1,1),1)
t2 = sample(seq(0.1,1.5,0.1),1)*sample(c(-1,1),1)
r3 = r1*r2
t3 = t1+t2

lar = sample(0:3,1)
ssr = sample(seq(0.02,0.2,0.01),1)
multr = -lar:(3-lar)
anlir = r3+multr*ssr
solr = paste0(1*(0:3==lar),collapse="")

lat = sample(0:3,1)
sst = 0.1
multt = -lat:(3-lat)
anlit = t3+multt*sst
solt = paste0(1*(0:3==lat),collapse="")
```

Question
========

### Background

[Multiplying complex numbers from their polar parameters](https://en.wikipedia.org/wiki/Complex_number#Multiplication_and_division_in_polar_form) is surprisingly easy. Let $z_1$ have modulus $r_1$ and argument $\theta_1$. And let $z_2$ have modulus $r_2$ and argument $\theta_2$.
$$z_1 ~~=~~ r_1\cos(\theta_1)~+~r_1\sin(\theta_1)i$$
$$z_2 ~~=~~ r_2\cos(\theta_2)~+~r_2\sin(\theta_2)i$$
Let a third complex number $z_3$ have modulus $r_3$ and argument $\theta_3$ and equal the product of the other two numbers.
$$z_3 = z_1 \cdot z_2$$
It can be proven that the product's modulus is the **product** of the moduli, and the product's argument is the **sum** of the arguments.
$$r_3 = r_1 \cdot r_2$$
$$\theta_3 = \theta_1 + \theta_2 $$

### The Question

Complex number $z_1$ has modulus $r_1=`r r1`$ and argument $\theta_1=`r t1`$ radians. 
Complex number $z_2$ has modulus $r_2=`r r2`$ and argument $\theta_2=`r t2`$ radians.
Complex number $z_3$ is the product of $z_1$ and $z_2$. Find the polar parameters of $z_3$.

* $r_3=$ ##ANSWER1##
* $\theta_3=$ ##ANSWER2## 

Answerlist
--------

`r anlir`
`r anlit`

Solution
========

$$r_3 = (`r r1`)(`r r2`) = `r r3`$$
$$\theta_3 = (`r t1`)+(`r t2`) = `r t3`$$


Meta-information
============
extype: cloze
exclozetype: schoice|schoice
exsolution: `r solr`|`r solt`
exname: multiply_complex_polar