---
output: pdf_document
params:
    rseed: 1
    showsol: true
    titex: "Classwork"
urlcolor: blue
---

```{r,echo=F}
set.seed(params$rseed)
```

Name: \hspace{4in} Date: \hfill \vspace{3pt} \hrule

## Draw Inverse Functions (8 pts, version `r params$rseed`)

For each one-to-one function's curve, please plot the inverse function's curve on same axes.

```{r,fig.dim=c(4,4),echo=FALSE,results="asis"}
par(mar=c(3,3,1,1))
while(T){
    xy = sample(1:9,6)
    x = sort(xy[1:3])
    y = sort(xy[4:6],decreasing = sample(c(T,F),1))
    if((y[2]-y[1])*(x[3]-x[2])!=(y[3]-y[2])*(x[2]-x[1]) && (y[2]-y[1])!=-(x[2]-x[1]) && (y[3]-y[2])!=-(y[2]-y[1])){break}
}

par(pty="s")
plot(0,0,type="n",xlim=c(0,10),ylim=c(0,10),lwd=2,ylab="y",xlab="x")
mtext("x",1,1.5)
mtext("y",2,1.5)
for(j in seq(0,10,1)){
  abline(h=j,lty=3)
  abline(v=j,lty=3)
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)
lines(x,y,col="blue",lwd=2)
points(x,y,col="blue",pch=19,cex=0.5)
# legend("topright","y=f(x)",lwd=2,col="blue")

if(params$showsol){
    abline(0,1,col="black",cex="0.5",lty=2)
    lines(y,x,col="red",lwd=2)
}
```

```{r,fig.dim=c(4,4),echo=FALSE,results="asis"}
par(mar=c(3,3,1,1))
while(T){
    xy = sample(1:9,6)
    x = sort(xy[1:3])
    y = sort(xy[4:6],decreasing = sample(c(T,F),1))
    if((y[2]-y[1])*(x[3]-x[2])!=(y[3]-y[2])*(x[2]-x[1]) && (y[2]-y[1])!=-(x[2]-x[1]) && (y[3]-y[2])!=-(y[2]-y[1])){break}
}

par(pty="s")
plot(0,0,type="n",xlim=c(0,10),ylim=c(0,10),lwd=2,ylab="y",xlab="x")
mtext("x",1,1.5)
mtext("y",2,1.5)
for(j in seq(0,10,1)){
  abline(h=j,lty=3)
  abline(v=j,lty=3)
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)
lines(x,y,col="blue",lwd=2)
points(x,y,col="blue",pch=19,cex=0.5)
# legend("topright","y=f(x)",lwd=2,col="blue")

if(params$showsol){
    abline(0,1,col="black",cex="0.5",lty=2)
    lines(y,x,col="red",lwd=2)
}
```

\newpage

```{r,fig.dim=c(4,4),echo=FALSE,results="asis"}
par(mar=c(3,3,1,1))
while(T){
    xy = sample(1:9,6)
    x = sort(xy[1:3])
    y = sort(xy[4:6],decreasing = sample(c(T,F),1))
    if((y[2]-y[1])*(x[3]-x[2])!=(y[3]-y[2])*(x[2]-x[1]) && (y[2]-y[1])!=-(x[2]-x[1]) && (y[3]-y[2])!=-(y[2]-y[1])){break}
}

par(pty="s")
plot(0,0,type="n",xlim=c(0,10),ylim=c(0,10),lwd=2,ylab="y",xlab="x")
mtext("x",1,1.5)
mtext("y",2,1.5)
for(j in seq(0,10,1)){
  abline(h=j,lty=3)
  abline(v=j,lty=3)
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)
lines(x,y,col="blue",lwd=2)
points(x,y,col="blue",pch=19,cex=0.5)
# legend("topright","y=f(x)",lwd=2,col="blue")

if(params$showsol){
    abline(0,1,col="black",cex="0.5",lty=2)
    lines(y,x,col="red",lwd=2)
}
```

```{r,fig.dim=c(4,4),echo=FALSE,results="asis"}
par(mar=c(3,3,1,1))
while(T){
    xy = sample(1:9,6)
    x = sort(xy[1:3])
    y = sort(xy[4:6],decreasing = sample(c(T,F),1))
    if((y[2]-y[1])*(x[3]-x[2])!=(y[3]-y[2])*(x[2]-x[1]) && (y[2]-y[1])!=-(x[2]-x[1]) && (y[3]-y[2])!=-(y[2]-y[1])){break}
}

par(pty="s")
plot(0,0,type="n",xlim=c(0,10),ylim=c(0,10),lwd=2,ylab="y",xlab="x")
mtext("x",1,1.5)
mtext("y",2,1.5)
for(j in seq(0,10,1)){
  abline(h=j,lty=3)
  abline(v=j,lty=3)
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)
lines(x,y,col="blue",lwd=2)
points(x,y,col="blue",pch=19,cex=0.5)
# legend("topright","y=f(x)",lwd=2,col="blue")

if(params$showsol){
    abline(0,1,col="black",cex="0.5",lty=2)
    lines(y,x,col="red",lwd=2)
}
```


