```{r,echo=F,warning=F}
matpr = function(A){
  pra = "\\begin{bmatrix}\n"
  for(i in 1:dim(A)[1]){
    pra = paste0(pra,paste0(A[i,],collapse=" & "))
    if(i<dim(A)[1]){pra = paste0(pra,"\\\\\n")} else {pra = paste0(pra,"\n")}
  }
  pra = paste0(pra,"\\end{bmatrix}")
  return(pra)
}

while(T){
  dims = c(2,2,2,2)
  a = matrix(sample(-9:9,prod(dims[1:2]),T),nrow = dims[1])
  b = matrix(sample(-9:9,prod(dims[3:4]),T),nrow = dims[3])
  pra = matpr(a)
  prb = matpr(b)
  p = matrix(a%*%b,nrow=dims[1])
  prp = matpr(p)
  if(max(abs(p))<100){break}
}

ann = dims[1]*dims[4]
anma = paste0("##ANSWER",1:ann,"##")

ac = unique(sort(p))
al = paste0("* ",ac,collapse="\n")
al = paste0(rep(al,ann),collapse="\n")
schs = paste0(rep("schoice",ann),collapse="|")

sols = character()
for(i in 1:ann){
  sol = paste0(1*(ac==p[i]),collapse="")
  sols = c(sols,sol)
}
sols = paste0(sols,collapse="|")

solstr = paste0("The product matrix has ",dims[1]," rows and ", dims[4], " columns.\n\n")

for(i in 1:dims[1]){
  for(j in 1:dims[4]){
    solstr = paste0(solstr,"To find the product matrix's value in row ",i," and column ",j,", sum the products of corresponding elements of row ",i," in matrix A and column ",j," in matrix B.\n","$$C_{[",i,",",j,"]}=")
    damath = paste0("(",a[i,],")(",b[,j],")",collapse="+")
    solstr = paste0(solstr,damath,"=",p[i,j],"$$\n\n")
  }
}

```

Question
========

Matrices $A$ and $B$ are defined below.

$$A = `r pra`$$
$$B = `r prb`$$

Find the [product](https://en.wikipedia.org/wiki/Matrix_multiplication) $C=AB$.




$AB=$
```{r,echo=F}
knitr::kable(matrix(anma,dims[1]), "html")
```


Answerlist
--------

`r al`

Solution
========

We wish to do matrix multiplication:

$$`r pra``r prb`$$


`r solstr`

All of that work leads to the answer:

$$C = AB = `r prp`$$
```{r,echo=F}
A = a
B = b
C = A%*%B
nf = dim(A)[2]
np = dim(A)[1]
ns = dim(B)[2]
nc = nf+ns
nr = np+nf
```


```{r,echo=F,fig.dim=c(4.5,4.5/(nc+1)*(nr+1))}

library(latex2exp)
par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(0,nc+1),ylim=c(0,nr+1),asp=1)

clrs = c("red","yellow","maroon","tan")
clrs = c(rgb(1,0,0,0.2),rgb(1,1,0,0.4),rgb(0.8,0,0.8,0.3),rgb(0.6,0.5,0.2,0.2),rgb(0.2,0.3,0.8,0.2))
for(i in 1:nf){
    polygon(c(i-0.5,i-0.5,nf+0.5,nf+ns+0.5,nf+ns+0.5,nf+0.5,i+0.5,i+0.5),
            c(0.5,np+0.5,np+nf-i+1.5,np+nf-i+1.5,np+nf-i+0.5,np+nf-i+0.5,np+0.5,0.5),col=clrs[i],border = F)
    xt1 = i-0.3
    xt2 = nf+0.5
    yt1 = np+0.5
    yt2 = np+nf-i+1.3
    srt = atan2(yt2-yt1,xt2-xt1)/pi*180
    # text((xt1+xt2)/2,(yt1+yt2)/2,foods[i],srt=srt,cex=0.8)
}


for(i in 1:np){
    for(j in 1:nf){
        text(j,np-i+1,A[i,j])
    }
}

for(i in 1:nf){
    for(j in 1:ns){
        text(j+nf,np+nf-i+1,sprintf("%d",B[i,j]))
    }
}


for(i in 1:np){
    for(j in 1:ns){
        text(nf+j,np+1-i,C[i,j])
    }
}

for(i in 0:np){
    lines(c(0.5,nc+0.5),c(i,i)+0.5)
}
for(i in 0:ns){
    lines(nf+c(i,i)+0.5,c(0.5,np+nf+0.5))
}

lines(c(nf+0.5,nf+0.5),c(np,0)+0.5,lwd=3)
lines(c(nf+0.5,nf+ns+0.5),c(np,np)+0.5,lwd=3)

# text(0,2,op1)
# text(5,7,op2)

```
\

Meta-information
============
extype: cloze
exclozetype: `r schs`
exsolution: `r sols`
exname: mult_mats