```{r data generation, echo = FALSE, results = "hide",warning=FALSE}

deg1 = round(runif(1,15,75),1)
deg2 = 90-deg1


```

Question
========

A right triangle is drawn such that its hypotenuse connects the origin to the edge of the unit circle in the first quadrant. The acute angle at the origin has a measure of `r deg1`°. What is the measure, in degrees, of the other acute angle of the right triangle?

```{r,echo=F,fig.dim=c(6,6)}
par(mar=c(0,0,0,0),pty="s")
dd = 1.2
plot(0,0,"n",xlim=c(-dd,dd),ylim=c(-dd,dd),axes=F,ann=F)
for(i in seq(-dd,dd,0.1)){
    lines(c(i,i),c(-dd,dd),col="grey",lwd=0.5)
    lines(c(-dd,dd),c(i,i),col="grey",lwd=0.5)
}
for(i in seq(-1,1,1)){
    lines(c(i,i),c(-dd,dd),col="darkgrey",lwd=1)
    lines(c(-dd,dd),c(i,i),col="darkgrey",lwd=1)
}
arrows(-dd*1.04,0,dd*1.04,0,0.1,10,3,lwd=3,col="darkgrey")
arrows(0,-dd*1.04,0,dd*1.04,0.1,10,3,lwd=3,col="darkgrey")
text(1.02,-0.04,"1")
text(-0.03,1.03,"1")
text(1.17,-0.04,"x")
text(-0.03,1.17,"y")

th = seq(0,2*pi,pi/360)
lines(cos(th),sin(th))

rad1 = deg1*pi/180

polygon(c(0,cos(rad1),cos(rad1)),c(0,sin(rad1),0),border="black",lwd=2)
db = 0.02
lines(c(cos(rad1)-db,cos(rad1)-db,cos(rad1)),
      c(0,db,db))


th2 = seq(0,rad1,pi/360)
lines(0.1*cos(th2),0.1*sin(th2),col="red",lwd=2)
text(0.2*cos(rad1/2),0.2*sin(rad1/2),paste0(deg1,"°",collapse=""),col="red")

rad2 = deg2*pi/180
th3 = seq(3*pi/2-rad2,3*pi/2,pi/360)
lines(cos(rad1)+0.1*cos(th3),sin(rad1)+0.1*sin(th3),col="blue",lwd=2)
text(cos(rad1)+0.2*cos(-pi/2-rad2/2),
     sin(rad1)+0.2*sin(-pi/2-rad2/2),"?",col="blue")


```
\



Solution
========





Meta-information
============
extype: num
exsolution: `r deg2`
exname: right_tri_complems_deg
extol: 0.0001