---
output: 
  pdf_document:
    extra_dependencies: ["fancyhdr","multicol"]
fontsize: 12pt
params:
  num: "1234"
  mytitle: "Two-step Equations"
  showsol: False
geometry: "left=3cm,right=3cm,top=3cm,bottom=3cm"
---

```{r,echo=F}
library(latex2exp)

set.seed(as.numeric(params$num))
showsol = params$showsol
if(showsol){
  soltxt = "SOL"
} else {
  soltxt = ""
}

al = numeric()

```

\setlength{\headheight}{18.0pt}
\fancyhead[L]{\sc{`r params$mytitle` v`r params$num` `r soltxt`}}
\fancyhead[R]{\bf \large Name:\hspace{2in}}
\fancyfoot[R]{\sc Page \thepage ~ of 2}
\fancyfoot[C]{}
\pagestyle{fancy}


```{r,echo=F}
am = "B\\cdot(x+A)"
ad = "\\frac{x+A}{B}"
sm = "B\\cdot(x-A)"
sd = "\\frac{x-A}{B}"
ma = "A x+B"
da = "\\frac{x}{A}+B"
ms = "A x-B"
ds = "\\frac{x}{A}-B"
qs = c(am,ad,sm,sd,ma,da,ms,ds)

am = "B\\cdot(x+A)"
ad = "\\frac{x+A}{B}"
sm = "B\\cdot(x-A)"
sd = "\\frac{x-A}{B}"
ma = "A\\cdot x+B"
da = "\\frac{x}{A}+B"
ms = "A\\cdot x-B"
ds = "\\frac{x}{A}-B"
q2s = c(am,ad,sm,sd,ma,da,ms,ds)

exn = sample(1:length(qs),1)

while(T){
  nums = c(sample(2:9,2))
  x = sample(2:12,1)*sample(c(-1,1),1)
  a = nums[1]
  b = nums[2]
  if(exn==1){
    y = b*(x+a)
  } else if(exn==2){
    y = (x+a)/b
  } else if(exn==3){
    y = (x-a)*b
  } else if(exn==4){
    y = (x-a)/b
  } else if(exn==5){
    y = a*x+b
  } else if(exn==6){
    y = x/a+b
  } else if(exn==7){
    y = a*x-b
  } else if(exn==8){
    y = x/a-b
  }
  if(y%%1==0 && abs(y)<70 && abs(y)>0 && x!=a){break}
}

wd = c("add A and then multiply by B",
       "add A and then divide by B",
       "subtract A and then multiply by B",
       "subtract A and then divide by B",
       "multiply by A and then add B",
       "divide by A and then add B",
       "multiply by A and then subtract B",
       "divide by A and then subtract B")

q = gsub("B",nums[2],gsub("A",nums[1],qs[exn]))
a = gsub("x",y,gsub("B",nums[1],gsub("A",nums[2],q2s[length(qs)-exn+1])))

exp1 = gsub("B",nums[2],gsub("A",nums[1],wd[exn]))
exp2 = gsub("B",nums[1],gsub("A",nums[2],wd[length(qs)-exn+1]))

ques = paste0(y,"=",q)
al = c(al,x)
```


1. Solve the equation:
$$`r ques`$$

\vfill


```{r,echo=F}
exn = sample(1:length(qs),1)
while(T){
  nums = c(sample(2:9,2))
  x = sample(2:12,1)*sample(c(-1,1),1)
  a = nums[1]
  b = nums[2]
  if(exn==1){
    y = b*(x+a)
  } else if(exn==2){
    y = (x+a)/b
  } else if(exn==3){
    y = (x-a)*b
  } else if(exn==4){
    y = (x-a)/b
  } else if(exn==5){
    y = a*x+b
  } else if(exn==6){
    y = x/a+b
  } else if(exn==7){
    y = a*x-b
  } else if(exn==8){
    y = x/a-b
  }
  if(y%%1==0 && abs(y)<70 && abs(y)>0 && x!=a){break}
}

q = gsub("B",nums[2],gsub("A",nums[1],qs[exn]))
a = gsub("x",y,gsub("B",nums[1],gsub("A",nums[2],q2s[length(qs)-exn+1])))

exp1 = gsub("B",nums[2],gsub("A",nums[1],wd[exn]))
exp2 = gsub("B",nums[1],gsub("A",nums[2],wd[length(qs)-exn+1]))

ques = paste0(y,"=",q)
al = c(al,x)
```

2. Solve the equation:
$$`r ques`$$

\vfill

```{r,echo=F}
exn = sample(1:length(qs),1)
while(T){
  nums = c(sample(2:9,2))
  x = sample(2:12,1)*sample(c(-1,1),1)
  a = nums[1]
  b = nums[2]
  if(exn==1){
    y = b*(x+a)
  } else if(exn==2){
    y = (x+a)/b
  } else if(exn==3){
    y = (x-a)*b
  } else if(exn==4){
    y = (x-a)/b
  } else if(exn==5){
    y = a*x+b
  } else if(exn==6){
    y = x/a+b
  } else if(exn==7){
    y = a*x-b
  } else if(exn==8){
    y = x/a-b
  }
  if(y%%1==0 && abs(y)<70 && abs(y)>0 && x!=a){break}
}

q = gsub("B",nums[2],gsub("A",nums[1],qs[exn]))
a = gsub("x",y,gsub("B",nums[1],gsub("A",nums[2],q2s[length(qs)-exn+1])))

exp1 = gsub("B",nums[2],gsub("A",nums[1],wd[exn]))
exp2 = gsub("B",nums[1],gsub("A",nums[2],wd[length(qs)-exn+1]))

ques = paste0(y,"=",q)
al = c(al,x)
```

3. Solve the equation:
$$`r ques`$$

\vfill

\newpage

```{r,echo=F}
exn = sample(1:length(qs),1)
while(T){
  nums = c(sample(2:9,2))
  x = sample(2:12,1)*sample(c(-1,1),1)
  a = nums[1]
  b = nums[2]
  if(exn==1){
    y = b*(x+a)
  } else if(exn==2){
    y = (x+a)/b
  } else if(exn==3){
    y = (x-a)*b
  } else if(exn==4){
    y = (x-a)/b
  } else if(exn==5){
    y = a*x+b
  } else if(exn==6){
    y = x/a+b
  } else if(exn==7){
    y = a*x-b
  } else if(exn==8){
    y = x/a-b
  }
  if(y%%1==0 && abs(y)<70 && abs(y)>0 && x!=a){break}
}

q = gsub("B",nums[2],gsub("A",nums[1],qs[exn]))
a = gsub("x",y,gsub("B",nums[1],gsub("A",nums[2],q2s[length(qs)-exn+1])))

exp1 = gsub("B",nums[2],gsub("A",nums[1],wd[exn]))
exp2 = gsub("B",nums[1],gsub("A",nums[2],wd[length(qs)-exn+1]))

ques = paste0(y,"=",q)
al = c(al,x)
```

4. Solve the equation:
$$`r ques`$$

\vfill

```{r,echo=F}
exn = sample(1:length(qs),1)
while(T){
  nums = c(sample(2:9,2))
  x = sample(2:12,1)*sample(c(-1,1),1)
  a = nums[1]
  b = nums[2]
  if(exn==1){
    y = b*(x+a)
  } else if(exn==2){
    y = (x+a)/b
  } else if(exn==3){
    y = (x-a)*b
  } else if(exn==4){
    y = (x-a)/b
  } else if(exn==5){
    y = a*x+b
  } else if(exn==6){
    y = x/a+b
  } else if(exn==7){
    y = a*x-b
  } else if(exn==8){
    y = x/a-b
  }
  if(y%%1==0 && abs(y)<70 && abs(y)>0 && x!=a){break}
}

q = gsub("B",nums[2],gsub("A",nums[1],qs[exn]))
a = gsub("x",y,gsub("B",nums[1],gsub("A",nums[2],q2s[length(qs)-exn+1])))

exp1 = gsub("B",nums[2],gsub("A",nums[1],wd[exn]))
exp2 = gsub("B",nums[1],gsub("A",nums[2],wd[length(qs)-exn+1]))

ques = paste0(y,"=",q)
al = c(al,x)
```

5. Solve the equation:
$$`r ques`$$

\vfill

```{r,echo=F}
exn = sample(1:length(qs),1)
while(T){
  nums = c(sample(2:9,2))
  x = sample(2:12,1)*sample(c(-1,1),1)
  a = nums[1]
  b = nums[2]
  if(exn==1){
    y = b*(x+a)
  } else if(exn==2){
    y = (x+a)/b
  } else if(exn==3){
    y = (x-a)*b
  } else if(exn==4){
    y = (x-a)/b
  } else if(exn==5){
    y = a*x+b
  } else if(exn==6){
    y = x/a+b
  } else if(exn==7){
    y = a*x-b
  } else if(exn==8){
    y = x/a-b
  }
  if(y%%1==0 && abs(y)<70 && abs(y)>0 && x!=a){break}
}

q = gsub("B",nums[2],gsub("A",nums[1],qs[exn]))
a = gsub("x",y,gsub("B",nums[1],gsub("A",nums[2],q2s[length(qs)-exn+1])))

exp1 = gsub("B",nums[2],gsub("A",nums[1],wd[exn]))
exp2 = gsub("B",nums[1],gsub("A",nums[2],wd[length(qs)-exn+1]))

ques = paste0(y,"=",q)
al = c(al,x)

line="blah text blah blah etc etc"
write(paste0(params$num,":  ",paste0(al,collapse=" ")),file="ans.txt",append=TRUE)
```

6. Solve the equation:
$$`r ques`$$

\vfill




