---
title: "Project Dice"
---

# Overview

You have been given a 6-sided die. This is a 3D-printed die, and it might be weighted such that the average is not 3.5. You will roll the die 50 times (on a surface that causes the die to bounce) and collect the data.

You will generate a 95% confidence interval using two different techniques:

* Bootstrapping
* Using the confidence-interval formula: $\bar{x}\pm \frac{2s}{\sqrt{n}}$

Lastly, you will determine whether you have enough evidence to conclude the expected value (population mean) is not 3.5.

# Report

This report can be shorter than the report for Project Coin Spin. I want the following:

* Title
* Name
* A summary of the project. Something like, "I was handed a 6-sided die and told to get a 95% confidence interval of the die's population mean (expected value). I was instructed to use both bootstrapping and a formula, so I ended up with two confidence intervals."
* Raw roll data as a comma-separated list or a table (in the doc). I should be able to copy and paste the data easily.
* Description of the bootstrapping algorithm.
* Link to spreadsheet (for bootstrapping and sample mean $\bar{x}$ and sample standard deviation $s$)
* State the confidence interval (both boundaries) from the bootstrapping algorithm.
* Declare the sample size ($n$), the sample mean ($\bar{x}$), and the sample standard deviation ($s$) using math typesetting (using `Insert`, `Equation` in the doc).
* Typeset the confidence-interval formula.
* State the confidence interval (both boundaries) from the formula.
* State whether the confidence intervals are in rough agreement (I think they probably will be).
* Conclusion about the [expected value](https://en.wikipedia.org/wiki/Expected_value) of your die.
    * If you confidence intervals do not contain 3.5, you can conclude the expected value is NOT 3.5.
    * If a confidence interval does contain 3.5, you are left with two possibilities, both of which should be stated:
        * You need more data to show the expected value is not 3.5.
        * The expected value is 3.5.
        
**Export your report as a pdf** to submit on Canvas.


# Spreadsheet

```{r echo=F}
lets = LETTERS
for(ai in LETTERS){
    for(aj in LETTERS){
        lets = c(lets,paste0(ai,aj,collapse=""))
    }
}
lc = lets[54]
```

* Put your sample data in column A, in range A1:A50.
* In cell B1, use formula `=COUNT(A1:A50)`. This is your sample size ($n$).
* In cell B2, use formula `=AVERAGE(A1:A50)`. This is your sample mean ($\bar{x}$).
* In cell B3, use formula `=STDEV(A1:A50)`. This is your sample standard deviation ($s$).
* In cell B4, use formula `B2-2*B3/sqrt(B1)` to get formulaic lower boundary of confidence interval.
* In cell B5, use formula `B2+2*B3/sqrt(B1)` to get formulaic upper boundary of confidence interval.
* Insert 30 extra columns.
* In cells D1:BA1000, use formula `=INDEX($A$1:$A$50,RANDBETWEEN(1,50),1)` to resample 1000 times.
* In cell BC1, use formula `=AVERAGE(D1:BA1)`. Drag the formula down through BC1000.
* Calculate the 2.5th and 97.5th percentiles of the resampled means. These are your boundaries of your bootstrap 95% confidence interval.



