---
output: slidy_presentation
---

# Agenda

* Entrance ticket: [ET_09_15](https://bart.instructure.com/courses/2110/quizzes/3177)
* Exam Expectations
* As a class we will talk through a practice exam (version 50):
    * https://chadworley.github.io/algtwo2026/daily_materials/written_exam/prac/we01_reflections_v050.pdf
* Some people still need to finish and hand in their practice exams.

# Exam Expectations

* After attendance, I will hand out the exam.
    * At that point, **silence** and **computers away** until every person is finished.
    * Please bring a book to read after you are done.
* If you feel you need a simple calculator, you can bring one.
* No notes (unless your 504/IEP explicitly states you can use a sheet of notes).
* As you've already seen the structure of all the problems on the exam, I see no reason that I will need to answer any questions about the exam during the exam.
* Please attempt every question. Partial credit is your friend!
* Retakes (with new versions) will be allowed during Flex Blocks (supervised by a teacher).






