---
header-includes:
   - \usepackage{array}
   - \usepackage{color}
   - \usepackage{tabularx}
output: pdf_document
params:
    rseed: 1
    showsol: true
    titex: "Practice"
urlcolor: blue
---

```{r,echo=F}
set.seed(params$rseed)
options(scipen=99)
```

Name: \hspace{4in} Date: \hfill \vspace{3pt} \hrule

## \sc Arithmetric Quiz (no calculator) (`r params$titex` v`r params$rseed`)

<!-- 1 -->

```{r q1prep,echo=F}
a = sample(10000:99999,1)
b = sample(10000:99999,1)
```
\

1. Find the sum of `r a` plus `r b` without a calculator.

```{r,echo=F,results='asis'}
if(params$showsol){
    cat("\\color{red}")
    cat(a+b)
    cat("\\color{black}")
}
```

\vfill

<!-- 2 -->

```{r q2prep,echo=F}
while(T){
    ab = sort(sample(10000:99999,2))
    b=ab[2]
    a=ab[1]
    if(b-a>1000){break}
}
```
\

2. Find the difference of `r b` minus `r a` without a calculator.

```{r,echo=F,results='asis'}
if(params$showsol){
    cat("\\color{red}")
    cat(b-a)
    cat("\\color{black}")
}
```


\vfill

\newpage

<!-- 3 -->

```{r q3prep,echo=F}
a = sample(100:999,1)
b = sample(100:999,1)
```
\

3. Find the product of `r a` times `r b` without a calculator.

```{r,echo=F,results='asis'}
if(params$showsol){
    cat("\\color{red}")
    cat(a*b)
    cat("\\color{black}")
}
```

\vfill

<!-- 4 -->

```{r q4prep,echo=F}
divisor = sample(3:6,1)
mult = sample(1111:9999,1)
prod = divisor*mult
```
\

4. Find the quotient of `r prod` divided by `r divisor` without a calculator.

```{r,echo=F,results='asis'}
if(params$showsol){
    cat("\\color{red}")
    cat(mult)
    cat("\\color{black}")
}
```


\vfill
