---
output: pdf_document
---

```{r,echo=F}
library(latex2exp)

hmoves = c("shift left 2","shift right 2","H stretch factor 2","H shrink factor 2")
hops = list(function(x){x-2},
            function(x){x+2},
            function(x){2*x},
            function(x){x/2})
hexp = c("x+2","x-2","\\frac{x}{2}","2x")
hct = c("a-2","a+2","2a","\\frac{a}{2}")

vmoves = c("shift down 2","shift up 2","V stretch factor 2","V shrink factor 2")
vops = list(function(x){x-2},
            function(x){x+2},
            function(x){2*x},
            function(x){x/2})
vexp = c("f{\\left(x\\right)}-2","f{\\left(x\\right)}+2","2\\cdot f{\\left(x\\right)}","\\frac{f{\\left(x\\right)}}{2}")
vct = c("b-2","b+2","2b","\\frac{b}{2}")

mkplt = function(){
    lim = 10
    plot(0,0,"n",xlim=c(-lim,lim),ylim=c(-lim,lim),axes=F,ann=F)
    
    for(i in -lim:lim){
        lines(c(-lim,lim),c(i,i),col="grey",lwd=0.3)
        lines(c(i,i),c(-lim,lim),col="grey",lwd=0.3)
    }
    for(i in seq(-lim,lim,5)){
        lines(c(-lim,lim),c(i,i),col="darkgrey",lwd=0.6)
        lines(c(i,i),c(-lim,lim),col="darkgrey",lwd=0.6)
    }
    abline(h=0,lwd=1)
    abline(v=0,lwd=1)
    text(lim,0,"x",adj=c(0,1.2),cex=0.7)
    text(0,lim,"y",adj=c(1.2,0),cex=0.7)
}

```

### Reference: shifting and stretching, all constants equal 2!

We will use the following function as an example to examine all 16 possible combinations of translations and scaling, with one horizontal transformation and one vertical transformation:

```{r,echo=F,fig.dim=c(4,2)}
a = c(-4,-2,2,4)
b = c(-4,2,-2,4)
par(mar=c(0,0,0,0),oma=c(0,0,0,0),pty="s",mfrow=c(1,2))
mkplt()

lines(a,b,col="blue",lwd=1.5)
points(a,b,pch=19,cex=0.5,col="blue")

plot(0,0,"n",axes=F,ann=F)
legend("center","y = f(x)",col="blue",lwd=1.5)
```



```{r,echo=F,fig.dim=c(6,6)}
par(mar=c(2,3,2,1),oma=c(0,0,0,0),pty="s",mfrow=c(2,2))

doit = function(hwo,vwo){
    x = hops[[hwo]](a)
    y = vops[[vwo]](b)
    ca = paste0("$g(x)=",gsub("x",hexp[hwo],vexp[vwo],fixed=T),"$",collapse="")
    ct = paste0("$(a,b)\\to\\left(",hct[hwo],",",vct[vwo],"\\right)$",collapse="")
    mkplt()
    lines(a,b,col="grey",lwd=1.5)
    points(a,b,pch=19,cex=0.5,col="grey")
    lines(x,y,col="black",lwd=1.5)
    points(x,y,pch=19,cex=0.5,col="black")
    mtext(TeX(ca),1,-1,cex=0.6,at = -10,adj=0,padj=1)
    mtext(TeX(ct),1,-1,cex=0.6,at = 10,adj=1,padj=1)
    mtext(paste0(hmoves[hwo]," and ",vmoves[vwo]),3,0,cex=0.6)
}
doit(1,1)
doit(1,2)
doit(1,3)
doit(1,4)

```


\newpage

```{r,echo=F,fig.dim=c(6,9)}
par(mar=c(1.5,2,1.5,1),oma=c(0,0,0,0),pty="s",mfrow=c(4,3))

doit = function(hwo,vwo){
    x = hops[[hwo]](a)
    y = vops[[vwo]](b)
    ca = paste0("$g(x)=",gsub("x",hexp[hwo],vexp[vwo],fixed=T),"$",collapse="")
    ct = paste0("$(a,b)\\to\\left(",hct[hwo],",",vct[vwo],"\\right)$",collapse="")
    mkplt()
    lines(a,b,col="grey",lwd=1.5)
    points(a,b,pch=19,cex=0.5,col="grey")
    lines(x,y,col="black",lwd=1.5)
    points(x,y,pch=19,cex=0.5,col="black")
    mtext(TeX(ca),1,-1,cex=0.5,at = -10,adj=0,padj=1)
    mtext(TeX(ct),1,-1,cex=0.5,at = 10,adj=1,padj=1)
    mtext(paste0(hmoves[hwo]," and ",vmoves[vwo]),3,0,cex=0.6)
}
doit(2,1)
doit(3,1)
doit(4,1)
doit(2,2)
doit(3,2)
doit(4,2)
doit(2,3)
doit(3,3)
doit(4,3)
doit(2,4)
doit(3,4)
doit(4,4)

```










