```{r,echo=FALSE}
options(scipen=999)

ngraphs = 4
nchoice = 6
As = numeric()
hs = list()
ds = list()
es = list()
ers = character()
ss = character()
sn = numeric()
corrs = numeric()
dposs = list(c(1,1),c(1,2),c(2,1),c(2,2))
sposs = list(c(1,1),c(1,-1),c(-1,1),c(-1,-1))
for(i in 1:ngraphs){
    hch = sample(1:4,1)
    dch = sample(1:4,1)
    A = sample(c(-1,1),1)
    while(T){
        hb = sort(sample(1:9,2))
        h = hb*sposs[[hch]]
        if(abs(diff(abs(hb)))>2){break}
    }
    d = dposs[[dch]]
    hs[[i]] = h
    ds[[i]] = d
    As = c(As,A)
    eq = character()
    mmm = 0
    soln=0
    for(j in 1:4){
        for(k in 1:4){
            for(l in c(-1,1)){
                mmm = mmm+1
                hh = hb*sposs[[j]]
                dd = dposs[[k]]
                neq = paste0("{",l,"}(x-",hh[1],")^{",dd[1],"}(x-",hh[2],")^{",dd[2],"}",collapse="")
                neq = gsub("--","+",neq,fixed=T)
                neq = gsub("^{1}","",neq,fixed=T)
                neq = gsub("{-1}","-",neq,fixed=T)
                neq = gsub("{1}","",neq,fixed=T)
                eq = c(eq,neq)
                if(sum(hh==h)==2 && sum(dd==d)==2 && l==A){
                    soln=mmm
                    }
            }
        }
    }
    eqnums = sort(c(soln,sample((1:length(eq))[-soln],nchoice-1)))
    es[[i]] = eq[eqnums]
    ers = c(ers,eq[soln])
    ss = c(ss,paste0(1*(eqnums==soln),collapse=""))
    sn = c(sn,soln)
    corrs = c(corrs,(1:nchoice)[eqnums==soln])
}

```



Question
========

```{r,echo=F,results='asis',fig.dim=c(5,3)}
xx = seq(-12,12,0.01)
for(i in 1:ngraphs){
    cat(paste0("\n\n### Graph ",i,"\n\n",collapse=""))
    hh = hs[[i]]
    dd = ds[[i]]
    eqs = es[[i]]
    aa = As[i]
    yy = aa*(xx-hh[1])^dd[1]*(xx-hh[2])^dd[2]
    x2 = seq(min(hh),max(hh),0.01)
    y2 = aa*(x2-hh[1])^dd[1]*(x2-hh[2])^dd[2]
    mama = max(abs(y2))
    par(mar=c(0,0,0,0))
    plot(xx,yy,"l",xlim=c(-11,11),ylim=c(-1.1*mama,1.1*mama),axes=F,ann=F)
    arrows(-11,0,11,0,0.1,10,3)
    arrows(0,-mama*1.1,0,mama*1.1,0.1,10,3)
    for(jj in 1:10){
        if(jj%%5==0){
            lines(c(jj,jj),c(mama/20,-mama/20),lwd=1.3)
            lines(c(-jj,-jj),c(mama/20,-mama/20),lwd=1.3)
        } else {
            lines(c(jj,jj),c(mama/30,-mama/30))
            lines(c(-jj,-jj),c(mama/30,-mama/30))
        }
        
    }
    lines(xx,yy,col="blue",lwd=2)
    points(hh,c(0,0),col="black",pch=20,cex=1.4)
    cat(paste0("\\\n\nWhich function matches Graph ",i,"?\n"))
    eee = es[[i]]
    nnn = length(eee)
    cat(paste0("\n* $",LETTERS[1:nnn],"(x)~=~",eee,"$",collapse="\n"))
    cat("\n\n")
    cat(paste0("##ANSWER",i,"##\n\n"))
}
```
\


Answerlist
--------

```{r,echo=F,results='asis'}
for(i in 1:ngraphs){
    cat(paste0("* ",LETTERS[1:nchoice],"(x)\n",collapse=""))
}
```


Solution
========

```{r,echo=F,results='asis'}
for(i in 1:ngraphs){
    cat(paste0("* Graph ",i," is $",LETTERS[corrs[i]],"(x)~=~",ers[i],"$\n"))
}
```

Remember, each factor is $(x-r)$ where $r$ is the root. If the factor is squared, we expect a bounce. Lastly, make sure to pay attention to the sign in front, which will dictate the end behavior.



Meta-information
============
extype: cloze
exclozetype: `r paste0(rep("schoice",ngraphs),collapse="|")`
exsolution: `r paste0(ss,collapse="|")`
exname: match_graph_poly_eq