---
title: "Wave Cheat Sheet"
output: pdf_document
---

## Parent Functions

### The sine function $y=\sin(t)$

* Hits midline with positive slope at $t=0$

```{r,echo=F,fig.dim=c(8,3)}
library(latex2exp)
# par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(-8,8),ylim=c(-1,1),asp=1,ann=F,axes=F)
# for(i in seq(-1,1,0.1)){
#     abline(h=i,col="lightgrey",lwd=0.8)
# }
# for(i in seq(-3*pi,3*pi,pi/24)){
#     abline(v=i,col="lightgrey",lwd=0.8)
# }
# for(i in seq(-1,1,0.5)){
#     abline(h=i,col="grey",lwd=1)
# }
# for(i in seq(-3*pi,3*pi,pi/4)){
#     abline(v=i,col="grey",lwd=0.8)
# }
# arrows(-8.3,0,8.3,0,0.05,20,3)
# arrows(0,-1.07,0,1.07,0.05,20,3)
abline(h=0)
abline(v=0)

texts = c("$-2\\pi$","$\\frac{-3\\pi}{2}$","$-\\pi$","$\\frac{-\\pi}{2}$","$0$",
          "$\\frac{\\pi}{2}$","$\\pi$","$\\frac{3\\pi}{2}$","$2\\pi$")
xpos = pi*c(-2,-1.5,-1,-0.5,0,0.5,1,1.5,2)
# mtext(TeX(texts),1,2,at=xpos)
axis(1,xpos,TeX(texts),line=1,padj = 0.5)
mtext("t",1,4)

abline(h=c(-1,1),lty=2)
# text(xpos,0,TeX(texts),adj=c(0.5,1.2))
x = seq(-3*pi,3*pi,pi/360)
lines(x,sin(x),col="blue",lwd=2)
legend("topleft","y=sin(t)",col="blue",lwd=2,bg="white")
# text(c(0,0),c(-1,1),c(-1,1),adj=c(1.2,0.5))
axis(2,c(-1,0,1),line = 1)
mtext("y",2,3)
```


### The cosine function $y=\cos(t)$

* Has a maximum at $t=0$

```{r,echo=F,fig.dim=c(8,3)}
library(latex2exp)
# par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(-8,8),ylim=c(-1,1),asp=1,ann=F,axes=F)
# for(i in seq(-1,1,0.1)){
#     abline(h=i,col="lightgrey",lwd=0.8)
# }
# for(i in seq(-3*pi,3*pi,pi/24)){
#     abline(v=i,col="lightgrey",lwd=0.8)
# }
# for(i in seq(-1,1,0.5)){
#     abline(h=i,col="grey",lwd=1)
# }
# for(i in seq(-3*pi,3*pi,pi/4)){
#     abline(v=i,col="grey",lwd=0.8)
# }
# arrows(-8.3,0,8.3,0,0.05,20,3)
# arrows(0,-1.07,0,1.07,0.05,20,3)
abline(h=0)
abline(v=0)

texts = c("$-2\\pi$","$\\frac{-3\\pi}{2}$","$-\\pi$","$\\frac{-\\pi}{2}$","$0$",
          "$\\frac{\\pi}{2}$","$\\pi$","$\\frac{3\\pi}{2}$","$2\\pi$")
xpos = pi*c(-2,-1.5,-1,-0.5,0,0.5,1,1.5,2)
# mtext(TeX(texts),1,2,at=xpos)
axis(1,xpos,TeX(texts),line=1,padj = 0.5)
mtext("t",1,4)

abline(h=c(-1,1),lty=2)

# text(xpos,0,TeX(texts),adj=c(0.5,1.2))
x = seq(-3*pi,3*pi,pi/360)
lines(x,cos(x),col="blue",lwd=2)
legend("topleft","y=cos(t)",col="blue",lwd=2,bg="white")
# text(c(0,0),c(-1,1),c(-1,1),adj=c(1.2,0.5))
axis(2,c(-1,0,1),line = 1)
mtext("y",2,3)
```

\newpage

### Temporal Sinusoidal Oscillation

$$\begin{aligned}y&=A\sin(Bt)+D&\text{or}&&y&=A\cos(Bt)+D\end{aligned}$$

* Amplitude = $|A|$
* Angular frequency = $B$, and $B>0$
* Period = $P=\frac{2\pi}{B}$
* Frequency = $f=\frac{B}{2\pi}$
* Offset = $D$, so midline is at $y=D$.


```{r,echo=F,fig.dim=c(7,4)}
par(mar=c(0,0,0,0))


```


