```{r data generation, echo = FALSE, results = "hide"}

elements = c("+F","-F","[+F]","[-F]")

strings = character()

connections = function(string="AA+AA+AA+A+A",angle=pi/2,angle_initial=pi/2){
    switch = 1
    d = angle_initial
    x = 0
    y = 0
    xl = c(x)
    yl = c(y)
    dsave = numeric()
    xsave = numeric()
    ysave = numeric()
    chs = strsplit(string,"")[[1]]
    xl = numeric(sum(chs %in% LETTERS)+sum(chs=="]")+1)
    yl = numeric(sum(chs %in% LETTERS)+sum(chs=="]")+1)
    draw = numeric(sum(chs %in% LETTERS)+sum(chs=="]")+1)
    draw[1]=1
    j = 1
    for(i in 1:nchar(string)){
        ch = chs[i]
        cn = as.integer(charToRaw(ch))
        if(cn>=as.integer(charToRaw("A")) && cn<=as.integer(charToRaw("L"))){
            j = j+1
            draw[j] = 1
            x = x+cos(d)
            y = y+sin(d)
            xl[j] = x
            yl[j] = y
        }
        if(cn>=as.integer(charToRaw("M")) && cn<=as.integer(charToRaw("Z"))){
            j = j+1
            draw[j] = 0
            x = x+cos(d)
            y = y+sin(d)
            xl[j] = x
            yl[j] = y
        }
        if(cn==as.integer(charToRaw("["))){
            dsave = c(dsave,d)
            xsave = c(xsave,x)
            ysave = c(ysave,y)
        }
        if(cn==as.integer(charToRaw("]"))){
            j = j+1
            draw[j] = 0
            x = xsave[length(xsave)]
            y = ysave[length(ysave)]
            d = dsave[length(dsave)]
            if(length(xsave)>1){
                xsave = xsave[1:(length(xsave)-1)]
                ysave = ysave[1:(length(ysave)-1)]
                dsave = dsave[1:(length(dsave)-1)]
            } else {
                xsave = numeric()
                ysave = numeric()
                dsave = numeric()
            }
            xl[j] = x
            yl[j] = y
        }
        if(cn==as.integer(charToRaw("-"))){
            d = d+angle*switch
        }
        if(cn==as.integer(charToRaw("+"))){
            d = d-angle*switch
        }
        if(cn==as.integer(charToRaw("."))){
            switch = switch*(-1)
        }
    }
    conns = character()
    for(i in 2:length(xl)){
        if(draw[i-1]){
            conns = c(conns,paste0("(",round(xl[i-1]),",",round(yl[i-1]),")-(",round(xl[i]),",",round(yl[i]),")",collapse=""))
            conns = c(conns,paste0("(",round(xl[i]),",",round(yl[i]),")-(",round(xl[i-1]),",",round(yl[i-1]),")",collapse=""))
        }
    }
    conns = sort(conns)
    return(conns)
}

conns = character()
for(jjj in 1:6){
    while(T){
        start = "F"
        s = start
        for(i in 1:3){
            s2 = strsplit(s,"")[[1]]
            nds = which(s2=="F")
            ii = sample(nds,1)
            s2[ii] = sample(elements,1)
            s3 = paste0(s2,collapse="")
            s3 = gsub("+-","",s3,fixed=T)
            s3 = gsub("-+","",s3,fixed=T)
            s3 = gsub("F","FF",s3,fixed=T)
            s = s3
        }
        s = paste0("F",s,"F",collapse="")
        print(s)
        s2 = strsplit(s,"")[[1]]
        conn = connections(s)
        print(conn)
        if(sum(s2=="[")==sum(s2=="]") && !(s%in%strings) && length(unique(conn))==length(conn) && !(paste0(conn,collapse=";")%in%conns)){break}
    }
    strings = c(strings,s)
    conns = c(conns,paste0(conn,collapse=";"))
}

xyd = function(string="AA+AA+AA+A+A",angle=pi/2,angle_initial=pi/2){
    switch = 1
    d = angle_initial
    x = 0
    y = 0
    xl = c(x)
    yl = c(y)
    dsave = numeric()
    xsave = numeric()
    ysave = numeric()
    chs = strsplit(string,"")[[1]]
    xl = numeric(sum(chs %in% LETTERS)+sum(chs=="]")+1)
    yl = numeric(sum(chs %in% LETTERS)+sum(chs=="]")+1)
    draw = numeric(sum(chs %in% LETTERS)+sum(chs=="]")+1)
    draw[1]=1
    j = 1
    for(i in 1:nchar(string)){
        ch = chs[i]
        cn = as.integer(charToRaw(ch))
        if(cn>=as.integer(charToRaw("A")) && cn<=as.integer(charToRaw("L"))){
            j = j+1
            draw[j] = 1
            x = x+cos(d)
            y = y+sin(d)
            xl[j] = x
            yl[j] = y
        }
        if(cn>=as.integer(charToRaw("M")) && cn<=as.integer(charToRaw("Z"))){
            j = j+1
            draw[j] = 0
            x = x+cos(d)
            y = y+sin(d)
            xl[j] = x
            yl[j] = y
        }
        if(cn==as.integer(charToRaw("["))){
            dsave = c(dsave,d)
            xsave = c(xsave,x)
            ysave = c(ysave,y)
        }
        if(cn==as.integer(charToRaw("]"))){
            j = j+1
            draw[j] = 0
            x = xsave[length(xsave)]
            y = ysave[length(ysave)]
            d = dsave[length(dsave)]
            if(length(xsave)>1){
                xsave = xsave[1:(length(xsave)-1)]
                ysave = ysave[1:(length(ysave)-1)]
                dsave = dsave[1:(length(dsave)-1)]
            } else {
                xsave = numeric()
                ysave = numeric()
                dsave = numeric()
            }
            xl[j] = x
            yl[j] = y
        }
        if(cn==as.integer(charToRaw("-"))){
            d = d+angle*switch
        }
        if(cn==as.integer(charToRaw("+"))){
            d = d-angle*switch
        }
        if(cn==as.integer(charToRaw("."))){
            switch = switch*(-1)
        }
    }
    return(list(xl,yl,draw,x,y,d,xsave,ysave,dsave))
}

plotit = function(xyd,lwd=1,col="blue"){
    x = xyd[[1]]
    y = xyd[[2]]
    d = xyd[[3]]
    plot(0,0,"n",xlim=c(-10,10),ylim=c(-10,10),axes=F,ann=F)
    starts = numeric()
    if(d[1]){
        starts = c(1)
    }
    starts = c(starts,which(diff(d)==1))
    ends = which(diff(d)==-1)
    if(d[length(d)]==1){
        ends = c(ends,length(d))
    }
    for(i in 1:length(starts)){
        lines(x[starts[i]:ends[i]],y[starts[i]:ends[i]],lwd=lwd,col=col)
    }
}

wo = sample(1:6,1)
given = strings[wo]
sol = paste0(1*(wo==1:6),collapse="")

```

Question
========

`r given`


```{r,echo=F,fig.dim=c(5,7)}
par(mar=c(0,4,0,0),oma=c(0,0,0,0),pty="s",mfrow=c(3,2))
plotit(xyd(strings[1],pi/2,pi/2),lwd=2,col="blue")
box()
text(-9,9,"A")
plotit(xyd(strings[2],pi/2,pi/2),lwd=2,col="blue")
box()
text(-9,9,"B")
plotit(xyd(strings[3],pi/2,pi/2),lwd=2,col="blue")
box()
text(-9,9,"C")
plotit(xyd(strings[4],pi/2,pi/2),lwd=2,col="blue")
box()
text(-9,9,"D")
plotit(xyd(strings[5],pi/2,pi/2),lwd=2,col="blue")
box()
text(-9,9,"E")
plotit(xyd(strings[6],pi/2,pi/2),lwd=2,col="blue")
box()
text(-9,9,"F")
```


Solution
========



Meta-information
============
extype: schoice
exsolution: `r sol`
exname: lsys_string