---
title: "Syllabus: Algebra 2"
author: "Mr. Worley"
output: 
    pdf_document:
        toc: true
---


# Course Overview

* Algebra II (with Trigonometry and Statistics)
* Mostly Juniors, some Sophomores, some Seniors
* Mr. Chad Worley
* chad.worley@bartcharter.org

# Course Description

This course follows the [Massachusetts Curriculum Framework](https://www.doe.mass.edu/frameworks/math/2017-06.pdf) for an Algebra 2 course:

> "Instructional time should focus on four critical areas: (1) relate arithmetic of rational expressions to arithmetic of rational numbers; (2) expand understandings of functions and graphing to include trigonometric functions; (3) synthesize and generalize functions and extend understanding of exponential functions to logarithmic functions; and (4) relate data display and summary statistics to probability and explore a variety of data collection methods."

The four quarters of the school year will roughly match with those four critical areas. We will focus on mastering all learning objectives in the Massachusetts Curriculum Framework for Algebra II.

# Typical Class

* Entrance ticket (10 min): practice SAT/ACT/NY Regents questions
* Practice problems
    * Most practice problems are randomly varied. Usually just the numbers change.
    * First, Mr. Worley shows how to work through an example while discussing the rationale of each step.
    * Then, students can work on their versions.
        * Collaboration is encouraged.
        * Each student will have own versions.
        * Multiple attempts allowed.
    * Typically around 4-5 practice problems per day.
    * If students are unable to finish in allotted time, they are expected to complete problems as homework.
* Blooket practice
    * Some fundamental skills will be reinforced with Blooket.
    
# Tests

* Online mastery (typically accounts for most of a class)
    * Students work through approximately 10 problems (usually same as practice problems).
    * Only see grade after completing all problems.
    * Can be attempted multiple times.
    * Highest score counts.
    * These are done individually.
* Paper tests (typically accounts for most of a class)
    * Typically 1 page (front and back)
    * Meant to be completed in approximately 20 minutes.
    * Can be attempted multiple times.
    * Highest score counts.
    * These are done individually.
* Cumulative exams
    * Approximately once per quarter.

# Classroom Expectations & Norms

* Do not talk while Mr. Worley is lecturing.
* Raise your hand to ask a question.
* Collaboration is encouraged for practice problems, but students work through quizzes, tests, and exams individually.

# Materials

Every day you should have:

* A chromebook
* A writing utensil
* Blank paper (or a whiteboard)



