---
title: "Welcome to Algebra 2!"
output: slidy_presentation
---

# Mr. Worley

* chad.worley@bartcharter.org
* Canvas: https://bart.instructure.com/courses/2110

# Overview of course

This course focuses on the following topics, roughly a quarter of the year spent on each.

1. Functions
    * Parent functions
    * Describing features
    * Transformations (shift/stretch/flip)
2. Quadratics
    * Quadratic Equations 
    * Quadratic Graphs
    * Complex Numbers
3. Radicals and Polynomials
    * Equations
    * Graphs
4. More Polynomials

# Grade Categories and Percentages

* Classwork: 50%
    * Unfinished classwork becomes homework
* Assessments: 40%
* Work Habits: 10%
    * Quiet during lecture
    * Focus during practice
    * Collaborative during group work
    * Effort

# Late policies

* Most assignments will have a -2% penalty per day (calculated automatically by Canvas).
* The largest penalty will be -30%, so you can always get up to 70% on any assignment until the end of quarter.
* If you are absent, you can request me to remove late penalties after completing the assignment.
    * You get approximately 1.5 times the days absent to complete the work without any late penalty.

# Materials

Every day you should have:

* A charged chromebook
* A writing utensil
* Blank paper (I will try to keep a stack of scratch paper in room)

# Artificial Intelligence

* We will investigate a new tool this year:
    * MagicSchool (in Classlink)
* Honestly, this is all new. I expect you to use it like a tutor.
    * No AI will be used on assessments.
    * If you use AI on practice problems, try to go beyond just getting the answer. Ask AI for help understanding the underlying concepts that motivate the individual steps.


# Handbook

* [https://www.bartcharter.org/apps/pages/Student-Handbook](https://www.bartcharter.org/apps/pages/Student-Handbook)
* Phones off and away.
    * NOT simply silent and in pocket!
* No food or drink (except water).
* Do not leave classroom without SmartPass active.
    * Do not leave while you are still in queue.

# Statements of harm/abuse

* Any statement of intent to do harm (to self or others) will be immediately brought to a professional's attention.
* Any statement of abuse will be immediately brought to a professional's attention.



