---
title: "Weighted die analysis"
output: 
    html_document:
        toc: true
---

```{r,fig.dim=c(6,6)}
par(mar=c(0,0,0,0),pty="s")
plot(c(-16,-16,16,16,-16),c(-16,16,16,-16,-16),"l",xlim=c(-20,20),ylim=c(-20,20),axes=F,ann=F)
polygon(c(-13,-13,13,13),c(-13,13,13,-13))
lines(c(-13,13),c(5,5))
lines(c(16.8,17.2,17,17,16.8,17.2),c(13,13,13,16,16,16))
text(18,14.5,"w")
lines(c(-16.8,-17.2,-17,-17,-16.8,-17.2),c(0,0,0,13,13,13))
text(-18,6.5,"r")
lines(c(-0.2,0.2,0,0,-0.2,0.2),c(0,0,0,5,5,5),lwd=2)
text(1,2.5,"x")
```






```{r}
x = c(2,6,5,6,6,
      1,4,4,5,6,
      1,3,5,5,6,
      2,3,3,4,6,
      2,3,4,4,5,
      2,2,3,5,5,
      1,1,2,2,6,
      2,3,6,6,6,
      1,3,5,6,6,
      1,3,3,4,5,
      2,3,3,4,5,
      1,2,2,4,6,
      2,3,3,4,6,
      2,4,4,6,6,
      1,2,2,3,6,
      2,3,3,4,6,
      3,3,4,5,6,
      4,5,6,6,6,
      2,2,3,5,6,
      2,5,5,6,6,
      2,3,4,6,6,
      2,3,3,3,4,
      2,3,3,4,6)

n = length(x)
xbar = mean(x)
print(n)
print(xbar)
s = sd(x)
print(s)
me = 2*s/sqrt(n)
print(me)
print(xbar-3.5)
```
