---
output: slidy_presentation
---

# Zero-product property

If a product equals zero, at least one of the factors equals zero.

# Use zero-product property to get solutions to quadratic equation

If equation is in factored form, this is easy!

Solve:
$$(x+5)(x-8)~=~0$$

>- The product of $(x+5)$ and $(x-8)$ needs to equal zero. If either $x+5=0$ or $x-8=0$, then the product is zero.
>- If $x+5=0$ then $x=-5$.
>- If $x-8=0$ then $x=8$.

# Fraction solutions

Solve:
$$(3x+5)(7x-8)~=~0$$

>- The product of $(3x+5)$ and $(7x-8)$ needs to equal zero. If either $3x+5=0$ or $7x-8=0$, then the product is zero.
>- If $3x+5=0$ then $3x=-5$ and finally $x=\frac{-5}{3}$.
>- If $7x-8=0$ then $7x=8$ and finally $x=\frac{8}{7}$.



# Solve equation by factoring

Solve:
$$x^2-3x-40~=~0$$

>- First, factor the left-hand side of the equation.
>- $(x+5)(x-8)~=~0$
>- Find the solutions:
>- $x=-5$
>- $x=8$


# Solve equation by first getting one side to be zero

Solve:
$$3x^2-7x-35~=~2x^2-4x+5$$

>- To make right-hand side equal zero, subtract $2x^2-4x+5$ from both sides.
>- $x^2-3x-40~=~0$
>- Factor the left-hand side of the equation.
>- $(x+5)(x-8)~=~0$
>- Find the solutions:
>- $x=-5$
>- $x=8$



