---
title: "Assignment: Research Questions"
subtitle: "Due: Mon Aug 26"
output:
  html_document:
    toc: true
---

# Overview

You will write 12 potential research questions. There will be 4 types of questions, and you will give **3 questions for each type**. Submit your questions on Canvas.

## The Types

* Estimate a single proportion.
* Estimate a single mean.
* Compare two proportions.
* Compare two means.

## Realistic-ness

* These questions should be potentially researched, by you, in a few weeks. In fact, I expect that one of these will get developed into your research project.

## Examples

### Estimate Proportion

1. What proportion of trees have orange/yellow leaves (in late September)?
2. What proportion of students believe that studying with music helps their concentration?
3. What proportion of free throws do you make (during calm conditions)?
4. What proportion of spins of a coin (on edge, on table, like a top) land heads?

### Estimate Mean

1. What is the average hours of sleep for a high-school students on a school night?
2. What is the average number of bounces when you skip a rock on a smooth lake?
3. What is the average weight of an apple?
4. What is your average number of deaths in a round of free-for-all videogame session?
5. What is the average weight of bird seed eaten from a feeder per day?

### Test for Difference of Proportions

1. Does strategy influence the proportion of wins in an arcade game?
2. Does using a fertilizer cause a higher proportion of seeds to sprout compared to not using any fertilizer?
3. Does shooting a basketball right/left handed cause a difference in proportion of freethrows made? (Or does changing the person alter the proportion made?)

### Test for Difference of Means

1. Does the type of music played in the background affect the average number of listener's deaths in a round of free-for-all?
2. Does one lure catch more fish per hour than another lure?
3. Do different shoes change the average time to run 100 meters?
4. Can you accomplish two tasks simultaneously faster than the same two tasks sequentially? (You have to try your hardest in all cases.)
