---
title: "Assignment: Study Design"
subtitle: "Due: Thu Aug 29"
output:
  html_document:
    toc: true
---

# Overview

1. Pick a research question (either from your list of 12 or a new one).
2. Describe a survey, experiment, or observational study that could be used to address the research question.
3. Describe how you would use randomization in your study.
4. Describe limitations of your study.
5. Make sure to discuss the population, parameter, sample, and statistic.

# Example

My research question is whether the [anchoring effect](https://en.wikipedia.org/wiki/Anchoring_effect) experiment can be replicated at BART with my Algebra 2 students. Of course, my Algebra 2 students are not representative of the human population at large, but because I am running an experiment, I could still potentially show strong evidence for a cause-effect between the anchor and the guess.

I will print out 30 cards. Half of the cards will read, "In 10 seconds, please estimate $1\times 2\times 3\times 4\times 5\times 6\times 7\times 8$." The other half read, "In 10 seconds, please estimate $8\times 7\times 6\times 5\times 4\times 3\times 2\times 1$." I will shuffle the cards, deal them out to the students face down. I will instruct the students that I have written a math problem that I want them to ESTIMATE the solution to within 10 seconds of flipping over the cards.

The anchoring effect predicts that students given the first type of card (group 1) will tend to guess lower numbers than the students given the second type of card (group 2). Each group's guesses will be averaged, and then compared to see if the difference is significant.

# Example 2

I want to estimate the probability that a 2012 eagle-back quarter will land heads-up after spinning like a top (on its edge) on a table. In this case, the population is the infinite spins this coin could be spin, and the parameter is the probability.

This will be an "experiment", but without random assignment to two groups. In fact, I'd be tempted to call this an observational study, even though I will be actively spinning the quarters.

I will spin the quarter 200 times. These spins, and their results (heads or tails), will be the sample. I will get the sample proportion (the statistic of interest) by dividing the head count by 200. 







