---
title: "Understanding Samples and Populations"
output:
  slidy_presentation:
    theme: cerulean
---

## Slide 1: What is a Population?

* **Definition:** A [population](https://en.wikipedia.org/wiki/Statistical_population) is the **entire group** we are interested in studying.
* **Example:**
    * All students in a school
    * All trees in a forest
    * All cars in a city
    
*(Some people get confused because they think "population" means the population count, like how many people live in a town. In Statistics, when we say "what is the population", we are not asking how many people live in a place.)*


## Slide 2: What is a Population Parameter?

* **Definition:** A [population parameter](https://en.wikipedia.org/wiki/Statistical_parameter) is a **numerical value** that describes a characteristic of the population.
* **Example:**
    * Average height of all students in a school
    * Proportion of trees in a forest that are oak
    * Average age of cars in a city

## Slide 3: What is a Sample?

* **Definition:** A [sample](https://en.wikipedia.org/wiki/Sampling_(statistics)) is a **subset of the population** that we collect data from.
* **Example:**
    * A group of 50 students from a school
    * A group of 100 trees in a forest
    * A group of 20 cars in a city

## Slide 4: What is a Sample Statistic?

* **Definition:** A [sample statistic](https://en.wikipedia.org/wiki/Statistic) is a **numerical value** that describes a characteristic of the sample.
* **Example:**
    * Average height of 50 students in a school
    * Proportion of oak trees in a group of 100 trees
    * Average age of 20 cars in a city

## Slide 5: Key Points

* **Goal:** We use sample statistics to **estimate population parameters**.
* **Inference:** The goal is to use the sample to **make inferences** about the population.
* **Representation:** The sample must be **representative** of the population to ensure accurate estimates.

## Slide 6: Example

* **Population:** All voters in a city
* **Population parameter:** Proportion of voters who support a particular candidate.
* **Sample:** A group of 1000 randomly selected voters.
* **Sample statistic:** Proportion of voters in the sample who support the candidate.

## Slide 7: Consistent Variables

### Statistics

|stat | variable | spoken |
|:---:|:---:|:---:|
| sample mean | $\bar{x}$ | "x bar" |
| sample proportion | $\widehat{p}$ | "p hat" |
| sample standard deviation | $s$ | "s" |
| sample count, sample size | $n$ | "n" |

### Parameters

|param | variable | spoken |
|:---:|:---:|:---:|
| population mean | $\mu$ | "mu" |
| population proportion | $p$ | "p" |
| population standard deviation | $\sigma$ | "sigma" |


## Slide 8: Conclusion

Understanding the difference between samples and populations, along with their respective statistics and parameters, is crucial for drawing meaningful conclusions from data. By carefully selecting and analyzing samples, we can make accurate inferences about the larger population.