```{r,echo=F,warning=F}
fixer = function(exp){
  exp = gsub("+-","-",exp,fixed=T)
  exp = gsub("t^0","",exp,fixed=T)
  exp = gsub("h^0","",exp,fixed=T)
  exp = gsub("t^1","t",exp,fixed=T)
  exp = gsub("h^1","h",exp,fixed=T)
  return(exp)
}
abcd = sample(11:100,4)/10
a = abcd[1]
b = abcd[2]
c = abcd[3]
d = abcd[4]

```

Question
========

First, we can prove that if $f(t) = m(t)+n(t)$ then $f'(t) = m'(t)+n'(t)$. In other words, the derivative of a sum equals the sum of the derivatives. Or, in other words, a derivative operator can be distributed over terms of a sum. The proof follows.

$$f'(t) = \lim_{h\to 0}\frac{f(t+h)-f(t)}{h}$$
$$f'(t) = \lim_{h\to 0}\frac{\left(m(t+h)+n(t+h)\right)-\left(m(t)+n(t)\right)}{h}$$
$$f'(t) = \lim_{h\to 0}\frac{\left(m(t+h)-m(t)\right)+\left(n(t+h)-n(t)\right)}{h}$$
$$f'(t) = \lim_{h\to 0}\left(\frac{m(t+h)-m(t)}{h}+\frac{n(t+h)-n(t)}{h}\right)$$
$$f'(t) = \lim_{h\to 0}\frac{m(t+h)-m(t)}{h}+\lim_{h\to 0}\frac{n(t+h)-n(t)}{h}$$
$$f'(t) = m'(t)+n'(t)$$

Also, if $g(t) = at^b$ then $g'(t) = (ab)t^{b-1}$. In other words, the derivative of a power function is found by multiplying the coefficient by the power and then reducing the power by one.



Let $f(t)$ be a function defined below:
$$f(t)~=~`r a`t^{`r b`}+`r c`t^{`r d`}$$

Using the rules above, it is clear that the derivative can be written in the following form:

$$f'(t)~=~ pt^$$




Solution
========

We were given $f(t)$.
$$f(t)=`r ex1`$$
We were given the limit definition of a derivative.
$$f'(t) ~=~ \lim_{h\to 0}\frac{f(t+h)-f(t)}{h}$$
Use the given function in the limit definition.
$$f'(t)~=~`r ex2`$$
Use the correct [binomial expansion](https://en.wikipedia.org/wiki/Binomial_theorem).

$$f'(t)~=~`r ex3`$$

Distribute.
$$f'(t)~=~`r ex4`$$

Combine the like terms.
$$f'(t)~=~`r ex5`$$

Notice all remaining terms in numerator share a common factor of $h$, which is also in the denominator. We can eliminate this common factor.

$$f'(t)~=~`r ex6`$$

Now we can replace $h$ with $0$ (because there won't be division by 0).
$$f'(t)~=~`r ex7`$$
Simplify. Anything times 0 is 0. Anything plus 0 is that thing.

$$f'(t)~=~`r a*b`t^{`r b-1`}$$



Meta-information
============
extype: cloze
exclozetype: schoice|schoice
exsolution: `r sol1`|`r sol2`
exname: lim_def_pow