```{r,echo=F,warning=F}
fixer = function(exp){
  exp = gsub("+-","-",exp,fixed=T)
  exp = gsub("--","+",exp,fixed=T)
  exp = gsub("x^0","",exp,fixed=T)
  exp = gsub("x^1","x",exp,fixed=T)
  return(exp)
}

while(T)
{
  tf = runif(1,3,20)
  Pb = runif(1,30,90)
  pmax = runif(1,400,1200)
  tm = 1/3*tf
  A = -27/4*(Pb - pmax)/tf^3
  
  # P(t) = A*t(t-tf)^2+Pb
  # P(t) = A*t(t^2-2*tf*t+tf^2)+Pb
  # P(t) = At^3 - 2*tf*A*t^2 + tf^2*A*t + Pb
  # E(t) = 1/4*A*t^4 - 2/3*A*t^3*tf + 1/2*A*t^2*tf^2 + Pb*t
  
  a = round(1/4*A,1)
  b = round(-2/3*A*tf,1)
  c = round(1/2*A*tf^2,1)
  d = round(Pb,1)
  if(a>0.1 && max(c(a,b,c,d))<1000){break}
}

ex1 = fixer(paste0(a,"t^4+",b,"t^3+",c,"t^2+",d,"t",collapse=""))
```

Question
========

A human converts chemical potential (energy stored as ATP, sugar, fat, etc...) into kinetic energy (without any loss to friction) by pedaling a bicycle. Over time, the amount of energy increases, following the polynomial expression below.
$$E(t) ~=~ `r ex1`$$

```{r,echo=F,fig.dim=c(6,6)}
tt = seq(0,tf,length.out=100)
EE = a*tt^4+b*tt^3+c*tt^2+d*tt
plot(tt,EE,type="l",xlab="time (s)",ylab="energy (J)")
```
\


Solution
========



Meta-information
============
extype: num
exsolution: 1
exname: ddt_energy
extol: 0.01