---
output: slidy_presentation
---

# Agenda

* Entrance Ticket: [ET_0929](https://bart.instructure.com/courses/2110/quizzes/3203)
    * Review of function translations
* A [new parent-function reference](https://chadworley.github.io/algtwo2026/u02/09_29/parent_functions.pdf)
* [PCW_09_29_graph_parent_translations](https://bart.instructure.com/courses/2110/assignments/28864)
    * Graph 8 shifted parent functions on paper
    * Due today!

# Shifts

* Adding/subtracting in the argument shifts function horizontally. The direction is "backwards".
* Adding/subtracting outside the function shifts function vertically. The direction is "normal".
* Examples:
    * If we compare $y=f(x)$ and $y=f(x+2)+3$, the second curve is congruent to the first, but the second curve is shifted 2 units **left** and 3 units **up**.
    * If we compare $y=f(x)$ and $y=f(x-2)+3$, the second curve is congruent to the first, but the second curve is shifted 2 units **right** and 3 units **up**.
    * If we compare $y=f(x)$ and $y=f(x+2)-3$, the second curve is congruent to the first, but the second curve is shifted 2 units **left** and 3 units **down**.
    * If we compare $y=f(x)$ and $y=f(x-2)-3$, the second curve is congruent to the first, but the second curve is shifted 2 units **right** and 3 units **down**.

