```{r data generation, echo = FALSE, results = "hide",warning=FALSE}
xs = seq(-3*pi,3*pi,pi/1080)
y1 = sin(xs)
y2 = cos(xs)
y3 = tan(xs)
ys = list(y1,y2,y3)
ord = sample(1:3)

ach = c("sin","cos","tan")
al1 = paste0("* f(x) = ",ach,"(x)",collapse="\n")
al2 = paste0("* g(x) = ",ach,"(x)",collapse="\n")
al3 = paste0("* h(x) = ",ach,"(x)",collapse="\n")

sol1 = paste0(1*(ord[1]==1:3),collapse="")
sol2 = paste0(1*(ord[2]==1:3),collapse="")
sol3 = paste0(1*(ord[3]==1:3),collapse="")


```

Question
========

Match the graphs to their trigonometric functions.

```{r,echo=F,fig.dim=c(8,4)}
plot(0,0,"n",xlim=c(-7,7),ylim=c(-2,2),asp=1,xlab="x",ylab="y=f(x)")
arrows(-7,0,7,0,0.1,15,3)
arrows(0,2,0,-2,0.1,15,3)
for(i in 1:(length(xs)-1)){
    x1 = xs[i]
    x2 = xs[i+1]
    y1 = ys[[ord[1]]][i]
    y2 = ys[[ord[1]]][i+1]
    if(abs(y2-y1)<100){
        lines(c(x1,x2),c(y1,y2),col="blue",lwd=2)
    }
}
```
\

* ##ANSWER1##


```{r,echo=F,fig.dim=c(8,4)}
plot(0,0,"n",xlim=c(-7,7),ylim=c(-2,2),asp=1,xlab="x",ylab="y=g(x)")
arrows(-7,0,7,0,0.1,15,3)
arrows(0,2,0,-2,0.1,15,3)
for(i in 1:(length(xs)-1)){
    x1 = xs[i]
    x2 = xs[i+1]
    y1 = ys[[ord[2]]][i]
    y2 = ys[[ord[2]]][i+1]
    if(abs(y2-y1)<100){
        lines(c(x1,x2),c(y1,y2),col="blue",lwd=2)
    }
}
```
\

* ##ANSWER2##


```{r,echo=F,fig.dim=c(8,4)}
plot(0,0,"n",xlim=c(-7,7),ylim=c(-2,2),asp=1,xlab="x",ylab="y=h(x)")
arrows(-7,0,7,0,0.1,15,3)
arrows(0,2,0,-2,0.1,15,3)
for(i in 1:(length(xs)-1)){
    x1 = xs[i]
    x2 = xs[i+1]
    y1 = ys[[ord[3]]][i]
    y2 = ys[[ord[3]]][i+1]
    if(abs(y2-y1)<100){
        lines(c(x1,x2),c(y1,y2),col="blue",lwd=2)
    }
}
```
\

* ##ANSWER3##

Answerlist
--------

`r al1`
`r al2`
`r al3`

Solution
========

Try typing `y=sin(x)` and `y=cos(x)` and `y=tan(x)` into [Desmos](https://www.desmos.com/calculator).


Meta-information
============
extype: cloze
exclozetype: schoice|schoice|schoice
exsolution: `r sol1`|`r sol2`|`r sol3`
exname: trig_parents