```{r,echo=F,warning=F}
# F-TF.B.5. Choose trigonometric functions to model periodic phenomena with specified amplitude, frequency, and midline.
while(T){
    AfD = signif(10^(runif(3,0.04,1)*sample(c(-1,1),3,T)),2)
    A = AfD[1]*sample(c(-1,1),1)
    f = AfD[2]
    D = AfD[3]*sample(c(-1,1),1)
    ach = sort(unique(signif(c(AfD,-AfD,AfD*2*pi,-AfD*2*pi,2*pi/AfD,-2*pi/AfD),2)))
    ach2 = sort(unique(abs(signif(c(AfD,-AfD,AfD*2*pi,-AfD*2*pi,2*pi/AfD,-2*pi/AfD),2))))
    if(T){break}
    if(length(ach)==18 && min(diff(ach))>0.02 && min(diff(log(ach)))>log(1.1)){break}
}

al = paste0("* ",ach,collapse="\n")
al2 = paste0("* ",ach2,collapse="\n")
sol1 = paste0(1*(A==ach),collapse="")
sol2 = paste0(1*(signif(f*2*pi,2)==ach2),collapse="")
sol3 = paste0(1*(D==ach),collapse="")

statements = c(paste0("The amplitude is ",abs(A)," meters."),
               paste0("The frequency is ",f," hertz."),
               paste0("The midline is at ",D," meters."))

sc = sample(1:2,1)
func = c("sin","cos")[sc]
if(sc==1 && A>0){
    s4 = "At $t=0$, the mass is at the midline with an upwards velocity."
}
if(sc==1 && A<0){
    s4 = "At $t=0$, the mass is at the midline with an downwards velocity."
}
if(sc==2 && A>0){
    s4 = "At $t=0$, the mass is at the maximum height."
}
if(sc==2 && A<0){
    s4 = "At $t=0$, the mass is at the minimum height."
}

st = sample(statements)
st = paste0(1:3,". ",st,collapse="\n")

fch = c("sin","cos")
fal = paste0("* ",fch,collapse="\n")
solf = paste0(1*(1:2==sc),collapse="")

Dstr = paste0("+",D)
if(D<0){
    Dstr = paste0(D)
}
B = signif(2*pi*f,2)

```

Question
========

A mass-spring system oscillates with the following characteristics:

`r st`
4. `r s4`

Choose a trigonometric function ($g$), and the parameters ($A$, $B$, and $D$), to model this oscillatory motion.

$$y~=~A\cdot g(Bt)+D$$

* $g=$ ##ANSWER1##
* $A=$ ##ANSWER2##
* $B=$ ##ANSWER3##
* $D=$ ##ANSWER4##


Answerlist
--------

`r fal`
`r al`
`r al2`
`r al`

Solution
========


The only calculation needed is to convert the [frequency](https://en.wikipedia.org/wiki/Frequency) ($f=`r f`$) into [angular frequency](https://en.wikipedia.org/wiki/Angular_frequency) ($B$) by multiplying by $2\pi$.
$$B=2\pi f$$
$$B=`r 2*pi*f`$$

1. If the wave starts at a midline and is increasing (going up), then $A>0$ and $g=\sin$.
2. If the wave starts at a midline and is decreasing (going down), then $A<0$ and $g=\sin$.
3. If the wave starts at a maximum, then $A>0$ and $g=\cos$.
4. If the wave starts at a minimum, then $A<0$ and $g=\cos$.

The amplitude is the absolute value of $A$.
$$|A|~=~`r abs(A)`$$

The midline is simply given:
$$D=`r D`$$

So,

$$y ~=~ `r signif(A,2)`\cdot\`r func`(`r signif(B,2)`t)`r Dstr`$$



Meta-information
============
extype: cloze
exclozetype: schoice|schoice|schoice|schoice
exsolution: `r solf`|`r sol1`|`r sol2`|`r sol3`
exname: pick_wave_pams