```{r,echo=F,warning=F}
phases = seq(0,2*pi-pi/12,pi/12)

```

Question
========


In [additive synthesis](https://en.wikipedia.org/wiki/Additive_synthesis), a musician combines [pure tones](https://en.wikipedia.org/wiki/Pure_tone) by adding together sine waves to produce a large variety of tones.

In [harmonic](https://en.wikipedia.org/wiki/Harmonic_series_(music)#Terminology) additive synthesis, a sine wave with a fundamental frequency is added to sine waves with positive-integer multiples of the fundamental frequency. Each harmonic has its own amplitude and phase shift. The exact set of harmonics, their amplitudes, and their phases dictates the [timbre](https://en.wikipedia.org/wiki/Timbre) of the [musical tone](https://en.wikipedia.org/wiki/Musical_tone).

For example, the musician might combine a sine wave with amplitude of 1 and frequency of 50 Hz with another sine wave with amplitude 1 and frequency of 100 Hz. The remaining decision is the phase shift ($c$).

$$y~~=~~\sin(2\pi50 t)~+~\sin(2\pi 100 t+c)$$






Answerlist
--------




Solution
========





Meta-information
============
extype: cloze
exclozetype: 
exsolution: 
exname: match_animations