---
title: "Daily agenda for Precalculus 2023-2024"
output:
  html_document:
    toc: true
    toc_depth: 2
---

## Week 1: Aug 21 - Aug 25

### Monday Aug 21

* Half day for 6th and 9th graders.

### Tuesday Aug 22

* **Entrance:** 
  * Getting-to-know-you survey
* **Objectives:** 
  * Get overview of class
  * Generate random numbers using a spreadsheet
* **Agenda:** 
  * Introductions
  * [Outline the class](https://chadworley.github.io/precalculus/unit_00_overview/slides_01/slides_01.pdf){target="_blank"}
* **Homework:**
  * None
  
### Wednesday Aug 23

* **Entrance:** 
  * calculate mean of integers between 1 and 6.
* **Objectives:** 
  * Calculate population mean from probability distribution using [online tool](https://chadworley.github.io/cltsim.html){target="_blank"}.
  * Calculare a $z$-score
  * Use random numbers to simulate a model.
  * Create histogram from data.
  * Differentiate between population and sample.
  * Make inference when observation and model don't align.
* **Agenda:** 
  * Questions: [population mean and $z$-score](https://chadworley.github.io/precalculus/unit_01_stats/week_01/002_practice/outcanvas/002_shared1.html){target="_blank"}.
  * [Dice rolling project](https://chadworley.github.io/precalculus/unit_01_stats/week_01/002_dice-rolling_project/002_dice-rolling_project.pdf){target="_blank"}
* **Homework:**
  * Finish the dice-rolling project
  
### Thursday Aug 24

* **Entrance**
  * When rolling 100d6, the expected total is $\text{ET}=350$ with a standard error of $\text{SE}=17$. When rolling the  3d-printed dice, our class rolled a total of $\sum x =448$ with $n=100$ rolls. Calculate a $z$-score. $$z = \frac{\sum x - \text{ET}}{\text{SE}} $$
* **Objectives:** 
  * Calculate standard-normal probabilities using [online tool](https://chadworley.github.io/sn.html){target="_blank"}.
* **Agenda:** 
  * [Standard-normal probability practice problems](https://chadworley.github.io/precalculus/unit_01_stats/week_01/003_z_prob/outcanvas/003_shared1.html){target="_blank"}
* **Homework:**
  * Finish practice problems
  
### Friday Aug 25

* **Entrance**
  * [/precalculus/unit_01_stats/week_01/ET_04/ET_04.html](/precalculus/unit_01_stats/week_01/ET_04/ET_04.html){target="_blank"}
* **Objectives:**
  * Calculate $p$-values using [online tool](https://chadworley.github.io/sn.html){target="_blank"}.
* **Agenda:** 
  * [$p$-value practice problems](https://chadworley.github.io/precalculus/unit_01_stats/week_01/004_p-value/outcanvas/004_shared1.html){target="_blank"}
* **Homework:**
  * Finish practice problems

## Week 2: Aug 28 - Sep 1

### Monday Aug 28

* Entrance
  * Without referencing anything but your own thoughts, express your understanding of a p-value.
* Objectives
  * Learn to calculate standard deviation. 
* Agenda
  * [Standard deviation](https://chadworley.github.io/precalculus/unit_01_stats/week_02/005_sd/outcanvas/005_shared_questions1.html)
* Homework
  * Finish the questions
  
### Tuesday Aug 29

* Objectives
  * Use a spreadsheet to calculate standard deviation
* Agenda
  * [Standard deviation project](https://chadworley.github.io/precalculus/unit_01_stats/week_02/006_sd_project/006_sd_proj.pdf){target="_blank"}
* Homework
  * Finish project

### Wednesday Aug 30

* Objective
  * Use technology to repeatedly simulate a model.
  * Visualize the standard error of a mean decreasing as sample size increases.
  * Graph overlapping line plots.
* Agenda
  * [Running-average project](https://chadworley.github.io/precalculus/unit_01_stats/week_02/007_running_ave_proj/007_running_ave_proj.pdf){target="_blank"}
* Homework
  * Finish project

### Thursday Aug 31

* Objective
  * Calculate probabilities of [sampling distributions](https://en.wikipedia.org/wiki/Sampling_distribution){target="_blank"} of averages and totals.
* Agenda
  * [Calculate CLT problems](https://chadworley.github.io/precalculus/unit_01_stats/week_02/008_prob_of_ave_CLT/outcanvas/008_shared1.html){target="_blank"}
* Homework
  * Finish problems

### Friday Sep 01

* Agenda
  * Finish problems and projects from earlier classes.
  
## Week 3: Sep 04 - Sep 08

### Mon Sep 04

* Holiday

### Tue Sep 05

* I-ready testing

### Wed Sep 06

* I-ready testing

### Thu Sep 07

* I-ready testing

### Fri Sep 08

* Objective
  * Calculate confidence intervals.
* Agenda
  * [Confidence-interval problems](https://chadworley.github.io/precalculus/unit_01_stats/week_03/009_confidence_intervals_and_histogram_shapes/outcanvas/009__shared1.html){target="_blank"}
* Homework
  * Finish problems.

## Week 4: Sep 11 - Sep 15

### Monday Sep 11

* Objectives
  * Calculate and interpret confidence intervals.
* Agenda
  * [Confidence-interval problems](https://chadworley.github.io/precalculus/unit_01_stats/week_03/009_confidence_intervals_and_histogram_shapes/outcanvas/009__shared1.html){target="_blank"}
* Homework
  * Finish the questions
  
### Tuesday Sep 12

* Objectives
  * Calculate and interpret confidence intervals.
* Agenda
  * [Confidence-interval problems](https://chadworley.github.io/precalculus/unit_01_stats/week_03/009_confidence_intervals_and_histogram_shapes/outcanvas/009__shared1.html){target="_blank"}
* Homework
  * Finish the questions
  
### Wednesday Sep 13

* Objectives
  * Calculate and interpret confidence intervals.
  * Start considering the 2-week project.
* Agenda
  * [Confidence-interval problems](https://chadworley.github.io/precalculus/unit_01_stats/week_03/009_confidence_intervals_and_histogram_shapes/outcanvas/009__shared1.html){target="_blank"}
  * [Project seeds](https://chadworley.github.io/precalculus/unit_01_stats/week_02/project_seeds.pdf){target="_blank"}
  * One-on-one discussions regarding adding personal flair to the two-week-long stats project.
* Homework
  * Finish the questions

### Thursday Sep 14

* Objectives
  * Develop understanding of probability, using AND, OR, and GIVEN.
  * Solve a simple problem that implicitly uses Bayes' Theorem.
  * Continue considering the 2-week project.
* Agenda
  * [Probability problems](https://chadworley.github.io/precalculus/unit_01_stats/week_04/010_probability/010_prob_shared1.html){target="_blank"}
  * [Project seeds](https://chadworley.github.io/precalculus/unit_01_stats/week_02/project_seeds.pdf){target="_blank"}
  * One-on-one discussions regarding adding personal flair to the two-week-long stats project.
* Homework
  * None
  
### Friday Sep 15

* Objectives
  * Develop understanding of probability, using AND, OR, and GIVEN.
  * Solve a simple problem that implicitly uses Bayes' Theorem.
  * Continue considering the 2-week project.
* Agenda
  * [Probability problems](https://chadworley.github.io/precalculus/unit_01_stats/week_04/010_probability/010_prob_shared1.html){target="_blank"}
  * [Project seeds](https://chadworley.github.io/precalculus/unit_01_stats/week_02/project_seeds.pdf){target="_blank"}
  * One-on-one discussions regarding adding personal flair to the two-week-long stats project.
* Homework
  * None




## Week 05: Sep 18 - Sep 22

We continue with concepts in probability. We calculate number of [permutations](https://en.wikipedia.org/wiki/Permutation) and [combinations](https://en.wikipedia.org/wiki/Combination). We also hint at [Bayes' Theorem](https://en.wikipedia.org/wiki/Bayes%27_theorem) and develop an understanding of the [binomial distribution](https://en.wikipedia.org/wiki/Binomial_distribution).

* [More probability problems canvas questions](https://chadworley.github.io/precalculus/unit_01_stats/week_05/011_shared1.html)
* [Binomial Distribution Lecture](https://chadworley.github.io/precalculus/unit_01_stats/week_05/lecture.html#1) (Sep 19th)
* Learning outcomes:
  * S.CP.B.9: Use permutations and combinations to compute probabilities of compound events and solve problems.
  * S.MD.A.2: Calculate the expected value of a random variable; interpret it as the mean of the probability distribution.
  * S.MD.A.3: Develop a probability distribution for a random variable defined for a sample space in which theoretical probabilities can be calculated; find the expected value.

## Week 06: Sep 25 - Sep 29

* [Stats project](https://chadworley.github.io/precalculus/unit_01_stats/stats_project/Research_Project.pdf)

## Week 07: Oct 02 - Oct 06

* [Textbook chapter 1](https://openstax.org/books/precalculus-2e/pages/1-introduction-to-functions)
* [Function intro canvas questions](https://chadworley.github.io/precalculus/unit_02_functions/01_functions/012_shared1.html)
* Learning outcomes:
  * F.IF.A: Understand the concept of a function and use function notation.
  * F.IF.A.1: Understand that a function from one set (called the domain) to another set (called the range) assigns to each element of the domain exactly one element of the range. If $f$ is a function and $x$ is an element of its domain, then $f(x)$ denotes the output of $f$ corresponding to the input $x$. The graph of $f$ is the graph of the equation $y = f(x)$.
  * F.IF.A.2: Use function notation, evaluate functions for inputs in their domains, and interpret statements that use function notation in terms of a context.
  * F.IF.B.5: Relate the domain of a function to its graph and, where applicable, to the quantitative relationship it describes.
  * F.IF.B.6: Calculate and interpret the average rate of change of a function (presented symbolically or as a table) over a specified interval. Estimate the rate of change from a graph.

## Week 08: Oct 09 - Oct 13

* [Textbook chapter 1](https://openstax.org/books/precalculus-2e/pages/1-introduction-to-functions)
* [More functions canvas questions](https://chadworley.github.io/precalculus/unit_02_functions/02_functions_cont/013_shared1.html)
* Learning outcomes:
  * F.IF.B: Interpret functions that arise in applications in terms of the context (linear, quadratic, exponential, rational, polynomial, square root, cube root, trigonometric, logarithmic).
  

## Week 09: Oct 16 - Oct 20

* [Textbook chapter 1](https://openstax.org/books/precalculus-2e/pages/1-introduction-to-functions)
* [Even more functions canvas questions](https://chadworley.github.io/precalculus/unit_02_functions/03_functions_galore/014_shared1.html)
* [Sine slope mini project](https://chadworley.github.io/precalculus/unit_02_functions/03_functions_galore/Sine_slope_mini_project.pdf) (Due Oct 23)

## Week 10: Oct 23 - Oct 27

* [Textbook chapter 2](https://openstax.org/books/precalculus-2e/pages/2-introduction-to-linear-functions)
* [Linear functions canvas questions](https://chadworley.github.io/precalculus/unit_3_linear/015_linear_shared1.html)

## Week 11: Oct 30 - Nov 03

* [Textbook chapter 3](https://openstax.org/books/precalculus-2e/pages/3-introduction-to-polynomial-and-rational-functions)
* [Polynomials, rationals, complex numbers canvas questions](https://chadworley.github.io/precalculus/016_polynomial_and_rational/016_shared1.html)

## Week 12: Nov 06 - Nov 10

* [Textbook chapter 4](https://openstax.org/books/precalculus-2e/pages/4-introduction-to-exponential-and-logarithmic-functions)
* [Exponential and logarithmic canvas questions](https://chadworley.github.io/precalculus/017_geometric_exp_log/017_shared1.html)

## Week 13: Nov 13 - Nov 17

* [Textbook chapter 4](https://openstax.org/books/precalculus-2e/pages/4-introduction-to-exponential-and-logarithmic-functions)
* [Geometric series and fractals canvas questions](https://chadworley.github.io/precalculus/018_geom_series/018_shared1.html)

## Week 14: Nov 20 - Nov 24 (Thanksgiving)

* [Textbook chapter 4](https://openstax.org/books/precalculus-2e/pages/4-introduction-to-exponential-and-logarithmic-functions)
* [Exponential and logarithmic identities canvas questions](https://chadworley.github.io/precalculus/019_exp_log_identities/019_shared1.html)

## Week 15: Nov 27 - Dec 01

* [Exp, log, chaos, and Euler's method  canvas questions](https://chadworley.github.io/precalculus/020_exp_log_graphs_and_inverses/020_shared1.html)
* [Wikipedia: Euler's method](https://en.wikipedia.org/wiki/Euler_method)

## Week 16: Dec 04 - Dec 08

* Presentation of art projects
* In-class review: [Regents Algebra 2](https://www.nysedregents.org/algebratwo/) minus trigonometry.
* [Canvas problems](https://chadworley.github.io/precalculus/021_review/021_shared1.html)

## Week 17: Dec 11 - Dec 15

Most of this week will be taken by the interim. Since Thursday is a field-trip day, the interim will happen Tue, Wed, and Fri. The few students on Thursday will have a make-up day.

* [Finish review problems](https://chadworley.github.io/precalculus/021_review/021_shared1.html)
* Interims

### Monday Dec 11

Review various topics.

* Entrance ticket: [Algebra of framing with uniform mat](https://chadworley.github.io/precalculus/021_review/021_shared1.html#Q13v1)
* Work through examples:
  * [Rationalize denominator of complex fraction](https://chadworley.github.io/precalculus/021_review/021_shared1.html#Q9v1)
  * [Find pH from [H$^+$] and log table](https://chadworley.github.io/precalculus/021_review/021_shared1.html#Q10v1)
  * [Probabilities from Venn diagram](https://chadworley.github.io/precalculus/021_review/021_shared1.html#Q12v1)
* Students work through their versions on Canvas.


