```{r,echo=F}

```

Question
========

```{r,fig.dim=c(8,8),echo=F}
library(latex2exp)
par(mar=c(0,0,0,0),pty="s")
plot(0,0,type="n",xlim=c(-1.3,1.3),ylim=c(-1.3,1.3),axes=F,ann=F)
arrows(-1.05,0,1.05,0,0.08,12,3)
arrows(0,-1.05,0,1.05,0.08,12,3)
th = seq(0,2*pi,length.out=120)
lines(cos(th),sin(th))
th12 = seq(0,2*pi,length.out=25)
for(t in th12){
  lines(c(0,cos(t)),c(0,sin(t)),lty=3,col="grey")
}
thsp = c(0,pi/6,pi/4,pi/3,pi/2,2*pi/3,3*pi/4,5*pi/6,pi,
         7*pi/6,5*pi/4,4*pi/3,3*pi/2,5*pi/3,7*pi/4,11*pi/6)

ts = c("0","\\frac{\\pi}{6}","\\frac{\\pi}{4}","\\frac{\\pi}{3}",
       "\\frac{\\pi}{2}","\\frac{2\\pi}{3}","\\frac{3\\pi}{4}",
       "\\frac{5\\pi}{6}","\\pi","\\frac{7\\pi}{6}","\\frac{5\\pi}{4}",
       "\\frac{4\\pi}{3}","\\frac{3\\pi}{2}","\\frac{5\\pi}{3}",
       "\\frac{7\\pi}{4}","\\frac{11\\pi}{6}","2\\pi")

xs = c("1","\\frac{\\sqrt{3}}{2}","\\frac{\\sqrt{2}}{2}","\\frac{1}{2}","0",
       "\\frac{-1}{2}","\\frac{-\\sqrt{2}}{2}","\\frac{-\\sqrt{3}}{2}","-1",
       "\\frac{-\\sqrt{3}}{2}","\\frac{-\\sqrt{2}}{2}","\\frac{-1}{2}","0",
       "\\frac{1}{2}","\\frac{\\sqrt{2}}{2}","\\frac{\\sqrt{3}}{2}","1")

ys = c("0","\\frac{1}{2}","\\frac{\\sqrt{2}}{2}","\\frac{\\sqrt{3}}{2}","1",
       "\\frac{\\sqrt{3}}{2}","\\frac{\\sqrt{2}}{2}","\\frac{1}{2}","0",
       "\\frac{-1}{2}","\\frac{-\\sqrt{2}}{2}","\\frac{-\\sqrt{3}}{2}","-1",
       "\\frac{-\\sqrt{3}}{2}","\\frac{-\\sqrt{2}}{2}","\\frac{-1}{2}","0")

for(i in 1:length(thsp)){
  t = thsp[i]
  lines(c(0,cos(t)),c(0,sin(t)),col="red")
  points(cos(t),sin(t),pch=20,col="red")
  text(1.2*cos(t),1.2*sin(t),TeX(paste0("$\\left(",xs[i],",",ys[i],"\\right)$",collapse="")),cex=0.8)
}
```





Solution
========



Meta-information
============
extype: num
exsolution: 1
exname: srt
extol: 0.01