## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file syllabus_precalc_23-24.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_140 = Integer(140); _sage_const_65 = Integer(65); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_70 = Integer(70); _sage_const_73p33 = RealNumber('73.33'); _sage_const_76p66 = RealNumber('76.66'); _sage_const_80 = Integer(80); _sage_const_83p33 = RealNumber('83.33'); _sage_const_86p66 = RealNumber('86.66'); _sage_const_90 = Integer(90); _sage_const_93p33 = RealNumber('93.33'); _sage_const_96p66 = RealNumber('96.66'); _sage_const_2 = Integer(2); _sage_const_67 = Integer(67); _sage_const_152 = Integer(152); _sage_const_169 = Integer(169)## This file (syllabus_precalc_23-24.sagetex.sage) was *autogenerated* from syllabus_precalc_23-24.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('syllabus_precalc_23-24', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_140 
_st_.blockbegin()
try:
 g = Graphics()
 g += line([(_sage_const_65 ,_sage_const_0 ),(_sage_const_100 ,_sage_const_0 )],axes=False,xmin=_sage_const_65 ,xmax=_sage_const_100 ,ymin=-_sage_const_3 ,ymax=_sage_const_3 ,aspect_ratio=_sage_const_1 )
 nums = [_sage_const_70 ,_sage_const_73p33 ,_sage_const_76p66 ,_sage_const_80 ,_sage_const_83p33 ,_sage_const_86p66 ,_sage_const_90 ,_sage_const_93p33 ,_sage_const_96p66 ,_sage_const_100 ]
 lets = ["C-","C","C+","B-","B","B+","A-","A","A+"]
 for i in nums:
     g += line([(i,-_sage_const_1 ),(i,_sage_const_3 )])
     g += text(round(i,_sage_const_2 ),(i,-_sage_const_2 ))
 for i in range(len(nums)-_sage_const_1 ):
     pos = (nums[i]+nums[i+_sage_const_1 ])/_sage_const_2 
     g += text(lets[i],(pos,_sage_const_1 ))
 g += text("no credit",(_sage_const_67 ,_sage_const_1 ))
except:
 _st_.goboom(_sage_const_152 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_169 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=g,fig_tight=True)
except:
 _st_.goboom(_sage_const_169 )
_st_.endofdoc()

