---
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=1in
urlcolor: blue
---

```{r,echo=F}
dim = 4
```

# Notes: Parent Function Transformations

1. Make an accurate graph, and locate the features (using interval notation).

$$y~=~3\sqrt{\frac{x+4}{2}}-5$$

\vfill

```{r,echo=F,fig.dim=c(dim,dim)}
mkgrid = function(){
    par(mar=c(0,0,0,0),oma=c(0,0,0,0),pty="s")
    lim = 10
    plot(0,0,"n",xlim=c(-lim*1.15,lim*1.15),ylim=c(-lim*1.2,lim*1.2),axes=F,ann=F)
    for(i in -lim:lim){
        lines(c(-lim,lim),c(i,i),col="grey",lwd=0.3)
        lines(c(i,i),c(-lim,lim),col="grey",lwd=0.3)
    }
    for(i in seq(-lim,lim,5)){
        lines(c(-lim,lim),c(i,i),col="darkgrey",lwd=0.8)
        lines(c(i,i),c(-lim,lim),col="darkgrey",lwd=0.8)
    }
    arrows(-lim*1.1,0,lim*1.1,0,0.1,15,3,lwd=1.5)
    arrows(0,-lim*1.1,0,lim*1.1,0.1,15,3,lwd=1.5)
    text(5,-0.5,"5",col="darkgrey",cex=0.6)
    text(10,-0.5,"10",col="darkgrey",cex=0.6)
    text(-5,-0.5,"-5",col="darkgrey",cex=0.6)
    text(-10,-0.5,"-10",col="darkgrey",cex=0.6)
    for(i in c(-10,-5,5,10)){
        polygon(c(i-0.4,i-0.4,i+0.4,i+0.4),c(-0.1,-0.9,-0.9,-0.1),col="white",border = NA)
        text(i,-0.5,i,col="black",cex=0.6)
        polygon(c(-0.1,-0.95,-0.95,-0.1),c(i-0.4,i-0.4,i+0.4,i+0.4),col="white",border = NA)
        text(-0.5,i,i,col="black",cex=0.6)
    }
}
mkgrid()
```


\begin{tabular}{|m{1in}|m{5in}|}\hline
Feature & Where \\ \hline \hline
Domain &  \\ [2em]  \hline
Range &  \\ [2em]  \hline
Positive &  \\  [2em]  \hline
Negative &   \\ [2em]  \hline
Increasing & \\ [2em]  \hline
Decreasing &  \\ [2em]  \hline
Asymptote(s) &  \\ [2em]  \hline
\end{tabular}







