---
output: pdf_document
geometry: "left=2cm,right=2cm,top=2cm,bottom=2cm"
urlcolor: blue
---
\raggedleft 
\makebox[0.5\textwidth]{\large Name:\enspace\hrulefill}

\raggedright

# Slope function of sine curve

We will:

* measure the slope, $m$, of a sine curve at multiple values of $x$
* make a table of pairs of $x$ and $m(x)$
* plot the slope function: $y=m(x)$
* determine an algebraic function that matches those pairs
* summarize, rephrase, and interpret

## Set up Desmos to find slope

1. Open [Desmos graphing calculator](https://www.desmos.com/calculator){target="_blank"}
2. To draw sine function, enter expression $$f(x) = \sin(x)$$
3. To draw a point at $x=a$, enter expression $$(a,\,f(a))$$ and make slider for $a$.
4. To draw a point at $x=a+h$, enter expression $$(a+h,\,f(a+h))$$ and make slider for $h$.
5. To calculate the slope between points, enter expression $$m=\frac{f(a+h)-f(a)}{h}$$
6. To draw the line through points (using [point-slope form](https://en.wikipedia.org/wiki/Linear_equation#Point%E2%80%93slope_form_or_Point-gradient_form){target="_blank"}), enter expression $$y=m(x-a)+f(a)$$
7. Tinker with $a$ and $h$ to make sure you understand their significance.

## Tinker with $h$ while $a=1$

8. Set $a$ equal to 1.
9. Vary $h$ between the values 0.1, 0.01, 0.001, and 0.0001 while recording $m$. Fill out the table below.


\begin{center}
    \begin{tabular}{|p{3cm}|p{3cm}|p{3cm}|}
        \hline
        $a$ & $h$ & $m$  \\ \hline \hline
        \vspace{0.1cm} 1 & \vspace{0.1cm} 0.1 \vspace{0.1cm} &  \\ \hline
        \vspace{0.1cm} 1 & \vspace{0.1cm} 0.01 \vspace{0.1cm} &  \\ \hline
        \vspace{0.1cm} 1 & \vspace{0.1cm} 0.001 \vspace{0.1cm} &  \\ \hline
        \vspace{0.1cm} 1 & \vspace{0.1cm} 0.0001 \vspace{0.1cm} &  \\ \hline
    \end{tabular}
\end{center}

10. What did you just do, and what did you just find? Use your words (and maybe a sketch) to interpret the above table.

\newpage

## Tinker with $a$ while $h\le 0.1$

11. Set $h$ equal to 0.1 or smaller. Its exact value should not matter much.
12. Let $a$ vary between 0 and 6.5 with a step size of $\frac{1}{2}$. Record the slopes.


\begin{tabular}{|p{3cm}|p{3cm}|}
    \hline
    $a$ & $m(a)$  \\ \hline \hline
    \vspace{0.1cm} 0 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 0.5 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 1 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 1.5 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 2 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 2.5 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 3 \vspace{0.1cm} &  \\ \hline
\end{tabular}
\hspace{2cm}
\begin{tabular}{|p{3cm}|p{3cm}|}
    \hline
    $a$ & $m(a)$  \\ \hline \hline
    \vspace{0.1cm} 3.5 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 4 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 4.5 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 5 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 5.5 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 6 \vspace{0.1cm} &  \\ \hline
    \vspace{0.1cm} 6.5 \vspace{0.1cm} &  \\ \hline
\end{tabular}

13. Plot those ordered pairs below.

\vspace{-1cm}
```{r,echo=FALSE,results="asis",fig.dim=c(5,4)}
library(latex2exp)
plot(0,0,type="n",xlim=c(0,7),ylim=c(-2,2),ylab="m(a)",xlab="a")
for(j in seq(-10,10,1)){
  abline(h=j,lty=1,lwd=0.5)
  abline(v=j,lty=1,lwd=0.5)
}
for(j in seq(-10,10,0.2)){
  abline(h=j,lty=3,lwd=0.5)
  abline(v=j,lty=3,lwd=0.5)
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)
```
\

14. Consider the parent functions. Do any of them resemble the plot above?

\vfill

15. Rephrase. What did you do? What did you learn? How would you explain this?

\vfill


        
