```{r,echo=F,warning=F}
twoangs = sample(seq(0.5,5.5,0.1),2)
a = twoangs[1]
b = twoangs[2]


```

Question
========

Some equations are true for ANY substitutions of numbers for the variables (see [universal quantification](https://en.wikipedia.org/wiki/Universal_quantification)). Other equations are only true for SOME substitutions of numbers (see [existential quantification](https://en.wikipedia.org/wiki/Existential_quantification)).

When an equation is true for ANY substitution, we call it an [identity](https://en.wikipedia.org/wiki/Identity_(mathematics)). If you want to be fancy, you might put a "for all" symbol ($\forall$) nearby, or use a triple equals ($\equiv$) to reinforce that an equation is an identity.

An essential identity in trigonometry is the [angle sum identity](https://en.wikipedia.org/wiki/List_of_trigonometric_identities#Angle_sum_and_difference_identities). We already saw how to derive the ratios of $30-60-90$ and $45-45-90$ triangles, but the angle-sum identity (indirectly) allows us to find exact ratios for a LOT of other right triangles.

The angle-sum and angle-difference identities are true for all values of $\alpha$ and $\beta$:

$$\sin(\alpha+\beta) ~\equiv~ \sin(\alpha)\cos(\beta)+\cos(\alpha)\sin(\beta)$$
$$\cos(\alpha+\beta) ~\equiv~ \cos(\alpha)\cos(\beta)-\sin(\alpha)\sin(\beta)$$
$$\sin(\alpha-\beta) ~\equiv~ \sin(\alpha)\cos(\beta)-\cos(\alpha)\sin(\beta)$$
$$\cos(\alpha-\beta) ~\equiv~ \cos(\alpha)\cos(\beta)+\sin(\alpha)\sin(\beta)$$


Solution
========


Meta-information
============
extype: num
exsolution: 1
exname: angle_sum
extol: 0.01