```{r data generation, echo = FALSE, results = "hide",warning=FALSE}
library(latex2exp)
while(T){
    r = round(runif(1,2,9),1)
    theta = round(runif(1,1,5),1)
    L = theta*r
    if(round(L,1)==L && abs(theta-pi)>0.2 && theta%%1!=0 && r%%1!=0 && L%%1!=0){break}
}

rr = r
tt = theta
ll = L

vi = sample(1:3,1)
if(vi==1){
    rr = "r"
    v = rr
    a = r
} else if(vi==2){
    tt = "\\theta"
    v = tt
    a = theta
} else {
    ll = "L"
    v = ll
    a = L
}

```

Question
========

The circle below has a radius equal to $`r rr`$ meters. The central angle equals $`r tt`$ radians. The subtended arc has a length of $`r ll`$ meters.

```{r,echo=F,fig.dim=c(4,4)}
par(mar=c(0,0,0,0),pty="s")
th = seq(0,2*pi,pi/300)
plot(cos(th),sin(th),"l",axes=F,ann=F,xlim=c(-1.2,1.2),ylim=c(-1.2,1.2))
lines(c(cos(theta),0),c(sin(theta),0),col="black")
lines(c(0,1),c(0,0),col="purple",lwd=3)
points(0,0,pch=20,col="purple")
text(0.5,-0.07,TeX(paste0("$",rr,"$")),col="purple")
th2 = seq(0,theta,pi/300)
lines(0.2*cos(th2),0.2*sin(th2),col="blue",lwd=3)
n = length(th2)
arrows(0.2*cos(th2[n-1]),0.2*sin(th2[n-1]),0.2*cos(th2[n]),0.2*sin(th2[n]),0.07,30,2,"blue",lwd=3)
text(0.3*cos(theta/2),0.3*sin(theta/2),TeX(paste0("$",tt,"$")),col="blue")
lines(cos(th2),sin(th2),col="red",lwd=3)
text(1.1*cos(theta/2),1.1*sin(theta/2),TeX(paste0("$",ll,"$")),col="red")
```
\

Find $`r v`$.

Solution
========

See [circular arcs](https://en.wikipedia.org/wiki/Circular_arc).

$$L~=~r \theta$$


Meta-information
============
extype: num
exsolution: `r a`
exname: r_theta_L_get_unknown