---
title: "Syllabus: Math Literacy"
author: "Mr. Worley"
output: html_document
---


# Course Overview

* Math Literacy
* Mr. Chad Worley
* chad.worley@bartcharter.org

# Course Description

Uncover the hidden beauty and power of mathematics as we journey through fascinating branches you won't find anywhere else in high school. Your learning will come alive through captivating, student-driven projects that span the breadth of mathematical inquiry. Past projects have included Code-Cracking, complex origami models, and statistical research into student interests. Math Literacy is more than just a class; it's an adventure in mathematical discovery. Our goal is to empower you with unwavering math confidence, equip you with the skills to confidently tackle any mathematical challenge you encounter in life, and open your eyes to the boundless, beautiful, and often surprising realms of mathematics that lie beyond the standard curriculum. Get ready to think, create, and explore like never before! Any student can take this course; students who are not planning on degrees in STEM may find this course better fits their interests and goals. This course does not prevent any student from taking further math courses in college.  

# Grade Categories and Percentages

* Classwork: 50%
    * Unfinished classwork becomes homework
* Assessments: 40%
* Work Habits: 10%
    * Quiet during lecture
    * Focus during practice
    * Collaborative during group work
    * Effort

# Materials

Every day you should have:

* A chromebook
* A writing utensil
* Blank paper (I will try to keep a stack of scratch paper in room)

# Handbook

* [https://www.bartcharter.org/apps/pages/Student-Handbook](https://www.bartcharter.org/apps/pages/Student-Handbook)


# Statements of harm/abuse

* Any statement of intent to do harm (to self or others) will be immediately brought to a professional's attention.
* Any statement of abuse will be immediately brought to a professional's attention.




