---
header-includes:
   - \usepackage{array}
   - \usepackage{color}
output: pdf_document
params:
    rseed: 1
    showsol: false
    titex: ""
urlcolor: blue
---


```{r,echo=F}
set.seed(params$rseed)
library(latex2exp)
if(params$showsol){
    solstart = ""
    solend = "\\vfill"
    hidesolstart = "<!---"
    hidesolend = "-->"
    showsol = T
} else {
    solstart = "<!---"
    solend = "-->"
    hidesolstart = ""
    hidesolend = ""
    showsol = F
}
```

Name: \hspace{4in} Date: \hfill \vspace{3pt} \hrule

## u13 A Story of Special Right Triangles

1. The first special right triangle has a hypotenuse of length 1 and is isosceles. Draw a diagram, and label the sides, using a variable for the non-obvious lengths.

\vspace{4in}

2. How large are the angles, from least to greatest, in the triangle you drew above? Answer in both degrees and radians.

\vspace{1in}

3. Use the Pythagorean Theorem to find the unknown lengths. Please answer in exact (and simplified) form.

\newpage

## u13 A Story of Special Right Triangles

4. The second special right triangle is formed by splitting an equilateral triangle in half. The right triangle should have a hypotenuse of length 1. Draw the equilateral triangle with dashed lines; draw the right triangle with solid lines; label the side lengths of the right triangle, using a variable for the non-obvious length.

\vspace{4in}

5. How large are the angles, from least to greatest, of the right triangle? Answer in both degrees and radians.

\vspace{1in}

6. Use the Pythagorean Theorem to find the length of the unknown side. Please answer in exact (and simplified) form.






