---
output: pdf_document
params:
    rseed: 0
    showsol: false
    useseed: false
    titex: "PCW_09_23: Graphing Function Transformations"
urlcolor: blue
---

```{r,echo=F}
if(params$useseed){
    set.seed(params$rseed)
}
```

Name: \hspace{4in} Date: \hfill \vspace{3pt} \hrule

# `r params$titex` (version `r params$rseed`)

```{r,echo=F}
exp_types = sample(1:8,4)
et1 = exp_types[1]
et2 = exp_types[2]
exp_frames = c("M\\left(x+A\\right)",
               "Mx+A",
               "M\\left(x-A\\right)",
               "Mx-A",
               "\\frac{x+A}{M}",
               "\\frac{x}{M}+A",
               "\\frac{x-A}{M}",
               "\\frac{x}{M}-A")

exp_frames2 = c("M\\cdot \\left(x+A\\right)",
               "M\\cdot x+A",
               "M\\cdot \\left(x-A\\right)",
               "M\\cdot x-A",
               "\\frac{x+A}{M}",
               "\\frac{x}{M}+A",
               "\\frac{x-A}{M}",
               "\\frac{x}{M}-A")

funcs = list(function(x,A,M){M*(x+A)},
             function(x,A,M){M*x+A},
             function(x,A,M){M*(x-A)},
             function(x,A,M){M*x-A},
             function(x,A,M){(x+A)/M},
             function(x,A,M){x/M+A},
             function(x,A,M){(x-A)/M},
             function(x,A,M){x/M-A}
             )
while(T){
    mults = sample(c(2:3),2)
    Mx = mults[1]
    My = mults[2]
    xspace1 = 1 #sample(1:3,1)
    yspace1 = 1 #sample(1:3,1)
    xspace2 = xspace1*mults[1]
    yspace2 = yspace1*mults[2]
    xbig = sort(sample(-floor(20/xspace2):floor(20/xspace2),5))*xspace2+sample(0:(xspace2-1),1)*sample(c(-1,1),1)
    ybig = sample(-floor(20/yspace2):floor(20/yspace2),5)*yspace2+sample(0:(yspace2-1),1)*sample(c(-1,1),1)
    shifts = sample(5:9,2)
    Ax = shifts[1]
    Ay = shifts[2]
    if(et1<5){
        xsmall = funcs[[9-et1]](xbig,Ax,Mx)
        x1 = xbig
        x2 = xsmall
    } else {
        xsmall = funcs[[et1]](xbig,Ax,Mx)
        x1 = xsmall
        x2 = xbig
    }
    if(et2<5){
        ysmall = funcs[[9-et2]](ybig,Ay,My)
        y1 = ysmall
        y2 = ybig
    } else {
        ysmall = funcs[[et2]](ybig,Ay,My)
        y1 = ybig
        y2 = ysmall
    }
    alldem = c(x1,x2,y1,y2)
    # m11 = (y1[2]-y1[1])/(x1[2]-x1[1])
    # m12 = (y1[3]-y1[2])/(x1[3]-x1[2])
    # m13 = (y1[4]-y1[3])/(x1[4]-x1[3])
    m1 = diff(y1)/diff(x1)
    th1 = atan(m1)
    dth1 = diff(th1)
    m2 = diff(y2)/diff(x2)
    th2 = atan(m2)
    dth2 = diff(th2)
    if(min(alldem)>=-20 && max(alldem)<=20 && sum(alldem%%1==0)==length(alldem) &&
       min(alldem)<0 && max(alldem)>0 && 
       min(abs(dth1)) > pi/12 && min(abs(dth2)) > pi/12 && 
       min(x1)<0 && max(x1)>0 && 
       min(y1)<0 && max(y1)>0 && 
       min(x2)<0 && max(x2)>0 && 
       min(y2)<0 && max(y2)>0 ){break}
}


exp1 = exp_frames2[et2]
exp1 = gsub("x","f{\\left[X\\right]}",exp1,fixed=T)
exp1 = gsub("A",Ay,exp1,fixed=T)
exp1 = gsub("M",My,exp1,fixed=T)
exp1 = gsub("X",exp_frames[et1],exp1,fixed=T)
exp1 = gsub("A",Ax,exp1,fixed=T)
exp1 = gsub("M",Mx,exp1,fixed=T)

```

1. Curve $y=f[x]$ is plotted below.

```{r,echo=F,fig.dim=c(6,6)}
par(mar=c(3,3,0,0),oma=c(0,0,0,0),pty="s")
plot(0,0,"n",xlim=c(-20,20),ylim=c(-20,20),axes=F,ann=F)
for(i in -20:20){
    lines(c(i,i),c(-20,20),lwd=0.4)
    lines(c(-20,20),c(i,i),lwd=0.4)
}
for(i in seq(-20,20,5)){
    lines(c(i,i),c(-20,20),lwd=0.8)
    lines(c(-20,20),c(i,i),lwd=0.8)
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)
# axis(1,line=0)
# axis(2,line=0)
# mtext("x",1,line=0.5,at=17.5)
# mtext("y",2,line=0.5,at=17.5)
lines(x1,y1,col="blue",lwd=3)
points(x1,y1,col="blue",pch=19,cex=0.8)

for(i in seq(5,20,5)){
    text(i,0,i,cex=0.5,adj=c(0.5,1.5))
    text(-i,0,-i,cex=0.5,adj=c(0.5,1.5))
    text(0,i,i,cex=0.5,adj=c(1.2,0.5))
    text(0,-i,-i,cex=0.5,adj=c(1.2,0.5))
}

text(20,0,"x",adj=c(-0.8,1.1))
text(0,20,"y",adj=c(1.1,-0.8))

if(params$showsol==T){
    lines(x2,y2,col="red",lwd=3)
    points(x2,y2,col="red",pch=19,cex=0.8)
}


```


On the same plane, please draw the curve represented by the equation below:

$$y=`r exp1`$$


\newpage



# `r params$titex` (version `r params$rseed`)

```{r,echo=F}
et1 = 9-exp_types[1]
et2 = 9-exp_types[2]
exp_frames = c("M\\left(x+A\\right)",
               "Mx+A",
               "M\\left(x-A\\right)",
               "Mx-A",
               "\\frac{x+A}{M}",
               "\\frac{x}{M}+A",
               "\\frac{x-A}{M}",
               "\\frac{x}{M}-A")

exp_frames2 = c("M\\cdot \\left(x+A\\right)",
               "M\\cdot x+A",
               "M\\cdot \\left(x-A\\right)",
               "M\\cdot x-A",
               "\\frac{x+A}{M}",
               "\\frac{x}{M}+A",
               "\\frac{x-A}{M}",
               "\\frac{x}{M}-A")

funcs = list(function(x,A,M){M*(x+A)},
             function(x,A,M){M*x+A},
             function(x,A,M){M*(x-A)},
             function(x,A,M){M*x-A},
             function(x,A,M){(x+A)/M},
             function(x,A,M){x/M+A},
             function(x,A,M){(x-A)/M},
             function(x,A,M){x/M-A}
             )
while(T){
    mults = sample(c(2:3),2)
    Mx = mults[1]
    My = mults[2]
    xspace1 = 1 #sample(1:3,1)
    yspace1 = 1 #sample(1:3,1)
    xspace2 = xspace1*mults[1]
    yspace2 = yspace1*mults[2]
    xbig = sort(sample(-floor(20/xspace2):floor(20/xspace2),5))*xspace2+sample(0:(xspace2-1),1)*sample(c(-1,1),1)
    ybig = sample(-floor(20/yspace2):floor(20/yspace2),5)*yspace2+sample(0:(yspace2-1),1)*sample(c(-1,1),1)
    shifts = sample(5:9,2)
    Ax = shifts[1]
    Ay = shifts[2]
    if(et1<5){
        xsmall = funcs[[9-et1]](xbig,Ax,Mx)
        x1 = xbig
        x2 = xsmall
    } else {
        xsmall = funcs[[et1]](xbig,Ax,Mx)
        x1 = xsmall
        x2 = xbig
    }
    if(et2<5){
        ysmall = funcs[[9-et2]](ybig,Ay,My)
        y1 = ysmall
        y2 = ybig
    } else {
        ysmall = funcs[[et2]](ybig,Ay,My)
        y1 = ybig
        y2 = ysmall
    }
    alldem = c(x1,x2,y1,y2)
    # m11 = (y1[2]-y1[1])/(x1[2]-x1[1])
    # m12 = (y1[3]-y1[2])/(x1[3]-x1[2])
    # m13 = (y1[4]-y1[3])/(x1[4]-x1[3])
    m1 = diff(y1)/diff(x1)
    th1 = atan(m1)
    dth1 = diff(th1)
    m2 = diff(y2)/diff(x2)
    th2 = atan(m2)
    dth2 = diff(th2)
    if(min(alldem)>=-20 && max(alldem)<=20 && sum(alldem%%1==0)==length(alldem) &&
       min(alldem)<0 && max(alldem)>0 && 
       min(abs(dth1)) > pi/12 && min(abs(dth2)) > pi/12 && 
       min(x1)<0 && max(x1)>0 && 
       min(y1)<0 && max(y1)>0 && 
       min(x2)<0 && max(x2)>0 && 
       min(y2)<0 && max(y2)>0 ){break}
}


exp1 = exp_frames2[et2]
exp1 = gsub("x","f{\\left[X\\right]}",exp1,fixed=T)
exp1 = gsub("A",Ay,exp1,fixed=T)
exp1 = gsub("M",My,exp1,fixed=T)
exp1 = gsub("X",exp_frames[et1],exp1,fixed=T)
exp1 = gsub("A",Ax,exp1,fixed=T)
exp1 = gsub("M",Mx,exp1,fixed=T)

```

2. Curve $y=f[x]$ is plotted below.

```{r,echo=F,fig.dim=c(6,6)}
par(mar=c(3,3,0,0),oma=c(0,0,0,0),pty="s")
plot(0,0,"n",xlim=c(-20,20),ylim=c(-20,20),axes=F,ann=F)
for(i in -20:20){
    lines(c(i,i),c(-20,20),lwd=0.4)
    lines(c(-20,20),c(i,i),lwd=0.4)
}
for(i in seq(-20,20,5)){
    lines(c(i,i),c(-20,20),lwd=0.8)
    lines(c(-20,20),c(i,i),lwd=0.8)
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)
# axis(1,line=0)
# axis(2,line=0)
# mtext("x",1,line=0.5,at=17.5)
# mtext("y",2,line=0.5,at=17.5)
lines(x1,y1,col="blue",lwd=3)
points(x1,y1,col="blue",pch=19,cex=0.8)

for(i in seq(5,20,5)){
    text(i,0,i,cex=0.5,adj=c(0.5,1.5))
    text(-i,0,-i,cex=0.5,adj=c(0.5,1.5))
    text(0,i,i,cex=0.5,adj=c(1.2,0.5))
    text(0,-i,-i,cex=0.5,adj=c(1.2,0.5))
}

text(20,0,"x",adj=c(-0.8,1.1))
text(0,20,"y",adj=c(1.1,-0.8))

if(params$showsol==T){
    lines(x2,y2,col="red",lwd=3)
    points(x2,y2,col="red",pch=19,cex=0.8)
}


```


On the same plane, please draw the curve represented by the equation below:

$$y=`r exp1`$$



