---
title: "Wallpaper groups"
output: ioslides_presentation
---

## Wallpaper groups

**Have you ever noticed how patterns repeat in wallpaper?**  It's not just random – there's a hidden math behind it! Today, we're going to explore the secret world of **wallpaper groups**.

## Transformations

**Think of it like this:** Imagine you're designing a tile floor. You can move the tiles around in different ways:

* **Slide:**  Shifting the tile left, right, up, or down.
* **Flip:**  Turning the tile upside down or reflecting it like a mirror.
* **Rotate:**  Spinning the tile around a point. 

**It's amazing how different patterns can be created by combining just a few simple movements!**  This hidden math is everywhere in our world, from the patterns in nature to the designs we use every day. 

## The 17 wallpaper groups {.columns-2}

* p1
* pg
* pm
* cm
* p2
* pgg
* pmm
* cmm
* pmg
* p4
* p4m
* p4g
* p3
* p3m1
* p31m
* p6
* p6m

## Examples {.smaller}

Wikipedia has some good examples:

* [https://en.wikipedia.org/wiki/Wallpaper_group#The_seventeen_groups](https://en.wikipedia.org/wiki/Wallpaper_group#The_seventeen_groups)

## Tools

* [https://math.hws.edu/eck/js/symmetry/wallpaper.html](https://math.hws.edu/eck/js/symmetry/wallpaper.html)
* [https://eschersket.ch/](https://eschersket.ch/)


## Assignment

* Produce at least one "wallpaper" image for each of the 17 wallpaper groups.
    * All the wallpapers should feel connected. They can share stylistic elements. Or maybe they come together to tell a story. You will eventually write an overall project statement.
* For each wallpaper, produce an artist's statement. Each statement should include specifics.
    * What symmetries were imposed by the wallpaper group? (In your own words.)
    * How did you work with these symmetries to produce an interesting pattern?
    * How did the wallpaper fit into your overall theme?

## Presentation    

* Make a slideshow. I want 20 slides.
    * Title slide
    * Overall project statement
    * 17 slides, one for each wallpaper group. A short artist statement for each (on the side).
    * Conclusion slide. What thoughts do you want to leave off on with your audience?

