---
title: "mortgage"
author: "MrW"
output: html_document
---

A mortgage has principal $P$, interest rate $r$. Let functon $f$ represent the amount of debt remaining after $x$ months. We can define the function recursively.

$$f(x)~~=~~ \left(1+\frac{r}{12}\right)\cdot f(x-1)~-~ k$$

$$f(0)~=~ P$$

It'll be helpful to define the monthly scale factor $m$.

$$m~=~\left(1+\frac{r}{12}\right)$$


We can restate the recursive definition.

$$f(x)~~=~~ m\cdot f(x-1)~-~ k$$

$$f(0)~=~ P$$

Express the first few iterations to look for patterns. After some trail-and-error, I decided it would be helpful to expand all the expressions (getting rid of parentheses).

$$f(1)~=~mP-k$$
$$f(2)~=~m(mP-k)-k~=~m^2P-mk-k$$

$$f(3)~=~m(m^2P-mk-k)-k~=~m^3P-m^2k-mk-k$$

$$f(4)~=~m(m^3P-m^2k-mk-k)-k~=~m^4P-m^3k-m^2k-mk-k$$

Notice the geometric series. We can apply the [partial geometric series formula](https://chadworley.github.io/a2/u17/slides_sum_geometric/sum_geometric.html).

$$f(4)~=~ m^4P -k(1+m+m^2+m^3) ~=~ m^4P-k\frac{1-m^4}{1-m}$$

We can hope (and later verify) the pattern continues as we expect. We can now define the function explicitly.

$$f(x) ~=~ m^xP-\frac{k(1-m^x)}{1-m}$$

We might be interested in considering when the debt is reduced to 0. We can use $n$ to represent the number of months needed to pay off the loan.

Solve $f(n)=0$.

$$0 ~=~ m^nP-k\frac{1-m^n}{1-m}$$

$$\frac{k(1-m^n)}{1-m} ~=~ m^nP$$

$$\frac{k}{1-m} -\frac{km^n}{1-m} ~=~ m^nP$$

$$\frac{k}{1-m} ~=~ m^nP + \frac{km^n}{1-m} $$


$$\frac{k}{1-m} ~=~ m^n\left(P + \frac{k}{1-m}\right) $$


$$\frac{k}{1-m} ~=~ m^n\left(\frac{P-Pm+k}{1-m}\right) $$


$$\frac{k}{P-Pm+k} ~=~ m^n$$



$$\log\left(\frac{k}{P-Pm+k}\right) ~=~ n\log(m)$$


$$n~=~\log_m\left(\frac{k}{P-Pm+k}\right)$$

Remember: $m~=~1+\frac{r}{12}$ and $k=$ monthly payment and $P=$ Principal.


I guess I actually want to know $k$...

$$m^n~=~\frac{k}{P-Pm+k}$$


$$m^nP-m^{n+1}P+m^nk~=~k$$


$$m^nP-m^{n+1}P~=~k-m^nk$$

$$\frac{m^nP-m^{n+1}P}{1-m^n}~=~k$$

CAS

$$k=\frac{Pm^n(m-1)}{m^n-1}$$
