---
title: "Induction fail"
output: html_document
---

# Maximum regions when cutting a circle with $n$ lines.

* One line can split a circle into 2 regions.

```{r,echo=F,fig.dim=c(3,3)}
th=seq(0,2*pi,pi/20)
par(mar=c(0,0,0,0),pty="s")
plot(cos(th),sin(th),"l",xlim=c(-1,1),ylim=c(-1,1),ann=F,axes=F)
th2 = c(pi/8,9*pi/8)
lines(cos(th2),sin(th2))
```
\

* Two lines can split a circle into 4 regions.

```{r,echo=F,fig.dim=c(3,3)}
th=seq(0,2*pi,pi/20)
par(mar=c(0,0,0,0),pty="s")
plot(cos(th),sin(th),"l",xlim=c(-1,1),ylim=c(-1,1),ann=F,axes=F)
th3 = c(5*pi/8,12*pi/8)
lines(cos(th2),sin(th2))
lines(cos(th3),sin(th3))
```
\

* Three lines can split a circle into 7 regions.

```{r,echo=F,fig.dim=c(3,3)}
th=seq(0,2*pi,pi/20)
par(mar=c(0,0,0,0),pty="s")
plot(cos(th),sin(th),"l",xlim=c(-1,1),ylim=c(-1,1),ann=F,axes=F)
th4 = c(11*pi/8,2*pi/8)
lines(cos(th2),sin(th2))
lines(cos(th3),sin(th3))
lines(cos(th4),sin(th4))
```
\

* Four lines can split a circle into 11 regions.

```{r,echo=F,fig.dim=c(3,3)}
th=seq(0,2*pi,pi/20)
par(mar=c(0,0,0,0),pty="s")
plot(cos(th),sin(th),"l",xlim=c(-1,1),ylim=c(-1,1),ann=F,axes=F)
th5 = c(7*pi/8,15*pi/8)
lines(cos(th2),sin(th2))
lines(cos(th3),sin(th3))
lines(cos(th4),sin(th4))
lines(cos(th5),sin(th5))
```
\

* Five lines can split a circle into 16 regions.

```{r,echo=F,fig.dim=c(3,3)}
th=seq(0,2*pi,pi/20)
par(mar=c(0,0,0,0),pty="s")
plot(cos(th),sin(th),"l",xlim=c(-1,1),ylim=c(-1,1),ann=F,axes=F)
th6 = c(7.5*pi/8,0.5*pi/8)
lines(cos(th2),sin(th2))
lines(cos(th3),sin(th3))
lines(cos(th4),sin(th4))
lines(cos(th5),sin(th5))
lines(cos(th6),sin(th6))
```
\


