---
output: 
  pdf_document:
    extra_dependencies: ["fancyhdr"]
fontsize: 12pt
---

\fancyhead[L]{\sc{Calculus Unit 1 Assessment 1}}
\fancyhead[R]{\bf \large Name:\hspace{2in}}
\fancyfoot[R]{\sc Page \thepage}
\fancyfoot[C]{}
\pagestyle{fancy}

<!-- ### Student Abilities

1. Find the limit of a function graphically.
2. Find the limit of a function by using tables.
3. Find the limit of a function analytically.
4. Determine whether a function is continuous.
5. Discuss the different types of discontinuity. -->


## Question 1

The function $f(x)$ is graphed below. Complete the table. (Some may be undefined; you can write DNE for "does not exist".)

```{r,fig.width=4,fig.height=4,echo=F,fig.align="center"}
library(shape)
par(mar=c(0,0,0,0))
plot(0,0,type="n",axes=F,ann=F,xlim=c(-10,10),ylim=c(-10,10))
for(i in -10:10){
  lines(c(i,i),c(-10,10),lty=3)
  lines(c(-10,10),c(i,i),lty=3)
}
Arrows(-10,0,10,0,code=3,lwd=2)
Arrows(0,-10,0,10,code=3,lwd=2)
text(10.5,-0.5,"x")
text(-0.5,10.5,"y")

f = function(x){x+15}
x = seq(-10,-7,0.01)
lines(x,f(x),lwd=2)
points(-7,f(-7),pch=16,cex=1.5)

f = function(x){-x}
x = seq(-7,-2,0.01)
lines(x,f(x),lwd=2)
points(-7,f(-7),pch=16,cex=1.5,col="white")
points(-7,f(-7),pch=1,cex=1.5)
points(-5,f(-5),pch=16,cex=1.5,col="white")
points(-5,f(-5)+3,pch=16,cex=1.5,col="black")
points(-5,f(-5),pch=1,cex=1.5)
points(-3,f(-3),pch=16,cex=1.5,col="white")
points(-3,f(-3),pch=1,cex=1.5)

f = function(x){(x^2)/(x-2)+3}
x = seq(-2,2,0.01)
lines(x,f(x),lwd=2)
abline(v=2,lty=2,lwd=1.5)

f = function(x){sqrt(x-2)}
x = seq(2,6,0.01)
lines(x,f(x),lwd=2)
points(2,f(2),pch=16,cex=1.5,col="black")

f = function(x){-(x-8)^2+6}
x = seq(6,10,0.01)
lines(x,f(x),lwd=2)
points(2,f(2),pch=16,cex=1.5,col="black")

```

| $a$ | $f(a)$ | $\lim\limits_{x\to a^-} f(x)$ | $\lim\limits_{x\to a^+} f(x)$ | $\lim\limits_{x\to a} f(x)$ |
|:---:|:---:|:---:|:---:|:---:|
| \vfill\LARGE $-7$\vfill | | | | |
| \LARGE$-5$\vfill | | | | |
| \LARGE$-3$\vfill | | | | |
| \LARGE$2$\vfill | | | | |
| \LARGE$6$\vfill | | | | |


\newpage


## Question 2

Evaluate the limits.

### Part A

$$\lim_{x\to 3} \frac{x^2+3x-18}{x^2-7x+12}$$

\vfill

### Part B

$$\lim_{x\to 2} \frac{\sqrt{x+7}-3}{x-2}$$

\vfill

### Part C

$$\lim_{x\to \infty} \frac{3x^2-5x+9}{2x^2-20}$$

\vfill

\newpage



### Definition of continuous

A function, $g(x)$, is continuous at $x=a$ if:

1. $g(a)$ is defined.
2. $\lim\limits_{x\to a}g(x)$ exists.
3. $\lim\limits_{x\to a}g(x)=g(a)$

\vspace{15pt}

\hrule


## Question 3

Determine if the function below is continuous at $x=2$. Explain why or why not.

$$f(x) = \begin{cases} 
\frac{(x+1)(x-2)}{x-2} & x<2 \\
3 & x= 2 \\
4x-6 & x>2
\end{cases}$$

\newpage

### Statement of Intermediate Value Theorem

The **intermediate value theorem** states if a function, $f$, is continuous on domain $[a,b]$, and $u$ is between $f(a)$ and $f(b)$, then there is a $c\in(a,b)$ such that $f(c)=u$. Note, $c \in (a,b)$ means $c$ is between $a$ and $b$.

\vspace{15pt}

\hrule



## Question 4



Use the intermediate value theorem to show the equation
$$10x^3-7x^2-14x+3 = 0$$
has at least one solution on the interval $(1,2)$.

\newpage


## Question 5 (bonus)

Evaluate the limit. *Hint: expand the numerator, combine similar terms, factor, and eliminate common factors.*

$$\lim_{h\to0}\frac{(3+h)^2-(3)^2}{h} $$
\vfill

Evaluate the limit.

$$\lim_{h\to0}\frac{(a+h)^2-(a)^2}{h} $$

\vfill


\newpage


























