```{r,echo=FALSE}
options(scipen=999)


while(T){
    degs1 = sort(sample(0:5,2))
    degs2 = sort(sample(0:5,2))
    c1 = sample(1:9,2)
    c2 = sample(1:9,2)
    d1 = degs1[1]+degs2[1]
    d2 = degs1[2]+degs2[1]
    d3 = degs1[1]+degs2[2]
    d4 = degs1[2]+degs2[2]
    n1 = c1[1]*c2[1]
    n2 = c1[2]*c2[1]
    n3 = c1[1]*c2[2]
    n4 = c1[2]*c2[2]
    d = c(d1,d2,d3,d4)
    n = c(n1,n2,n3,n4)
    if(length(unique(d))==4 && max(n)<10 && max(d)<8 && max(n)>2){break}
}


A = sum(c1*10^degs1)
B = sum(c2*10^degs2)

P = sum(n*10^d)
fp = format(P,big.mark=",",scientific=F)
opts = c(P)
while(length(opts)<9){
    dd = sample(0:7,4)
    pp = sum(n*10^dd)
    if(!(pp %in% opts)){
        opts = sort(c(opts,pp))
    }
}

o2 = character()
for(i in opts){
    o2 = c(o2,format(i,big.mark=",",scientific=F))
}
opts = o2


alP = paste0("* ",opts,collapse="\n")
solP = paste0(1*(opts==fp),collapse="")

ch = 0:9
ans = c(n4,d4,n3,d3,n2,d2,n1,d1)
sols = character()
for(i in ans){
    sols = c(sols,paste0(1*(ch==i),collapse=""))
}
sols = paste0(sols,collapse="|")

al = paste0("* ",ch,collapse="\n")
fal = paste0(rep(al,8),collapse="\n")

```


Question
========

Let's consider an alternative method for finding the product (multiplication) of `r A` and `r B`. We first break each number into a base-10 expansion.

$$`r A`~~=~~`r c1[2]`\cdot 10^{`r degs1[2]`}~+~`r c1[1]`\cdot 10^{`r degs1[1]`}$$
$$`r B`~~=~~`r c2[2]`\cdot 10^{`r degs2[2]`}~+~`r c2[1]`\cdot 10^{`r degs2[1]`}$$

To proceed with evaluating the product, we can use the [distributive property](https://en.wikipedia.org/wiki/Distributive_property) (or, more specifically, the [FOIL method](https://en.wikipedia.org/wiki/FOIL_method)). To do that, fill out the product table below. For each cell, find the product of the column header times the row header.

```{css,echo=F}
.boxy td {
    padding: 2em;
    border: 1px solid black;
    text-align: center;
    font-size: 1em;
    color: black;
    background-color: white;
  }
.boxy th {
    background-color: rgb(200, 200, 200);
    color: black;
    padding: 2em;
    font-size: 1em;
    text-align: center;
    border: 1px solid black;
  }
.boxy td:first-child {
    background-color: rgb(200, 200, 200);
    color: black;
    padding: 2em;
    font-size: 1em;
    text-align: center;
    border: 1px solid black;
  }
.boxy select {
    width: 5em;
    margin-bottom: 0.5em;
    margin-top: 0.5em;
    margin-right: 0em;
    margin-left: 0.5em;
}
.sml select {
    font-size: 0.8em;
    margin-bottom: 1em;
    margin-top: 0.5em;
    margin-right: 0.5em;
    margin-left: 0em;
}
```

<div class="boxy">

|  \* | $`r c1[2]`\cdot 10^{`r degs1[2]`}$ | $`r c1[1]`\cdot 10^{`r degs1[1]`}$ |
|:---:|:---:|:---:|
|$`r c2[2]`\cdot 10^{`r degs2[2]`}$|##ANSWER1##$\cdot 10$<sup class="sml">##ANSWER2##</sup> |##ANSWER3##$\cdot 10$<sup class="sml">##ANSWER4##</sup> |
|$`r c2[1]`\cdot 10^{`r degs2[1]`}$|##ANSWER5##$\cdot 10$<sup class="sml">##ANSWER6##</sup> | ##ANSWER7##$\cdot 10$<sup class="sml">##ANSWER8##</sup> |

</div>


```{css,echo=F}
.last select{
    width: 12em;
}
```

<div class="last">
Thus, the product equals ##ANSWER9##.
</div>

Answerlist
--------

`r fal`
`r alP`


Solution
========

Remember that $(A\cdot10^a)\cdot(B\cdot 10^b) ~~\equiv~~ (A\cdot B)\cdot10^{a+b}$. You might want to review some [exponent rules](https://en.wikipedia.org/wiki/Exponentiation#Identities_and_properties).

<div class="boxy">

|  \* | $`r c1[2]`\cdot 10^{`r degs1[2]`}$ | $`r c1[1]`\cdot 10^{`r degs1[1]`}$ |
|:---:|:---:|:---:|
|$`r c2[2]`\cdot 10^{`r degs2[2]`}$| $`r n4`\cdot 10^{`r d4`}$ | $`r n3`\cdot 10^{`r d3`}$ |
|$`r c2[1]`\cdot 10^{`r degs2[1]`}$| $`r n2`\cdot 10^{`r d2`}$ | $`r n1`\cdot 10^{`r d1`}$ |

</div>

`r format(P,big.mark=",",scientific=FALSE)`

Meta-information
============
extype: cloze
exclozetype: schoice|schoice|schoice|schoice|schoice|schoice|schoice|schoice|schoice
exsolution: `r sols`|`r solP`
exname: base10_multiply