---
output: pdf_document
---


```{r,fig.dim=c(4,4),echo=FALSE,results="asis"}
par(pty="s")
plot(0,0,type="n",xlim=c(-10,10),ylim=c(-10,10),axes=FALSE,ann=FALSE)
for(i in seq(-10,10,0.2)){
  for(j in seq(-10,10,1)){
    points(i,j,pch=19,cex=0.01)
    points(j,i,pch=19,cex=0.01)
  }
}
abline(h=0)
abline(v=0)
par(pty="s")
plot(0,0,type="n",xlim=c(-10,10),ylim=c(-10,10),axes=FALSE,ann=FALSE)
for(i in seq(-10,10,0.2)){
  for(j in seq(-10,10,1)){
    points(i,j,pch=19,cex=0.01)
    points(j,i,pch=19,cex=0.01)
  }
}
abline(h=0)
abline(v=0)
```
\
```{r,fig.dim=c(4,4),echo=FALSE,results="asis"}
par(pty="s")
plot(0,0,type="n",xlim=c(-10,10),ylim=c(-10,10),axes=FALSE,ann=FALSE)
for(i in seq(-10,10,0.2)){
  for(j in seq(-10,10,1)){
    points(i,j,pch=19,cex=0.01)
    points(j,i,pch=19,cex=0.01)
  }
}
abline(h=0)
abline(v=0)
```
```{r,fig.dim=c(4,4),echo=FALSE,results="asis"}
par(pty="s")
plot(0,0,type="n",xlim=c(-10,10),ylim=c(-10,10),axes=FALSE,ann=FALSE)
for(i in seq(-10,10,0.2)){
  for(j in seq(-10,10,1)){
    points(i,j,pch=19,cex=0.01)
    points(j,i,pch=19,cex=0.01)
  }
}
abline(h=0)
abline(v=0)
```
\

