```{r,echo=F}

# set oA, oB, i, nAB
# u = oA+oB-i
# A = oA+i
# B = oB+i
# tot = u+nAB
# oA, oB, i, u, A, B, nAB, tot   

while(T){
    da4 = sample(2:30,3)
    oA = da4[1]
    oB = da4[2]
    I = da4[3]
    U = oA+oB-I
    A = oA+I
    B = oB+I
    a = c(oA,oB,I,U,A,B)
    n = length(a)
    whichgive = sample(1:n,3)
    gottem = 1*(1:n==whichgive[1])+1*(1:n==whichgive[2])+1*(1:n==whichgive[3])
    eqs = list(c(1,2,3,4),c(1,3,5),c(2,3,6))
    for(i in 1:10){
        for(eq in eqs){
            if(sum(gottem[eq])+1==length(eq)){
                for(j in eq){
                    gottem[j] = 1
                }
            }
        }
    }
    if(length(unique(a))==n && min(a)>=0 && sum(gottem)==n){break}
}
states = c(paste0("The volume remaining when object B is subtracted from object A is ",oA," cubic meters.",collapse=""),
           paste0("The volume remaining when object A is subtracted from object B is ",oB," cubic meters.",collapse=""),
           paste0("The volume of the intersection is ",I," cubic meters.",collapse=""),
           paste0("The volume of the union is ",U," cubic meters.",collapse=""),
           paste0("The volume of object A is ",A," cubic meters.",collapse=""),
           paste0("The volume of object B is ",B," cubic meters.",collapse="")
           )

```


Question
========

Consider the Venn diagram below.

```{r,echo=F,fig.dim=c(4,3)}
circ = function(x0,y0,r){
    th = seq(0,2*pi,pi/100)
    lines(x0+r*cos(th),y0+r*sin(th))
}
par(mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(0,8),ylim=c(0,6),axes=F,ann=F)
circ(2.5,3,2.5)
circ(5.5,3,2.5)
```
\

Solution
========



Meta-information
============
extype: cloze
exclozetype: schoice|schoice|schoice|schoice|schoice|schoice
exsolution: 
exname: union_intersect_subtract


