```{r,echo=FALSE}
options(scipen=99)


webs = c("https://en.wikipedia.org/wiki/Equal_temperament#Five-,_seven-,_and_nine-tone_temperaments_in_ethnomusicology",
"https://en.wikipedia.org/wiki/Equal_temperament#7-tone_equal_temperament",
"https://en.wikipedia.org/wiki/Equal_temperament#Five-,_seven-,_and_nine-tone_temperaments_in_ethnomusicology",
  "https://en.wikipedia.org/wiki/12_equal_temperament",
  "https://en.wikipedia.org/wiki/15_equal_temperament",
  "https://en.wikipedia.org/wiki/17_equal_temperament",
  "https://en.wikipedia.org/wiki/19_equal_temperament",
  "https://en.wikipedia.org/wiki/22_equal_temperament",
  "https://en.wikipedia.org/wiki/23_equal_temperament",
  "https://en.wikipedia.org/wiki/Quarter_tone",
  "https://en.wikipedia.org/wiki/31_equal_temperament",
  "https://en.wikipedia.org/wiki/34_equal_temperament",
  "https://en.wikipedia.org/wiki/41_equal_temperament",
  "https://en.wikipedia.org/wiki/53_equal_temperament",
  "https://en.wikipedia.org/wiki/58_equal_temperament",
  "https://en.wikipedia.org/wiki/72_equal_temperament",
  "https://en.wikipedia.org/wiki/96_equal_temperament")

Ns = c(5,7,9,12,15,17,19,22,23,24,31,34,41,53,58,72,96)

sel = sample(1:length(Ns),1)
wb = webs[sel]
N = Ns[sel]

i440 = sample((N*3):(N*5),1)
idiff = sample(5:(N*2),1)*sample(c(-1,1),1)
i2 = i440+idiff
f = 440*2^(idiff/N)
```

Question
========

In music, an [equal temperament](https://en.wikipedia.org/wiki/Equal_temperament) implies the available [fundamental frequencies](https://en.wikipedia.org/wiki/Fundamental_frequency) follow a geometric progression. Imagine a [keyboard instrument](https://en.wikipedia.org/wiki/Keyboard_instrument) for [`r N` EDO](`r wb`). That means there are `r N` frequencies per octave, and the ratio between neighboring frequencies is $2^{1/`r N`} \approx `r 2^(1/N)`$. That instrument acts as a [function](https://en.wikipedia.org/wiki/Function_(mathematics)) that maps [key number ($k$) to frequency ($f$)](https://en.wikipedia.org/wiki/Piano_key_frequencies).

Let's assume a [concert pitch](https://en.wikipedia.org/wiki/Concert_pitch) of [440 Hz](https://en.wikipedia.org/wiki/A440_(pitch_standard)) is assigned to the key number `r i440`, so we can calculate the frequency from any key number using the following [exponential function](https://en.wikipedia.org/wiki/Exponential_function).

$$f = 440 \cdot 2^{(k-`r i440`)/`r N`} $$

The inverse of exponentiation is the [logarithm](https://en.wikipedia.org/wiki/Logarithm). This allows us to create a formula to calculate the key number from the frequency.

$$k = `r N` \log_2\left(\frac{f}{440}\right)+`r i440`$$

What key number produces a frequency of $f=`r f`$ Hz? (Please round to nearest integer.)

Solution
========

$$k = `r N` \log_2\left(\frac{`r f`}{440}\right)+`r i440`$$

$$k=`r i2`$$

If your calculator does not allow logs with base 2, you can use the [change-of-base  identity](https://en.wikipedia.org/wiki/List_of_logarithmic_identities#Changing_the_base).

$$k = `r N` \frac{\log\left(\frac{`r f`}{440}\right)}{\log(2)}+`r i440`= `r i2`$$


Meta-information
============
extype: num
exsolution: `r i2`
extol: 0
exname: equal_temperament_get_freq