```{r,echo=FALSE}
x = runif(1,0.5,7)
y = exp(x)
y = signif(y,4)
x = log(y)

```


Question
========

Solve the equation below in which $e$ is [Euler's number](https://en.wikipedia.org/wiki/E_(mathematical_constant)).

$$`r y`=e^{x}$$


Solution
========

If a function is $f(x)=e^x$, the inverse function is $f^{-1}(x)=\ln(x)$ and is called the [natural logarithm](https://en.wikipedia.org/wiki/Natural_logarithm). Notice $\ln$ is just another way of writing $\log_e$.

So, our first step will be to take the natural logarithm of both sides.

$$\ln(`r y`)=\ln\left(e^{x}\right)$$

The inverse functions undo each other.

$$\ln(`r y`)=x$$

Some people prefer to know how to go from the given equation to the last equation without considering the application of a function to both sides of the equation followed by a simplification. They would refer to the given equation as being in "exponential form" and the above equation as the "logarithmic form". You could search the internet for "convert between exponential and logarithmic" to find resources.

You can use a calculator to evaluate $\ln(`r y`)$.

$$x~=~`r x`$$


Meta-information
============
extype: num
exsolution: `r x`
exname: solve_e_to_x
extol: 0.01