```{r,echo=FALSE}
A = round(runif(1,30,100),1)
B = round(runif(1,0.01,0.5),2)
if(B==1){
  B = 1.1
}
C = round(runif(1,1,30),1)
Tf = round(runif(1,0.1,0.5)*A+C,1)
tf = -log((Tf-C)/A)/B
hl = log(2)/B
```


Question
========

Let's say a warm block initially at `r A+C`°C is placed outside on a moderately windy day. The outdoor temperature is `r C`°C. Moment by moment, the instantaneous rate of cooling is proportional to the difference of temperatures. The exact rate depends of many components:

* Mass of the block
* Material of the block
* Shape is the block
* Speed of the wind
* Etc...

For this block, all the effects combine into a single proportionality constant: `r B` $\text{min}^{-1}$. So, at any moment, the rate of change equals $-`r B`(T-`r C`)$ $\frac{^\circ\text{C}}{\text{min}}$. This implies that every `r round(hl,3)` minutes, the [temperature difference halves](https://en.wikipedia.org/wiki/Half-life).

By reviewing [Newton's law of cooling](https://en.wikipedia.org/wiki/Newton%27s_law_of_cooling), we see this block's temperature follows an offset-exponential function of time.

$$T(t) ~=~ `r A`e^{-`r B` t}+`r C`$$

where $T$ is in degrees Celsius and $t$ is in minutes. **How many minutes does it take for the block's temperature to reach `r Tf` degrees Celsius?**

The tolerance is $\pm0.01$ min.


Solution
========

Plug in the temperature.

$$`r Tf` ~=~ `r A`e^{-`r B` t}+`r C`$$

Subtract `r C` from both sides.

$$`r Tf-C` ~=~ `r A`e^{-`r B` t}$$

Divide both sides by `r A`.

$$\frac{`r Tf-C`}{`r A`} ~=~ e^{-`r B` t}$$

Take the natural logarithm of both sides.

$$\ln \left(\frac{`r Tf-C`}{`r A`}\right) ~=~ \ln\left(e^{-`r B` t}\right)$$

Apply the [log-of-a-power identity](https://en.wikipedia.org/wiki/List_of_logarithmic_identities#Logarithm_of_a_power).

$$\ln \left(\frac{`r Tf-C`}{`r A`}\right) ~=~ -`r B`t\ln\left(e\right)$$

The natural logarithm is base $e$, so $\ln(e)=1$.

$$\ln \left(\frac{`r Tf-C`}{`r A`}\right) ~=~ -`r B`t$$

Divide both sides by $-`r B`$.

$$t = `r tf`$$


Meta-information
============
extype: num
exsolution: `r tf`
exname: solve_time
extol: 0.01