---
title: "Exponent Rules"
output: html_document
---


## Basic examples for exponents and logarithms

I find it instructive to consider the following equalities.

$$\begin{aligned}
10^4 ~&=~ 10000 &&\text{so}& \log_{10}(10000) &= 4 \\\\
10^3 ~&=~ 1000 &&\text{so}& \log_{10}(1000) &= 3 \\\\
10^2 ~&=~ 100 &&\text{so}& \log_{10}(100) &= 2 \\\\
10^1 ~&=~ 10 &&\text{so}& \log_{10}(10) &= 1 \\\\
10^0 ~&=~ 1 &&\text{so}& \log_{10}(1) &= 0 \\\\
10^{-1} ~&=~ 0.1 &&\text{so}& \log_{10}(0.1) &= -1 \\\\
10^{-2} ~&=~ 0.01 &&\text{so}& \log_{10}(0.01) &= -2 \\\\
10^{-3} ~&=~ 0.001 &&\text{so}& \log_{10}(0.001) &= -3 \\\\
10^{-4} ~&=~ 0.0001 &&\text{so}& \log_{10}(0.0001) &= -4 \\\\\\\\
2^{10} ~&=~ 1024 &&\text{so}& \log_{2}(1024) &= 10 \\\\
2^9 ~&=~ 512 &&\text{so}& \log_{2}(512) &= 9 \\\\
2^8 ~&=~ 256 &&\text{so}& \log_{2}(256) &= 8 \\\\
2^7 ~&=~ 128 &&\text{so}& \log_{2}(128) &= 7 \\\\
2^6 ~&=~ 64 &&\text{so}& \log_{2}(64) &= 6 \\\\
2^5 ~&=~ 32 &&\text{so}& \log_{2}(32) &= 5 \\\\
2^4 ~&=~ 16 &&\text{so}& \log_{2}(16) &= 4 \\\\
2^3 ~&=~ 8 &&\text{so}& \log_{2}(8) &= 3 \\\\
2^2 ~&=~ 4 &&\text{so}& \log_{2}(4) &= 2 \\\\
2^1 ~&=~ 2 &&\text{so}& \log_{2}(2) &= 1 \\\\
2^0 ~&=~ 1 &&\text{so}& \log_{2}(1) &= 0 \\\\
2^{-1} ~&=~ \frac{1}{2} &&\text{so}& \log_{2}\left(\frac{1}{2}\right) &= -1 \\\\
2^{-2} ~&=~ \frac{1}{4} &&\text{so}& \log_{2}\left(\frac{1}{4}\right) &= -2 \\\\
2^{-3} ~&=~ \frac{1}{8} &&\text{so}& \log_{2}\left(\frac{1}{8}\right) &= -3 \\\\
2^{-4} ~&=~ \frac{1}{16} &&\text{so}& \log_{2}\left(\frac{1}{16}\right) &= -4 \\\\
2^{-5} ~&=~ \frac{1}{32} &&\text{so}& \log_{2}\left(\frac{1}{32}\right) &= -5 \\\\
2^{-6} ~&=~ \frac{1}{64} &&\text{so}& \log_{2}\left(\frac{1}{64}\right) &= -6 \\\\
2^{-7} ~&=~ \frac{1}{128} &&\text{so}& \log_{2}\left(\frac{1}{128}\right) &= -7 \\\\
2^{-8} ~&=~ \frac{1}{256} &&\text{so}& \log_{2}\left(\frac{1}{256}\right) &= -8 \\\\
2^{-9} ~&=~ \frac{1}{512} &&\text{so}& \log_{2}\left(\frac{1}{512}\right) &= -9 \\\\
2^{-10} ~&=~ \frac{1}{1024} &&\text{so}& \log_{2}\left(\frac{1}{1024}\right) &= -10 \\\\
\end{aligned}$$





## Exponential identities

Let $a$ and $b$ be bases of exponential expressions. We can assume that $a>0$ and $b>0$, so that the rules work perfectly.

Let $x$ and $y$ represent numbers in the exponents.

The following equations are identities, meaning they hold true for all possible values (subject to stated constraints). Some of these identities are redundant, but it is useful to consider all of them.

$$
\begin{aligned}
a^1 &\equiv a \\\\
a^{-1} &\equiv \frac{1}{a} \\\\
a^0 &\equiv 1 \\\\
a^{x+y} &\equiv a^x \cdot a^y \\\\
a^{x-y} &\equiv \frac{a^x}{a^y} \\\\
a^{xy} &\equiv \left(a^x\right)^y \\\\
a^{\frac{x}{y}} &\equiv \sqrt[y]{a^x} \\\\
(ab)^x &\equiv a^x\cdot b^x\\\\
\left(\frac{a}{b}\right)^x &\equiv \frac{a^x}{b^x}\\\\
\end{aligned}
$$

It should also be mentioned that in an equation where both sides have the same base with different exponents, the exponents are equal:


$$\begin{aligned}
&\text{If} \\
&& a^x &= a^y \\
&\text{then} \\
&& x&=y
\end{aligned}$$

## Logarithms

Logarithmic functions are the inverse of exponential functions. 

$$\begin{aligned}
&\text{If} \\
&& z &= b^x \\
&\text{then} \\
&& \log_b(z) &= x
\end{aligned}$$

Or, in function notation: 

$$\begin{aligned}
&\text{If} \\
&& f(x) &= b^x \\
&\text{then} \\
&& f^{-1}(x) &= \log_b(x)
\end{aligned}$$


Logarithms have their own set of [interesting identities](https://en.wikipedia.org/wiki/List_of_logarithmic_identities) (the linked wikipedia article expands on these rules very thoroughly). Again, let's assume $a>0$ and $b>0$. In addition, let $c>0$.


$$
\begin{aligned}
\log_b\left(a^x\right) &\equiv x\cdot \log_b(a) \\\\
\log_b(b) &\equiv 1 \\\\
\log_b(1) &\equiv 0 \\\\
\log_b\left(b^x\right) &\equiv x \\\\
b^{\log_b(a)} &\equiv a \\\\
\log_b\left(ac\right) &\equiv \log_b(a)+\log_b(c)\\\\
\log_b\left(\frac{a}{c}\right) &\equiv \log_b(a)-\log_b(c)\\\\
\log_b(a) &\equiv \frac{\log_c(a)}{\log_c(b)}\\\\
\end{aligned}
$$

Most calculators (including Desmos) default to a base of 10 when the base is not indicated.

$$\text{Usually:}~~~~~~\log(a) \equiv \log_{10}(a)$$

Most calculators also have a built-in function for base-$e$ logarithm, where $e$ is Euler's number and is approximately equal to 2.718. This base-$e$ logarithm is called the natural logarithm.

$$\ln(a)~\equiv~\log_{e}(a)$$





