```{r,echo=F}
gcd2 <- function(a, b) {
  if (b == 0) a else Recall(b, a %% b)
}
gcd <- function(...) Reduce(gcd2, c(...))
while(T){
    primes = c(2,3,5,7,11)
    n1 = sample(3:7,1)
    n2 = sample(3:7,1)
    p1 = sample(primes,n1,T,c(8,5,6,3,3))
    p2 = sample(primes,n2,T,c(8,5,6,3,3))
    c1 = prod(p1)
    c2 = prod(p2)
    gcf = gcd2(c1,c2)
    lcm = c1*c2/gcf
    if(gcf>1 && sum(c1==7)<2 && sum(c1==11)<2 && sum(c2==7)<2 && sum(c2==11)<2 && c1<500 && c2<500 && lcm>max(c(c1,c2)) && !(gcf %in% primes)){break}
}


```


Question
========

What is the greatest common factor of `r c1` and `r c2`?


Solution
========

Determine the prime factorization for each by using a factor tree.

```{r,echo=F}
vals1 = sort(unique(p1))
cnts1 = numeric()
for(v in vals1){
    cnts1 = c(cnts1,sum(p1==v))
}
ex1 = paste0(vals1,"^{",cnts1,"}",collapse="\\cdot ")

vals2 = sort(unique(p2))
cnts2 = numeric()
for(v in vals2){
    cnts2 = c(cnts2,sum(p2==v))
}
ex2 = paste0(vals2,"^{",cnts2,"}",collapse="\\cdot ")

vals3 = unique(c(p1,p2))
cnts3 = numeric()
p3 = numeric()

Acnt = cnts1
Bcnt = cnts2

for(v in vals3){
    beep = min(c(sum(p1==v),sum(p2==v)))
    cnts3 = c(cnts3,beep)
    p3 = c(p3,rep(v,beep))
    Acnt[vals1==v] = Acnt[vals1==v]-beep
    Bcnt[vals2==v] = Bcnt[vals2==v]-beep
}
ex2 = paste0(vals2,"^{",cnts2,"}",collapse="\\cdot ")

pA = numeric()
pB = numeric()

for(i in vals1){
    pA = c(pA,rep(i,Acnt[vals1==i]))
}

for(i in vals2){
    pB = c(pB,rep(i,Bcnt[vals2==i]))
}

```

$$`r c1` = `r ex1`$$
$$`r c2` = `r ex2`$$

Make a Venn diagram.

```{r,echo=F,fig.dim=c(3,1.5),fig.align='center',fig.cap=""}
par(mar=c(0,0,0,0))
plot(0,0,type="n",axes=F,ann=F,xlim=c(0,2),ylim=c(0,1))
th = seq(0,2*pi,pi/100)
lines(0.5*cos(th)+0.7,0.5*sin(th)+0.5)
lines(0.5*cos(th)+1.3,0.5*sin(th)+0.5)
txi = paste0(sort(p3),collapse="\n")
text(1,0.5,txi)
txa = paste0(sort(pA),collapse="\n")
text(0.5,0.5,txa)
txb = paste0(sort(pB),collapse="\n")
text(1.5,0.5,txb)
text(0.2,0.95,c1)
text(1.8,0.95,c2)
```

Find the product of the intersection.

$$`r paste0(p3,collapse="\\cdot")`=`r gcf`$$


Meta-information
============
extype: num
exsolution: `r gcf`
exname: GCF

