---
output: pdf_document
params:
    rseed: 1
---

```{r,echo=F}
set.seed(params$rseed)
sols = numeric()
```

Name: \hspace{4in} Date: \hfill \hrule

# Multiply 2-digit numbers (version `r params$rseed`)

```{r,echo=F}
options(scipen=999)
digits = sample(2:9,4)
At = digits[1]
Ao = digits[2]
Bt = digits[3]
Bo = digits[4]
A = At*10+Ao
B = Bt*10+Bo
sols = c(sols,A*B)
```

1. Find the product of `r A` and `r B`.

\vfill

```{r,echo=F}
digits = sample(2:9,4)
At = digits[1]
Ao = digits[2]
Bt = digits[3]
Bo = digits[4]
A = At*10+Ao
B = Bt*10+Bo
sols = c(sols,A*B)
```

2. Find the product of `r A` and `r B`.

\vfill

\newpage

```{r,echo=F}
options(scipen=999)
digits = sample(2:9,4)
At = digits[1]
Ao = digits[2]
Bt = digits[3]
Bo = digits[4]
A = At*10+Ao
B = Bt*10+Bo
sols = c(sols,A*B)
```

3. Find the product of `r A` and `r B`.

\vfill

```{r,echo=F}
digits = sample(2:9,4)
At = digits[1]
Ao = digits[2]
Bt = digits[3]
Bo = digits[4]
A = At*10+Ao
B = Bt*10+Bo
sols = c(sols,A*B)
```

4. Find the product of `r A` and `r B`.

\vfill


```{r,echo=F}
line = paste0(c(params$rseed,sols),collapse="  ")
write(line,file="multiply_2digit_sols.txt",append=TRUE)
```

