```{r data generation, echo = FALSE, results = "hide"}
library(reticulate)
xs = -5:5
n = sample(3:5,1)
xp = c(-5,sample(-4:4,n),5)
yp = sample(-4:4,n+2)
ii = xs %in% xp
print(ii)
al = paste0("* ",x,"\n",collapse="")

# ans1 = paste0(1*(x==an1),collapse="")
# ans2 = paste0(1*(x==an2),collapse="")
```

Question
========

Let functions $f$ and $g$ be defined by the graph below.

```{r,fig.dim=c(5,5),echo=FALSE,results="asis"}
par(pty="s")
plot(0,0,type="n",xlim=c(0,10),ylim=c(0,10),lwd=2,ylab="y",xlab="x")
for(j in seq(0,10,1)){
  abline(h=j,lty=3)
  abline(v=j,lty=3)
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)
xspline(x,y,shape=c(0,rep(-0.2,length(x1)-2),0),border = "blue",lwd=4)
```


Evaluate the following:

* $g(f(`r a`)) =$ ##ANSWER1##
* $f(g(`r b`)) =$ ##ANSWER2##

Answerlist
--------

`r al`
`r al`

Solution
========

* $g(f(`r a`))=g(`r f[which(x1==a)]`)=`r an1`$
* $f(g(`r b`))=f(`r g[which(x2==b)]`)=`r an2`$


Meta-information
============
extype: cloze
exclozetype: schoice|schoice
exsolution: `r ans1`|`r ans2`
exname: compose_graphs