```{r data generation, echo = FALSE, results = "hide"}
funs = list(c("$|x|$","absolute",function(x){abs(x)}),
            c("$x^2$","quadratic",function(x){x^2}),
            c("$x^3$","cubic",function(x){x^3}),
            c("$\\frac{1}{x}$","reciprocal",function(x){1/x}),
            c("$\\sqrt{x}$","square root",function(x){x^(1/2)}),
            c("$\\sqrt[3]{x}$","cube root",function(x){abs(x)^(1/3)*sign(x)}),
            c("$\\sin(x)$","sine",function(x){sin(x)}),
            c("$\\cos(x)$","cosine",function(x){cos(x)}),
            c("$\\tan(x)$","tangent",function(x){tan(x)}),
            c("$e^x$","exponential",function(x){exp(x)}),
            c("$\\ln(x)$","logarithmic",function(x){log(x)}),
            c("$\\frac{e^x}{e^x+1}$","logistic",function(x){exp(x)/(exp(x)+1)}),
            c("$\\frac{1}{x^2}$","squared reciprocal",function(x){1/x^2})
            )
n = length(funs)
eqs = character()
nms = character()
for(fun in funs){
  eqs = c(eqs,fun[[1]][1])
  nms = c(nms,fun[[2]][1])
}
shifts = sample(c(1:3),2)*sample(c(-1,1),2,T)
h = shifts[1]
k = shifts[2]
fn = sample(1:n,1) 
f = funs[[fn]][3]
flatex = funs[[fn]][1]
fname = funs[[fn]][2]
```

Question
========

Match the graphs with their names.

```{r,fig.dim=c(5,5),echo=FALSE,results="asis"}
for(i in 1:length(funs)){
  fun = funs[[ord[i]]]
  par(pty="s")
  x = seq(-4.999,4.999,0.001)
  suppressWarnings(plot(x,fun[[3]](x),type="n",xlim=c(-5,5),ylim=c(-5,5),lwd=2,ylab="f(x)",xlab="x"))
  for(j in -5:5){
    abline(h=j,lty=3)
    abline(v=j,lty=3)
  }
  abline(h=0,lwd=2)
  abline(v=0,lwd=2)
  suppressWarnings({y = fun[[3]](x)})
  breaks = c(0,which(diff(y)>0.2),length(x))
  for(j in 1:(length(breaks)-1)){
    suppressWarnings(lines(x[(breaks[j]+1):(breaks[j+1]-1)],y[(breaks[j]+1):(breaks[j+1]-1)],type="l",lwd=4,col="blue"))
  }
  cat(paste0("\n##ANSWER",i,"##\n\n"))
}
```

Answerlist
--------
```{r,echo=FALSE,results="asis"}
for(i in 1:length(funs)){
  cat(nmli)
}
```


Solution
========

You could try graphing the options or referencing a parent-function chart.


Meta-information
============
extype: cloze
exclozetype: `r paste0(rep("schoice",length(funs)),collapse="|")`
exsolution: `r paste0(answers,collapse="|")`
exname: match_parent_functions
exshuffle: false