```{r,echo=F,warning=F}
names = c("sin(x)","cos(x)","tan(x)","csc(x)","sec(x)","cot(x)",
          "arcsin(x)","arccos(x)","arctan(x)",
          "arccsc(x)","arcsec(x)","arccot(x)")
dx = 14/(1001-1)
xs = seq(-7,7,length.out=1001)
ys = list(sin(xs),cos(xs),tan(xs),1/sin(xs),1/cos(xs),1/tan(xs),
          asin(xs),acos(xs),atan(xs),asin(1/xs),acos(1/xs),atan(1/xs))

ys2 = ys
#ys2 = sample(ys)

```

Question
========

Match each plot with its function.

```{r,echo=F,fig.dim=c(5,5),results='asis'}
for(i in 1:length(names)){
  par(pty="s")
  cat(paste0("## Plot ",i,"\n",collapse=""))
  plot(0,0,type="n",xlim=c(-7,7),ylim=c(-7,7),
       xlab="x",ylab="y")
  arrows(-7.5,0,7.5,0,length=0.1,angle=20,code=3)
  arrows(0,-7.5,0,7.5,length=0.1,angle=20,code=3)
  x = xs
  y = ys2[[i]]
  spots = !is.nan(y)
  x = x[spots]
  y = y[spots]
  spots = abs(y)<10
  x = x[spots]
  y = y[spots]
  beg1 = c(1,which(diff(x)>1.1*dx),length(x))
  if(length(beg1)<2){
    lines(x,y)
  } else {
    for(j in 1:(length(beg1)-1)){
      lines(x[(beg1[j]+1):(beg1[j+1]-1)],
            y[(beg1[j]+1):(beg1[j+1]-1)],col="blue",lwd=2)
    }
  }
  
  
  cat(paste0("##ANSWER",i,"##\n\n",collapse=""))
}
```
\


Solution
========



Meta-information
============
extype: cloze
exclozetype: 
exsolution: 
exname: polar_graphs