---
title: "Some parent functions"
output:
  pdf_document:
    pandoc_args: [
      "-V", "classoption=twocolumn"
    ]
---

```{r,echo=F}
fdim = 3
```

### Absolute-value function

$$b=|a|$$

```{r,echo=F,fig.dim=c(fdim,fdim),fig.align='center'}
startit = function(){
    par(mar=c(0,0,0,0),oma=c(0,0,0,0),pty="s")
    plot(0,0,"n",xlim=c(-10,10),ylim=c(-10,10),axes=F,ann=F)
    for(i in -10:10){
        lines(c(-10,10),c(i,i),col="grey",lwd=0.5)
        lines(c(i,i),c(-10,10),col="grey",lwd=0.5)
    }
    for(i in seq(-10,10,5)){
        lines(c(-10,10),c(i,i),col="darkgrey",lwd=0.8)
        lines(c(i,i),c(-10,10),col="darkgrey",lwd=0.8)
    }
    arrows(-10.7,0,10.7,0,0.05,15,3,lwd=1.5)
    arrows(0,-10.7,0,10.7,0.05,15,3,lwd=1.5)
    text(5,-0.5,"5",cex=0.7)
    text(-0.5,5,"5",cex=0.7)
    text(10.3,-0.5,"a",cex=0.7)
    text(-0.5,10.3,"b",cex=0.7)
}
startit()
x = seq(-10,10,0.1)
y = abs(x)
lines(x,y,lwd=3,col="blue")
xp = 0
yp = 0
points(yp,xp,pch=19,col="blue",cex=0.8)
```

\vfill

### Reciprocal function

$$b=\frac{1}{a}~~~~\text{or}~~~~b=a^{-1}$$

```{r,echo=F,fig.dim=c(fdim,fdim),fig.align='center'}
startit()
x1 = seq(-10,-1/10,0.01)
y1 = 1/x1
lines(x1,y1,lwd=3,col="blue")
x2 = seq(1/10,10,0.01)
y2 = 1/x2
lines(x2,y2,lwd=3,col="blue")
xp = c(-1,1)
yp = 1/xp
points(yp,xp,pch=19,col="blue",cex=0.8)
```

\vfill

\newpage

### Squaring function (Quadratic)

$$b=a^2$$

```{r,echo=F,fig.dim=c(fdim,fdim),fig.align='center'}
startit()
x = seq(-sqrt(10),sqrt(10),0.01)
y = x^2
lines(x,y,lwd=3,col="blue")
xp = -3:3
yp = xp^2
points(xp,yp,pch=19,col="blue",cex=0.8)
```

\vfill


### Square-root function

$$b=\sqrt{a}~~~~\text{or}~~~~b=a^{1/2}$$

```{r,echo=F,fig.dim=c(fdim,fdim),fig.align='center'}
startit()
x = seq(0,sqrt(10),0.01)
y = x^2
lines(y,x,lwd=3,col="blue")
xp = 0:3
yp = xp^2
points(yp,xp,pch=19,col="blue",cex=0.8)
```

\vfill


\newpage


### Cubing function (Cubic)

$$b=a^3$$

```{r,echo=F,fig.dim=c(fdim,fdim),fig.align='center'}
startit()
x = seq(-10^(1/3),10^(1/3),0.01)
y = x^3
lines(x,y,lwd=3,col="blue")
xp = -2:2
yp = xp^3
points(xp,yp,pch=19,col="blue",cex=0.8)
```

\vfill

### Cube-root function

$$b=\sqrt[3]{a}~~~~\text{or}~~~~b=a^{1/3}$$

```{r,echo=F,fig.dim=c(fdim,fdim),fig.align='center'}
startit()
x = seq(-10,10,0.01)
y = sign(x)*abs(x)^(1/3)
lines(x,y,lwd=3,col="blue")
xp = c(-8,-1,0,1,8)
yp = sign(xp)*abs(xp)^(1/3)
points(xp,yp,pch=19,col="blue",cex=0.8)
```

\vfill

\newpage

### Exponential (base 2) function

$$b=2^a$$

```{r,echo=F,fig.dim=c(fdim,fdim),fig.align='center'}
startit()
x = seq(-10,log(10)/log(2),0.001)
y = 2^x
lines(x,y,lwd=3,col="blue")
xp = c(0,1,2,3)
yp = 2^xp
points(xp,yp,pch=19,col="blue",cex=0.8)
```

\vfill

### Logarithmic (base 2) function

$$b=\log_2(a)$$

```{r,echo=F,fig.dim=c(fdim,fdim),fig.align='center'}
startit()
x = seq(-10,log(10)/log(2),0.001)
y = 2^x
lines(y,x,lwd=3,col="blue")
xp = c(0,1,2,3)
yp = 2^xp
points(yp,xp,pch=19,col="blue",cex=0.8)
```

\vfill

