---
title: "Massachusetts Standards"
output:
  html_document:
    toc: true
    toc_depth: 3
---

# N: Number and Quantity

## CN: The Complex Number System
### A. Perform arithmetic operations with complex numbers.

1. Know there is a complex number i such that $i^2 = -1$, and every complex number has the form $a + bi$ with $a$ and $b$ real.
2. Use the relation $i^2 = -1$ and the Commutative, Associative, and Distributive properties to add, subtract, and multiply complex numbers.

### C. Use complex numbers in polynomial identities and equations.

7. Solve quadratic equations with real coefficients that have complex solutions.
8. (+) Extend polynomial identities to the complex numbers. For example, rewrite $x^2 + 4$ as $(x + 2i) (x – 2i)$.
9. (+) Know the Fundamental Theorem of Algebra; show that it is true for quadratic polynomials.

## VM: Vector and Matrix Quantities
### A. Represent and model with vector quantities.

1. (+) Recognize vector quantities as having both magnitude and direction. Represent vector quantities by directed line segments, and use appropriate symbols for vectors and their magnitudes (e.g., $\boldsymbol{v}$, $|v|$, $|| v ||$, $v$).
2. (+) Find the components of a vector by subtracting the coordinates of an initial point from the
coordinates of a terminal point.
3. (+) Solve problems involving velocity and other quantities that can be represented by vectors.

### C. Perform operations on matrices and use matrices in applications.



# A: Algebra
## SSE: Seeing Structure in Expressions
### A. Interpret the structure of expressions (linear, quadratic, exponential, polynomial, rational).
### B. Write expressions in equivalent forms to solve problems.
## APR: Arithmetic with Polynomials and Rational Expressions
### A. Perform arithmetic operations on polynomials.
### B. Understand the relationship between zeros and factors of polynomials.
### C. Use polynomial identities to solve problems.
### D. Rewrite rational expressions.
## CED: Creating Equations
### A. Create equations that describe numbers or relationships.
## REI: Reasoning with Equations and Inequalities
### A. Understand solving equations as a process of reasoning and explain the reasoning.
### B. Solve equations and inequalities in one variable.
### C. Solve systems of equations.
### D. Represent and solve equations and inequalities graphically.

# F: Functions
## IF: Interpreting Functions
### A. Understand the concept of a function and use function notation.
### B. Interpret functions that arise in applications in terms of the context (linear, quadratic, exponential, rational, polynomial, square root, cube root, trigonometric, logarithmic).
### C. Analyze functions using different representations.
## BF: Building Functions
### A. Build a function that models a relationship between two quantities.
### B. Build new functions from existing functions.
## LE: Linear, Quadratic, and Exponential Models
### A. Construct and compare linear, quadratic, and exponential models and solve problems.
### B. Interpret expressions for functions in terms of the situation they model.
## TF: Trigonometric Functions
### A. Extend the domain of trigonometric functions using the unit circle.
### B. Model periodic phenomena with trigonometric functions.
### C. Prove and apply trigonometric identities.

# G: Geometry
## CO: Congruence
### A. Experiment with transformations in the plane.
### B. Understand congruence in terms of rigid motions.
### C. Prove geometric theorems and, when appropriate, the converse of theorems.
### D. Make geometric constructions.
## SRT: Similarity, Right Triangles, and Trigonometry
### A. Understand similarity in terms of similarity transformations.
### B. Prove theorems involving similarity.
### C. Define trigonometric ratios and solve problems involving right triangles.
### D. Apply trigonometry to general triangles.
## C: Circles
### A. Understand and apply theorems about circles.
### B. Find arc lengths and areas of sectors of circles.
## GPE: Expressing Geometric Properties with Equations
### A. Translate between the geometric description and the equation for a conic section.
### B. Use coordinates to prove simple geometric theorems algebraically.
## GMD: Geometric Measurement and Dimension
### A. Explain volume formulas and use them to solve problems.
### B. Visualize relationships between two-dimensional and three-dimensional objects.
## MG: Modeling with Geometry
### A. Apply geometric concepts in modeling situations.

# S: Statistics and Probability
## ID: Interpreting Categorical and Quantitative Data
### A. Summarize, represent, and interpret data on a single count or measurement variable. Use calculators, spreadsheets, and other technology as appropriate.
### B. Summarize, represent, and interpret data on two categorical and quantitative variables.
### C. Interpret linear models.
## IC: Making Inferences and Justifying Conclusions
### A. Understand and evaluate random processes underlying statistical experiments. Use calculators, spreadsheets, and other technology as appropriate.
### B. Make inferences and justify conclusions from sample surveys, experiments, and observational studies.
## CP: Conditional Probability and the Rules of Probability
### A. Understand independence and conditional probability and use them to interpret data from simulations or experiments.
### B. Use the rules of probability to compute probabilities of compound events in a uniform probability model.
## MD: Using Probability to Make Decisions
### A. Calculate expected values and use them to solve problems.
### B. Use probability to evaluate outcomes of decisions.

