```{r,echo=FALSE}
# Perfect squares and differences of squares

pn = function(coeffs,pows){
    pows = pows[coeffs!=0]
    coeffs = coeffs[coeffs!=0]
    ex1 = paste0("{",coeffs,"}x^{",pows,"}",collapse="+")
    ex1 = gsub("+{-","-{",ex1,fixed=T)
    ex1 = gsub("{1}x^{0}","1",ex1,fixed=T)
    ex1 = gsub("{-1}x^{0}","-1",ex1,fixed=T)
    ex1 = gsub("{1}x","x",ex1,fixed=T)
    ex1 = gsub("{-1}x","-x",ex1,fixed=T)
    ex1 = gsub("x^{0}","",ex1,fixed=T)
    ex1 = gsub("x^{1}","x",ex1,fixed=T)
    ex1 = gsub("+-","-",ex1,fixed=T)
    ex1 = gsub("{","",ex1,fixed=T)
    ex1 = gsub("}","",ex1,fixed=T)
    if(ex1 == ""){
        ex1 = "0"
    }
    return(ex1)
}
gcd2 <- function(a, b) {
    if (b == 0) a else Recall(b, a %% b)
}
gcd <- function(...) Reduce(gcd2, c(...))


standards = character()
factoreds = character()


sqrts = sample(3:8,3)

for(jj in 1:3){
    while(T){
        ABCD = sample(2:9,4)*sample(c(-1,1),4,T)
        A = 1 #ABCD[1]
        B = sqrts[jj] #ABCD[2]
        C = 1 #ABCD[3]
        D = B #ABCD[4]
        exp1 = pn(c(A,B),1:0)
        exp2 = pn(c(C,D),1:0)
        exp3 = pn(c(A*C,A*D,B*C,B*D),c(2,1,1,0))
        exp4 = pn(c(A*C,A*D+B*C,B*D),c(2,1,0))
        exp5 = paste0("(",exp1,")(",exp2,")")
        if(!(exp4%in%standards) && abs(gcd(A,B))==1 && abs(gcd(C,D))==1 && (A*D+B*C)!=0){break}
    }
    standards = c(standards,exp4)
    factoreds = c(factoreds,exp5)
}


for(jj in 1:3){
    while(T){
        ABCD = sample(2:9,4)*sample(c(-1,1),4,T)
        A = 1 #ABCD[1]
        B = -sqrts[jj] #ABCD[2]
        C = 1 #ABCD[3]
        D = B #ABCD[4]
        exp1 = pn(c(A,B),1:0)
        exp2 = pn(c(C,D),1:0)
        exp3 = pn(c(A*C,A*D,B*C,B*D),c(2,1,1,0))
        exp4 = pn(c(A*C,A*D+B*C,B*D),c(2,1,0))
        exp5 = paste0("(",exp1,")(",exp2,")")
        if(!(exp4%in%standards) && abs(gcd(A,B))==1 && abs(gcd(C,D))==1 && (A*D+B*C)!=0){break}
    }
    standards = c(standards,exp4)
    factoreds = c(factoreds,exp5)
}


for(jj in 1:3){
    while(T){
        ABCD = sample(2:9,4)*sample(c(-1,1),4,T)
        A = 1 #ABCD[1]
        B = sqrts[jj] #ABCD[2]
        C = 1 #ABCD[3]
        D = -B #ABCD[4]
        exp1 = pn(c(A,B),1:0)
        exp2 = pn(c(C,D),1:0)
        exp3 = pn(c(A*C,A*D,B*C,B*D),c(2,1,1,0))
        exp4 = pn(c(A*C,A*D+B*C,B*D),c(2,1,0))
        exp5 = paste0("(",exp1,")(",exp2,")")
        if(!(exp4%in%standards) && abs(gcd(A,B))==1 && abs(gcd(C,D))==1){break}
    }
    standards = c(standards,exp4)
    factoreds = c(factoreds,exp5)
}

oa = sample(1:length(standards))
ob = sample(1:length(standards))

al = paste0("* ",factoreds[ob],collapse="\n")
fal = paste0(rep(al,length(standards)),collapse="\n")

sols = character()
for(i in oa){
    sols = c(sols,paste0(1*(i==ob),collapse=""))
}


```


Question
========

Match the standard form expressions to their equivalent factored forms.

```{r,echo=F,results='asis'}
for(i in 1:length(standards)){
    cat("* $")
    cat(standards[oa[i]])
    cat("~\\equiv$ ##ANSWER")
    cat(i)
    cat("##\n")
}
```

Answerlist
--------

`r fal`

Solution
========

These are [perfect-square trinomials](https://www.khanacademy.org/math/math2/xe2ae2386aa2e13d6:quad-1/xe2ae2386aa2e13d6:perfect-sq/a/factoring-quadratics-perfect-squares) and [differences of squares](https://en.wikipedia.org/wiki/Difference_of_two_squares).


```{r,echo=F,results='asis'}
for(i in 1:length(standards)){
    cat("* $")
    cat(standards[oa[i]])
    cat("~\\equiv ")
    cat(factoreds[oa[i]])
    cat("$\n")
}
```


Meta-information
============
extype: cloze
exclozetype: `r paste0(rep("schoice",length(standards)),collapse="|")`
exsolution: `r paste0(sols,collapse="|")`
exname: match_factored_standard_A