---
output: slidy_presentation
---


# Combining like terms

>- "Terms" are expressions that are added (or subtracted) to something.
>- "Factors" are expressions that are multiplied (or divided) by something.
>- Terms can be composed of factors (and vice versa).

>- We will start with 3 types of terms:\
    * Quadratic terms (a number times $x^2$)
    * Linear terms (a number times $x$)
    * Constant terms (just a number)

>- A common step when simplifying expressions is to **combine like terms**. For example... imagine we are simplifying the following expression.$$4x+5+8x^2+7+9x-3x^2$$

>- We identify the quadratic terms are $8x^2$ and $-3x^2$.
>- We identify the linear terms are $4x$ and $9x$.
>- We identify the constants are $5$ and $7$. 
>- Thus, when we combine like terms we get... (and put in standard order of quadratic, linear, and then constant)...
>- We get $$5x^2+13x+12$$
>- Notice "combine" means add the coefficients... and "coefficient" is the numerical part of the term.


# Combine-like-terms example 1

Consider the function below.

$$f(x)~=~ 6x^2 +8x+4+3x^2-x-2$$

When simplified, that function can be written in standard form:

$$f(x)~=~ ax^2+bx+c$$

where $a$, $b$, and $c$ are integers. Find $a$, $b$, and $c$.

>- Combine the quadratic terms.$$6x^2+3x^2~\equiv~ 9x^2$$
>- Combine the linear terms. Notice $-x$ is equivalent to $-1x$, but we do not write coefficients of 1 or -1. $$8x-x~\equiv~ 7x$$
>- Combine the constant terms.$$4-2~\equiv~ 2$$
>- Write the function.
$$f(x)~=~ 9x^2+7x+2$$
>- Identify the parameters.$$a=9$$ $$b=7$$ $$c=2$$



# Combine-like-terms example 2

Consider the function below.

$$f(x)~=~ 2+8+4x-5x-3+9x^2-x-8x^2+6x$$

When simplified, that function can be written in standard form:

$$f(x)~=~ ax^2+bx+c$$

where $a$, $b$, and $c$ are integers. Find $a$, $b$, and $c$.

>- Combine the quadratic terms.$$9x^2-8x^2+6x^2~\equiv~ 7x^2$$
>- Combine the linear terms. $$4x-5x-x~\equiv~ -2x$$
>- Combine the constant terms.$$2+8-3~\equiv~ 7$$
>- Write the function.
$$f(x)~=~ 7x^2-2x+7$$
>- Identify the parameters.$$a=7$$ $$b=-2$$ $$c=7$$







# Warmup

>- What do I get when I add $3x$ plus $4x$?
>- $7x$
>- What do I get when I add $x$ plus $4x$?
>- $5x$
>- What do I get when I add $3x^2$ plus $4x^2$?
>- $7x^2$
>- What do I get when I add $3x^2$ plus $4x$?
>- $3x^2+4x$ Notice we can only combine [like terms](https://en.wikipedia.org/wiki/Like_terms#Example).
>- What do I get when I multiply $2$ times $x$?
>- $2x$
>- What do I get when I multiply $x$ times $x$?
>- $x^2$
>- What do I get when I multiply $3x$ times $5x$?
>- $15x^2$
>- What do I get when I distribute $2\cdot (3x+5)$?
>- $6x+10$
>- What do I get when I distribute $x\cdot (3x+5)$?
>- $3x^2+5x$



# Distributing a sum times a sum


>- What do I get when I distribute $(x+2)\cdot (3x+5)$?
>- First, distribute $(x+2)$ to each term in $3x+5$.\
$$(x+2)\cdot 3x ~~~+~~~ (x+2)\cdot 5$$
>- Distribute $3x$ to each term in its $(x+2)$ multiplier.\
$$3x^2+6x ~~~+~~~ (x+2)\cdot 5$$
>- Distribute $5$ to each term in its $(x+2)$ multiplier.\
$$3x^2+6x ~~~+~~~ 5x+10$$
>- Notice we have two [like terms](https://en.wikipedia.org/wiki/Like_terms#Example).








