---
title: "Polynomial Reflections"
author: "Mr. Worley"
date: "2025 Sep 8"
output:
    slidy_presentation:
        incremental: false
# output: html_document
---


# Agenda

* Complete the entrance ticket:
    * [ET_09_08](https://bart.instructure.com/courses/2110/quizzes/3164)
* Algebraic simplification of polynomial reflections.
* Identify and construct even and odd functions.

# Some rules about exponents...

$$3^2 = 9$$
$$\fbox{$(-3)^2 = 9$}$$
$$-3^2 = -9$$
$$-(3^2) = -9$$
$$2^3 = 8$$
$$\fbox{$(-2)^3 = -8$}$$
$$-2^3 = -8$$
$$-(2^3) = -8$$

# Some rules about exponents...

For all values of $x$...

\begin{align}
(-x)^2 &= x^2 \\
(-x)^3 &= -x^3 \\
(-x)^4 &= x^4 \\
(-x)^5 &= -x^5 \\
(-x)^6 &= x^6 \\
(-x)^7 &= -x^7
\end{align}

# Distributing a negative to multiple terms

Let's say I have a function written as follows:

$$f(x)~=~-\left(x^7-x^6-x^5+x^4+x^3+x^2-x+1\right)$$

I can rewrite the expression without parentheses by distributing the negative. Both expressions will evaluate equivalently for any value of $x$ (because they are equivalent expressions).

$$f(x)~=~-x^7+x^6+x^5-x^4-x^3-x^2+x-1$$

# Problem 1

Let function $f$ be defined with the following polynomial.

$$f(x)~=~3x^7+5x^6+x^5-x^4-4x^3+7x^2+6x+1$$

Write a polynomial expression, without any parentheses, that is equivalent to $f(-a)$.

$$f(-a)~=~ ?$$

* Substitute $(-a)$ for each instance of $x$.
$$f(-a)~=~ 3(-a)^7+5(-a)^6+(-a)^5-(-a)^4-4(-a)^3+7(-a)^2+6(-a)+1$$
* Use rules of negatives raised to integer powers.
    * A negative raised to an even power is positive.
    * A negative raised to an odd power is negative.
* So, whether each term has a $+$ or $-$ in front depends on whether the original term had a $+$ or $-$ and whether the power was even or odd.
$$f(-a)~=~ -3a^7+5a^6-a^5-a^4+4a^3+7a^2-6a+1$$
* I should say, we did not need to use $a$. We could have used $x$.
$$f(-x)~=~ -3x^7+5x^6-x^5-x^4+4x^3+7x^2-6x+1$$
* We can graph curve $y=3x^7+5x^6+x^5-x^4-4x^3+7x^2+6x+1$ and curve $y=-3x^7+5x^6-x^5-x^4+4x^3+7x^2-6x+1$. What rigid transformation will relate the two curves?
* The two curves will be horizontal reflections over the $y$ axis.\
```{r,echo=F,fig.dim=c(5,5)}
library(latex2exp)
xmax = 1.4
x = seq(-xmax,xmax,0.01)
y1 = 3*x^7+5*x^6+x^5-x^4-4*x^3+7*x^2+6*x+1
y2 = -3*x^7+5*x^6-x^5-x^4+4*x^3+7*x^2-6*x+1
ymax = max(y1)
ymin = min(y1)
plot(x,y1,"l",col="blue",lwd=3,ylab="y")
abline(h=0,lwd=2)
abline(v=0,lwd=2)
lines(x,y1,col="blue",lwd=3)
lines(x,y2,col="red",lwd=3)
legend("top",c(TeX("$y=3x^7+5x^6+x^5-x^4-4x^3+7x^2+6x+1$"),
               TeX("$y=-3x^7+5x^6-x^5-x^4+4x^3+7x^2-6x+1$")),
       col=c("blue","red"),lwd=c(3,3))
```


# Problem 2

Let function $f$ be defined with the following polynomial.

$$f(x)~=~6x^3+4x^2-x+8$$

Write a polynomial expression, without any parentheses, that is equivalent to $f(-a)$.

* Follow the same procedure. Replace each instance of $x$ with $-a$. Then use rules about negatives raised to powers to simplify.
$$f(-a)~=~6(-a)^3+4(-a)^2-(-a)+8$$
$$f(-a)~=~-6a^3+4a^2+a+8$$

# Problem 3

Let function $f$ be defined with the following polynomial.

$$f(x)~=~6x^3+4x^2-x+8$$

Write a polynomial expression, without any parentheses, that is equivalent to $-f(a)$.

* Replace each instance of $x$ with $a$. Then, multiply the whole thing by $-1$ (by putting a negative symbol in front and parentheses around the whole polynomial).
$$-f(a)~=~-\left(6a^3+4a^2-a+8\right)$$
* Distribute the negative to every term.
$$-f(a)~=~-6a^3-4a^2+a-8$$

# Problem 4

Let function $f$ be defined with the following polynomial.

$$f(x)~=~6x^3+4x^2-x+8$$

Write a polynomial expression, without any parentheses, that is equivalent to $-f(-a)$.

* Replace each instance of $x$ with $-a$. Then, multiply the whole thing by $-1$ (by putting a negative symbol in front and parentheses around the whole polynomial).
$$-f(-a)~=~-\left(6(-a)^3+4(-a)^2-(-a)+8\right)$$
* Use rules about negatives raised to powers to simplify.
$$-f(-a)~=~-\left(-6a^3+4a^2+a+8\right)$$
* Distribute the negative to every term.
$$-f(-a)~=~6a^3-4a^2-a+8$$

# Shortcut rules

* Each term of a polynomial is either ODD powered or EVEN powered.
* To find $f(-x)$ from polynomial $f(x)$, switch sign on ODD powered terms.
* To find $-f(-x)$ from polynomial $f(x)$, switch sign on EVEN powered terms.
* To find $-f(x)$ from polynomial $f(x)$, switch sign on ALL terms.
* The linear term (like $-5x$ or $+7x$) is an ODD powered term, because $x^1\equiv x$.
* The constant term (like $-5$ or $+7$) is an EVEN powered term, because $x^0 \equiv 1$ if we ignore the special case of $0^0$, which is undefined.

# Classwork break

Complete the following online-classwork "quizzes":

1. [OCW_0707A_polynom_reflect_MC](https://bart.instructure.com/courses/2110/quizzes/3165)
2. [OCW_0707B_polynom_reflect_v2](https://bart.instructure.com/courses/2110/quizzes/3167)

