---
output: html_document
urlcolor: blue
---

# L-systems and Turtle Graphics Slideshow Instructions

You will submit a slideshow with:

* Title Slide
* 2-5 slides describing L-systems and Turtle Graphics (with original examples)
    * [https://en.wikipedia.org/wiki/L-system](https://en.wikipedia.org/wiki/L-system)
    * [https://en.wikipedia.org/wiki/Turtle_graphics](https://en.wikipedia.org/wiki/Turtle_graphics)
* A showcase of at least 10 striking, original, varied, and differently colored L-system patterns.
    * Next to each pattern (or on an adjacent slide), display the **key parameters**:
        * Start string
        * Replacement rules
        * Number of iterations (the number of recursions)
        * Angle (how much the turtle turns with each + or -)
    * Each pattern should also have a description. You can describe your process or what thoughts were evoked by the result.
* How to produce patterns?
    * Explore possible patterns with this tool helpful: https://draemm.li/various/fractals/l-systems/
        * Look at the instructions and examples.
        * Adjust the key parameters.
    * Once you've found a pattern you like, use [this R code](https://sagecell.sagemath.org/?z=eJzFF2tv2zbwuwH_B1YBCqmmH3LRYQ2mAo7jtgHSpEg9DJ1hBLRE22woyRCpRMTQ_76jKFmyLKdbP2x-QOQ9eQ8d787QF0rRVsqdOB8Og4TQMBxwNnwkCYtTMVwnxJeEiyHvCyUkDcWw2zlDvwuK5JYJ5McBrGIUkgcKGx4n65SjNYsIR480ESyOhGa4oE8kobjGBM8ologIRNdr5jMayQH6GqcoZJutRBGlgRYcUD-hJFdHUZSGK5qgeI0S6qdGOlop5KI4QePBYNDtaGWfJ3eTT7P57A5dzt5f3VzNr25vvnQ7QpJEIg_5tjWxnG4nSTkVsOdMSA3yrIve_mvhbgfVP9aFJlj0-9PptE-Wi-LZQjgFwun0GE4ONfTyM1R2eOhNt0OiDaew_GVkmM6uInDBJqEU3MgiJhnh9yXR6JAAAwC8OiNCYvQ2X9_EidwiO92BKs4iep-HCFi34tEeDd5gF7sOOtNu90mEINAxSsHZ1oqn1NJeTTYr28WjwRj-bx0N0awaAsyl1CcWgBoPve52Vpu9DhBC_Aer2_l88-F-xzLK94RvRiMDXjNO7yMSanOsa0ixeZrIwS7aWCaUF7Pr2z_Qx9ndDF19QdPbyxlEGX2-u72YXFx_RZe36OZ2jmaXV3M0_1hRdDsbKoXUp1inkS_BwXYefpwHHUfOXyY6QidEjjH7dZzY374hFiH3fE9kCMf6iFYF0aSsoPS3JAEFTp1Df3xtrEhXcBRAY4aZc0jA1vYLJgZRyrmdH22x8LfL5ZGg6gg7CC8dgbQxrjFgcDonO0E9y2qo-I4oh5D-E4H-9jk51fZ73S-5A8cGUiASKtNEexxEfM9jkSn_MBYJizaeNZn0il9vYuE8r70dG47N8r5IeAOCk3kmL_fBe2Iy97Br9gEsDxgNONOvilmqapnxvBRkhZXKbFWxBWX6jYSCQxPm2wU0EOSRHoOzdrBqB7fkjXbGQcgP80ajG7njR9pWMWCRpBua2FrQPL4jT7ByanSQX370zmul1FXQQS9fgrDfTlBcA8VRThvX-LZe6Kg08kS7O-v5sbCDBkZ7X_UEi44wZTA4zpo8RVw4Vk5rAj5r4acfWvjnDy20bibNV-H_MNE7YcCixYAyT307X-Gjs-zx-er4RHt8vvqpcy1_2rFa5YLTaCO35nzOssXJdSrVRqWrQVCnCtqowIYDVe_cttJbOsyczT0_5Om7Tal1J6oGj3qGpwxc0OAJTvCcru0nalLbAZ8hOVHw9ur_mxTvt6W49lI_r_b_XmDvlMDeTwoctAjc305m8cruu8e2F48MGiOgDEkG3nP6IdSPrKyrqsKpAqdKXBbmOLtg7BWMzrC4j1UNrwq8quEr0RA22GCtrLw_Mt0dgLi-1uIMAfOqFJtjFO-rJqa4-fOWOhtjlV_bwjF9gB4SdjyW9U4AGgPMnwJv_9rlJUD5i4W7XFaXdg4ZlxC_hLwuIVqsPcIjbEUWzjgLPR_8DR0qVvUNyajw3kN3EXnvm9fx-Lx8qQ9CqRtcod2zYH13ieGxdDCkstkqs4XWxDcAbQv8nX144QftrH3Q7OJGR3y0X228spGG9nwOow90zBj-4OBdQgUMSwLlDEJPQ3Eqd6lEIAWUQUcRkgRM1u6Ar4PjkNS3O6k8S-jSq4uxaZQPuuNqKAEa07mZFs4WpjEbur-OXu1Yo0s7GE9KEu2aavJwqiTYR76aIAAb0MdBvF7rQgOmQOMDk9mUM_8hn__0YKAD8qAnQwGDq4pTGFGoSLl8YTl_A-Bo8Jk=&lang=r&interacts=eJyLjgUAARUAuQ==) to produce a final PNG image. You can adjust the background color, the line color, and the PNG resolution (how many pixels it has as its width/height).
        * [https://tinyurl.com/LSYSTURTLE](https://tinyurl.com/LSYSTURTLE)
    * You could also use https://chadworley.github.io/Lsys_string_gen.html along with Turbo Turtle (Scratch)
    
You can see an exemplar here: https://chadworley.github.io/ml2026/Lsys/slides_Lsys_exemplar.html



