---
title: "Weekly agenda for Precalculus 2023-2024"
output:
  html_document:
    toc: true
    toc_depth: 2
---


## Week 01: Aug 21 - Aug 25

We use the dice-rolling project as an example to discuss various concepts in Statistics. When we roll 100 standard dice, we get a total near 350, because the population mean is 3.5 for fair 6-sided dice. When we roll 100 special dice, we get a total above 400, because those dice are weighted. We learn $z$-scores are a way to determine whether a sample's total is typical or outlandish.

* Entrance tickets
  * [day 1 (average)](https://chadworley.github.io/precalculus/unit_01_stats/week_01/ET_01/ET_01.html)
  * [day 2 (AAD)](https://chadworley.github.io/precalculus/unit_01_stats/week_01/ET_02/ET_02.html)
  * [day 3 (z score)](file:///Users/chad.worley@bartcharter.org/Documents/chadworley.github.io/precalculus/unit_01_stats/week_01/ET_03/ET_03.html)
  * [day 4 (stats reading)](https://chadworley.github.io/precalculus/unit_01_stats/week_01/ET_04/ET_04.html)
* [Dice-rolling project](https://chadworley.github.io/precalculus/unit_01_stats/week_01/002_dice-rolling_project/002_dice-rolling_project.html)
* [Canvas questions](https://chadworley.github.io/precalculus/unit_01_stats/week_01/canvas_probs/week_01_shared1.html)
* Learning outcomes
  * S.MD.A: Calculate expected values and use them to solve problems.
  * S.MD.A.2: Calculate the expected value of a random variable; interpret it as the mean of the probability distribution.
  * S.IC.A.1: Understand statistics as a process for making inferences about population parameters based on a random sample from that population.
  * S.IC.A.2: Decide if a specified model is consistent with results from a given data-generating process (e.g., using simulation).
  * S.ID.A.4: Use the mean and standard deviation of a data set to fit it to a normal distribution and to estimate population percentages. Recognize that there are data sets for which such a procedure is not appropriate. Use calculators, spreadsheets, and tables to estimate areas under the normal curve.
  * S.IC.B.5: Use data from a randomized experiment to compare two treatments; use simulations to decide if differences between parameters are significant.


## Week 02: Aug 28 - Sep 01

We focus on variability. We learn about standard deviation and standard error.

* [Standard deviation canvas questions](https://chadworley.github.io/precalculus/unit_01_stats/week_02/005_sd/outcanvas/005_shared_questions1.html)
* [SD proj](https://chadworley.github.io/precalculus/unit_01_stats/week_02/006_sd_project/006_sd_proj.pdf)
* [Running average](https://chadworley.github.io/precalculus/unit_01_stats/week_02/007_running_ave_proj/007_running_ave_proj.pdf)
* [Probability of total or average canvas questions](https://chadworley.github.io/precalculus/unit_01_stats/week_02/008_prob_of_ave_CLT/008_prob_of_ave_or_sum_shared1.html)
* [CLT probability canvas questions](https://chadworley.github.io/precalculus/unit_01_stats/week_02/008_prob_of_ave_CLT/outcanvas/008_shared1.html)
* Learning outcomes
  * S.ID.A: Summarize, represent, and interpret data on a single count or measurement variable. Use calculators, spreadsheets, and other technology as appropriate.
  * S.ID.A.2: Use statistics appropriate to the shape of the data distribution to compare center (median, mean) and spread (interquartile range, standard deviation) of two or more different data sets.
  * S.IC.B.4: Use data from a sample survey to estimate a population mean or proportion; develop a margin of error through the use of simulation models for random sampling.

## Week 03: Sep 04 - Sep 08

From a sample, we calculate a confidence interval, which indicates our best estimate of a population parameter (population mean or proportion) along with our uncertainty due to a small sample size. We learn an approximate method of $\bar{x}\pm \frac{2s}{\sqrt{n}}$ or $\hat{p}\pm2\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}$ for a 95\% confidence interval. Based on the confidence interval, we can reject or retain a null hypothesis.

* [Confidence Intervals canvas questions](https://chadworley.github.io/precalculus/unit_01_stats/week_03/009_confidence_intervals_and_histogram_shapes/009_Confidence_Intervals_shared1.html)
* Learning outcomes:
  * S.IC.B: B. Make inferences and justify conclusions from sample surveys, experiments, and observational studies.
  * S.IC.B.5: Use data from a randomized experiment to compare two treatments; use simulations to decide if differences between parameters are significant.

## Week 04: Sep 11 - Sep 15

We dive deep into some concepts in probability like [independence](https://en.wikipedia.org/wiki/Independent_and_identically_distributed_random_variables) and [conditional probability](https://en.wikipedia.org/wiki/Conditional_probability).

* [Probability canvas questions](https://chadworley.github.io/precalculus/unit_01_stats/week_04/010_probability/010_prob_shared1.html)
* Learning outcomes
  * S.CP.A: Understand independence and conditional probability and use them to interpret data from simulations or experiments.
  * S.CP.A.1: Describe events as subsets of a sample space (the set of outcomes) using characteristics (or categories) of the outcomes, or as unions, intersections, or complements of other events (“or,” “and,” “not”).
  * S.CP.B: Use the rules of probability to compute probabilities of compound events in a uniform probability model.

## Week 05: Sep 18 - Sep 22

We continue with concepts in probability. We calculate number of [permutations](https://en.wikipedia.org/wiki/Permutation) and [combinations](https://en.wikipedia.org/wiki/Combination). We also hint at [Bayes' Theorem](https://en.wikipedia.org/wiki/Bayes%27_theorem) and develop an understanding of the [binomial distribution](https://en.wikipedia.org/wiki/Binomial_distribution).

* [More probability problems canvas questions](https://chadworley.github.io/precalculus/unit_01_stats/week_05/011_shared1.html)
* [Binomial Distribution Lecture](https://chadworley.github.io/precalculus/unit_01_stats/week_05/lecture.html#1) (Sep 19th)
* Learning outcomes:
  * S.CP.B.9: Use permutations and combinations to compute probabilities of compound events and solve problems.
  * S.MD.A.2: Calculate the expected value of a random variable; interpret it as the mean of the probability distribution.
  * S.MD.A.3: Develop a probability distribution for a random variable defined for a sample space in which theoretical probabilities can be calculated; find the expected value.

## Week 06: Sep 25 - Sep 29

* [Stats project](https://chadworley.github.io/precalculus/unit_01_stats/stats_project/Research_Project.pdf)

## Week 07: Oct 02 - Oct 06

* [Textbook chapter 1](https://openstax.org/books/precalculus-2e/pages/1-introduction-to-functions)
* [Function intro canvas questions](https://chadworley.github.io/precalculus/unit_02_functions/01_functions/012_shared1.html)
* Learning outcomes:
  * F.IF.A: Understand the concept of a function and use function notation.
  * F.IF.A.1: Understand that a function from one set (called the domain) to another set (called the range) assigns to each element of the domain exactly one element of the range. If $f$ is a function and $x$ is an element of its domain, then $f(x)$ denotes the output of $f$ corresponding to the input $x$. The graph of $f$ is the graph of the equation $y = f(x)$.
  * F.IF.A.2: Use function notation, evaluate functions for inputs in their domains, and interpret statements that use function notation in terms of a context.
  * F.IF.B.5: Relate the domain of a function to its graph and, where applicable, to the quantitative relationship it describes.
  * F.IF.B.6: Calculate and interpret the average rate of change of a function (presented symbolically or as a table) over a specified interval. Estimate the rate of change from a graph.

## Week 08: Oct 09 - Oct 13

* [Textbook chapter 1](https://openstax.org/books/precalculus-2e/pages/1-introduction-to-functions)
* [More functions canvas questions](https://chadworley.github.io/precalculus/unit_02_functions/02_functions_cont/013_shared1.html)
* Learning outcomes:
  * F.IF.B: Interpret functions that arise in applications in terms of the context (linear, quadratic, exponential, rational, polynomial, square root, cube root, trigonometric, logarithmic).
  

## Week 09: Oct 16 - Oct 20

* [Textbook chapter 1](https://openstax.org/books/precalculus-2e/pages/1-introduction-to-functions)
* [Even more functions canvas questions](https://chadworley.github.io/precalculus/unit_02_functions/03_functions_galore/014_shared1.html)
* [Sine slope mini project](https://chadworley.github.io/precalculus/unit_02_functions/03_functions_galore/Sine_slope_mini_project.pdf) (Due Oct 23)

## Week 10: Oct 23 - Oct 27

* [Textbook chapter 2](https://openstax.org/books/precalculus-2e/pages/2-introduction-to-linear-functions)
* [Linear functions canvas questions](https://chadworley.github.io/precalculus/unit_3_linear/015_linear_shared1.html)

## Week 11: Oct 30 - Nov 03

* [Textbook chapter 3](https://openstax.org/books/precalculus-2e/pages/3-introduction-to-polynomial-and-rational-functions)
* [Polynomials, rationals, complex numbers canvas questions](https://chadworley.github.io/precalculus/016_polynomial_and_rational/016_shared1.html)

## Week 12: Nov 06 - Nov 10

* [Textbook chapter 4](https://openstax.org/books/precalculus-2e/pages/4-introduction-to-exponential-and-logarithmic-functions)
* [Exponential and logarithmic canvas questions](https://chadworley.github.io/precalculus/017_geometric_exp_log/017_shared1.html)

## Week 13: Nov 13 - Nov 17

* [Textbook chapter 4](https://openstax.org/books/precalculus-2e/pages/4-introduction-to-exponential-and-logarithmic-functions)
* [Geometric series and fractals canvas questions](https://chadworley.github.io/precalculus/018_geom_series/018_shared1.html)

## Week 14: Nov 20 - Nov 24 (Thanksgiving)

* [Textbook chapter 4](https://openstax.org/books/precalculus-2e/pages/4-introduction-to-exponential-and-logarithmic-functions)
* [Exponential and logarithmic identities canvas questions](https://chadworley.github.io/precalculus/019_exp_log_identities/019_shared1.html)

## Week 15: Nov 27 - Dec 01

* [Exp, log, chaos, and Euler's method  canvas questions](https://chadworley.github.io/precalculus/020_exp_log_graphs_and_inverses/020_shared1.html)
* [Wikipedia: Euler's method](https://en.wikipedia.org/wiki/Euler_method)

## Week 16: Dec 04 - Dec 08

* Presentation of art projects
* In-class review: [Regents Algebra 2](https://www.nysedregents.org/algebratwo/) minus trigonometry.
* [Canvas problems](https://chadworley.github.io/precalculus/021_review/021_shared1.html)

## Week 17: Dec 11 - Dec 15

* [Finish review problems](https://chadworley.github.io/precalculus/021_review/021_shared1.html)
* Interims

## Week 18: Dec 18 - Dec 22

* [Introduction to angles (radians)](https://chadworley.github.io/precalculus/022_radians_degrees/022_shared1.html)

## Week 19: Winter Break!

* Hiking and Biking

## Week 20: Jan 01 - Jan 05

* [Right-triangle trigonometry](https://chadworley.github.io/precalculus/023_SOHCAHTOA/023_shared1.html)



