```{r data generation, echo = FALSE, results = "hide"}
peqs = c("b = |a|",
         "b = √a",
         "b = a²",
         "b = ∛a",
         "b = a³",
         "b = 2ˣ",
         "b = log₂(a)",
         "b = 1/a",
         "b = 3ˣ",
         "b = log₃(a)")

pas = list(c(-3,-2,-1,0,1,2,3),
           c(0,1,4,9,16,25,36),
           c(-3,-2,-1,0,1,2,3),
           c(-27,-8,-1,0,1,8,27),
           c(-3,-2,-1,0,1,2,3),
           c(-3,-2,-1,0,1,2,3),
           c("\\frac{1}{8}","\\frac{1}{4}","\\frac{1}{2}",1,2,4,8),
           c(-2,-1,"\\frac{-1}{2}","\\frac{1}{2}",1,2),
           c(-3,-2,-1,0,1,2,3),
           c("\\frac{1}{27}","\\frac{1}{9}","\\frac{1}{3}",1,3,9,27))

pbs = list(c(3,2,1,0,1,2,3),
           c(0,1,2,3,4,5,6),
           c(9,4,1,0,1,4,9),
           c(-3,-2,-1,0,1,2,3),
           c(-27,-8,-1,0,1,8,27),
           c("\\frac{1}{8}","\\frac{1}{4}","\\frac{1}{2}",1,2,4,8),
           c(-3,-2,-1,0,1,2,3),
           c("\\frac{-1}{2}",-1,-2,2,1,"\\frac{1}{2}"),
           c("\\frac{1}{27}","\\frac{1}{9}","\\frac{1}{3}",1,3,9,27),
           c(-3,-2,-1,0,1,2,3)
           )

ord1 = sample(1:10)
ord2 = sample(1:10)

ach = peqs[ord2]
al = paste0("* ",ach,collapse="\n")

sols = character()
for(i in 1:10){
    sols = c(sols,paste0(1*(1:10==which(ord2==ord1[i])),collapse=""))
}

```

Question
========

What parent function matches the table?

```{r,echo=F,results='asis',warning=F}
library(kableExtra)
a = pas[[ord1[1]]]
b = pbs[[ord1[1]]]
df = data.frame(paste0("$",a,"$"),paste0("$",b,"$"))
names(df) = c("$a$","$b$")
kable(df) %>%
    kable_styling("bordered",full_width = F)

```

* ##ANSWER1##


Answerlist
--------

`r al`



Solution
========







Meta-information
============
extype: schoice
exsolution: `r sols[1]`
exname: parent_tables